Gr = [
"Video - Nuovo robot bipede presentato ieri a Tokyo|La Schaft Robotics di Google ha svelato la sua creazione robotica|2016/04/video-nuovo-robot-bipede-presentato-ieri-a-tokyo.html?t=scienza,robot,robotica,automa,google,ingegneria,automazione,informatica,tokyo,geek&amp;d=9|YT_iyZE0psQsX0",
"Video - La prossima generazione di robot umanoidi|Non è fantascienza, è l'ultima creazione di Boston Dynamics, rilevata da Google nel 2013|2016/02/video-la-prossima-generazione-di-robot-umanoidi.html?t=robot,robotica,spazio,fantascienza,scienza,isaac-asimov,automa,boston-dynamics,google,intelligenza-artificiale&amp;d=25|YT_rVlhMGQgDkY",
"Video - Il robot che scala le pareti|VertiGo, per scalare una parete verticale, sfrutta alcune eliche montate sul dorso|2016/01/video-il-robot-che-scala-le-pareti.html?t=robot,automa,zurigo,veicolo,disney,fibra-di-carbonio,video&amp;d=1|YT_tmm6etLlleA",
"Video - Un robot umanoide per le missioni spaziali|R5 Valkyrie è pensato come un robot umanoide da inviare nello spazio, forse su Marte|2015/12/video-un-robot-umanoide-per-le-missioni-spaziali.html?t=nasa,spazio,robot,marte,massachusetts-institute-of-technology,northeastern-university,universita-del-texas,boston,darpa&amp;d=25|YT_jtnu9cmJKQM",
"Video - Abiogenesis: il corto di fantascienza che ha vinto tutto|Un corto fantascientifico del talentuoso Richard Mans ci fa vedere come potrebbe essere andata|2015/07/video-abiogenesis-il-corto-di-fantascienza-che-ha-vinto-tutto.html?t=fantascienza,spazio,nasa,vita,robot,sonda,video&amp;d=23|asteroid",
"Il robot maggiordomo soppianterà le badanti|Il nuovo robot dovrà essere in grado di assolvere a tutta una serie di compiti pratici, dalla preparazione del cibo alla gestione della casa|2015/03/il-robot-maggiordomo-soppiantera-le-badanti.html?t=robot,automa,badante,anziano,pisa&amp;d=6|robot-hello",
"Video - Il nuovo cane robotico di Google e Boston Dynamics|Può salire e scendere le scale, spostarsi su percorsi accidentati e riprendere l'equilibrio velocemente|2015/02/video-il-nuovo-cane-robotico-di-google-e-boston-dynamics.html?t=robot,google,boston-dynamics,cane&amp;d=11|robot-dog",
];
