Gr = [
"Panca Ginnica Smile Gym|Attrezzo home fitness composto da una base d'appoggio con tappetino|2017/12/panca-ginnica-smile-gym|data.oliviero.it/imgprodotto/panca-ginnica-smile-gym_71326",
"Panca Addominali con leg extension AB LEG|Panca piana fitness per addominali pieghevole Realizzata in tubolare|2017/12/panca-addominali-con-leg-extension-ab-leg|data.oliviero.it/imgprodotto/panca-addominali-con-leg-extension-ab-leg_71319",
"Tavolo da ping pong T604 Giardino Outdoor|Caratteristiche tecniche: Tavolo montato su ruote gemellari Ø 80 mm|2017/12/tavolo-da-ping-pong-t604-giardino-outdoor|data.oliviero.it/imgprodotto/tavolo-da-ping-pong-t604-giardino-outdoor_475_big",
"Sacco boxe 25 Kg|Caratteristiche : SACCO: realizzato in ecopelle MISURE: DIAM. cm. 35|2017/12/sacco-boxe-25-kg|data.oliviero.it/imgprodotto/sacco-boxe-25-kg_71354",
"Cyclette Ritmo|Bici da camera pieghevole con un semplice movimento MODELLO: RITMO|2017/12/cyclette-ritmo|data.oliviero.it/imgprodotto/cyclette-ritmo_71268",
"Tavolo Ping Pong T905 Superior Outdoor con kit di montaggio|Con l'arrivo della bella stagione cresce il desiderio di trascorrere|2017/12/tavolo-ping-pong-t905-superior-outdoor-con-kit-di-montaggio|data.oliviero.it/imgprodotto/tavolo-ping-pong-t905-superior-outdoor-con-kit-di-montaggio_162516",
"Cintura Vibrante Vibro Sauna 656V vibrosauna|Cintura massaggiante e vibrante, con effetto sauna. La sua funzione|2017/12/cintura-vibrante-vibro-sauna-656v-vibrosauna|data.oliviero.it/imgprodotto/cintura-vibrante-vibro-sauna-656v-vibrosauna_71259",
"Massaggiatore Plantare|massaggiatore elettrico plantare ad azione massaggiante|2017/12/massaggiatore-plantare|data.oliviero.it/imgprodotto/massaggiatore-plantare_71346",
"Sacco boxe + Guantoni|Sacco + guanti da allenamento Caratteristiche : Completo boxe|2017/12/sacco-boxe-+-guantoni|data.oliviero.it/imgprodotto/sacco-boxe-guantoni_71355",
"Panca Inversione TURN UP|Panca fitness ad inversione ideale per combattere i dolori alla|2017/12/panca-inversione-turn-up|data.oliviero.it/imgprodotto/panca-inversione-turn-up_71324",
"Tavolo Ping Pong T914 Super Gara Indoor|MODELLO: TAVOLO PING PONG 'SUPER GARA' Tavolo montato su ruote|2017/12/tavolo-ping-pong-t914-super-gara-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-t914-super-gara-indoor_6990_big",
"Set Aerobica Basic|Guanti in pelle + 2 manubri da kg. 2 cad. Caratteristiche tecniche:|2017/12/set-aerobica-basic|data.oliviero.it/imgprodotto/set-aerobica-basic_71336",
"Tavola da neve Snow Slide|SNOW-SLIDE Tavola in poliuretano espanso rigido Alette direzionali|2017/12/tavola-da-neve-snow-slide|data.oliviero.it/imgprodotto/tavola-da-neve-snow-slide_14552_big",
"Cuscino Massaggiante Massage Cushion|Cuscino massaggiante ad alimentazione elettrica, riscaldante|2017/12/cuscino-massaggiante-massage-cushion|data.oliviero.it/imgprodotto/cuscino-massaggiante-massage-cushion_71341",
"Tavolo Ping Pong T614 gara Indoor|Caratteristiche tecniche: Tavolo montato su ruote gemellari Ø 80 mm|2017/12/tavolo-ping-pong-t614-gara-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-t614-gara-indoor_478_big",
"Tavolo Ping Pong T905 Superior da esterno|Con l'arrivo della bella stagione cresce il desiderio di trascorrere|2017/12/tavolo-ping-pong-t905-superior-da-esterno|data.oliviero.it/imgprodotto/tavolo-ping-pong-t905-superior-da-esterno_6991_big",
"Tavolo T914 Super Gara Indoor con kit di montaggio|Tavolo montato su ruote gemellari 80 mm. Piani spessore 14/16 in|2017/12/tavolo-t914-super-gara-indoor-con-kit-di-montaggio|data.oliviero.it/imgprodotto/tavolo-t914-super-gara-indoor-con-kit-di-montaggio_71226",
"Tapis Roulant magnetico YOUNG|Tapis roulant magnetico COMPLETAMENTE ASSEMBLATO Caratteristiche:|2017/12/tapis-roulant-magnetico-young|data.oliviero.it/imgprodotto/tapis-roulant-magnetico-young_71284",
"Panca Multifunzione gonfiabile Air Bench|Panca fitness gonfiabile multifunzione di ultima generazione|2017/12/panca-multifunzione-gonfiabile-air-bench|data.oliviero.it/imgprodotto/panca-multifunzione-gonfiabile-air-bench_71313",
"Cuscino Massaggiante Air Massager|Cuscino massaggiante ad aria ad alimentazione elettrica DESCRIZIONE|2017/12/cuscino-massaggiante-air-massager|data.oliviero.it/imgprodotto/cuscino-massaggiante-air-massager_71339",
"Materassino Massaggiante Sound Massage Mat|Tappetino massaggiante pieghevole con 5 motori vibranti DESCRIZIONE|2017/12/materassino-massaggiante-sound-massage-mat|data.oliviero.it/imgprodotto/materassino-massaggiante-sound-massage-mat_71343",
"Set Yoga SIDDHARTHA|SET YOGA Siddhartha ideale per Yoga. Elegante scatola in cartone|2017/12/set-yoga-siddhartha|data.oliviero.it/imgprodotto/set-yoga-siddhartha_162522",
"Cyclette Virgola|Bici da camera ultraleggera e con dimensioni ridotte; ideale per|2017/12/cyclette-virgola|data.oliviero.it/imgprodotto/cyclette-virgola_71263",
"Panca Multifunzione Hydro Master|Panca fitness multifunzione di ultima generazione che, grazie ai|2017/12/panca-multifunzione-hydro-master|data.oliviero.it/imgprodotto/panca-multifunzione-hydro-master_163732",
];
