Gr = [
"Maxi Trolley SJ Girl|Questo è il Big trolley Sj! Adatto per la scuola con una capienza di|2017/12/maxi-trolley-sj-girl|data.oliviero.it/imgprodotto/maxi-trolley-sj-girl_166215",
"Astuccio 3 Zip SJ Boy|L'ASTUCCIO 3 ZIP SJ GANG è l'accessorio che non può mancare nel tuo|2017/12/astuccio-3-zip-sj-boy|data.oliviero.it/imgprodotto/astuccio-3-zip-sj-boy_166375",
"Trolley Maxi Round Sunflowers|Per chi ancora non lo conoscesse, questo è Maxi Trolley Round: un|2017/12/trolley-maxi-round-sunflowers|data.oliviero.it/imgprodotto/trolley-maxi-round-sunflowers_166145",
"Zaino Maxi Sj Girl|Sempre per la scuola una versione alternativa con un modello tondo:|2017/12/zaino-maxi-sj-girl|data.oliviero.it/imgprodotto/zaino-maxi-sj-girl_166211",
"Portapenne Round Plus|Un portapenne attrezzato per organizzare al meglio penne, matite|2017/12/portapenne-round-plus|data.oliviero.it/imgprodotto/portapenne-round-plus_166360",
"Portapenne Round Plus Round Girl|Un portapenne attrezzato per organizzare al meglio penne, matite|2017/12/portapenne-round-plus-round-girl|data.oliviero.it/imgprodotto/portapenne-round-plus-round-girl_166268",
"Astuccio 3 Zip Colorful Boy|L'ASTUCCIO 3 ZIP Seven School è l'accessorio che non può mancare nel|2017/12/astuccio-3-zip-colorful-boy|data.oliviero.it/imgprodotto/astuccio-3-zip-colorful-boy_166321",
"Zaino The Double Pink Hearts|È uno zaino ma sono due. Da un lato fantasia e dall'altro tinta|2017/12/zaino-the-double-pink-hearts|data.oliviero.it/imgprodotto/zaino-the-double-pink-hearts_167522",
"Zaino Sdoppiabile Sj Boy|ZAINO SDOPPIABILE SJ CON FLIP SYSTEM! Lo zaino che volta|2017/12/zaino-sdoppiabile-sj-boy|data.oliviero.it/imgprodotto/zaino-sdoppiabile-sj-boy_166217",
"Astuccio 3 Zip Shift|L'ASTUCCIO 3 ZIP Seven School è l'accessorio che non può mancare nel|2017/12/astuccio-3-zip-shift|data.oliviero.it/imgprodotto/astuccio-3-zip-shift_166351",
"Zaino Triplicabile Bundle Girl|Moltiplica lo spazio e stai sempre al passo con le mode! Guarda che|2017/12/zaino-triplicabile-bundle-girl|data.oliviero.it/imgprodotto/zaino-triplicabile-bundle-girl_166114",
"Zaino Advanced Colorful Girl|Lo zaino pensato per chi ha esigenze di carico ma non vuole|2017/12/zaino-advanced-colorful-girl|data.oliviero.it/imgprodotto/zaino-advanced-colorful-girl_166195",
"Portapenne Widget|Tanti modelli, grafiche e colori… proprio per tutti i gusti!!!|2017/12/portapenne-widget|data.oliviero.it/imgprodotto/portapenne-widget_166288",
"Astuccio 3 Zip Bitmap|L'ASTUCCIO 3 ZIP Seven School è l'accessorio che non può mancare nel|2017/12/astuccio-3-zip-bitmap|data.oliviero.it/imgprodotto/astuccio-3-zip-bitmap_166301",
"Diario 10 Mesi SJ Gang Girl|Seven SJ gang Girl diario agenda 10 mesi non datato, pagine|2017/12/diario-10-mesi-sj-gang-girl|data.oliviero.it/imgprodotto/diario-10-mesi-sj-gang-girl_167506",
"Astuccio 3 Zip SJ High Tech|L'ASTUCCIO 3 ZIP SJ GANG è l'accessorio che non può mancare nel tuo|2017/12/astuccio-3-zip-sj-high-tech|data.oliviero.it/imgprodotto/astuccio-3-zip-sj-high-tech_166381",
"Portapenne Fancy|Tanti modelli, grafiche e colori… proprio per tutti i gusti!!!|2017/12/portapenne-fancy|data.oliviero.it/imgprodotto/portapenne-fancy_166319",
"Portapenne Pinky Hearts|Tanti modelli, grafiche e colori… proprio per tutti i gusti!!!|2017/12/portapenne-pinky-hearts|data.oliviero.it/imgprodotto/portapenne-pinky-hearts_166363",
"Trolley New Jack Bitmap|Non conosci ancora Jack??? JACK è il trolley brevettato Seven che|2017/12/trolley-new-jack-bitmap|data.oliviero.it/imgprodotto/trolley-new-jack-bitmap_166146",
"Trolley Maxi Round Bitmap|Per chi ancora non lo conoscesse, questo è Maxi Trolley Round: un|2017/12/trolley-maxi-round-bitmap|data.oliviero.it/imgprodotto/trolley-maxi-round-bitmap_166148",
"Zaino Sdoppiabile Swag Boy|Per te, che sei sempre alla ricerca di qualcosa di veramente nuovo,|2017/12/zaino-sdoppiabile-swag-boy|data.oliviero.it/imgprodotto/zaino-sdoppiabile-swag-boy_166122",
"Astuccio 3 Zip Sunflower|L'ASTUCCIO 3 ZIP Seven School è l'accessorio che non può mancare nel|2017/12/astuccio-3-zip-sunflower|data.oliviero.it/imgprodotto/astuccio-3-zip-sunflower_166289",
"Zaino Advanced Bitmap|Lo zaino pensato per chi ha esigenze di carico ma non vuole|2017/12/zaino-advanced-bitmap|data.oliviero.it/imgprodotto/zaino-advanced-bitmap_166298",
"Trolley Maxi Round Widget|Per chi ancora non lo conoscesse, questo è Maxi Trolley Round: un|2017/12/trolley-maxi-round-widget|data.oliviero.it/imgprodotto/trolley-maxi-round-widget_166138",
"Zaino Small Sj Face|Per il tempo un modello di zaino tondo con 12 lt di capacità|2017/12/zaino-small-sj-face|data.oliviero.it/imgprodotto/zaino-small-sj-face_166106",
"Astuccio 3 Zip Colorful Girl|L'ASTUCCIO 3 ZIP Seven School è l'accessorio che non può mancare nel|2017/12/astuccio-3-zip-colorful-girl|data.oliviero.it/imgprodotto/astuccio-3-zip-colorful-girl_166328",
"Diario 10 mesi SJ Gang Boy|Seven SJ gang faccine diario agenda 10 mesi non datato, pagine|2017/12/diario-10-mesi-sj-gang-boy|data.oliviero.it/imgprodotto/diario-10-mesi-sj-gang-boy_167512",
"Portapenne Bitmap per la scuola|Gli accessori che non possono mancare nel tuo zaino per la scuola|2017/11/portapenne-bitmap-per-la-scuola|data.oliviero.it/imgprodotto/portapenne-bitmap_166310",
];
