Gr = [
"Ellittica Rivo P Black Edition|RIVO P 07644-500 Passo dopo passo verso la tua forma ideale. Grazie|2017/12/ellittica-rivo-p-black-edition|data.oliviero.it/imgprodotto/ellittica-rivo-p-black-edition_130310",
"Cyclette Ergo S6|KETTLER ERGO S6 Un vero ergometro con 2 modalità di utilizzo:|2017/12/cyclette-ergo-s6|data.oliviero.it/imgprodotto/cyclette-ergo-s6_158038",
"Gym Bike Racer 1 speed bike|RACER 1 GYM BIKE KETTLER COD.7639-700; Tecnologia affidabile per il|2017/12/gym-bike-racer-1-speed-bike|data.oliviero.it/imgprodotto/gym-bike-racer-1-speed-bike_157997",
"Panca Inversione Apollo|La panca gravitazionale APOLLO permette, con il suo movimento di|2017/12/panca-inversione-apollo|data.oliviero.it/imgprodotto/panca-inversione-apollo_50639_big",
"Tapis Roulant Track 5|KETTLER Track 5, oltre al sistema EASY ROLLER e allo Shock Absorber|2017/12/tapis-roulant-track-5|data.oliviero.it/imgprodotto/tapis-roulant-track-5_162679",
"Ministepper con Computer|Il Kettler Mini-Stepper con computer slancia la vostra circolazione|2017/12/ministepper-con-computer|data.oliviero.it/imgprodotto/ministepper-con-computer_8432_big",
"Modulo Leg extension, Leg Curl|KINETIC SYSTEM Il nuovo concetto modulare Kinetic system è costituito|2017/12/modulo-leg-extension-leg-curl|data.oliviero.it/imgprodotto/modulo-leg-extension-leg-curl-kinetic-system_130393",
"Gym Bike Racer 9 incluso World Tours 2.0|La cyclette Racer 9 da Kettler è naturalmente per ciclisti ambiziosi|2017/12/gym-bike-racer-9-incluso-world-tours-2-0|data.oliviero.it/imgprodotto/gym-bike-racer-9-incluso-world-tours-2-0_158083",
"Stepper Montana|stepper ideale per l'home- fitness. Caratteristiche: Training PC:|2017/12/stepper-montana|data.oliviero.it/imgprodotto/stepper-montana_57_big",
"Tavolo Ping Pong Outdoor 10 Blu|OUTDOOR 10 Modello per uso ricreativo per utilizzatori di tutte le|2017/12/tavolo-ping-pong-outdoor-10-blu|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-10-blu_110975",
"Vogatore Coach E|Il vogatore professionale creato e progettato per eliminare tutti gli|2017/12/vogatore-coach-e|data.oliviero.it/imgprodotto/vogatore-coach-e_6974_big",
"Vogatore Rower NEW|Migliora la tua forma fisica con ROWER, il rinnovato vogatore|2017/12/vogatore-rower-new|data.oliviero.it/imgprodotto/vogatore-rower-new_130399",
"Gym Bike Speed 5|Kettler Speed 5 è un modello di Gymbike con telaio solido in acciaio|2017/12/gym-bike-speed-5|data.oliviero.it/imgprodotto/gym-bike-speed-5_71160",
"Modulo Dip Station|KINETIC SYSTEM Il nuovo concetto modulare Kinetic system è costituito|2017/12/modulo-dip-station|data.oliviero.it/imgprodotto/modulo-dip-station-kinetic-system_130391",
"Ellittica Unix Ex|UNIX EX ELLITTICA ERGOMETRO KETTLER COD.7670-760 Modello top della|2017/12/ellittica-unix-ex|data.oliviero.it/imgprodotto/ellittica-unix-ex_72661",
"Panca Addominali AB Trainer|AB-TRAINER 07629-600 Panca Inclinata da allenamento inclinazione|2017/12/panca-addominali-ab-trainer|data.oliviero.it/imgprodotto/panca-addominali-ab-trainer_130321",
"Cyclette Golf S4|KETTLER GOLF S4 Computer LCD alta risoluzione multi informazione con|2017/12/cyclette-golf-s4|data.oliviero.it/imgprodotto/cyclette-golf-s4_158002",
"Tavolo Ping Pong Axos Indoor 3|Ping Pong - AXOS INDOOR 3 Articolo no.: 07136-900 Modello per uso|2017/12/tavolo-ping-pong-axos-indoor-3|data.oliviero.it/imgprodotto/tavolo-ping-pong-axos-indoor-3_110098",
"Cyclette Giro C3 Black|KETTLER GIRO C3 BLACK Computer LCD multi informazione con qualità|2017/12/cyclette-giro-c3-black|data.oliviero.it/imgprodotto/cyclette-giro-c3-black_157995",
"Ellittica Cross P NEW|Versione computerizzata con sistema di frenaggio magnetico|2017/12/ellittica-cross-p-new|data.oliviero.it/imgprodotto/ellittica-cross-p-new_130316",
"Cyclette Ergo C12|Un vero ergometro con 2 modalità di utilizzo: modalità AUTO (rpm|2017/12/cyclette-ergo-c12|data.oliviero.it/imgprodotto/cyclette-ergo-c12_158045",
"Modulo Double Cable Pulley|KINETIC SYSTEM Il nuovo concetto modulare Kinetic system è costituito|2017/12/modulo-double-cable-pulley|data.oliviero.it/imgprodotto/modulo-double-cable-pulley-kinetic-system_130397",
"Ellittica Rivo M Black Edition|RIVO M 07643-300 Fitness per tutti! Avvicinarsi al fitness è un gioco|2017/12/ellittica-rivo-m-black-edition|data.oliviero.it/imgprodotto/ellittica-rivo-m-black-edition_130308",
"Vogatore Coach S|NUOVO COACH S 07975-170 Con il nuovo KETTLER COACH S si amplia la|2017/12/vogatore-coach-s|data.oliviero.it/imgprodotto/vogatore-coach-s_90370",
"Ellittica Elliptical P NEW|ELLIPTICAL P 07649-500 Ellittica top di gamma per un allenamento|2017/12/ellittica-elliptical-p-new|data.oliviero.it/imgprodotto/ellittica-elliptical-p-new_130319",
"Tavolo Ping Pong Outdoor 6|OUTDOOR 6 07177-900 Modello per uso ricreativo per utilizzatori di|2017/12/tavolo-ping-pong-outdoor-6|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-6_110126",
"Tapis Roulant Run 11|Ha un ottimo nastro da corsa di dimensioni 51 × 152 cm che consente|2017/12/tapis-roulant-run-11|data.oliviero.it/imgprodotto/tapis-roulant-run-11_93239",
"Panca Alpha Pro|NUOVO ALPHA PRO 07708-110 CERTIFICAZIONE SEMI PROFESSIONALE La panca|2017/12/panca-alpha-pro|data.oliviero.it/imgprodotto/panca-alpha-pro_90363",
"Panca Addominali Athos|PANCHE DA ALLENAMENTO Le panche da allenamento Kettler sono dei veri|2017/12/panca-addominali-athos|data.oliviero.it/imgprodotto/panca-addominali-athos_130329",
"Cyclette Cycle M LA accesso facilitato|CYCLE M LA07629-400 Modello di ingresso nel mondo KETTLER, la|2017/12/cyclette-cycle-m-la-accesso-facilitato|data.oliviero.it/imgprodotto/cyclette-cycle-m-la-accesso-facilitato_130294",
"Panca Addominali Combi Trainer|Combi-TRAINER 07629-700 Panca multi-funzione (hyperextension|2017/12/panca-addominali-combi-trainer|data.oliviero.it/imgprodotto/panca-addominali-combi-trainer_130326",
"Cyclette Golf C2|KETTLER GOLF C2 Computer LDC multi informazione, facile da usare con|2017/12/cyclette-golf-c2|data.oliviero.it/imgprodotto/cyclette-golf-c2_158001",
"Modulo Leg Press|KINETIC SYSTEM Il nuovo concetto modulare Kinetic system è costituito|2017/12/modulo-leg-press|data.oliviero.it/imgprodotto/modulo-leg-press-kinetic-system_130395",
"Tavolo Ping Pong Axos Outdoor 1|Ping Pong - AXOS OUTDOOR 1 Articolo No.: 07047-900 Modello per uso|2017/12/tavolo-ping-pong-axos-outdoor-1|data.oliviero.it/imgprodotto/tavolo-ping-pong-axos-outdoor-1_110102",
"Crossrack NEW!|Descrizione: Ketter Cross Rack è una multi stazione per allenamento|2017/12/crossrack-new|data.oliviero.it/imgprodotto/crossrack-new-_162691",
"Tavolo Ping Pong Axos Indoor 1|Ping Pong - AXOS INDOOR 1 Articolo No.: 07046-900 Caratteristiche|2017/12/tavolo-ping-pong-axos-indoor-1|data.oliviero.it/imgprodotto/tavolo-ping-pong-axos-indoor-1_110095",
"Cyclette Golf C4|KETTLER GOLF C4 Computer LCD alta risoluzione multi informazione con|2017/12/cyclette-golf-c4|data.oliviero.it/imgprodotto/cyclette-golf-c4_158003",
"Cyclette Ergo C10|Un vero ergometro con 2 modalità di utilizzo: modalità AUTO (rpm|2017/12/cyclette-ergo-c10|data.oliviero.it/imgprodotto/cyclette-ergo-c10_158044",
"Panca Addominali Universal Bench|UNIVERSAL 07629-800 Robusta panca piana/inclinabile deale per|2017/12/panca-addominali-universal-bench|data.oliviero.it/imgprodotto/panca-addominali-universal-bench_130328",
"Cyclette Ergo C8|KETTLER ERGO C8 Un vero ergometro con 2 modalità di utilizzo:|2017/12/cyclette-ergo-c8|data.oliviero.it/imgprodotto/cyclette-ergo-c8_158043",
"Cyclette Giro S1 Black|Computer LDC multi informazione, facile da usare con una|2017/12/cyclette-giro-s1-black|data.oliviero.it/imgprodotto/cyclette-giro-s1-black_157977",
"Ellittica Advantage Rivo M 2012|Il nuovo Crosstrainer Kettler Rivo M è uno attrezzo home-fitness|2017/12/ellittica-advantage-rivo-m-2012|data.oliviero.it/imgprodotto/ellittica-advantage-rivo-m-2012_12829_big",
"Vogatore Favorit|Vogare è un allenamento di resistenza che impegna omogeneamente tutti|2017/12/vogatore-favorit|data.oliviero.it/imgprodotto/vogatore-favorit_43_big",
"Ergo S con Fascia Cardio Polar|ERGO S con fascia cardio Polar incluso World Tours 2.0 up-grade|2017/12/ergo-s-con-fascia-cardio-polar|data.oliviero.it/imgprodotto/ergo-s-con-fascia-cardio-polar_162669",
"Recumbent Cycle R NEW|7986-897 La bicicletta da camera recumbent CYCLE R garantisce una|2017/12/recumbent-cycle-r-new|data.oliviero.it/imgprodotto/recumbent-cycle-r-new_130299",
"Cyclette Giro S3 black|KETTLER GIRO S3 BLACK Computer LCD multi informazione con qualità|2017/12/cyclette-giro-s3-black|data.oliviero.it/imgprodotto/cyclette-giro-s3-black_157994",
"Gym Ball 65 cm|PALLA DA GINNASTICA LINEA BALANCE KETTLER COD. 7350-124 (Ø 65 cm|2017/12/gym-ball-65-cm|data.oliviero.it/imgprodotto/gym-ball-65-cm_141942",
"Ping Pong Axos Indoor 10|Piano gioco in speciale materiale di legno spessore mm.22 con|2017/12/ping-pong-axos-indoor-10|data.oliviero.it/imgprodotto/ping-pong-axos-indoor-10_147334",
"Cyclette Ergo C6|KETTLER ERGO C6 Un vero ergometro con 2 modalità di utilizzo:|2017/12/cyclette-ergo-c6|data.oliviero.it/imgprodotto/cyclette-ergo-c6_158042",
"Tavolo Ping Pong Outdoor 4|KETTLER OUTDOOR 4 Articolo No.: 07172-700 Modello per uso ricreativo|2017/12/tavolo-ping-pong-outdoor-4|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-4_110124",
"Vogatore Stroker con fascia cardio inclusa|Dim. Aperto 206 x 52 x 67 cm Dim. Chiuso - Fascia Cardiaca Sì|2017/12/vogatore-stroker-con-fascia-cardio-inclusa|data.oliviero.it/imgprodotto/vogatore-stroker-con-fascia-cardio-inclusa_14382_big",
"Palla tonificante 1,5 kg|La sfera tonificante offre un completamento agli esercizi fatti fino|2017/12/palla-tonificante-1-5-kg|data.oliviero.it/imgprodotto/palla-tonificante-1-5-kg_74583",
"Ellittica Cross M NEW|07647-800 Modello di ingresso nel mondo delle ellittiche KETTLER. La|2017/12/ellittica-cross-m-new|data.oliviero.it/imgprodotto/ellittica-cross-m-new_130314",
"Recumbent Giro R Black Edition|GIRO R 07629-000 Sicura, comoda e confortevole. Con GIRO R / GIRO|2017/12/recumbent-giro-r-black-edition|data.oliviero.it/imgprodotto/recumbent-giro-r-black-edition_130305",
"Cyclette Cycle P NEW|CYCLE P 07628-900 Versione computerizzata con sistema di frenaggio|2017/12/cyclette-cycle-p-new|data.oliviero.it/imgprodotto/cyclette-cycle-p-new_130296",
"Porta Pesi diam 25|Supporto universale che offre posto per tutto ciò che è necessario|2017/12/porta-pesi-diam-25|data.oliviero.it/imgprodotto/porta-pesi-diam-25_71165",
"Tavolo Ping Pong Sketch Pong Outdoor|Il nuovissimo tavolo da ping pong Kettler SketchPong ha un look|2017/12/tavolo-ping-pong-sketch-pong-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-sketch-pong-outdoor_147321",
"Leg Extension per Alpha Pro|PESI E PANCA NON INCLUSI Con questo accessorio leg extension per la|2017/12/leg-extension-per-alpha-pro|data.oliviero.it/imgprodotto/leg-extension-per-alpha-pro_90368",
"Vogatore Coach M|Il vogatore professionale creato e progettato per eliminare tutti gli|2017/12/vogatore-coach-m|data.oliviero.it/imgprodotto/vogatore-coach-m_6894_big",
"Tavolo Ping Pong Smash 7 da esterno|SMASH OUTDOOR 7 Piano gioco 'ALU-TEC', un rivestimento multistrato|2017/12/tavolo-ping-pong-smash-7-da-esterno|data.oliviero.it/imgprodotto/tavolo-ping-pong-smash-7-da-esterno_59087",
"Ellittica Vito M Fun|La Vito M Fun è dotata di un volano dal peso di 14 Kg, che permetterà|2017/12/ellittica-vito-m-fun|data.oliviero.it/imgprodotto/ellittica-vito-m-fun-7658-100_162632",
"Panca Multifunzione Fitmaster|La stazione multifunzione Kettler Fitmaster 300 è una stazione|2017/12/panca-multifunzione-fitmaster|data.oliviero.it/imgprodotto/panca-multifunzione-fitmaster_140051",
"Panca Multifunzione Multigym|Il Kettler Powercenter Multigym per un approccio a costi ridotti|2017/12/panca-multifunzione-multigym|data.oliviero.it/imgprodotto/panca-multifunzione-multigym_165866",
"Tavolo Ping Pong Outdoor 10 Verde|OUTDOOR 10 Modello per uso ricreativo per utilizzatori di tutte le|2017/12/tavolo-ping-pong-outdoor-10-verde|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-10-verde_111276",
];
