Gr = [
"Tavolo Ping Pong Outdoor 4|KETTLER OUTDOOR 4 Articolo No.: 07172-700 Modello per uso ricreativo|2017/12/tavolo-ping-pong-outdoor-4|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-4_110124",
"Vogatore Stroker con fascia cardio inclusa|Dim. Aperto 206 x 52 x 67 cm Dim. Chiuso - Fascia Cardiaca Sì|2017/12/vogatore-stroker-con-fascia-cardio-inclusa|data.oliviero.it/imgprodotto/vogatore-stroker-con-fascia-cardio-inclusa_14382_big",
"Palla tonificante 1,5 kg|La sfera tonificante offre un completamento agli esercizi fatti fino|2017/12/palla-tonificante-1-5-kg|data.oliviero.it/imgprodotto/palla-tonificante-1-5-kg_74583",
"Ellittica Cross M NEW|07647-800 Modello di ingresso nel mondo delle ellittiche KETTLER. La|2017/12/ellittica-cross-m-new|data.oliviero.it/imgprodotto/ellittica-cross-m-new_130314",
"Recumbent Giro R Black Edition|GIRO R 07629-000 Sicura, comoda e confortevole. Con GIRO R / GIRO|2017/12/recumbent-giro-r-black-edition|data.oliviero.it/imgprodotto/recumbent-giro-r-black-edition_130305",
"Cyclette Cycle P NEW|CYCLE P 07628-900 Versione computerizzata con sistema di frenaggio|2017/12/cyclette-cycle-p-new|data.oliviero.it/imgprodotto/cyclette-cycle-p-new_130296",
"Porta Pesi diam 25|Supporto universale che offre posto per tutto ciò che è necessario|2017/12/porta-pesi-diam-25|data.oliviero.it/imgprodotto/porta-pesi-diam-25_71165",
"Tavolo Ping Pong Sketch Pong Outdoor|Il nuovissimo tavolo da ping pong Kettler SketchPong ha un look|2017/12/tavolo-ping-pong-sketch-pong-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-sketch-pong-outdoor_147321",
"Leg Extension per Alpha Pro|PESI E PANCA NON INCLUSI Con questo accessorio leg extension per la|2017/12/leg-extension-per-alpha-pro|data.oliviero.it/imgprodotto/leg-extension-per-alpha-pro_90368",
"Vogatore Coach M|Il vogatore professionale creato e progettato per eliminare tutti gli|2017/12/vogatore-coach-m|data.oliviero.it/imgprodotto/vogatore-coach-m_6894_big",
"Tavolo Ping Pong Smash 7 da esterno|SMASH OUTDOOR 7 Piano gioco 'ALU-TEC', un rivestimento multistrato|2017/12/tavolo-ping-pong-smash-7-da-esterno|data.oliviero.it/imgprodotto/tavolo-ping-pong-smash-7-da-esterno_59087",
"Ellittica Vito M Fun|La Vito M Fun è dotata di un volano dal peso di 14 Kg, che permetterà|2017/12/ellittica-vito-m-fun|data.oliviero.it/imgprodotto/ellittica-vito-m-fun-7658-100_162632",
"Panca Multifunzione Fitmaster|La stazione multifunzione Kettler Fitmaster 300 è una stazione|2017/12/panca-multifunzione-fitmaster|data.oliviero.it/imgprodotto/panca-multifunzione-fitmaster_140051",
"Panca Multifunzione Multigym|Il Kettler Powercenter Multigym per un approccio a costi ridotti|2017/12/panca-multifunzione-multigym|data.oliviero.it/imgprodotto/panca-multifunzione-multigym_165866",
"Tavolo Ping Pong Outdoor 10 Verde|OUTDOOR 10 Modello per uso ricreativo per utilizzatori di tutte le|2017/12/tavolo-ping-pong-outdoor-10-verde|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-10-verde_111276",
];
