Gr = [
"Tavolo Ping Pong Axos Indoor 1|Ping Pong - AXOS INDOOR 1 Articolo No.: 07046-900 Caratteristiche|2017/12/tavolo-ping-pong-axos-indoor-1|data.oliviero.it/imgprodotto/tavolo-ping-pong-axos-indoor-1_110095",
"Cyclette Golf C4|KETTLER GOLF C4 Computer LCD alta risoluzione multi informazione con|2017/12/cyclette-golf-c4|data.oliviero.it/imgprodotto/cyclette-golf-c4_158003",
"Cyclette Ergo C10|Un vero ergometro con 2 modalità di utilizzo: modalità AUTO (rpm|2017/12/cyclette-ergo-c10|data.oliviero.it/imgprodotto/cyclette-ergo-c10_158044",
"Panca Addominali Universal Bench|UNIVERSAL 07629-800 Robusta panca piana/inclinabile deale per|2017/12/panca-addominali-universal-bench|data.oliviero.it/imgprodotto/panca-addominali-universal-bench_130328",
"Cyclette Ergo C8|KETTLER ERGO C8 Un vero ergometro con 2 modalità di utilizzo:|2017/12/cyclette-ergo-c8|data.oliviero.it/imgprodotto/cyclette-ergo-c8_158043",
"Cyclette Giro S1 Black|Computer LDC multi informazione, facile da usare con una|2017/12/cyclette-giro-s1-black|data.oliviero.it/imgprodotto/cyclette-giro-s1-black_157977",
"Ellittica Advantage Rivo M 2012|Il nuovo Crosstrainer Kettler Rivo M è uno attrezzo home-fitness|2017/12/ellittica-advantage-rivo-m-2012|data.oliviero.it/imgprodotto/ellittica-advantage-rivo-m-2012_12829_big",
"Vogatore Favorit|Vogare è un allenamento di resistenza che impegna omogeneamente tutti|2017/12/vogatore-favorit|data.oliviero.it/imgprodotto/vogatore-favorit_43_big",
"Ergo S con Fascia Cardio Polar|ERGO S con fascia cardio Polar incluso World Tours 2.0 up-grade|2017/12/ergo-s-con-fascia-cardio-polar|data.oliviero.it/imgprodotto/ergo-s-con-fascia-cardio-polar_162669",
"Recumbent Cycle R NEW|7986-897 La bicicletta da camera recumbent CYCLE R garantisce una|2017/12/recumbent-cycle-r-new|data.oliviero.it/imgprodotto/recumbent-cycle-r-new_130299",
"Cyclette Giro S3 black|KETTLER GIRO S3 BLACK Computer LCD multi informazione con qualità|2017/12/cyclette-giro-s3-black|data.oliviero.it/imgprodotto/cyclette-giro-s3-black_157994",
"Gym Ball 65 cm|PALLA DA GINNASTICA LINEA BALANCE KETTLER COD. 7350-124 (Ø 65 cm|2017/12/gym-ball-65-cm|data.oliviero.it/imgprodotto/gym-ball-65-cm_141942",
"Ping Pong Axos Indoor 10|Piano gioco in speciale materiale di legno spessore mm.22 con|2017/12/ping-pong-axos-indoor-10|data.oliviero.it/imgprodotto/ping-pong-axos-indoor-10_147334",
"Cyclette Ergo C6|KETTLER ERGO C6 Un vero ergometro con 2 modalità di utilizzo:|2017/12/cyclette-ergo-c6|data.oliviero.it/imgprodotto/cyclette-ergo-c6_158042",
"Tavolo Ping Pong Outdoor 4|KETTLER OUTDOOR 4 Articolo No.: 07172-700 Modello per uso ricreativo|2017/12/tavolo-ping-pong-outdoor-4|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-4_110124",
"Vogatore Stroker con fascia cardio inclusa|Dim. Aperto 206 x 52 x 67 cm Dim. Chiuso - Fascia Cardiaca Sì|2017/12/vogatore-stroker-con-fascia-cardio-inclusa|data.oliviero.it/imgprodotto/vogatore-stroker-con-fascia-cardio-inclusa_14382_big",
"Palla tonificante 1,5 kg|La sfera tonificante offre un completamento agli esercizi fatti fino|2017/12/palla-tonificante-1-5-kg|data.oliviero.it/imgprodotto/palla-tonificante-1-5-kg_74583",
"Ellittica Cross M NEW|07647-800 Modello di ingresso nel mondo delle ellittiche KETTLER. La|2017/12/ellittica-cross-m-new|data.oliviero.it/imgprodotto/ellittica-cross-m-new_130314",
"Recumbent Giro R Black Edition|GIRO R 07629-000 Sicura, comoda e confortevole. Con GIRO R / GIRO|2017/12/recumbent-giro-r-black-edition|data.oliviero.it/imgprodotto/recumbent-giro-r-black-edition_130305",
"Cyclette Cycle P NEW|CYCLE P 07628-900 Versione computerizzata con sistema di frenaggio|2017/12/cyclette-cycle-p-new|data.oliviero.it/imgprodotto/cyclette-cycle-p-new_130296",
"Porta Pesi diam 25|Supporto universale che offre posto per tutto ciò che è necessario|2017/12/porta-pesi-diam-25|data.oliviero.it/imgprodotto/porta-pesi-diam-25_71165",
"Tavolo Ping Pong Sketch Pong Outdoor|Il nuovissimo tavolo da ping pong Kettler SketchPong ha un look|2017/12/tavolo-ping-pong-sketch-pong-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-sketch-pong-outdoor_147321",
"Leg Extension per Alpha Pro|PESI E PANCA NON INCLUSI Con questo accessorio leg extension per la|2017/12/leg-extension-per-alpha-pro|data.oliviero.it/imgprodotto/leg-extension-per-alpha-pro_90368",
"Vogatore Coach M|Il vogatore professionale creato e progettato per eliminare tutti gli|2017/12/vogatore-coach-m|data.oliviero.it/imgprodotto/vogatore-coach-m_6894_big",
"Tavolo Ping Pong Smash 7 da esterno|SMASH OUTDOOR 7 Piano gioco 'ALU-TEC', un rivestimento multistrato|2017/12/tavolo-ping-pong-smash-7-da-esterno|data.oliviero.it/imgprodotto/tavolo-ping-pong-smash-7-da-esterno_59087",
"Ellittica Vito M Fun|La Vito M Fun è dotata di un volano dal peso di 14 Kg, che permetterà|2017/12/ellittica-vito-m-fun|data.oliviero.it/imgprodotto/ellittica-vito-m-fun-7658-100_162632",
"Panca Multifunzione Fitmaster|La stazione multifunzione Kettler Fitmaster 300 è una stazione|2017/12/panca-multifunzione-fitmaster|data.oliviero.it/imgprodotto/panca-multifunzione-fitmaster_140051",
"Panca Multifunzione Multigym|Il Kettler Powercenter Multigym per un approccio a costi ridotti|2017/12/panca-multifunzione-multigym|data.oliviero.it/imgprodotto/panca-multifunzione-multigym_165866",
"Tavolo Ping Pong Outdoor 10 Verde|OUTDOOR 10 Modello per uso ricreativo per utilizzatori di tutte le|2017/12/tavolo-ping-pong-outdoor-10-verde|data.oliviero.it/imgprodotto/tavolo-ping-pong-outdoor-10-verde_111276",
];
