Gr = [
"Monopattino a tre ruote ADVENTURE KID GRAND PRIX rosso|Descrizione: Pieghevole : con sistema di chiusura rapido e sicuro|2017/12/monopattino-a-tre-ruote-adventure-kid-grand-prix-rosso|data.oliviero.it/imgprodotto/monopattino-a-tre-ruote-adventure-kid-grand-prix-rosso_162384",
"Skateboard Rocket Complete Fade Series|Skateboard perfetto per i principianti Deck: 7 strati macchiato|2017/12/skateboard-rocket-complete-fade-series|data.oliviero.it/imgprodotto/skateboard-rocket-complete-fade-series_157623",
"Longboard Carve Palm 35|Longboard Carve Palm 35 Caratteristiche Materiale (7 Ply Canadian|2017/12/longboard-carve-palm-35|data.oliviero.it/imgprodotto/longboard-carve-palm-35_125542",
"Skateboard Rocket Complete Eclipse Series|Nuova gamma da Skateboards Rocket! Deck: 7 strati Hardrock Acero|2017/12/skateboard-rocket-complete-eclipse-series|data.oliviero.it/imgprodotto/skateboard-rocket-complete-eclipse-series_157625",
"Longboard CRUISER BAY NEW|Descrizione: Dimensioni tavola : 96X24 cm spessore 12,5 mm Materiale|2017/12/longboard-cruiser-bay-new|data.oliviero.it/imgprodotto/longboard-cruiser-bay-new_162377",
"Skateboards Pro Script|Lunghezza: 31.0\"; Larghezza: 7.75\"; Tavola: 7 strati in acero; Ruote:|2017/12/skateboards-pro-script|data.oliviero.it/imgprodotto/skateboards-pro-script_151102",
"Longboard Mellow 41\"|Longboard Shore Crash Dimensione: 41\" x 9,25\" Colore: Ciano e azzurro|2017/12/longboard-mellow-41|data.oliviero.it/imgprodotto/longboard-mellow-41_125115",
"Skateboard FREEDOM PRO MILITARY|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola : ABS|2017/12/skateboard-freedom-pro-military|data.oliviero.it/imgprodotto/skateboard-freedom-pro-military_162376",
"Mini Longboard Maui|Longboard Maui 32\" Dimensione: 37\" x 9\" Carrello Alluminio Ruote 62|2017/12/mini-longboard-maui|data.oliviero.it/imgprodotto/mini-longboard-maui_151099",
"Skateboard Hula 30\"|Caratteristiche Stile di guida: Cruising, lunghezza: 76 cm|2017/12/skateboard-hula-30|data.oliviero.it/imgprodotto/skateboard-hula-30_165543",
"Scarpe con Ruote Force|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-force|data.oliviero.it/imgprodotto/scarpe-con-ruote-force-770836_157596",
"Monopattino RAPTOR PRO 200 nero arancio|Descrizione: Pieghevole : salvaspazio Tracolla removibile : inclusa|2017/12/monopattino-raptor-pro-200-nero-arancio|data.oliviero.it/imgprodotto/monopattino-raptor-pro-200-nero-arancio_162386",
"Longboard Carve Aloha 40|Longboard Carve Aloha 40 Caratteristiche Materiale (7 Ply Can. Maple|2017/12/longboard-carve-aloha-40|data.oliviero.it/imgprodotto/longboard-carve-aloha-40_125544",
"Skateboard FREEDOM tavola nera|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola|2017/12/skateboard-freedom-tavola-nera|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-nera-ruote-arancio_162374",
"Skateboard Cobra Surfing Board|Surfing Board Cobra, fantastico surfing board disponibile in|2017/12/skateboard-cobra-surfing-board|data.oliviero.it/imgprodotto/skateboard-cobra-surfing-board-70-710-0041_87728",
"Skateboard TRIBE PRO BLOODY SKULL|Descrizione: Dimensioni tavola : 79x20 cm Materiale tavola|2017/12/skateboard-tribe-pro-bloody-skull|data.oliviero.it/imgprodotto/skateboard-tribe-pro-bloody-skull_162366",
"Skateboard Dollars and Diamonds 31,5\"|Skateboard Dollars and Diamonds Tavola: dt-4, pro shape, 31,5'x7,5'|2017/12/skateboard-dollars-and-diamonds-31-5|data.oliviero.it/imgprodotto/skateboard-dollars-and-diamonds-31-5_125120",
"Longboard Calm Water 38\"|38\" Longboard \"Calm Water\" Serie California Dimensione: 38\" x 9,5\"|2017/12/longboard-calm-water-38|data.oliviero.it/imgprodotto/longboard-calm-water-38_125090",
"Skateboard STREET PRO GRAFFITI NEW|Descrizione: Dimensioni tavola : 79x20 cm Materiale tavola|2017/12/skateboard-street-pro-graffiti-new|data.oliviero.it/imgprodotto/skateboard-street-pro-graffiti-new_162370",
"Scarpe con Ruote|Tomaia in pelle sintetica con linguetta e collo imbottiti per un|2017/12/scarpe-con-ruote|data.oliviero.it/imgprodotto/scarpe-con-ruote-premium-1-lo_173202",
"Skateboard Music Punk|Tavola perfetta per i principianti Piattaforma: 7.5 / 7.75 '' x 31 ''|2017/12/skateboard-music-punk|data.oliviero.it/imgprodotto/skateboard-music-punk_151098",
"Skateboard FREEDOM tavola gialla|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola|2017/12/skateboard-freedom-tavola-gialla|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-gialla-ruote-azzurre_162372",
"Scarpe con Ruote Speed X2|Caratteristiche Tecniche : Le Heelys sono scarpe munite di ruote con|2017/12/scarpe-con-ruote-speed-x2|data.oliviero.it/imgprodotto/scarpe-con-ruote-speed-x2-770047k_153466",
"Surfskate Birdless 29\"|Il Ventura 29″ riproduce fedelmente la sensazione di una tavola da|2017/12/surfskate-birdless-29|data.oliviero.it/imgprodotto/surfskate-birdless-29_165563",
"Scarpe con Ruote Veloz|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-veloz|data.oliviero.it/imgprodotto/scarpe-con-ruote-veloz-770557h_131810",
"Skateboard FREEDOM tavola rossa|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola|2017/12/skateboard-freedom-tavola-rossa|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-rossa-ruote-gialle_162371",
"Skateboard Fishtail|Skateboard Fishtail, tavola concava da cm. 68,5 in legno di acero a|2017/12/skateboard-fishtail|data.oliviero.it/imgprodotto/skateboard-fishtail_87724",
"Longboard Sunshine Palm|Dimensione: 34\" x 9\" Carrello Alluminio Ruote 62 mm x 51mm Il|2017/12/longboard-sunshine-palm|data.oliviero.it/imgprodotto/longboard-sunshine-palm_151101",
"Hoverboard SKYLON 6.5|\"Hoverboard SKYLON 6.5 con Descrizione : Diametro ruota: 16,5 cm|2017/12/hoverboard-skylon-6-5|data.oliviero.it/imgprodotto/hoverboard-skylon-6-5_161078",
"Surfskate Ventura 29\"|Il Ventura 29″ riproduce fedelmente la sensazione di una tavola da|2017/12/surfskate-ventura-29|data.oliviero.it/imgprodotto/surfskate-ventura-29_165555",
"Skateboard FREEDOM PRO USA FLAG|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola : ABS|2017/12/skateboard-freedom-pro-usa-flag|data.oliviero.it/imgprodotto/skateboard-freedom-pro-usa-flag_162375",
"Skateboard TRIBE PRO USA FLAG|Descrizione: Dimensioni tavola : 79x20 cm Materiale tavola|2017/12/skateboard-tribe-pro-usa-flag|data.oliviero.it/imgprodotto/skateboard-tribe-pro-usa-flag_162368",
"Skateboard Torpedo 22,5in|Skateboard Torpedo 22,5in 28 \"x 7.5\" polipropilene stampato ad alto|2017/12/skateboard-torpedo-22-5in|data.oliviero.it/imgprodotto/skateboard-torpedo-22-5in_80083",
"Hoverboard TRACK 6.5|Hoverboard TRACK 6.5 Ø Descrizione: Diametro ruota: 16,5 cm (6.5\")|2017/12/hoverboard-track-6-5|data.oliviero.it/imgprodotto/hoverboard-track-6-5_161077",
"Scarpe con ruote Propel 2.0|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-propel-2-0|data.oliviero.it/imgprodotto/scarpe-con-ruote-propel-2-0-770603h_146320",
"Hoverboard VOYAGER 10.0|Hoverboard VOYAGER 10.0 Garlando Descrizione: Diametro ruota: 25,4 cm|2017/12/hoverboard-voyager-10-0|data.oliviero.it/imgprodotto/hoverboard-voyager-10-0_161079",
"Longboard Carve Tombrider 37|Longboard Carve Tombrider 37 Caratteristiche Materiale (6 Ply|2017/12/longboard-carve-tombrider-37|data.oliviero.it/imgprodotto/longboard-carve-tombrider-37_125543",
"Skateboard FREEDOM tavola azzurra|Skateboard con Ruote in fibra di poliuretano ad alta resistenza e durabilità|2017/08/skateboard-freedom-tavola-azzurra|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-azzurra-ruote-gialle_162373",
];
