Gr = [
"Skateboard STREET PRO GRAFFITI NEW|Descrizione: Dimensioni tavola : 79x20 cm Materiale tavola|2017/12/skateboard-street-pro-graffiti-new|data.oliviero.it/imgprodotto/skateboard-street-pro-graffiti-new_162370",
"Skateboard FREEDOM tavola gialla|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola|2017/12/skateboard-freedom-tavola-gialla|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-gialla-ruote-azzurre_162372",
"Surfskate Birdless 29\"|Il Ventura 29″ riproduce fedelmente la sensazione di una tavola da|2017/12/surfskate-birdless-29|data.oliviero.it/imgprodotto/surfskate-birdless-29_165563",
"Skateboard FREEDOM tavola rossa|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola|2017/12/skateboard-freedom-tavola-rossa|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-rossa-ruote-gialle_162371",
"Skateboard Fishtail|Skateboard Fishtail, tavola concava da cm. 68,5 in legno di acero a|2017/12/skateboard-fishtail|data.oliviero.it/imgprodotto/skateboard-fishtail_87724",
"Hoverboard SKYLON 6.5|\"Hoverboard SKYLON 6.5 con Descrizione : Diametro ruota: 16,5 cm|2017/12/hoverboard-skylon-6-5|data.oliviero.it/imgprodotto/hoverboard-skylon-6-5_161078",
"Surfskate Ventura 29\"|Il Ventura 29″ riproduce fedelmente la sensazione di una tavola da|2017/12/surfskate-ventura-29|data.oliviero.it/imgprodotto/surfskate-ventura-29_165555",
"Skateboard FREEDOM PRO USA FLAG|Descrizione: Dimensioni tavola : 57x15,2 cm Materiale tavola : ABS|2017/12/skateboard-freedom-pro-usa-flag|data.oliviero.it/imgprodotto/skateboard-freedom-pro-usa-flag_162375",
"Skateboard TRIBE PRO USA FLAG|Descrizione: Dimensioni tavola : 79x20 cm Materiale tavola|2017/12/skateboard-tribe-pro-usa-flag|data.oliviero.it/imgprodotto/skateboard-tribe-pro-usa-flag_162368",
"Hoverboard TRACK 6.5|Hoverboard TRACK 6.5 Ø Descrizione: Diametro ruota: 16,5 cm (6.5\")|2017/12/hoverboard-track-6-5|data.oliviero.it/imgprodotto/hoverboard-track-6-5_161077",
"Hoverboard VOYAGER 10.0|Hoverboard VOYAGER 10.0 Garlando Descrizione: Diametro ruota: 25,4 cm|2017/12/hoverboard-voyager-10-0|data.oliviero.it/imgprodotto/hoverboard-voyager-10-0_161079",
"Skateboard FREEDOM tavola azzurra|Skateboard con Ruote in fibra di poliuretano ad alta resistenza e durabilità|2017/08/skateboard-freedom-tavola-azzurra|data.oliviero.it/imgprodotto/skateboard-freedom-tavola-azzurra-ruote-gialle_162373",
"Longboard CRUISER LAND NEW|Skateboard Longboard in fibra di poliuretano ad alta resistenza|2017/07/longboard-cruiser-land-new|data.oliviero.it/imgprodotto/longboard-cruiser-land-new_162378",
];
