Gr = [
"I 10 Smartphone migliori a novembre 2016|I 10 Smartphone più consigliati da chi li ha comprati davvero|2016/11/i-10-smartphone-migliori-a-novembre-2016|AZ_412i-yS769L",
"Caricabatterie per Cellulari da Auto: i 10 migliori a novembre 2016|I 10 Caricabatterie per Cellulari da Auto migliori, subito disponibili|2016/11/caricabatterie-per-cellulari-da-auto-i-10-migliori-a-novembre-2016|AZ_41evr9FwwlL",
"Smartphone: i 15 migliori a luglio 2016|La top 15 dei migliori smartphone disponibili per l'acquisto: luglio 2016|2016/07/smartphone-i-15-migliori-a-luglio-2016.html?t=smartphone,cellulari,telefonia,telefono-cellulare,elettronica,dual-sim,android,app,sms,bluetooth,huawei,homtom,lg,motorola,samsung&amp;d=15|AZ_41XlgJ1gy+L",
"Caricabatterie per cellulari: i migliori in commercio a maggio 2016|I 16 caricabatterie per cellulari migliori: maggio 2016|2016/05/caricabatterie-per-cellulari-i-migliori-in-commercio-a-maggio-2016.html?t=smartphone,caricabatterie-cellulari,telefono-cellulare,cellulari,telefonia,dual-sim,android,app,sms,usb,elettronica,iphone,aukey,samsung&amp;d=24|AZ_41QDpSloOjL",
"La top 12 dei migliori smartphone Android in commercio: maggio 2016|La classifica dei 12 smartphone Android più venduti sul mercato|2016/05/la-top-12-dei-migliori-smartphone-android-in-commercio-maggio-2016.html?t=smartphone,telefono-cellulare,cellulari,telefonia,elettronica,dual-sim,android,app,sms,bluetooth,huawei,samsung,asus,motorola&amp;d=12|AZ_41G+npIlVGL",
"Un bellissimo smartphone Huawei a un prezzo incredibilmente basso|Prima leggete le caratteristiche di questo smartphone e poi provate a indovinare il prezzo|2016/02/un-bellissimo-smartphone-huawei-a-un-prezzo-incredibilmente-basso.html?t=smartphone,telefono-cellulare,telefonia,dual-sim,android,huawei&amp;d=16|AZ_41HoxvG5W7L",
"Uno smartphone con un grande display e un piccolo prezzo|Alcatel One Touch Pop 3, anche in confezione regalo con spedizione gratuita!|2016/01/uno-smartphone-con-un-grande-display-e-un-piccolo-prezzo.html?t=smartphone,telefono-cellulare,telefonia,dual-sim,android,alcatel&amp;d=12|AZ_8187r4vRqlL",
];
