Gr = [
"Friggitrici ad aria: le 14 migliori ad agosto 2016|Le 14 friggitrici ad aria più amate: la guida all'acquisto di agosto 2016|2016/08/friggitrici-ad-aria-le-14-migliori-ad-agosto-2016|AZ_41++XO88H6L",
"La top 13 dei migliori frullatori da tavolo: luglio 2016|I 13 frullatori da tavolo più apprezzati da chi lavora davvero in cucina|2016/07/la-top-13-dei-migliori-frullatori-da-tavolo-luglio-2016.html?t=cucina,frullatori-tavolo,frullatori,elettrodomestici,mixer,casa,bar,cibo,alimentazione,alimenti,gastronomia,tritatutto,duronic,electrolux,philips,black-and-decker,kenwood,princess,klarstein,tristar,imetec&amp;d=6|AZ_51plaqbLv0L",
"Le 15 centrifughe più apprezzate: luglio 2016|Le 15 centrifughe più gettonate: la classifica aggiornata a luglio 2016|2016/07/le-15-centrifughe-piu-apprezzate-luglio-2016.html?t=cucina,centrifughe,elettrodomestici,frutta,verdura,estrattori-di-succo,dieta,vitamine,salute,alimentazione,alimenti,casa,cibo,risparmio,succo,agrume,spremiagrumi,spremiagrumi-elettrici,moulinex,severin,princess,tristar,philips,russell-hobbs,bosch,rgv,clatronic,duronic&amp;d=1|AZ_41iY4xdDcnL",
"Piastre elettriche: le 14 migliori a giugno 2016|Le 14 piastre elettriche più apprezzate: giugno 2016|2016/06/piastre-elettriche-le-14-migliori-a-giugno-2016.html?t=cucina,piastre-elettriche,casa,bistecchiere,alimentazione,cibo,cottura,elettrodomestici,forni-elettrici,fornetti-elettrici,griglie-elettriche,severin,duronic,russell-hobbs,tristar,rowenta,koenig&amp;d=13|AZ_41ObagJyrFL",
"Il meglio delle gelatiere in commercio: maggio 2016|Le 13 gelatiere al top oggi sul mercato: maggio 2016|2016/05/il-meglio-delle-gelatiere-in-commercio-maggio-2016.html?t=cibo,gelato,gelatiere,sorbetto,yogurt,fresco,ghiaccio,panna,elettrodomestici,risparmio,gastronomia,alimentazione,cucina,de-longhi,koenig,duronic,gaggia,ariete,princess,kenwood&amp;d=30|AZ_31v6RMtROAL",
"La classifica dei 16 deumidificatori migliori di maggio 2016|I 16 deumidificatori migliori sul mercato|2016/05/la-classifica-dei-16-deumidificatori-migliori-di-maggio-2016.html?t=casa,letto,ufficio,climatizzazione,umidificatori,deumidificatori,aerosol,benessere,aria,respirazione,naso,gola,bronchi,polmoni,purificatori-d-aria,de-longhi,probreeze,olimpia,argoclima,duronic&amp;d=13|AZ_315fziMiu3L",
"18 marzo: i 15 deumidificatori migliori|Ecco i deumidificatori migliori, valutati al 18 marzo|2016/03/18-marzo-i-15-deumidificatori-migliori.html?t=casa,cucina,ufficio,climatizzazione,umidificatori,deumidificatori,de-longhi,probreeze,duronic,argoclima&amp;d=18|AZ_315fziMiu3L",
];
