Gr = [
"Calcio balilla G-500 Pure White|Estrema robustezza della struttura, eccellente stabilità ed|2017/12/calcio-balilla-g-500-pure-white|data.oliviero.it/imgprodotto/calcio-balilla-g-500-pure-white_72084",
"Calcio balilla G 500 Weatherproof|Modello per esterno, creato per soddisfare le esigenze di tutti|2017/12/calcio-balilla-g-500-weatherproof|data.oliviero.it/imgprodotto/calcio-balilla-g-500-weatherproof_149969",
"Calcio balilla XXL|Calciobalilla extralarge, per 8 giocatori, per un divertimento doppio|2017/12/calcio-balilla-xxl|data.oliviero.it/imgprodotto/calcio-balilla-xxl_150038",
"Calcio balilla G-500 Military Jungle|Estrema robustezza della struttura, eccellente stabilità ed|2017/12/calcio-balilla-g-500-military-jungle|data.oliviero.it/imgprodotto/calcio-balilla-g-500-military-jungle_72105",
"Calcio balilla Professional Training|Nuovo modello senza gettoniera che riprende i colori e le prestazioni|2017/12/calcio-balilla-professional-training|data.oliviero.it/imgprodotto/calcio-balilla-professional-training_136313",
"Calcio balilla G-500 Decò Ash Grey|Estrema robustezza della struttura, eccellente stabilità ed|2017/12/calcio-balilla-g-500-deco-ash-grey|data.oliviero.it/imgprodotto/calcio-balilla-g-500-dec%C3%B2-ash-grey_72100",
"Calcio balilla College Pro Cover|Calcio balilla senza gettoniera Mobile: Multistrato di pioppo|2017/12/calcio-balilla-college-pro-cover|data.oliviero.it/imgprodotto/calcio-balilla-college-pro-cover_136319",
"Calcio balilla G-500 Pure White H2O|Estrema robustezza della struttura, eccellente stabilità ed|2017/12/calcio-balilla-g-500-pure-white-h2o|data.oliviero.it/imgprodotto/calcio-balilla-g-500-pure-white-h2o_72088",
"Calcio balilla F 200 evolution|Prestigioso e adatto anche a funzioni di rappresentanza, F-200|2017/12/calcio-balilla-f-200-evolution|data.oliviero.it/imgprodotto/calcio-balilla-f-200-evolution_149979",
"Calcio balilla G-500 Pied de Poule|Estrema robustezza della struttura, eccellente stabilità ed|2017/12/calcio-balilla-g-500-pied-de-poule|data.oliviero.it/imgprodotto/calcio-balilla-g-500-pied-de-poule_72106",
"Calcio balilla Top Speed Official Competition (ITSF)|Calcio balilla Top Speed Official Competition omologato ITSF MOBILE|2017/12/calcio-balilla-top-speed-official-competition-itsf|data.oliviero.it/imgprodotto/calcio-balilla-top-speed-official-competition-itsf-_147265",
"Calcio balilla Roby Color Rosso|Calciobalilla senza gettoniera studiato per adattare la qualità dei|2017/12/calcio-balilla-roby-color-rosso|data.oliviero.it/imgprodotto/calcio-balilla-roby-color-rosso_72658",
"Calcio balilla Family Rosso|Calcio balilla Family Caratteristiche tecniche: Mobile in legno|2017/12/calcio-balilla-family-rosso|data.oliviero.it/imgprodotto/calcio-balilla-family-rosso_72666",
"Calcio Balilla International Champion Cover|Calcio Balilla coperto con vetro, Indoor con gettoniera MOBILE|2017/12/calcio-balilla-international-champion-cover|data.oliviero.it/imgprodotto/calcio-balilla-international-champion-cover_147258",
"Calcio balilla College Lift|MOBILE MULTISTRATO DI PIOPPO RIVESTITO IN LAMINATO MELAMINICO|2017/12/calcio-balilla-college-lift|data.oliviero.it/imgprodotto/calcio-balilla-college-lift_147233",
"Calcio balilla G-500 Animal Leopard|Estrema robustezza della struttura, eccellente stabilità ed|2017/12/calcio-balilla-g-500-animal-leopard|data.oliviero.it/imgprodotto/calcio-balilla-g-500-animal-leopard_72109",
"Calcio Balilla College 4x4 Blu|MOBILE MULTISTRATO DI PIOPPO RIVESTITO IN LAMINATO MELAMINICO|2017/12/calcio-balilla-college-4x4-blu|data.oliviero.it/imgprodotto/calcio-balilla-college-4x4-blu_147237",
"Calcio balilla Olympic con Gettoniera|OLYMPIC Prodotto in due diverse opzioni di colore: radica e nero|2017/12/calcio-balilla-olympic-con-gettoniera|data.oliviero.it/imgprodotto/calcio-balilla-olympic-con-gettoniera_2010_big",
"Calcio balilla G 2000 Evolution|Calcio balilla nero con bordatura e serigrafia silver, 10 palline in dotazione|2017/06/calcio-balilla-g-2000-evolution|data.oliviero.it/imgprodotto/calcio-balilla-g-2000-evolution_150011",
"Calcio balilla Champion|Calciobalilla Champion con gettoniera per il gioco internazionale|2017/04/calcio-balilla-champion|data.oliviero.it/imgprodotto/calcio-balilla-champion_73168",
];
