Gr = [
"Set Basket USA con canestro e pallone|Canestro e Pallone Basket USA set completo con rete e kit di|2017/12/set-basket-usa-con-canestro-e-pallone|data.oliviero.it/imgprodotto/set-basket-usa-con-canestro-e-pallone-70-320-0091_87713",
"Utilbasket a colonna|UTILBASKET A COLONNA con canestro e rete(senza tabellone)|2017/12/utilbasket-a-colonna|data.oliviero.it/imgprodotto/utilbasket-a-colonna_162172",
"Canestro San Diego|Un tabellone da basket professionale, dotato di tutto quello che|2017/12/canestro-san-diego|data.oliviero.it/imgprodotto/canestro-san-diego_1759_big",
"Impianto basket a parete|IMPIANTO BASKET-MINIBASKET A PARETE SINGOLO con piastra da fissare|2017/12/impianto-basket-a-parete|data.oliviero.it/imgprodotto/impianto-basket-a-parete_162170",
"Canestro basket sganciabile FIBA|CANESTRO BASKET SGANCIABILE FIBA a norme FIBA. Caratteristiche|2017/12/canestro-basket-sganciabile-fiba|data.oliviero.it/imgprodotto/canestro-basket-sganciabile-fiba_162181",
"Canestro Phoenix|Il divertimento da spiaggia per bambini e ragazzi in un kit completo|2017/12/canestro-phoenix|data.oliviero.it/imgprodotto/canestro-phoenix_1751_big",
"Canestro Boston|Boston è un tabellone da basket di qualità professionale e di misure|2017/12/canestro-boston|data.oliviero.it/imgprodotto/canestro-boston_1745_big",
"1 Piantana Basket Magic|Caratteristiche tecniche: Altezza cm. 158, con base zavorrabile con|2017/12/1-piantana-basket-magic|data.oliviero.it/imgprodotto/1-piantana-basket-magic-70-320-0046_157444",
"Canestro Tabellone 6098|UNICO PEZZO DISPONIBILE. PRODOTTO VENDUTO MONTATO SU BANCALE. EX|2017/12/canestro-tabellone-6098|data.oliviero.it/imgprodotto/canestro-tabellone-6098_19361_big",
"Canestro Detroit|Detroit è il tabellone da basket con colonna con altezza regolabile|2017/12/canestro-detroit|data.oliviero.it/imgprodotto/canestro-detroit_1755_big",
"Canestro El Paso|Tabellone da basket con colonna di altezza regolabile, adatto per|2017/12/canestro-el-paso|data.oliviero.it/imgprodotto/canestro-el-paso_1754_big",
"Canestri basket zincati a caldo|CANESTRI BASKET ZINCATI A CALDO rinforzati. Caratteristiche tecniche:|2017/12/canestri-basket-zincati-a-caldo|data.oliviero.it/imgprodotto/canestri-basket-zincati-a-caldo_162171",
"Basket a colonna Junior|BASKETBALL JUNIOR trasportabile. Caratteristiche tecniche: Base in|2017/12/basket-a-colonna-junior|data.oliviero.it/imgprodotto/basket-a-colonna-junior_162173",
"Canestro Basket Regolamentare 46 cm|Canestro basket adatto per tabellone regolamentare. Caratteristiche|2017/12/canestro-basket-regolamentare-46-cm|data.oliviero.it/imgprodotto/canestro-basket-regolamentare-46-cm-70-320-0021_157440",
"Canestro Seattle|Seattle è un tabellone da basket di qualità professionale e di misure|2017/12/canestro-seattle|data.oliviero.it/imgprodotto/canestro-seattle_1747_big",
"Canestro San Jose|un tabellone da basket di elevata qualità e design attraente, con|2017/12/canestro-san-jose|data.oliviero.it/imgprodotto/canestro-san-jose_1758_big",
"Piantana Basket USA trasportabile|1 Piantana Basket USA trasportabile e regolabile|2017/05/piantana-basket-usa-trasportabile|data.oliviero.it/imgprodotto/1-piantana-basket-usa-70-320-0016_157445",
];
