Gr = [
"Motozappe, Chitarre Elettriche: i 5 migliori di settembre 2016|I 5 migliori prodotti in Motozappe, Chitarre Elettriche|2016/09/motozappe-chitarre-elettriche-i-5-migliori-di-settembre-2016|AZ_31+U4v4Nr+L",
"10 chitarre elettriche consigliate: agosto 2016|Le 10 chitarre elettriche che vanno per la maggiore: la classifica|2016/08/10-chitarre-elettriche-consigliate-agosto-2016|AZ_31PRdTjHgpL",
"I 15 mixer per DJ al top: luglio 2016|La top 15 dei migliori mixer per DJ subito disponibili: luglio 2016|2016/07/i-15-mixer-per-dj-al-top-luglio-2016|AZ_31kRDvTBgCL",
"Video - Alan Walker sbarca in Grand Theft Auto|Un machinima di Faded girato completamente in Grand Theft Auto|2016/07/video-alan-walker-sbarca-in-grand-theft-auto.html?t=musica,canzoni,alan-walker,youtube,social-network,facebook,gaming,videogiochi,geek,nerd,machinima,grand-theft-auto&amp;d=22|grand-theft-auto",
"Prepariamoci a nuove esistenze: siete pronti per la prossima iterazione?|Ciò che deve accadere accadrà, perché è già accaduto|2016/06/prepariamoci-a-nuove-esistenze-siete-pronti-per-la-prossima-iterazione.html?t=fantascienza,geek,scrittori,ted-chiang,musica,canzoni,cantanti,franco-battiato,mondo-virtuale,realta-virtuale,metaverso,scienza,nick-bostrom&amp;d=10|recursion",
"Video - Quando Faded di Alan Walker era ancora Fade|La hit del momento ha una storia lunga, ed è rimasta in cantiere almeno un paio d'anni|2016/05/video-quando-faded-di-alan-walker-era-ancora-fade.html?t=musica,canzoni,sex-pistols,cantanti,alan-walker,mr-robot,serie-tv,sony&amp;d=15|YT_HHpVDRJ1Esg",
"Video - Se hai perso il transito di Mercurio e ora vuoi ammazzarti|ASPETTA, non tutto è perduto!|2016/05/video-se-hai-perso-il-transito-di-mercurio-e-ora-vuoi-ammazzarti.html?t=scienza,astronomia,astrofisica,spazio,inaf,pianeta,mercurio,sole,napoli,pink-floyd,queen,canzoni&amp;d=11|YT__uuVDA0FLlU",
"Da dove viene quel testo di Bob Marley?|Il discorso fatto alle Nazioni Unite dall'imperatore d'Etiopia, Hailé Selassié|2016/04/da-dove-viene-quel-testo-di-bob-marley.html?t=musica,bob-marley,giamaica,haile-selassie,canzoni,etiopia,africa,angola,mozambico,sudafrica&amp;d=18|bob-marley",
];
