Gr = [
"Le 10 Bistecchiere più quotate: dicembre 2016|Le 10 Bistecchiere che piacciono di più, disponibili da subito|2016/12/le-10-bistecchiere-piu-quotate-dicembre-2016|AZ_41PkSDq-ECL",
"I 10 barbecue elettrici migliori: ottobre 2016|I 10 barbecue elettrici che vanno per la maggiore, disponibili subito|2016/10/i-10-barbecue-elettrici-migliori-ottobre-2016|AZ_41yWuU5ChaL",
"Regolacapelli, Barbecue a Gas: i 5 migliori di settembre 2016|I 5 migliori prodotti in Regolacapelli, Barbecue a Gas|2016/09/regolacapelli-barbecue-a-gas-i-5-migliori-di-settembre-2016|AZ_31aIbn0FthL",
"Barbecue a gas: i 14 migliori a luglio 2016|I 14 barbecue a gas più comprati sul mercato: luglio 2016|2016/07/barbecue-a-gas-i-14-migliori-a-luglio-2016.html?t=cucina,barbecue,gas,grill,cibo,carne,gastronomia,alimentazione,outdoor,aria-aperta,giardino,terrazza,picnic,campeggio,camping,camper,tende-campeggio,tempo-libero,amici,famiglia&amp;d=23|AZ_51hQKvVWW1L",
"I 14 barbecue che incontrano il maggiore gradimento: giugno 2016|La top 14 dei migliori barbecue in commercio a giugno 2016|2016/06/i-14-barbecue-che-incontrano-il-maggiore-gradimento-giugno-2016.html?t=giardino,barbecue,picnic,terrazza,grill,tempo-libero,amici,famiglia,casa,cucina,cibo,carne,gastronomia,alimentazione&amp;d=10|AZ_412I-faTgbL",
"I 10 migliori essiccatori disponibili all'aprile 2016|Tutto il meglio degli essiccatori|2016/04/i-10-migliori-essiccatori-disponibili-all-aprile-2016.html?t=cucina,essiccatori,cibo,casa,alimentazione,gastronomia,cottura,dieta,elettrodomestici,grassi,benessere,vitamine,calorie,frutta,verdura,spezie,carne,pesce,melchioni,severin,beper,clatronic,princess,klarstein&amp;d=19|AZ_415chNCq9ZL",
"I 15 cibi da evitare assolutamente per una serata piccante|La lista nera dei cibi anti-afrodisiaci, stilata da una nutrizionista per il quotidiano Daily Mail|2015/04/i-15-cibi-da-evitare-assolutamente-per-una-serata-piccante.html?t=amore,dieta,alimentazione,broccoli,cioccolato,fagioli,formaggio,liquirizia,vino,carne,energy-drink&amp;d=13|couple-bed-sleepy",
];
