Gr = [
"I 15 ventilatori da tavolo più acquistati: luglio 2016|I 15 ventilatori da tavolo che vanno per la maggiore: la classifica aggiornata a luglio 2016|2016/07/i-15-ventilatori-da-tavolo-piu-acquistati-luglio-2016|AZ_51yc+UHPAPL",
"I 15 ventilatori a piantana migliori: luglio 2016|I 15 ventilatori a piantana consigliati, sul mercato oggi: luglio 2016|2016/07/i-15-ventilatori-a-piantana-migliori-luglio-2016.html?t=ventilatori,ventilatori-piantana,casa,ufficio,cucina,letto,bagno,climatizzazione,aria,vento,fresco,elettrodomestici,rowenta,tristar,aeg,argoclima&amp;d=18|AZ_312OT+nbVcL",
"I 15 ventilatori più venduti: luglio 2016|La top 15 dei migliori ventilatori disponibili per l'acquisto: luglio 2016|2016/07/i-15-ventilatori-piu-venduti-luglio-2016.html?t=casa,ventilatori,ventilatori-torre,ventilatori-soffitto,ufficio,cucina,letto,bagno,climatizzazione,aria,vento,fresco,elettrodomestici,csl,honeywell,rowenta,tristar&amp;d=9|AZ_51d97WS5TnL",
"I 15 migliori ventilatori a torre: giugno 2016|I 15 ventilatori a torre che ammazzano il caldo: giugno 2016|2016/06/i-15-migliori-ventilatori-a-torre-giugno-2016.html?t=casa,ventilatori-torre,ventilatori,cucina,letto,ufficio,climatizzazione,aria,vento,fresco,condizionatori,aria-condizionata,illuminazione,rowenta,oneconcept,clatronic,klarstein,honeywell,aeg,dyson&amp;d=29|AZ_31F1CMYTu-L",
"Condizionatori: De'Longhi PAC AN112 Silent VS oneConcept CarribeanBlue|De'Longhi PAC AN112 Silent, Climatizzatore Portatile Pinguino VS oneConcept CarribeanBlue Condizionatore ventilatore depuratore aria|2016/06/condizionatori-de-longhi-pac-an112-silent-vs-oneconcept-carribeanblue.html?t=condizionatori,climatizzatori,ventilatori,casa,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettrodomestici,fresco,benessere,aria,deumidificatori,de-longhi,oneconcept&amp;d=27|AZ_31p-7Yh3SQL",
"Condizionatore portatile Argoclima Relax: silenzioso e potente|Alta qualità di climatizzazione e utilizzo super-facile!|2016/05/condizionatore-portatile-argoclima-relax-silenzioso-e-potente.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,ventilatori,aria,vento,deumidificatori,argoclima&amp;d=26|AZ_816XVPYtl2L",
"Condizionatore d'aria TROTEC PAC 2000: spedizione gratis!|Il TROTEC PAC 2000 è uno dei condizionatori d'aria più apprezzati!|2016/05/condizionatore-d-aria-trotec-pac-2000-spedizione-gratis.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,ventilatori,aria,vento,deumidificatori&amp;d=25|AZ_61TSLz5mIxL",
"I 14 ventilatori da soffitto più apprezzati: maggio 2016|I 14 ventilatori da soffitto più interessanti per l'acquisto disponibili subito!|2016/05/i-14-ventilatori-da-soffitto-piu-apprezzati-maggio-2016.html?t=casa,cucina,letto,ufficio,ventilatori-soffitto,ventilatori,climatizzazione,aria,vento,fresco,condizionatori,aria-condizionata,illuminazione,westinghouse&amp;d=13|AZ_31Rnv3rPngL",
];
