Gr = [
"Video - Va bene lo Slow Food, ma qui si esagera!|Non irritiamoci, manteniamo una composta calma, lentamente|2016/04/video-va-bene-lo-slow-food-ma-qui-si-esagera.html?t=video-divertenti,umorismo,the-jackal,napoli,youtube,societa,candid-camera,lentezza,fretta,stress,scherzi&amp;d=3|YT_Wj7XgOxG2fM",
"Video - Non facciamoci fregare la ragazza da Rocco Siffredi!|In fondo cos'ha Rocco che noi non abbiamo?|2016/04/video-non-facciamoci-fregare-la-ragazza-da-rocco-siffredi.html?t=video-divertenti,umorismo,the-jackal,napoli,youtube,amore,donna,infedelta,tradimento,dating,incontri,rocco-siffredi&amp;d=1|YT_Pu5K2g8E1YE",
"Video - La faccia che faccia-mo è sempre quella vera?|A volte si è apprezzati anche maggiormente se ci si contiene un attimino|2016/03/video-la-faccia-che-faccia-mo-e-sempre-quella-vera.html?t=video-divertenti,umorismo,the-jackal,societa,youtube,napoli&amp;d=26|YT_gyMDi-Kjvk0",
"Video - I bambini augurano Buon Anno!|E anche da Luna42.com, auguri a tutti gli Italiani. Pure gli alieni|2016/01/video-i-bambini-augurano-buon-anno.html?t=bambini,video-divertenti,video,the-jackal,auguri&amp;d=1|YT_TMrM1sH2zfw",
"Video - È Natale! Mi ammazzo!|Aspetta che giorno è oggi? Zitto zitto forse anche quest'anno è andata|2015/12/video-e-natale-mi-ammazzo.html?t=video-divertenti,umorismo,the-jackal,societa,natale&amp;d=27|atomic-bomb",
"Video - Se lei ti chiede Rocco Siffredi|Se la tua ragazza ti chiede di vedere un film con Rocco Siffredi, ti devi preoccupare?|2015/12/video-se-lei-ti-chiede-rocco-siffredi.html?t=video-divertenti,umorismo,youtube,video,napoli,the-jackal,rocco-siffredi,amore&amp;d=13|YT_N8pBCp2OILE",
"Video - Il mondo visto dalla Mamma|Come vede il mondo la mia, la tua, la nostra Mamma. Cioè non nostra-nostra, intendevo... ok|2015/11/video-il-mondo-visto-dalla-mamma.html?t=video-divertenti,umorismo,youtube,video,napoli,the-jackal,mamma&amp;d=17|YT_9jMhgKYoq0A",
"Video - Passami l'insalatiera|Tutte le volte che mia nonna sbaglia il mio nome|2015/10/video-passami-l-insalatiera.html?t=video-divertenti,umorismo,youtube,video,napoli,nonno,nipote,tavola,the-jackal,cibo&amp;d=9|YT_FVslaLpSNRg",
];
