Gr = [
"I 15 ventilatori a piantana migliori: luglio 2016|I 15 ventilatori a piantana consigliati, sul mercato oggi: luglio 2016|2016/07/i-15-ventilatori-a-piantana-migliori-luglio-2016.html?t=ventilatori,ventilatori-piantana,casa,ufficio,cucina,letto,bagno,climatizzazione,aria,vento,fresco,elettrodomestici,rowenta,tristar,aeg,argoclima&amp;d=18|AZ_312OT+nbVcL",
"I 12 raffrescatori evaporativi più comprati: giugno 2016|La top 12 dei migliori raffrescatori evaporativi disponibili per l'acquisto|2016/06/i-12-raffrescatori-evaporativi-piu-comprati-giugno-2016.html?t=condizionatori,raffrescatori-evaporativi,casa,aria-condizionata,climatizzatori,climatizzazione,ufficio,bagno,cucina,elettrodomestici,fresco,benessere,aria,argoclima,rowenta,macom&amp;d=25|AZ_31VO+PVgi6L",
"I 10 condizionatori più venduti: giugno 2016|Condizionatori: i 10 migliori in commercio a giugno 2016|2016/06/i-10-condizionatori-piu-venduti-giugno-2016.html?t=casa,condizionatori,aria-condizionata,climatizzatori,climatizzazione,deumidificatori,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,benessere,argoclima,oneconcept,de-longhi&amp;d=11|AZ_41o0sWy6GyL",
"Condizionatore portatile Argoclima Relax: silenzioso e potente|Alta qualità di climatizzazione e utilizzo super-facile!|2016/05/condizionatore-portatile-argoclima-relax-silenzioso-e-potente.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,ventilatori,aria,vento,deumidificatori,argoclima&amp;d=26|AZ_816XVPYtl2L",
"I migliori 8 climatizzatori sul mercato: maggio 2016|Il top dei climatizzatori in commercio a maggio 2016|2016/05/i-migliori-8-climatizzatori-sul-mercato-maggio-2016.html?t=casa,climatizzatori,condizionatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,argoclima,de-longhi&amp;d=22|AZ_31p-7Yh3SQL",
"La classifica dei 16 deumidificatori migliori di maggio 2016|I 16 deumidificatori migliori sul mercato|2016/05/la-classifica-dei-16-deumidificatori-migliori-di-maggio-2016.html?t=casa,letto,ufficio,climatizzazione,umidificatori,deumidificatori,aerosol,benessere,aria,respirazione,naso,gola,bronchi,polmoni,purificatori-d-aria,de-longhi,probreeze,olimpia,argoclima,duronic&amp;d=13|AZ_315fziMiu3L",
"Aprile 2016: i migliori condizionatori: guida all'acquisto|Il meglio dei condizionatori in commercio|2016/04/aprile-2016-i-migliori-condizionatori-guida-all-acquisto.html?t=casa,condizionatori,climatizzazione,ufficio,bagno,cucina,elettronica,fresco,climatizzatori,samsung,de-longhi,klarstein,argoclima&amp;d=11|AZ_31p-7Yh3SQL",
"18 marzo: i 15 deumidificatori migliori|Ecco i deumidificatori migliori, valutati al 18 marzo|2016/03/18-marzo-i-15-deumidificatori-migliori.html?t=casa,cucina,ufficio,climatizzazione,umidificatori,deumidificatori,de-longhi,probreeze,duronic,argoclima&amp;d=18|AZ_315fziMiu3L",
];
