Gr = [
"Asciugacapelli: i 10 migliori a ottobre 2016|I 10 Asciugacapelli più interessanti da avere: la guida all'acquisto|2016/10/asciugacapelli-i-10-migliori-a-ottobre-2016|AZ_41Ykmr5l1ML",
"Le 10 piastre per capelli migliori vendute a settembre 2016|Le 10 piastre per capelli più vendute che puoi trovare: settembre 2016|2016/09/le-10-piastre-per-capelli-migliori-vendute-a-settembre-2016|AZ_41wbTDmdQ9L",
"I 15 migliori arricciacapelli venduti a luglio 2016|I 15 arricciacapelli più venduti: la classifica aggiornata a luglio 2016|2016/07/i-15-migliori-arricciacapelli-venduti-a-luglio-2016.html?t=donna,arricciacapelli,asciugacapelli,capelli,piastre-per-capelli,cura-della-persona,moda,acconciatura,trucco,make-up,bellezza,stile,remington,imetec&amp;d=8|AZ_41VNFUJB68L",
"I 14 asciugacapelli che piacciono di più: luglio 2016|I 14 asciugacapelli più apprezzati subito disponibili: luglio 2016|2016/07/i-14-asciugacapelli-che-piacciono-di-piu-luglio-2016.html?t=donna,asciugacapelli,capelli,piastre-per-capelli,cura-della-persona,moda,acconciatura,arricciacapelli,trucco,make-up,bellezza,remington,philips,rowenta,imetec,krups&amp;d=7|AZ_41rit6KqkVL",
"Il meglio degli asciugacapelli sul mercato: aprile 2016|Ecco i 14 asciugacapelli più venduti|2016/04/il-meglio-degli-asciugacapelli-sul-mercato-aprile-2016.html?t=asciugacapelli,donna,piastre-per-capelli,cura-della-persona,capelli,moda,acconciatura,arricciacapelli,trucco,make-up,bellezza,remington,philips,rowenta,imetec&amp;d=8|AZ_41OJXopSTLL",
"Il meglio delle piastre per capelli disponibili: aprile 2016|La classifica delle piastre per capelli migliori|2016/04/il-meglio-delle-piastre-per-capelli-disponibili-aprile-2016.html?t=donna,piastre-per-capelli,cura-della-persona,capelli,moda,acconciatura,arricciacapelli,trucco,make-up,bellezza,remington,imetec&amp;d=7|AZ_31gLoRfW1oL",
"Effetto Belen per tutte con questa piastra arricciacapelli!|La piastra arricciacapelli più venduta in assoluto|2016/01/effetto-belen-per-tutte-con-questa-piastra-arricciacapelli.html?t=donna,moda,capelli,acconciatura,arricciacapelli,trucco,make-up,bellezza,offerte,shopping&amp;d=26|AZ_517Ioysr4YL",
];
