Gr = [
"Asciugatrici: le 10 migliori a agosto 2016|La top 10 delle migliori asciugatrici subito disponibili: agosto 2016|2016/08/asciugatrici-le-10-migliori-a-agosto-2016|AZ_51nTuJEk8+L",
"I 10 tritaghiaccio che piacciono di più: agosto 2016|La top 10 dei migliori tritaghiaccio sul mercato a agosto 2016|2016/08/i-10-tritaghiaccio-che-piacciono-di-piu-agosto-2016|AZ_41ESwjUZVKL",
"Le 9 lavatrici da campeggio più gettonate: luglio 2016|La top 9 delle migliori lavatrici da campeggio disponibili per l'acquisto|2016/07/le-9-lavatrici-da-campeggio-piu-gettonate-luglio-2016|AZ_41dh+MXGF+L",
"Condizionatori portatili: oneConcept CTR-1 VS Pinguino De'Longhi PAC AN97|Condizionatori portatili a confronto: oneConcept CTR-1 VS Pinguino De'Longhi PAC AN97|2016/07/condizionatori-portatili-oneconcept-ctr-1-vs-pinguino-de-longhi-pac-an97.html?t=condizionatori,climatizzatori,deumidificatori,aria-condizionata,climatizzazione,casa,cucina,bagno,letto,ufficio,aria,vento,fresco,elettrodomestici,benessere,oneconcept,de-longhi&amp;d=2|AZ_41yIWsbEJTL",
"I 15 migliori ventilatori a torre: giugno 2016|I 15 ventilatori a torre che ammazzano il caldo: giugno 2016|2016/06/i-15-migliori-ventilatori-a-torre-giugno-2016.html?t=casa,ventilatori-torre,ventilatori,cucina,letto,ufficio,climatizzazione,aria,vento,fresco,condizionatori,aria-condizionata,illuminazione,rowenta,oneconcept,clatronic,klarstein,honeywell,aeg,dyson&amp;d=29|AZ_31F1CMYTu-L",
"Condizionatori: De'Longhi PAC AN112 Silent VS oneConcept CarribeanBlue|De'Longhi PAC AN112 Silent, Climatizzatore Portatile Pinguino VS oneConcept CarribeanBlue Condizionatore ventilatore depuratore aria|2016/06/condizionatori-de-longhi-pac-an112-silent-vs-oneconcept-carribeanblue.html?t=condizionatori,climatizzatori,ventilatori,casa,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettrodomestici,fresco,benessere,aria,deumidificatori,de-longhi,oneconcept&amp;d=27|AZ_31p-7Yh3SQL",
"I 10 condizionatori più venduti: giugno 2016|Condizionatori: i 10 migliori in commercio a giugno 2016|2016/06/i-10-condizionatori-piu-venduti-giugno-2016.html?t=casa,condizionatori,aria-condizionata,climatizzatori,climatizzazione,deumidificatori,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,benessere,argoclima,oneconcept,de-longhi&amp;d=11|AZ_41o0sWy6GyL",
"La classifica dei forni elettrici migliori al 25 marzo|Alla data del 25 marzo, ecco la classifica dei forni elettrici migliori|2016/03/la-classifica-dei-forni-elettrici-migliori-al-25-marzo.html?t=cucina,forni-elettrici,casa,elettrodomestici,forni,grill,cibo,alimentazione,spice,zephir,ariete,de-longhi,severin,kooper,oneconcept&amp;d=25|AZ_51UEsYger6L",
];
