Gr = [
"I 10 quadricotteri più comprati: ottobre 2016|La top 10 dei migliori quadricotteri sul mercato a ottobre 2016|2016/10/i-10-quadricotteri-piu-comprati-ottobre-2016|AZ_41t4Ui5xkUL",
"Seggiolini Per Auto, Elicotteri Telecomandati: i 5 migliori di agosto 2016|I 5 migliori prodotti in Seggiolini Per Auto, Elicotteri Telecomandati|2016/08/seggiolini-per-auto-elicotteri-telecomandati-i-5-migliori-di-agosto-2016|AZ_416-y8CjGrL",
"I 31 migliori elicotteri telecomandati: luglio 2016|La top 31 dei migliori elicotteri telecomandati subito disponibili|2016/07/i-31-migliori-elicotteri-telecomandati-luglio-2016|AZ_41t4Ui5xkUL",
"I 10 quadricotteri migliori: maggio 2016|La top 10 dei quadricotteri e droni più venduti a maggio 2016|2016/05/i-10-quadricotteri-migliori-maggio-2016.html?t=tempo-libero,drone,quadricottero,uav,aviazione,aeromobile,velivolo,aereo,volo,modellismo,giochi,giocattoli,elettronica,video,syma&amp;d=29|AZ_41t4Ui5xkUL",
"La classifica dei droni migliori al 26 marzo|Ecco la classifica dei migliori quadricotteri aggiornata alla data del 26 marzo|2016/03/la-classifica-dei-droni-migliori-al-26-marzo.html?t=tempo-libero,drone,quadricottero,uav,aviazione,aeromobile,velivolo,aereo,volo,elettronica,video,videocamere,sorveglianza,syma,haibei&amp;d=26|AZ_31wjCOG3PeL",
"Video - I video più belli ripresi dai droni lo scorso anno|Sequenze aeree incredibili, montate in un video bellissimo|2016/01/video-i-video-piu-belli-ripresi-dai-droni-lo-scorso-anno.html?t=drone,uav,aviazione,aeromobile,velivolo,aereo,volo,ambiente,ecologia,terra&amp;d=5|YT_AoPiLg8DZ3A",
"Video - Due enormi balene nuotano con surfista|Al largo della costa di Esperance, in Australia. Un incredibile filmato ripreso da un drone|2015/10/video-due-enormi-balene-nuotano-con-surfista.html?t=mare,oceano,biologia-marina,ambiente,ecologia,animali,natura,balena,esperance,australia,drone&amp;d=10|YT_g6U3VCneKfs",
"Il drone della pioggia|Il cloud seeding attraverso i droni è potenzialmente in grado di sconfiggere la siccità|2015/04/il-drone-della-pioggia.html?t=drone,pioggia,nuvola,siccita,reno,nevada,valtellina&amp;d=18|drone",
];
