Gr = [
"I 10 Smartphone migliori a novembre 2016|I 10 Smartphone più consigliati da chi li ha comprati davvero|2016/11/i-10-smartphone-migliori-a-novembre-2016|AZ_412i-yS769L",
"Caricabatterie per Cellulari da Auto: i 10 migliori a novembre 2016|I 10 Caricabatterie per Cellulari da Auto migliori, subito disponibili|2016/11/caricabatterie-per-cellulari-da-auto-i-10-migliori-a-novembre-2016|AZ_41evr9FwwlL",
"Realtà virtuale senza PC, nuovo sistema operativo e nuova videochiamata da Google|Project Alloy di Intel: una esperienza di realtà virtuale più immediata|2016/08/realta-virtuale-senza-pc-nuovo-sistema-operativo-e-nuova-videochiamata-da-google|vr_project-alloy",
"Orologi sportivi: i 13 migliori in commercio a luglio 2016|I 13 orologi sportivi che piacciono di più oggi sul mercato: luglio 2016|2016/07/orologi-sportivi-i-13-migliori-in-commercio-a-luglio-2016|AZ_41QZEjUGSoL",
"Smartphone: i 15 migliori a luglio 2016|La top 15 dei migliori smartphone disponibili per l'acquisto: luglio 2016|2016/07/smartphone-i-15-migliori-a-luglio-2016.html?t=smartphone,cellulari,telefonia,telefono-cellulare,elettronica,dual-sim,android,app,sms,bluetooth,huawei,homtom,lg,motorola,samsung&amp;d=15|AZ_41XlgJ1gy+L",
"I 14 smartwatch più apprezzati a giugno 2016|I 14 smartwatch più quotati: la classifica aggiornata a giugno 2016|2016/06/i-14-smartwatch-piu-apprezzati-a-giugno-2016.html?t=smartphone,smartwatch,orologi,elettronica,android,telefono-cellulare,cellulari,telefonia,iphone,blackberry,bluetooth,sony,asus&amp;d=9|AZ_41Ws8bfi3ZL",
"Caricabatterie per cellulari: i migliori in commercio a maggio 2016|I 16 caricabatterie per cellulari migliori: maggio 2016|2016/05/caricabatterie-per-cellulari-i-migliori-in-commercio-a-maggio-2016.html?t=smartphone,caricabatterie-cellulari,telefono-cellulare,cellulari,telefonia,dual-sim,android,app,sms,usb,elettronica,iphone,aukey,samsung&amp;d=24|AZ_41QDpSloOjL",
"La top 12 dei migliori smartphone Android in commercio: maggio 2016|La classifica dei 12 smartphone Android più venduti sul mercato|2016/05/la-top-12-dei-migliori-smartphone-android-in-commercio-maggio-2016.html?t=smartphone,telefono-cellulare,cellulari,telefonia,elettronica,dual-sim,android,app,sms,bluetooth,huawei,samsung,asus,motorola&amp;d=12|AZ_41G+npIlVGL",
];
