Gr = [
"Pantaloni Slim Fit Uomo Marrone|Collezione Autunno Inverno/2018 Pantaloni in tonalità marroni molto|2017/12/pantaloni-slim-fit-uomo-marrone|data.oliviero.it/imgprodotto/pantaloni-slim-fit-uomo-marrone_169182",
"Giubbino Uomo Blu|Collezione Autunno Inverno/2018 Piumino con cappuccio di tendenza|2017/12/giubbino-uomo-blu|data.oliviero.it/imgprodotto/giubbino-uomo-blu_169210",
"Camicia Jeans Dark Black|Collezione Autunno Inverno/2018 Modello slim fit Tessuto e look denim|2017/12/camicia-jeans-dark-black|data.oliviero.it/imgprodotto/camicia-jeans-dark-black_169143",
"Giubbino Uomo Asphalt|Collezione Autunno Inverno/2018 Piumino con cappuccio di tendenza|2017/12/giubbino-uomo-asphalt|data.oliviero.it/imgprodotto/giubbino-uomo-asphalt_169208",
"Pantaloni Slim Fit Uomo Dark Grey|Collezione Autunno Inverno/2018 Pantaloni navy con patta con bottoni|2017/12/pantaloni-slim-fit-uomo-dark-grey|data.oliviero.it/imgprodotto/pantaloni-slim-fit-uomo-dark-grey_169186",
"Cappello Giallo|Collezione Autunno Inverno/2018 Beanie basic Lavorazione a maglia|2017/12/cappello-giallo|data.oliviero.it/imgprodotto/cappello-giallo_169213",
"Giubbino Uomo Nero|Collezione Autunno inverno/2018 Parka regular fit Cappuccio con|2017/12/giubbino-uomo-nero|data.oliviero.it/imgprodotto/giubbino-uomo-nero_169206",
"Camicia Jeans Dark Blue Denim|Collezione Autunno Inverno/2018 Modello slim fit Tessuto e look denim|2017/12/camicia-jeans-dark-blue-denim|data.oliviero.it/imgprodotto/camicia-jeans-dark-blue-denim_169138",
"Pantaloni Uomo Camel|Collezione Autunno Inverno/2018 Chino con elasticità aggiunta Patta|2017/12/pantaloni-uomo-camel|data.oliviero.it/imgprodotto/pantaloni-uomo-camel_169188",
"Jeans Skinny Uomo Blu Denim|Blue jeans skinny con molta elasticità Scoloriti e trattati per un|2017/12/jeans-skinny-uomo-blu-denim|data.oliviero.it/imgprodotto/jeans-skinny-uomo-blu-denim_169194",
"Cappello Verde|Collezione Autunno Inverno/2018 Beanie basic Lavorazione a maglia|2017/12/cappello-verde|data.oliviero.it/imgprodotto/cappello-verde_169211",
"Cappello Rosso|Collezione Autunno Inverno/2018 Beanie basic Lavorazione a maglia|2017/12/cappello-rosso|data.oliviero.it/imgprodotto/cappello-rosso_169214",
"Jeans Skinny Uomo Grigio|- Jeans skinny a 5 tasche dal look virile - Look usurato naturale|2017/12/jeans-skinny-uomo-grigio|data.oliviero.it/imgprodotto/jeans-skinny-uomo-grigio_169192",
"Giubbino Uomo Verde|Collezione Autunno inverno/2018 Giacca trapuntata regular fit Tessuto|2017/12/giubbino-uomo-verde|data.oliviero.it/imgprodotto/giubbino-uomo-verde_169204",
"Jeans Slim Fit Uomo|Collezione Autunno Inverno/2018 Jeans slim fit Patta con bottoni|2017/12/jeans-slim-fit-uomo|data.oliviero.it/imgprodotto/jeans-slim-fit-uomo_169178",
"Jeans Skinny Uomo Black Denim|- Uno slim fit né troppo stretto né troppo largo - Jeans a cinque|2017/12/jeans-skinny-uomo-black-denim|data.oliviero.it/imgprodotto/jeans-skinny-uomo-black-denim_169196",
"Pantaloni Slim Fit Uomo Navy|Collezione Autunno Inverno/2018 Pantaloni navy con patta con bottoni|2017/12/pantaloni-slim-fit-uomo-navy|data.oliviero.it/imgprodotto/pantaloni-slim-fit-uomo-navy_169184",
];
