Tt = "D-Link";
Gr = [
"Le 10 Telecamere di Sorveglianza più utilizzate: novembre 2016|La top 10 delle migliori Telecamere di Sorveglianza: novembre 2016|2016/11/le-10-telecamere-di-sorveglianza-piu-utilizzate-novembre-2016|AZ_41e5QeygNkL",
"Le 16 migliori videocamere di sorveglianza a luglio 2016|Le 16 videocamere di sorveglianza in assoluto più apprezzate: luglio 2016|2016/07/le-16-migliori-videocamere-di-sorveglianza-a-luglio-2016.html?t=videocamere-sorveglianza,casa,antifurto,antifurto-casa,allarme,allarme-casa,sicurezza,telecamere-sorveglianza,furto,sistema-di-allarme,ladro,scasso,abitazione,elettronica,sorveglianza,ufficio,garage,negozio,video,videocamere,telecamere,wi-fi,wireless,smartphone,d-link,tp-link&amp;d=14|AZ_41gdzyxjU8L",
"I 15 modem migliori sul mercato a giugno 2016|I 15 modem migliori: la classifica di giugno 2016|2016/06/i-15-modem-migliori-sul-mercato-a-giugno-2016.html?t=internet,modem,router,wireless,wi-fi,wps,hardware,informatica,adsl,rete-informatica,lan,ethernet,usb,tp-link,asus,netgear,d-link,telecom&amp;d=9|AZ_31i1HQFC4fL",
"Il meglio dei wi-fi extender disponibili: maggio 2016|La top 16 dei wi-fi extender più interessanti da acquistare|2016/05/il-meglio-dei-wi-fi-extender-disponibili-maggio-2016.html?t=wi-fi,wi-fi-extender,wireless,wps,ripetitore-wi-fi,range-extender,elettronica,hardware,informatica,streaming,tp-link,netgear,d-link&amp;d=12|AZ_31vIiLpxNQL",
"Maggio 2016: le migliori telecamere di sorveglianza|Ecco la classifica aggiornata a maggio 2016 del meglio delle telecamere di sorveglianza|2016/05/maggio-2016-le-migliori-telecamere-di-sorveglianza.html?t=sicurezza,telecamere-sorveglianza,elettronica,video,videocamere,sorveglianza,casa,antifurto,furto,allarme,sistema-di-allarme,smartphone,telecamere,wireless,wi-fi,d-link,dbpower&amp;d=3|AZ_41gdzyxjU8L",
"La migliore videocamera di sorveglianza?|La videocamera di sorveglianza in testa a tutte le classifiche di vendita!|2016/02/la-migliore-videocamera-di-sorveglianza.html?t=offerte,shopping,videocamere,telecamere,sorveglianza,sicurezza,antifurto,sistema-di-allarme,d-link&amp;d=4|AZ_41f6KU1qCtL",
];
