Gr = [
"I 10 forni da incasso top: agosto 2016|La top 10 dei migliori forni da incasso disponibili da subito: agosto 2016|2016/08/i-10-forni-da-incasso-top-agosto-2016|AZ_31UdW8LJhwL",
"Le 10 cappe aspiranti al top: agosto 2016|La top 10 delle migliori cappe aspiranti disponibili da subito: agosto 2016|2016/08/le-10-cappe-aspiranti-al-top-agosto-2016|AZ_31olmRV52KL",
"Le 10 impastatrici più vendute: agosto 2016|Le 10 impastatrici più vendute disponibili da subito: agosto 2016|2016/08/le-10-impastatrici-piu-vendute-agosto-2016|AZ_41no-3PQJML",
"I 14 piani cottura più acquistati: luglio 2016|La top 14 dei migliori piani cottura disponibili per l'acquisto: luglio 2016|2016/07/i-14-piani-cottura-piu-acquistati-luglio-2016.html?t=cucina,piani-cottura,casa,piastre-elettriche,griglie-elettriche,elettrodomestici,forni-elettrici,fornetti-elettrici,alimentazione,cibo,cottura,pentole,padelle,casseruole,tegami,candy,ariston,electrolux,bosch,smeg,whirlpool&amp;d=20|AZ_315rWK2ZXeL",
"La top 13 dei migliori frullatori da tavolo: luglio 2016|I 13 frullatori da tavolo più apprezzati da chi lavora davvero in cucina|2016/07/la-top-13-dei-migliori-frullatori-da-tavolo-luglio-2016.html?t=cucina,frullatori-tavolo,frullatori,elettrodomestici,mixer,casa,bar,cibo,alimentazione,alimenti,gastronomia,tritatutto,duronic,electrolux,philips,black-and-decker,kenwood,princess,klarstein,tristar,imetec&amp;d=6|AZ_51plaqbLv0L",
"Le 10 lavastoviglie più comprate: giugno 2016|La top 10 delle migliori lavastoviglie sul mercato a giugno 2016|2016/06/le-10-lavastoviglie-piu-comprate-giugno-2016.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,pulizia,igiene,stoviglie,piatti,pentole,beko,electrolux,klarstein,bosch,ariston,indesit,smeg&amp;d=2|AZ_41tdMsxE9QL",
"Al marzo 2016, ecco le 9 lavastoviglie migliori|La nostra classifica delle 9 migliori lavastoviglie|2016/03/al-marzo-2016-ecco-le-9-lavastoviglie-migliori.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,igiene,stoviglie,klarstein,beko,indesit,bosch,smeg,electrolux&amp;d=31|AZ_51zRVIL8yqL",
"Le macchine per il caffè migliori, valutate al 19 marzo|Aggiornata alla data del 19 marzo, ecco la classifica delle migliori macchine per il caffè|2016/03/le-macchine-per-il-caffe-migliori-valutate-al-19-marzo.html?t=caffe,macchine-da-caffe,casa,alimentazione,cibo,cucina,elettrodomestici,bar,ufficio,dieta,salute,colazione,nespresso,nescafe,lavazza,saeco,moulinex,de-longhi,electrolux&amp;d=19|AZ_41zmPniin9L",
];
