Tt = "Elettricità";
Gr = [
"La top 10 delle Lampade da Tavolo: dicembre 2016|Le 10 Lampade da Tavolo che vanno per la maggiore, disponibili ora!|2016/12/la-top-10-delle-lampade-da-tavolo-dicembre-2016|AZ_31i7bnEmPTL",
"Lampade da Tavolo, Sacchi a Pelo: i 5 migliori di settembre 2016|I 5 migliori prodotti in Lampade da Tavolo, Sacchi a Pelo|2016/09/lampade-da-tavolo-sacchi-a-pelo-i-5-migliori-di-settembre-2016|AZ_31UGTnj4bNL",
"Le 15 lampade da tavolo più apprezzate di maggio 2016|Il meglio delle lampade da tavolo: la guida all'acquisto di maggio 2016|2016/05/le-15-lampade-da-tavolo-piu-apprezzate-di-maggio-2016.html?t=casa,lampada,lampade-da-tavolo,illuminazione,materiale-elettrico,ufficio,studio,scrivanie,arredamento,arredo,lampadine,elettricita,ghb,albrillo,onite,honsel&amp;d=24|AZ_41+8GOFxJyL",
"23 marzo: le 15 migliori lampade da tavolo|Ecco la classifica delle lampade da tavolo migliori aggiornata alla data del 23 marzo|2016/03/23-marzo-le-15-migliori-lampade-da-tavolo.html?t=casa,lampade-da-tavolo,lampada,illuminazione,lampadine,elettricita,materiale-elettrico,ufficio,arredamento,ghb,onite,aglaia,daffodil,honsel,albrillo&amp;d=23|AZ_31MfajZhMnL",
"Risparmiare tenendo sotto controllo gli elettrodomestici|Vale la pena di lasciare quella TV in stand-by? Quanto mi costa all'anno?|2016/02/risparmiare-tenendo-sotto-controllo-gli-elettrodomestici.html?t=casa,ufficio,cucina,elettronica,offerte,elettricita,energia,risparmio,elettrodomestici,rce&amp;d=22|AZ_81CxgbqM3nL",
"Lampadine LED a un prezzo accessibile, finalmente!|Guardate questa confezione di lampadine LED della Philips, tra le più vendute!|2016/02/lampadine-led-a-un-prezzo-accessibile-finalmente.html?t=offerte,shopping,illuminazione,lampadine,led,casa,cucina,elettricita,materiale-elettrico,philips&amp;d=17|AZ_81vAKIKEQmL",
"La stimolazione elettrica del cervello contro i danni dell'ictus|Un nuovo studio dell'Università di Milano-Bicocca rivela che una stimolazione elettrica del cervello può aumentare il recupero dei deficit motori|2015/02/la-stimolazione-elettrica-del-cervello-contro-i-danni-dell-ictus.html?t=ictus,medicina,salute,scienza,cervello,elettricita&amp;d=16|brain",
"Le nuove tariffe elettriche non saranno più in base ai consumi?|Con le nuove tariffe le categorie più svantaggiate saranno i non residenti e i single. Le modifiche sono attualmente già allo studio|2015/02/le-nuove-tariffe-elettriche-non-saranno-piu-in-base-ai-consumi.html?t=elettricita,tariffe&amp;d=14|electricity",
"Inaugurato in California il più grande impianto solare mai realizzato su suolo pubblico|8 milioni di pannelli solari fotovoltaici su un'estensione che supera i 16 chilometri quadrati|2015/02/inaugurato-in-california-il-piu-grande-impianto-solare-mai-realizzato-su-suolo-pubblico.html?t=impianto-fotovoltaico,pannello-solare,energie-rinnovabili,energia-solare,elettricita,california&amp;d=13|solar-panels-sunflowers",
];
