Tt = "T-Shirt";
Gr = [
"T-shirt uomo CMP62J JY610 001|Collezione : Primavera Estate Tipologia : T-Shirt Uomo manica lunga|2017/12/t-shirt-uomo-cmp62j-jy610-001|data.oliviero.it/imgprodotto/t-shirt-uomo-cmp62j-jy610-001_56766",
"T-Shirt Uomo Taglie Forti Oliva|Collezione Autunno Inverno/2018 T-Shirt manica lunga da uomo taglie|2017/12/t-shirt-uomo-taglie-forti-oliva|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-oliva_167336",
"T-Shirt Uomo Taglie Forti Navy|Collezione Autunno Inverno/2018 T-shirt uomo taglie forti con|2017/12/t-shirt-uomo-taglie-forti-navy|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-navy_167819",
"T-Shirt Uomo Jordan Dry Grigio|La t-shirt da allenamento Jordan Dry \"Beat The Best\" - Uomo|2017/12/t-shirt-uomo-jordan-dry-grigio|data.oliviero.it/imgprodotto/t-shirt-uomo-jordan-dry-grigio_167896",
"T-Shirt Uomo Navy|Collezione Primavera Estate T-Shirt uomo con girocollo e mezza|2017/12/t-shirt-uomo-navy|data.oliviero.it/imgprodotto/t-shirt-uomo-navy_165045",
"T-Shirt Uomo Grigio Melange|Collezione Primavera Estate Questa T-shirt da uomo è pensata per|2017/12/t-shirt-uomo-grigio-melange|data.oliviero.it/imgprodotto/t-shirt-uomo-grigio-melange-s98738_162965",
"T-Shirt Uomo Taglie Forti Bordeaux|T-Shirt uomo taglie forti: maniche lunghe, girocollo e logo al petto, cotone|2017/11/t-shirt-uomo-taglie-forti-bordeaux|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-bordeaux_167299",
"T-Shirt Uomo Taglie Forti Sabbia|T-Shirt taglie forti da uomo: girocollo, mezze maniche, stampa frontale|2017/08/t-shirt-uomo-taglie-forti-sabbia|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-sabbia-25613-90_164790",
"T-Shirt Donna Nero Leni|Collezione Primavera Estate T-shirt bianca a manica corta a righe|2017/07/t-shirt-donna-nero-leni|data.oliviero.it/imgprodotto/t-shirt-donna-nero-leni-72t2yb22000_161387",
"T-Shirt Uomo Los Angeles Box Graphic|Collezione Primavera Estate T-Shirt da uomo con stampa colorata|2017/07/t-shirt-uomo-los-angeles-box-graphic|data.oliviero.it/imgprodotto/t-shirt-uomo-los-angeles-box-graphic-bk7693_164777",
"Maglia calcio bambino Nazionale Italiana|La maglia per infiammare la passione di tutti i tifosi degli Azzurri|2017/06/maglia-calcio-bambino-nazionale-italiana|data.oliviero.it/imgprodotto/maglia-figc-kids-home-replica-748833_148488",
"T-Shirt Donna Nero stellata Converse|T-Shirt donna con girocollo e mezza manica Collezione Primavera Estate|2017/05/t-shirt-donna-nero-stellata-converse|data.oliviero.it/imgprodotto/t-shirt-donna-nero_165016",
"T-Shirt Uomo Taglie Forti Grigio - U546|Collezione Primavera Estate 2017 T-Shirt da uomo taglie forti|2017/05/t-shirt-uomo-taglie-forti-grigio-u546|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-grigio-u546_162808",
"T-Shirt donna mezza manica, scollatura a V|La mezza manica e la scollatura a V non passano mai di moda|2017/04/t-shirt-donna-mezza-manica-scollatura-a-v|data.oliviero.it/imgprodotto/t-shirt-donna-105847-006_50410_big",
"T-Shirt donna Banana Moon|Collezione Primavera Estate Tipologia: T-shirt da donna Tessuto...|2017/04/t-shirt-donna-banana-moon|data.oliviero.it/imgprodotto/t-shirt-donna-banana-moon_9558_big",
"T-Shirt Uomo Kennebec River Bianco|Collezione Primavera Estate 2017 - Adotta l'albero Timberland|2017/04/t-shirt-uomo-kennebec-river-bianco|data.oliviero.it/imgprodotto/t-shirt-uomo-kennebec-river-bianco-a1lad100_160924",
"Le 10 T-Shirt Taglie Forti scelte: febbraio 2017|La top 10 delle migliori T-Shirt Taglie Forti in commercio|2017/02/le-10-t-shirt-taglie-forti-scelte-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-taglie-forti-uomo-mare-nv31015ad-153_160712",
"Le 5 T-Shirt Sportive Uomo che più ci piacciono: febbraio 2017|La top 5 delle migliori T-Shirt Sportive Uomo disponibili da subito|2017/02/le-5-t-shirt-sportive-uomo-che-piu-ci-piacciono-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-sportiva-uomo-squadron-blue-827021-464_158073",
"Le 5 T-Shirt Running Donna scelte a febbraio 2017|La top 5 delle migliori T-Shirt Running Donna disponibili da subito|2017/02/le-5-t-shirt-running-donna-scelte-a-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-running-donna-response-v-neck-ax6577_151731",
"T-Shirt Neonati: le 5 scelte a febbraio 2017|Le 5 T-Shirt Neonati più belle disponibili subito per l'acquisto|2017/02/t-shirt-neonati-le-5-scelte-a-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-neonata-panna-202048-1111_154861",
"Le 10 T-Shirt Calcio migliori: febbraio 2017|Le 10 T-Shirt Calcio più vendute oggi sul mercato: febbraio 2017|2017/02/le-10-t-shirt-calcio-migliori-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-calcio-uomo-arancio-f50488_160382",
"Le 10 T-Shirt da Uomo più comprate: febbraio 2017|Le 10 T-Shirt da Uomo più utilizzate: la classifica aggiornata|2017/02/le-10-t-shirt-da-uomo-piu-comprate-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-uomo-bluette-essentials-linear-tee-s98734_159301",
"Le 10 T-Shirt da Donna più comprate: febbraio 2017|La classifica aggiornata dele 10 T-Shirt da Donna più comprate|2017/02/le-10-t-shirt-da-donna-piu-comprate-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-donna-x20129_50282_big",
];
