Tt = "T-Shirt";
Gr = [
"T-Shirt Uomo Nero|La t-shirt Nike Swoosh Athlete - Uomo è realizzata in morbido tessuto|2017/12/t-shirt-uomo-nero|data.oliviero.it/imgprodotto/t-shirt-uomo-nero_169690",
"T-Shirt da Basket Uomo Nero|La t-shirt da basket Nike Dry - Uomo è realizzata in tessuto|2017/12/t-shirt-da-basket-uomo-nero|data.oliviero.it/imgprodotto/t-shirt-da-basket-uomo-nero_167928",
"T-Shirt Sportiva Uomo Bianco|La t-shirt Nike Sportswear - Uomo è realizzata in puro cotone per un|2017/12/t-shirt-sportiva-uomo-bianco|data.oliviero.it/imgprodotto/t-shirt-sportiva-uomo-bianco-827021-100_158069",
"T-Shirt daTennis Nero|La t-shirt NikeCourt Rafael Nadal - Uomo è realizzata in morbido|2017/12/t-shirt-datennis-nero|data.oliviero.it/imgprodotto/t-shirt-datennis-nero_167936",
"T-Shirt Uomo Verdone|Sfoggia con orgoglio la tua passione per adidas indossando questa|2017/12/t-shirt-uomo-verdone|data.oliviero.it/imgprodotto/t-shirt-uomo-verdone_168367",
"T-shirt pretty|Collezione Primavera Estate Tipologia: T- shirt da donna Tessuto|2017/12/t-shirt-pretty|data.oliviero.it/imgprodotto/t-shirt-pretty_9624_big",
"T-Shirt donna taglie forti uomo|Collezione : Primavera Estate Tipologia : T-Shirt Taglie comode con|2017/12/t-shirt-donna-taglie-forti-uomo|data.oliviero.it/imgprodotto/t-shirt-donna-taglie-forti-uomo-510-800_57550",
"T-Shirt Uomo Nero ID Stadium Tee|Collezione Primavera Estate Questa T-shirt da uomo offre comfort|2017/12/t-shirt-uomo-nero-id-stadium-tee|data.oliviero.it/imgprodotto/t-shirt-uomo-nero-id-stadium-tee-s98714_159398",
"T-Shirt donna 5352|Collezione Primavera Estate Tipologia: T-shirt da donna Tessuto|2017/12/t-shirt-donna-5352|data.oliviero.it/imgprodotto/t-shirt-donna-5352_7559_big",
"T-Shirt Logo Rosso|Collezione Autunno Inverno/2018 Questa t-shirt girocollo con fit|2017/12/t-shirt-logo-rosso|data.oliviero.it/imgprodotto/t-shirt-logo-rosso_170627",
"T-Shirt Uomo Nero Essentials Base Tee|Questa T-shirt da uomo è pensata per offrirti comfort e copertura. Il|2017/12/t-shirt-uomo-nero-essentials-base-tee|data.oliviero.it/imgprodotto/t-shirt-uomo-nero-essentials-base-tee-s98742_159406",
"T-Shirt Uomo Nero Ess Linear Tee|Il cuore dell'Occidente. Mostra la tua passione per la Grande Mela|2017/12/t-shirt-uomo-nero-ess-linear-tee|data.oliviero.it/imgprodotto/t-shirt-uomo-nero-ess-linear-tee-s98731_162963",
"T-Shirt donna W15021 T7865 82143|Collezione Liu Jo Jeans T-Shirt da donna dal tessuto leggero effetto|2017/12/t-shirt-donna-w15021-t7865-82143|data.oliviero.it/imgprodotto/t-shirt-donna-w15021-t7865-82143_146714",
"T-Shirt Uomo Trefoil Nero|Collezione Primavera Estate Stile moderno e comfort si incontrano in|2017/12/t-shirt-uomo-trefoil-nero|data.oliviero.it/imgprodotto/t-shirt-uomo-trefoil-nero-ay7801_161988",
"T-Shirt Uomo Navy Essentials Linear Tee|Se vuoi essere alla moda e farti notare ecco la t-shirt fatta per te|2017/12/t-shirt-uomo-navy-essentials-linear-tee|data.oliviero.it/imgprodotto/t-shirt-uomo-navy-essentials-linear-tee-s98732_159403",
"Canotta gialla|Collezion: Primavera Estate Tipologia: Canotta da donna Tessuto|2017/12/canotta-gialla|data.oliviero.it/imgprodotto/canotta-gialla_61798",
"T-Shirt donna T15126 J7406|Collezine Liu Jo Sport T-Shirt da donna con mezza manica, ampio|2017/12/t-shirt-donna-t15126-j7406|data.oliviero.it/imgprodotto/t-shirt-donna-t15126-j7406_146523",
"T-Shirt Uomo Camouflage|Questa T-shirt da uomo sfoggia un accattivante look street-style|2017/12/t-shirt-uomo-camouflage|data.oliviero.it/imgprodotto/t-shirt-uomo-camouflage_168438",
"T-Shirt Donna Nero, Bianco|Sportiva e sofisticata, questa T-shirt da donna unisce lo stile anni|2017/12/t-shirt-donna-nero-bianco|data.oliviero.it/imgprodotto/t-shirt-donna-nero-bianco_168342",
"T-Shirt da Basket Bianco|La t-shirt da basket Nike Dry KD Freq Flyer - Uomo contribuisce|2017/12/t-shirt-da-basket-bianco|data.oliviero.it/imgprodotto/t-shirt-da-basket-bianco_167925",
"T-Shirt Uomo Nero Camouflage|T-shirt da uomo in autentico stile adidas originals, caratterizzata|2017/12/t-shirt-uomo-nero-camouflage|data.oliviero.it/imgprodotto/t-shirt-uomo-nero-camouflage_168415",
"T-Shirt Donna D2M Tee 3S Nero|Collezione Primavera Estate Tessuto 84% poliestere / 16% elastan|2017/12/t-shirt-donna-d2m-tee-3s-nero|data.oliviero.it/imgprodotto/t-shirt-donna-d2m-tee-3s-nero-bk2682_158889",
"T-shirt uomo Mention Manica Lunga Giacomo Agostini|Giacomo Agostini ci ha raccontato con una frase semplice cosa sia per|2017/12/t-shirt-uomo-mention-manica-lunga-giacomo-agostini|data.oliviero.it/imgprodotto/t-shirt-uomo-mention-manica-lunga-giacomo-agostini_93401",
"T-Shirt Uomo Freelift Prime|Allenati al massimo indossando questa T-shirt da uomo. Caratterizzata|2017/12/t-shirt-uomo-freelift-prime|data.oliviero.it/imgprodotto/t-shirt-uomo-freelift-prime-bk6092_163401",
"T-Shirt Retro Logo Navy|Collezione Autunno Inverno/2018 Ispirazione biker per questa t-shirt|2017/12/t-shirt-retro-logo-navy|data.oliviero.it/imgprodotto/t-shirt-retro-logo-navy_170621",
"T-Shirt Donna Kaki|Collezione Primavera Estate T-Shirt Champion da donna. Il modello|2017/12/t-shirt-donna-kaki|data.oliviero.it/imgprodotto/t-shirt-donna-kaki-109547-3044_159787",
"T-Shirt Uomo Blu|T-shirt da uomo in autentico stile adidas originals, caratterizzata|2017/12/t-shirt-uomo-blu|data.oliviero.it/imgprodotto/t-shirt-uomo-blu_168421",
"T-Shirt Uomo Rosso Nike Pro|La maglia da allenamento a manica corta Nike Pro - Uomo è dotata di|2017/12/t-shirt-uomo-rosso-nike-pro|data.oliviero.it/imgprodotto/t-shirt-uomo-rosso-nike-pro_161252",
"T-Shirt donna Arancio|Collezione Primavera Estate Tipologia: T-shirt mezza manica da donna|2017/12/t-shirt-donna-arancio|data.oliviero.it/imgprodotto/t-shirt-donna-arancio_5870_big",
"T-shirt uomo Vintage Giacomo Agostini|Blu pastello, con un motore MV Agusta stilizzato in colore panna, il|2017/12/t-shirt-uomo-vintage-giacomo-agostini|data.oliviero.it/imgprodotto/t-shirt-uomo-vintage-giacomo-agostini_93405",
"T-Shirt Uomo Grigio|Questa T-shirt da uomo è pensata per offrirti comfort e copertura|2017/12/t-shirt-uomo-grigio|data.oliviero.it/imgprodotto/t-shirt-uomo-grigio_167030",
"T-Shirt Logo Navy|Collezione Autunno Inverno/2018 Questa t-shirt blu girocollo, con|2017/12/t-shirt-logo-navy|data.oliviero.it/imgprodotto/t-shirt-logo-navy_170625",
"T-shirt uomo Legend Giacomo Agostini|Un capo nero racing, che ricorda quante vittorie ha conseguito|2017/12/t-shirt-uomo-legend-giacomo-agostini|data.oliviero.it/imgprodotto/t-shirt-uomo-legend-giacomo-agostini_93409",
"T-Shirt Donna Bianco|Collezione Autunno Inverno/2018 T-shirt manica corta donna. Taglio|2017/12/t-shirt-donna-bianco|data.oliviero.it/imgprodotto/t-shirt-donna-bianco_169764",
"T-Shirt Donna Grigio|Progettata per fornire massima libertà di movimento durante|2017/12/t-shirt-donna-grigio|data.oliviero.it/imgprodotto/t-shirt-donna-grigio_168413",
"T-Shirt Uomo Bianco|La t-shirt Nike Sportswear Air Photo - Uomo è realizzata in puro|2017/12/t-shirt-uomo-bianco|data.oliviero.it/imgprodotto/t-shirt-uomo-bianco_169675",
"T-shirt uomo C85571|Collezione : Primavera Estate Tipologia : T-shirt casual da uomo|2017/12/t-shirt-uomo-c85571|data.oliviero.it/imgprodotto/t-shirt-uomo-c85571_72322",
"T-Shirt Jordan Uomo Obsidian|La t-shirt Jordan Sportswear Flight Heritage - Uomo è realizzata in|2017/12/t-shirt-jordan-uomo-obsidian|data.oliviero.it/imgprodotto/t-shirt-jordan-uomo-obsidian_167892",
"T-Shirt Donna Essentials Linear Longsleeve Nero|Questa T-shirt aderente dal look classico sfoggia un taglio moderno|2017/12/t-shirt-donna-essentials-linear-longsleeve-nero|data.oliviero.it/imgprodotto/t-shirt-donna-essentials-linear-longsleeve-nero-b45746_158876",
"T-Shirt Jordan Uomo Bianco|La t-shirt Jordan Sportswear Flight Heritage - Uomo è realizzata in|2017/12/t-shirt-jordan-uomo-bianco|data.oliviero.it/imgprodotto/t-shirt-jordan-uomo-bianco_167891",
"T-Shirt donna 0512|Collezione Primavera Estate Tipologia: T-shirt da donna manica corta|2017/12/t-shirt-donna-0512|data.oliviero.it/imgprodotto/t-shirt-donna-0512_7519_big",
"T-Shirt donna Banana Moon|Collezione Primavera Estate Tipologia T-shirt da donna Tessuto|2017/12/t-shirt-donna-banana-moon|data.oliviero.it/imgprodotto/t-shirt-donna-banana-moon_9585_big",
"T-Shirt Uomo Blu notte|Sfoggia con orgoglio la tua passione per adidas indossando questa|2017/12/t-shirt-uomo-blu-notte|data.oliviero.it/imgprodotto/t-shirt-uomo-blu-notte_168369",
"T-Shirt Uomo Verde|La maglia da running a manica corta Nike Miler - Uomo è realizzata in|2017/12/t-shirt-uomo-verde|data.oliviero.it/imgprodotto/t-shirt-uomo-verde_169688",
"T-Shirt Donna Running Response Easy Orange|Collezione Primavera Estate Quando la pendenza ti mette alla prova,|2017/12/t-shirt-donna-running-response-easy-orange|data.oliviero.it/imgprodotto/t-shirt-donna-running-response-easy-orange-bp7455_159830",
"T-Shirt Jordan Nero|La t-shirt Jordan Sportswear Wings - Uomo sfoggia dettagli esclusivi|2017/12/t-shirt-jordan-nero|data.oliviero.it/imgprodotto/t-shirt-jordan-nero_167888",
"T-Shirt da Basket Nero|La t-shirt da basket Nike Dry Core Practice - Uomo è realizzata in|2017/12/t-shirt-da-basket-nero|data.oliviero.it/imgprodotto/t-shirt-da-basket-nero_167933",
"T-Shirt Uomo Royal|La maglia da allenamento a manica corta Nike Pro - Uomo è realizzata|2017/12/t-shirt-uomo-royal|data.oliviero.it/imgprodotto/t-shirt-uomo-royal_169691",
"T-Shirt Uomo Taglie Forti Melange|Collezione Primavera Estate T-Shirt mezza manica con stampa frontale|2017/12/t-shirt-uomo-taglie-forti-melange|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-melange-71395-045_162589",
"T-Shirt Tennis Donna Rosso Nikecourt Pure|La maglia da tennis NikeCourt Pure - Donna assicura mobilità in campo|2017/12/t-shirt-tennis-donna-rosso-nikecourt-pure|data.oliviero.it/imgprodotto/t-shirt-tennis-donna-rosso-nikecourt-pure_167906",
"T-Shirt Running Donna Nero Response|Collezione Primavera Estate Quando la pendenza ti mette alla prova,|2017/12/t-shirt-running-donna-nero-response|data.oliviero.it/imgprodotto/t-shirt-running-donna-nero-response-bp7463_159346",
"T-Shirt Donna Nero|Il top a manica corta con logo Nike Sportswear Essential - Donna|2017/12/t-shirt-donna-nero|data.oliviero.it/imgprodotto/t-shirt-donna-nero_167875",
"T-Shirt donna Banane|Collezione Primavera Estate Tipologia: Maglia mezza manica da donna|2017/12/t-shirt-donna-banane|data.oliviero.it/imgprodotto/t-shirt-donna-banane_12768_big",
"T-shirt uomo CMP62J JY610 001|Collezione : Primavera Estate Tipologia : T-Shirt Uomo manica lunga|2017/12/t-shirt-uomo-cmp62j-jy610-001|data.oliviero.it/imgprodotto/t-shirt-uomo-cmp62j-jy610-001_56766",
"T-Shirt Uomo Taglie Forti Oliva|Collezione Autunno Inverno/2018 T-Shirt manica lunga da uomo taglie|2017/12/t-shirt-uomo-taglie-forti-oliva|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-oliva_167336",
"T-Shirt Uomo Taglie Forti Navy|Collezione Autunno Inverno/2018 T-shirt uomo taglie forti con|2017/12/t-shirt-uomo-taglie-forti-navy|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-navy_167819",
"T-Shirt Uomo Jordan Dry Grigio|La t-shirt da allenamento Jordan Dry \"Beat The Best\" - Uomo|2017/12/t-shirt-uomo-jordan-dry-grigio|data.oliviero.it/imgprodotto/t-shirt-uomo-jordan-dry-grigio_167896",
"T-Shirt Uomo Navy|Collezione Primavera Estate T-Shirt uomo con girocollo e mezza|2017/12/t-shirt-uomo-navy|data.oliviero.it/imgprodotto/t-shirt-uomo-navy_165045",
"T-Shirt Uomo Grigio Melange|Collezione Primavera Estate Questa T-shirt da uomo è pensata per|2017/12/t-shirt-uomo-grigio-melange|data.oliviero.it/imgprodotto/t-shirt-uomo-grigio-melange-s98738_162965",
"T-Shirt Uomo Taglie Forti Bordeaux|T-Shirt uomo taglie forti: maniche lunghe, girocollo e logo al petto, cotone|2017/11/t-shirt-uomo-taglie-forti-bordeaux|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-bordeaux_167299",
"T-Shirt Uomo Taglie Forti Sabbia|T-Shirt taglie forti da uomo: girocollo, mezze maniche, stampa frontale|2017/08/t-shirt-uomo-taglie-forti-sabbia|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-sabbia-25613-90_164790",
"T-Shirt Donna Nero Leni|Collezione Primavera Estate T-shirt bianca a manica corta a righe|2017/07/t-shirt-donna-nero-leni|data.oliviero.it/imgprodotto/t-shirt-donna-nero-leni-72t2yb22000_161387",
"T-Shirt Uomo Los Angeles Box Graphic|Collezione Primavera Estate T-Shirt da uomo con stampa colorata|2017/07/t-shirt-uomo-los-angeles-box-graphic|data.oliviero.it/imgprodotto/t-shirt-uomo-los-angeles-box-graphic-bk7693_164777",
"Maglia calcio bambino Nazionale Italiana|La maglia per infiammare la passione di tutti i tifosi degli Azzurri|2017/06/maglia-calcio-bambino-nazionale-italiana|data.oliviero.it/imgprodotto/maglia-figc-kids-home-replica-748833_148488",
"T-Shirt Donna Nero stellata Converse|T-Shirt donna con girocollo e mezza manica Collezione Primavera Estate|2017/05/t-shirt-donna-nero-stellata-converse|data.oliviero.it/imgprodotto/t-shirt-donna-nero_165016",
"T-Shirt Uomo Taglie Forti Grigio - U546|Collezione Primavera Estate 2017 T-Shirt da uomo taglie forti|2017/05/t-shirt-uomo-taglie-forti-grigio-u546|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-grigio-u546_162808",
"T-Shirt donna mezza manica, scollatura a V|La mezza manica e la scollatura a V non passano mai di moda|2017/04/t-shirt-donna-mezza-manica-scollatura-a-v|data.oliviero.it/imgprodotto/t-shirt-donna-105847-006_50410_big",
"T-Shirt donna Banana Moon|Collezione Primavera Estate Tipologia: T-shirt da donna Tessuto...|2017/04/t-shirt-donna-banana-moon|data.oliviero.it/imgprodotto/t-shirt-donna-banana-moon_9558_big",
"T-Shirt Uomo Kennebec River Bianco|Collezione Primavera Estate 2017 - Adotta l'albero Timberland|2017/04/t-shirt-uomo-kennebec-river-bianco|data.oliviero.it/imgprodotto/t-shirt-uomo-kennebec-river-bianco-a1lad100_160924",
"Le 10 T-Shirt Taglie Forti scelte: febbraio 2017|La top 10 delle migliori T-Shirt Taglie Forti in commercio|2017/02/le-10-t-shirt-taglie-forti-scelte-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-taglie-forti-uomo-mare-nv31015ad-153_160712",
"Le 5 T-Shirt Sportive Uomo che più ci piacciono: febbraio 2017|La top 5 delle migliori T-Shirt Sportive Uomo disponibili da subito|2017/02/le-5-t-shirt-sportive-uomo-che-piu-ci-piacciono-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-sportiva-uomo-squadron-blue-827021-464_158073",
"Le 5 T-Shirt Running Donna scelte a febbraio 2017|La top 5 delle migliori T-Shirt Running Donna disponibili da subito|2017/02/le-5-t-shirt-running-donna-scelte-a-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-running-donna-response-v-neck-ax6577_151731",
"T-Shirt Neonati: le 5 scelte a febbraio 2017|Le 5 T-Shirt Neonati più belle disponibili subito per l'acquisto|2017/02/t-shirt-neonati-le-5-scelte-a-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-neonata-panna-202048-1111_154861",
"Le 10 T-Shirt Calcio migliori: febbraio 2017|Le 10 T-Shirt Calcio più vendute oggi sul mercato: febbraio 2017|2017/02/le-10-t-shirt-calcio-migliori-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-calcio-uomo-arancio-f50488_160382",
"Le 10 T-Shirt da Uomo più comprate: febbraio 2017|Le 10 T-Shirt da Uomo più utilizzate: la classifica aggiornata|2017/02/le-10-t-shirt-da-uomo-piu-comprate-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-uomo-bluette-essentials-linear-tee-s98734_159301",
"Le 10 T-Shirt da Donna più comprate: febbraio 2017|La classifica aggiornata dele 10 T-Shirt da Donna più comprate|2017/02/le-10-t-shirt-da-donna-piu-comprate-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-donna-x20129_50282_big",
];
