Gr = [
"I 10 pulitori a vapore migliori: ottobre 2016|Pulitori a vapore: i 10 migliori in commercio a ottobre 2016|2016/10/i-10-pulitori-a-vapore-migliori-ottobre-2016|AZ_41pLTthB5uL",
"I 10 migliori aspirapolvere a traino: agosto 2016|La top 10 dei migliori aspirapolvere a traino in commercio ad agosto 2016|2016/08/i-10-migliori-aspirapolvere-a-traino-agosto-2016|AZ_41s089jdtcL",
"Vaporetto: i 15 migliori in commercio a luglio 2016|La top 15 dei migliori vaporetto sul mercato a luglio 2016|2016/07/vaporetto-i-15-migliori-in-commercio-a-luglio-2016.html?t=casa,vaporetto,pulitori-a-vapore,elettrodomestici,igiene,pulizia,vapore,pavimento,cucina,bagno,scope-elettriche,polti,clatronic,scopa,koenig,hoover&amp;d=8|AZ_41pLTthB5uL",
"I 15 ferri a vapore migliori: giugno 2016|La classifica di giugno 2016 dei 15 ferri a vapore più venduti|2016/06/i-15-ferri-a-vapore-migliori-giugno-2016.html?t=casa,ferro-a-vapore,ferro-da-stiro,elettrodomestici,lavatrici,abbigliamento,vestito,igiene,pulizia,bucato,vapore,rowenta,de-longhi,philips,imetec,polti,black-and-decker,russell-hobbs&amp;d=21|AZ_41MqF2i2O2L",
"Il meglio delle scope a vapore di maggio 2016|Le 13 scope a vapore più apprezzate subito disponibili per l'acquisto: maggio 2016|2016/05/il-meglio-delle-scope-a-vapore-di-maggio-2016.html?t=elettrodomestici,scope-vapore,casa,lavapavimenti,aspirapolvere,scope-elettriche,pulizia,igiene,pavimento,cucina,bagno,robot-aspirapolvere,black-and-decker,vileda,imetec,clatronic,polti,ariete&amp;d=29|AZ_21lLe5YhnVL",
"I 10 aspirapolvere più interessanti per l'acquisto: aprile 2016|Il meglio degli aspirapolvere sul mercato|2016/04/i-10-aspirapolvere-piu-interessanti-per-l-acquisto-aprile-2016.html?t=elettrodomestici,aspirapolvere,casa,pulizia,igiene,pavimento,cucina,bagno,rowenta,black-and-decker,samsung,polti,ariete&amp;d=19|AZ_41ECpKYdioL",
"Il meglio dei ferri da stiro di aprile 2016: guida all'acquisto|I ferri da stiro migliori disponibili proprio ora|2016/04/il-meglio-dei-ferri-da-stiro-di-aprile-2016-guida-all-acquisto.html?t=elettrodomestici,casa,ferro-a-vapore,ferro-da-stiro,vestito,rowenta,imetec,philips,ariete,polti,de-longhi,koenig,termozeta,bosch&amp;d=4|AZ_41MqF2i2O2L",
];
