Gr = [
"Pallone Europei 2016 Top Glider|Supera gli avversari con questo pallone da calcio di alta qualità. La|2017/12/pallone-europei-2016-top-glider|data.oliviero.it/imgprodotto/pallone-europei-2016-top-glider_142224",
"Pallone FC Internazionale Prestige|Il pallone da calcio FC Internazionale Prestige offre un tocco|2017/12/pallone-fc-internazionale-prestige|data.oliviero.it/imgprodotto/pallone-fc-internazionale-prestige_169697",
"Pallone Calcio Menor|Pallone Nike FootballX Menor. Di dimensioni più piccole rispetto ai|2017/12/pallone-calcio-menor|data.oliviero.it/imgprodotto/pallone-calcio-menor_169698",
"Pallone Calcio Nike Premier League|Il pallone da calcio Nike Strike Premier League, con camera d'aria in|2017/12/pallone-calcio-nike-premier-league|data.oliviero.it/imgprodotto/pallone-calcio-nike-premier-league_169701",
"Pallone Calcio FC Internazionale Supporters|Il pallone da calcio FC Internazionale Supporters è resistente|2017/12/pallone-calcio-fc-internazionale-supporters|data.oliviero.it/imgprodotto/pallone-calcio-fc-internazionale-supporters-sc3019_152057",
"Pallone da Calcio Strike Serie A|Il pallone da calcio Serie A Strike è dotato di camera d'aria in|2017/12/pallone-da-calcio-strike-serie-a|data.oliviero.it/imgprodotto/pallone-da-calcio-strike-serie-a_167128",
"Pallone Calcio Roma Skills|Impreziosito dai dettagli del club e dotato di un rivestimento in|2017/12/pallone-calcio-roma-skills|data.oliviero.it/imgprodotto/pallone-calcio-roma-skills-sc2520-670_90249",
"Pallone da Calcio Ufficiale Ordem V Serie A|Il pallone da calcio Serie A Ordem V, con scanalature Nike Aerowtrac|2017/12/pallone-da-calcio-ufficiale-ordem-v-serie-a|data.oliviero.it/imgprodotto/pallone-da-calcio-ufficiale-ordem-v-serie-a_167129",
"Pallone Calcio UCL Finale 16 Capitano|Imponi il tuo ritmo in campo con questo robusto pallone pensato per|2017/12/pallone-calcio-ucl-finale-16-capitano|data.oliviero.it/imgprodotto/pallone-calcio-ucl-finale-16-capitano-ap0375_154552",
"Pallone Red Wind 13 Sweet Touch|Pallone beach volley per allenamento \"Sweet Touch\" indicato per tutti|2017/12/pallone-red-wind-13-sweet-touch|data.oliviero.it/imgprodotto/pallone-red-wind-13-sweet-touch_63894",
"Pallone Wilson|Il vincitore della categoria Migliore oggetto inanimato dei Critics|2017/12/pallone-wilson|data.oliviero.it/imgprodotto/pallone-wilson_124508",
"Pallone Calcio Strike La Liga 2017|Il pallone da calcio Nike Strike La Liga, con camera d'aria in gomma|2017/12/pallone-calcio-strike-la-liga-2017|data.oliviero.it/imgprodotto/pallone-calcio-strike-la-liga-2017_169702",
"Pallone Calcio FC Barcelona Skills|Il pallone da calcio FC Barcelona Skills offre un tocco di palla|2017/12/pallone-calcio-fc-barcelona-skills|data.oliviero.it/imgprodotto/pallone-calcio-fc-barcelona-skills_169695",
"Pallone Ufficiale Finale 17|Questo pallone è identico al modello utilizzato nelle partite della|2017/12/pallone-ufficiale-finale-17|data.oliviero.it/imgprodotto/pallone-ufficiale-finale-17_167032",
"Pallone calcio Serie A Skills|Il pallone da calcio Serie A Skills sfoggia un design resistente|2017/12/pallone-calcio-serie-a-skills|data.oliviero.it/imgprodotto/pallone-calcio-serie-a-skills_169699",
"Pallone Calcio Neymar Strike|Il pallone da calcio Neymar Strike è dotato di camera d'aria in gomma|2017/12/pallone-calcio-neymar-strike|data.oliviero.it/imgprodotto/pallone-calcio-neymar-strike_169692",
"Pallone Calcio FC Barcelona Prestige|Il pallone da calcio FC Barcelona Prestige offre un tocco eccellente|2017/12/pallone-calcio-fc-barcelona-prestige|data.oliviero.it/imgprodotto/pallone-calcio-fc-barcelona-prestige_169700",
];
