Gr = [
"Sdraio Ocean Ecrù|Sdraio Relax Multi-posizione Struttura in tubolare di ferro|2017/12/sdraio-ocean-ecru|data.oliviero.it/imgprodotto/sdraio-ocean-ecr%C3%B9_108539",
"Set Lobra Dining Ecrù|Set Pranzo composto da tavolo e 6 poltrone Struttura in tubolare di|2017/12/set-lobra-dining-ecru|data.oliviero.it/imgprodotto/set-lobra-dining-ecr%C3%B9_108543",
"Barbecue Grande Pupo|Barbecue a carbone Cottura a carbone Area di cottura diametro: 57 cm|2017/12/barbecue-grande-pupo|data.oliviero.it/imgprodotto/barbecue-grande-pupo_146591",
"Poltrona Start Similpelle Bianca|Poltrona per ufficio Operativa, con base e braccioli in nylon, seduta|2017/12/poltrona-start-similpelle-bianca|data.oliviero.it/imgprodotto/poltrona-start-similpelle-bianca_149141",
"Amaca Bali Ecrù|Amaca Prendisole Struttura in tubolare di ferro verniciato a polvere|2017/12/amaca-bali-ecru|data.oliviero.it/imgprodotto/amaca-bali-ecr%C3%B9_108452",
"Dondolo Douglas Beige|Poltrona dondolo oscillante Struttura in legno massello verniciato|2017/12/dondolo-douglas-beige|data.oliviero.it/imgprodotto/dondolo-douglas-beige_108477",
"Scrivania Picture_Car|Scrivania con struttura in ferro verniciato di colore bianco, vetro|2017/12/scrivania-picture_car|data.oliviero.it/imgprodotto/scrivania-picture_car_108531",
"Poltrona Sake Nera|Poltrona per ufficio Direzionale, con base in acciaio cromato|2017/12/poltrona-sake-nera|data.oliviero.it/imgprodotto/poltrona-sake-nera_108512",
"Sgabello Funny Nero|Sgabello con struttura in acciaio cromato, seduta in nylon|2017/12/sgabello-funny-nero|data.oliviero.it/imgprodotto/sgabello-funny-nero_108545",
"Sgabello Funny Rosso|Sgabello con struttura in acciaio cromato, seduta in nylon|2017/12/sgabello-funny-rosso|data.oliviero.it/imgprodotto/sgabello-funny-rosso_108546",
"Poltrona Start Similpelle Nera|Poltrona per ufficio Operativa, con base e braccioli in nylon|2017/04/poltrona-start-similpelle-nera|data.oliviero.it/imgprodotto/poltrona-start-similpelle-nera_159933",
"Set Zanzibar Dining Ecrù|Set pranzo composto da tavolo in vetro temperato e 6 poltrone|2017/04/set-zanzibar-dining-ecru|data.oliviero.it/imgprodotto/set-zanzibar-dining-ecr%C3%B9_146616",
"Scrivania View-Floor|Scrivania con struttura in ferro verniciato di colore bianco, vetro|2017/04/scrivania-view-floor|data.oliviero.it/imgprodotto/scrivania-view_floor_108537",
];
