Gr = [
"Pulse + Attacchi Rhythm Giallo|Snowboard + attacchi UOMO Snowboard Pulse Pochi euro, molti brividi|2017/12/pulse-+-attacchi-rhythm-giallo|data.oliviero.it/imgprodotto/pulse-attacchi-rhythm-giallo_94273",
"Scarpe Trail Running Snowcross 2 CSWP|Non lasciare che una tormenta di neve interrompa il tuo allenamento|2017/12/scarpe-trail-running-snowcross-2-cswp|data.oliviero.it/imgprodotto/scarpe-trail-running-snowcross-2-cswp_169151",
"Scarponi Snow Pearl|AUTO PILOT A tutto stile con la scarpa Pearl— Con scarpetta Silver|2017/12/scarponi-snow-pearl|data.oliviero.it/imgprodotto/scarponi-snow-pearl_94283",
"Scarpe Trail Running Ellipse 2 GTX W|Scarpa da escursionismo leggera superwoman, la ELLIPSE 2 GTX® da|2017/12/scarpe-trail-running-ellipse-2-gtx-w|data.oliviero.it/imgprodotto/scarpe-trail-running-ellipse-2-gtx-w_169588",
"Scarpe Trail Running Speedcross 4 W|La quarta versione di questa scarpa da corsa iconica rivolta da capo|2017/12/scarpe-trail-running-speedcross-4-w|data.oliviero.it/imgprodotto/scarpe-trail-running-speedcross-4-w-393439_163291",
"Scarpe Trekking Evasion 2 Aero|Andare lontano con lo sguardo verso l'orizzonte seguendo i propri|2017/12/scarpe-trekking-evasion-2-aero|data.oliviero.it/imgprodotto/scarpe-trekking-evasion-2-aero-393597_163289",
"Snowboard Lotus + Attacchi Spell|Snowboard LotusTempo di fioriture La progressione di tutto ciò che la|2017/12/snowboard-lotus-+-attacchi-spell|data.oliviero.it/imgprodotto/snowboard-lotus-attacchi-spell_157542",
"Scarpe Trail Running Speedcross 4|La quarta versione di questa scarpa da corsa iconica rivolta da capo|2017/12/scarpe-trail-running-speedcross-4|data.oliviero.it/imgprodotto/scarpe-trail-running-speedcross-4-383130_163259",
"Scarpe Trail Running Speedcross 4 GTX|La SPEEDCROSS 4 GTX® è molto più che una scarpa da running, è un vero|2017/12/scarpe-trail-running-speedcross-4-gtx|data.oliviero.it/imgprodotto/scarpe-trail-running-speedcross-4-gtx_169160",
"Sanchez + Attacchi Rhytym|La Salvatore Sanchez è una pasata totale! Una bella banana (profilo|2017/12/sanchez-+-attacchi-rhytym|data.oliviero.it/imgprodotto/sanchez-attacchi-rhytym_24188_big",
"Scarpe Trail Running Xa Pro 3D GTX|Non c'è cattivo tempo con la giusta attrezzatura. Esci a giocare con|2017/12/scarpe-trail-running-xa-pro-3d-gtx|data.oliviero.it/imgprodotto/scarpe-trail-running-xa-pro-3d-gtx_169158",
"Scarpe Speedcross 4 GTX W|La SPEEDCROSS 4 GTX® per donna è molto più che una scarpa da running|2017/12/scarpe-speedcross-4-gtx-w|data.oliviero.it/imgprodotto/scarpe-speedcross-4-gtx-w_168699",
"Snowboard Spark + Attacchi Spell|La tavola snowboard Salomon Spark dotata della nuova tecnologia|2017/12/snowboard-spark-+-attacchi-spell|data.oliviero.it/imgprodotto/snowboard-spark-attacchi-spell_157544",
"Zaino S-Lab Advanced Skin Hydro 12 Set|Nuovo zaino form-fitting per le gare sulle lunghe distanze, super|2017/12/zaino-s-lab-advanced-skin-hydro-12-set|data.oliviero.it/imgprodotto/zaino-s-lab-advanced-skin-hydro-12-set_80306",
"Scarpe Trail Running XA Lite GTX|Affronta con mente sveglia e passo leggero qualsiasi terreno, in|2017/12/scarpe-trail-running-xa-lite-gtx|data.oliviero.it/imgprodotto/scarpe-trail-running-xa-lite-gtx_169156",
"Sandali Techamphibian 3 W|L'ultima evoluzione della classica scarpa anfibia, con fodera più|2017/12/sandali-techamphibian-3-w|data.oliviero.it/imgprodotto/sandali-techamphibian-3-w-128490_147664",
"Scarpe Trekking Authentic LTR GTX|Scarpe Trekking Authentic LTR GTX - 373260 Scarpa leggera in pelle|2017/12/scarpe-trekking-authentic-ltr-gtx|data.oliviero.it/imgprodotto/scarpe-trekking-authentic-ltr-gtx-373260_145350",
];
