Gr = [
"Scarpe Shadow Original Uomo|Saucony Originals Shadow O' uomo: le sneakers scelte per leggerezza|2017/12/scarpe-shadow-original-uomo|data.oliviero.it/imgprodotto/scarpe-shadow-original-uomo_167367",
"Scarpe Running Freedom ISO W|Le scarpe running Saucony Freedom ISO rappresentano il massimo in|2017/12/scarpe-running-freedom-iso-w|data.oliviero.it/imgprodotto/scarpe-running-freedom-iso-w_167255",
"Scarpe Jazz Original Donna|Saucony Originals Jazz O' donna Nero/Verde Acqua : dal 1981 le|2017/12/scarpe-jazz-original-donna|data.oliviero.it/imgprodotto/scarpe-jazz-original-donna_167356",
"Scarpe Running Freedom ISO|Freedom rappresenta il punto più alto della tecnologia Saucony. Non|2017/12/scarpe-running-freedom-iso|data.oliviero.it/imgprodotto/scarpe-running-freedom-iso_167274",
"Scarpe Running Kinvara 8 Giro d'Italia|Questa versione con colorazione rosa e lacci tricolore è stata|2017/12/scarpe-running-kinvara-8-giro-d-italia|data.oliviero.it/imgprodotto/scarpe-running-kinvara-8-giro-ditalia_165011",
"Scarpe Running Grid Cohesion 9|Scarpe Running Grid Cohesion 9 - S15262-4 PROFILO ATLETA: l'entry|2017/12/scarpe-running-grid-cohesion-9|data.oliviero.it/imgprodotto/scarpe-running-grid-cohesion-9-s25262-20_149094",
"Scarpe Trail Running Xodus ISO|Da sempre la miglior scarpa da trail Saucony. Nuova versione con|2017/12/scarpe-trail-running-xodus-iso|data.oliviero.it/imgprodotto/scarpe-trail-running-xodus-iso-s20325-2_152469",
"Scarpe Jazz Original Uomo|Saucony Originals Jazz O' uomo Nero/Bianco: dal 1981 le sneakers|2017/12/scarpe-jazz-original-uomo|data.oliviero.it/imgprodotto/scarpe-jazz-original-uomo_153506",
"Scarpe Running Echelon 6|Drop: 8mm Tallone: 27mm Avampiede: 19mm PROFILO ATLETA: Scarpa da|2017/12/scarpe-running-echelon-6|data.oliviero.it/imgprodotto/scarpe-running-echelon-6_168710",
"Scarpe Running Jazz 18 (W)|PROFILO ATLETA: perché Jazz continua a essere il modello più amato?|2017/12/scarpe-running-jazz-18-w|data.oliviero.it/imgprodotto/scarpe-running-jazz-18-w-s10307-12_161068",
"Scarpe Running Jazz 18|perché Jazz continua a essere il modello più amato? Il segreto sta|2017/12/scarpe-running-jazz-18|data.oliviero.it/imgprodotto/scarpe-running-jazz-18_168718",
"Scarpe Fitness Kineta Relay|PROFILO: Dopo la corsa, per tenersi in forma anche in palestra|2017/12/scarpe-fitness-kineta-relay|data.oliviero.it/imgprodotto/scarpe-fitness-kineta-relay-s25244-24_163953",
"Scarpe Running Grid Cohesion 10|Le scarpe running Saucony Cohesion 10 sono state ridisegnate per|2017/12/scarpe-running-grid-cohesion-10|data.oliviero.it/imgprodotto/scarpe-running-grid-cohesion-10_167253",
"Scarpe Running Triumph ISO 3|Scarpa dell'anno ai Running Industry Awards, è il modello Saucony più|2017/12/scarpe-running-triumph-iso-3|data.oliviero.it/imgprodotto/scarpe-running-triumph-iso-3_167277",
"Scarpe Running Kineta Relay|Allenamento PROFILO: Dopo la corsa, per tenersi in forma anche in|2017/12/scarpe-running-kineta-relay|data.oliviero.it/imgprodotto/scarpe-running-kineta-relay-s15244-9_161057",
"Scarpe Running Ride 9|In perfetto equilibrio tra ammortizzamento e reattività e con un look|2017/12/scarpe-running-ride-9|data.oliviero.it/imgprodotto/scarpe-running-ride-9-s20334-1_152485",
"Scarpe Running Ride 10|Le scarpe running Saucony Ride 10 sono le ultime arrivate della|2017/12/scarpe-running-ride-10|data.oliviero.it/imgprodotto/scarpe-running-ride-10_167272",
"Scarpe Running Ride 9 Reflex (W)|Nuova Ride, che osiamo definire, come la migliore di sempre. Tra le|2017/12/scarpe-running-ride-9-reflex-w|data.oliviero.it/imgprodotto/scarpe-running-ride-9-reflex-w-s10331-2_153481",
"Scarpe Running Triumph ISO 4|Nuova versione Saucony Triumph Iso 4, con intersuola interamente in|2017/12/scarpe-running-triumph-iso-4|data.oliviero.it/imgprodotto/scarpe-running-triumph-iso-4_172203",
"Scarpe Jazz Original Vintage Donna|Le sneakers Saucony Originals sono un mix di stile, tendenza e gusto|2017/12/scarpe-jazz-original-vintage-donna|data.oliviero.it/imgprodotto/scarpe-jazz-original-vintage-donna_172377",
];
