Gr = [
"Spatola per Spalmare|Spatola prodotta in acciaio inox di alta qualità con eleganti|2017/12/spatola-per-spalmare|data.oliviero.it/imgprodotto/spatola-per-spalmare-638711_155230",
"MiniTritatutto 150 watt|MiniTritatutto 150 watt Codice: 90.330 Descrizione : Corpo in abs|2017/12/minitritatutto-150-watt|data.oliviero.it/imgprodotto/minitritatutto-150-watt_157400",
"Affetta verdure Ghidini 3 in 1|Affetta verdure Ghidini 3 in 1 Uno strumento utile e di facile|2017/12/affetta-verdure-ghidini-3-in-1|data.oliviero.it/imgprodotto/affetta-verdure-ghidini-3-in-1_156178",
"Affetta uovo Multifunzionale|A fettine sottili o a spicchi: decidi tu come preferisci tagliare le|2017/12/affetta-uovo-multifunzionale|data.oliviero.it/imgprodotto/affetta-uovo-multifunzionale_74106",
"Stampo per Angel Cake|La angel cake e la chiffon cake sono due deliziose torte soffici|2017/12/stampo-per-angel-cake|data.oliviero.it/imgprodotto/stampo-per-angel-cake-623152_155227",
"Accessorio Cappellini Atlas 150|Taglia a rulli la pasta, 1mm Capellini da fogli di pasta fino|2017/12/accessorio-cappellini-atlas-150|data.oliviero.it/imgprodotto/accessorio-cappellini-atlas-150_156200",
"Matterello Regolabile|Questo straordinario matterello consente di regolare lo spessore|2017/12/matterello-regolabile|data.oliviero.it/imgprodotto/matterello-regolabile-630182_155141",
"Stampo per ravioli quadrati|Siamo fan del 'fatto in casà e quando si parla di pasta fresca, ci|2017/12/stampo-per-ravioli-quadrati|data.oliviero.it/imgprodotto/stampo-per-ravioli-quadrati-630877_157775",
"Tostapane Bianco|Non perdere l'opportunità di acquistare il vostro acciaio|2017/12/tostapane-bianco|data.oliviero.it/imgprodotto/tostapane-bianco_156067",
"Biscottiera Elettrica|Biscottiera Codice: 90.603 Descrizione : Piastra in alluminio|2017/12/biscottiera-elettrica|data.oliviero.it/imgprodotto/biscottiera-elettrica-90-603_90285",
"Pestello Cocktail|Questo colorato accessorio in plastica resistente è ideale per|2017/12/pestello-cocktail|data.oliviero.it/imgprodotto/pestello-cocktail-308836_155204",
"Temperino Julienne Grande|Per preparare in modo semplice e veloce golosi spaghetti di verdura|2017/12/temperino-julienne-grande|data.oliviero.it/imgprodotto/temperino-julienne-grande-422061_155201",
"Spremiagrumi 47cm Rosso|Uno spremi melograno può essere utilizzato anche per altri agrumi ma|2017/12/spremiagrumi-47cm-rosso|data.oliviero.it/imgprodotto/spremiagrumi-47cm-rosso_156145",
"Frullatore a Immersione 220W Acciaio|Frullatore a Immersione 220W Acciaio Codice: 90.321 Descrizione|2017/12/frullatore-a-immersione-220w-acciaio|data.oliviero.it/imgprodotto/frullatore-a-immersione-220w-acciaio-90-321_89122",
"Affetta Ananas|Pratico e maneggevole, lo usi tutto l'anno, così potrai gustare|2017/12/affetta-ananas|data.oliviero.it/imgprodotto/affetta-ananas-643650_157830",
"Accessorio Mafaldine Atlas 150|Accessorio per macchina Atlas 150 per mafaldine. Progettato per|2017/12/accessorio-mafaldine-atlas-150|data.oliviero.it/imgprodotto/accessorio-mafaldine-atlas-150_156418",
"Lievita Pagnotta|Questo utensile si compone di un cestino traforato e di una ciotola|2017/12/lievita-pagnotta|data.oliviero.it/imgprodotto/lievita-pagnotta-643160_155248",
"Impastatrice professionale 1000 watt|Impastatrice 1000 watt Codice: 90.700 Descrizione : 5 L 6 velocità|2017/12/impastatrice-professionale-1000-watt|data.oliviero.it/imgprodotto/impastatrice-professionale-1000-watt-90-700_90349",
"Sminuzzatore erbe Aromatiche -|Il segreto per un trito perfetto in un lampo è questo utensile dalle|2017/12/sminuzzatore-erbe-aromatiche|data.oliviero.it/imgprodotto/sminuzzatore-erbe-aromatiche-_159493",
"Filtro con manico|I filtri permettono alle foglie del tè di aprirsi al meglio e di|2017/12/filtro-con-manico|data.oliviero.it/imgprodotto/filtro-con-manico_154083",
"Sminuzzatore per erbe Aromatiche Presto|Il segreto per un trito perfetto in un lampo è questo utensile dalle|2017/12/sminuzzatore-per-erbe-aromatiche-presto|data.oliviero.it/imgprodotto/sminuzzatore-per-erbe-aromatiche-presto_93295",
"Macchina per Lasagnette|ACCESSORIO LASAGNETTE MACCHINA PER LA PASTA IMPERIA Imperia simplex|2017/12/macchina-per-lasagnette|data.oliviero.it/imgprodotto/macchina-per-lasagnette_156470",
"Impastatrice professionale Bianco Nero|Impastatrice professionale Bianco Nero Descrizione: Ciotola|2017/12/impastatrice-professionale-bianco-nero|data.oliviero.it/imgprodotto/impastatrice-professionale-bianco-nero-90-344n_160647",
"Frullatore Smoothie Maker New Nova Princess|Frullatore pratico ideale per verdura, frutta fresca e yogurt Dotato|2017/12/frullatore-smoothie-maker-new-nova-princess|data.oliviero.it/imgprodotto/frullatore-smoothie-maker-new-nova-princess_115442",
"Macchina a Motore Per Pasta Fresca Atlas|Unione tra Atlas 150 e motore Pastadrive: un connubio perfetto tra|2017/12/macchina-a-motore-per-pasta-fresca-atlas|data.oliviero.it/imgprodotto/macchina-a-motore-per-pasta-fresca-atlas_156445",
"Temperino per carote linea Presto|Questo piccolo e colorato accessorio dalla lama affilata, crea, senza|2017/12/temperino-per-carote-linea-presto|data.oliviero.it/imgprodotto/temperino-per-carote-linea-presto_90703",
"Grattugia Multifunzione|La mandolina multifunzione è un pezzo forte nelle preparazioni in|2017/12/grattugia-multifunzione|data.oliviero.it/imgprodotto/grattugia-multifunzione-643860_155157",
"Centrifuga 350W per frutta e verdura|Centrifuga 350W per frutta e verdura Codice: 90.313A Descrizione|2017/12/centrifuga-350w-per-frutta-e-verdura|data.oliviero.it/imgprodotto/centrifuga-350w-per-frutta-e-verdura-90-313a_157371",
"Set costata con spezie cucina australiana|Set dall'atmosfera australiana ideale per servire deliziose carni|2017/12/set-costata-con-spezie-cucina-australiana|data.oliviero.it/imgprodotto/set-costata-con-spezie-cucina-australiana_156049",
"Spremiagrumi Elettrico 1 litro Bianco|Spremiagrumi Elettrico 1 litro Bianco Codice: 90.302/B Descrizione|2017/12/spremiagrumi-elettrico-1-litro-bianco|data.oliviero.it/imgprodotto/spremiagrumi-elettrico-1-litro-bianco-90-302-b_89066",
"Mandolina con lama in ceramica|L'allegria di colori vitaminici e la precisione di taglio di|2017/12/mandolina-con-lama-in-ceramica|data.oliviero.it/imgprodotto/mandolina-con-lama-in-ceramica_155127",
"Accessorio Spaghetti Chitarra Atlas 150|Accessorio per macchina Atlas 150 per spaghetti chitarra da 2 mm|2017/12/accessorio-spaghetti-chitarra-atlas-150|data.oliviero.it/imgprodotto/accessorio-spaghetti-chitarra-atlas-150_156414",
"Macchina caffè espresso 90.521|Macchina per il caffè espresso 90.521 Macchina caffè espresso Corpo|2017/12/macchina-caffe-espresso-90-521|data.oliviero.it/imgprodotto/macchina-caff%C3%A8-espresso-90-521_157643",
"Frullatore FR45|Frullatore a 2 velocità con bicchiere da 1,5 L per golosi frullati da|2017/12/frullatore-fr45|data.oliviero.it/imgprodotto/frullatore-fr45_155563",
"Taglia Patate a spirale|Vuoi preparare un contorno insolito? Prova il nuovo taglia patate:|2017/12/taglia-patate-a-spirale|data.oliviero.it/imgprodotto/taglia-patate-a-spirale-420637_157873",
"Shaker per Uova con separatore Albume|Prepari una frittata, un'omelette, delle crepes? Dolci a base di|2017/12/shaker-per-uova-con-separatore-albume|data.oliviero.it/imgprodotto/shaker-per-uova-con-separatore-albume_155167",
"Macchina Pasta Fresca Delicata|Caratteristiche Ideale per preparare pasta fresca fatta in casa come|2017/12/macchina-pasta-fresca-delicata|data.oliviero.it/imgprodotto/macchina-pasta-fresca-delicata_157728",
"Bollitore 1,7 litri|Bollitore 1,7 litri Codice: 90.393 Descrizione: Corpo in plastica|2017/12/bollitore-1-7-litri|data.oliviero.it/imgprodotto/bollitore-1-7-litri-90-393_88995",
"Paletta per Gnocchi|Tieni in forma i tuoi gnocchi! La paletta, grazie alla particolare|2017/12/paletta-per-gnocchi|data.oliviero.it/imgprodotto/paletta-per-gnocchi-420360_155101",
"Set 3 Misurini a Tazza|Tre misurini a tazza in plastica colorata resistente, permettono di|2017/12/set-3-misurini-a-tazza|data.oliviero.it/imgprodotto/set-3-misurini-a-tazza-420734_155162",
"Spatola in silicone|La spatola in silicone è indispensabile per preparare gli impasti|2017/12/spatola-in-silicone|data.oliviero.it/imgprodotto/spatola-in-silicone-420504_155178",
"Robot da Cucina 300 watt|Robot da Cucina 300 watt Codice: 90.312 Descrizione : Corpo in abs|2017/12/robot-da-cucina-300-watt|data.oliviero.it/imgprodotto/robot-da-cucina-300-watt-90-312_89077",
"Macchina Pasta Fresca Roller Classic Atlas 150|Un autentica e originale macchina italiana per la pasta fresca|2017/12/macchina-pasta-fresca-roller-classic-atlas-150|data.oliviero.it/imgprodotto/macchina-pasta-fresca-roller-classic-atlas-150_156435",
"Rullo Tagliapasta Multifunzionale|Per creare dolci e salatini dalle più svariate forme ecco il rullo|2017/12/rullo-tagliapasta-multifunzionale|data.oliviero.it/imgprodotto/rullo-tagliapasta-multifunzionale-630023_155134",
"Teiera con filtro 1,25 Lt|Resistente al calore, è ideale per preparare tè, infusi, tisane, ma|2017/12/teiera-con-filtro-1-25-lt|data.oliviero.it/imgprodotto/teiera-con-filtro-1-25-lt_93316",
"Frullatore FR75|Frullatore con bicchiere in vetro temperato e 6 lame, ideale per|2017/12/frullatore-fr75|data.oliviero.it/imgprodotto/frullatore-fr75_155562",
"Accessorio Vermicelli Atlas 150|Accessorio per macchina Atlas 150 per vermicelli. Progettato per|2017/12/accessorio-vermicelli-atlas-150|data.oliviero.it/imgprodotto/accessorio-vermicelli-atlas-150_156417",
"Sfogliatrici per impastatrice 90.342A|Sfogliatrici per impastatrice 90.342A Inclusi: Rotolo di stiramento|2017/12/sfogliatrici-per-impastatrice-90-342a|data.oliviero.it/imgprodotto/sfogliatrici-per-impastatrice-90-342a_160646",
"Macchina Per Pasta Fresca 180 Atlas|Caratteristiche principali del SMV Marcato Ampia 180 Macchina|2017/12/macchina-per-pasta-fresca-180-atlas|data.oliviero.it/imgprodotto/macchina-per-pasta-fresca-180-atlas_156439",
"Accessorio Spaghetti Atlas 150|Accessorio per macchina Atlas 150 per spaghetti da 2 mm. Progettato|2017/12/accessorio-spaghetti-atlas-150|data.oliviero.it/imgprodotto/accessorio-spaghetti-atlas-150_156202",
"Piastra Induzione PI01|Per padelle e caffettiere ad induzione. Potenza 2000 W 2 velocita di|2017/12/piastra-induzione-pi01|data.oliviero.it/imgprodotto/piastra-induzione-pi01_156338",
"Stampo per Ravioli Tondi|Siamo fan del 'fatto in casà e quando si parla di pasta fresca, ci|2017/12/stampo-per-ravioli-tondi|data.oliviero.it/imgprodotto/stampo-per-ravioli-tondi-630875_155240",
"Passaverdura cm 24|Professionale maneggievole e pratico. il Passaverdure I cucinieri|2017/12/passaverdura-cm-24|data.oliviero.it/imgprodotto/passaverdura-cm-24_156150",
"Coltello Pelacipolle|Uno strumento piccolo, leggero e utilissimo per pelare le cipolle!|2017/12/coltello-pelacipolle|data.oliviero.it/imgprodotto/coltello-pelacipolle-420633_155193",
"Grattugia Multifunzionale a tamburo|Sminuzzi, affetti e grattugi frutta, verdura, formaggio, legumi|2017/12/grattugia-multifunzionale-a-tamburo|data.oliviero.it/imgprodotto/grattugia-multifunzionale-a-tamburo-643582_157827",
"Grattugia a fori piccoli e medi|Eleganti ed incredibilmente funzionali le nuove grattugie della linea|2017/12/grattugia-a-fori-piccoli-e-medi|data.oliviero.it/imgprodotto/grattugia-a-fori-piccoli-e-medi_74071",
"Macchina per la pasta manuale|Macchina per la pasta manuale Corpo e rulli in acciaio Funzionamento|2017/12/macchina-per-la-pasta-manuale|data.oliviero.it/imgprodotto/macchina-per-la-pasta-manuale_160586",
"Temperino Julienne|Per preparare in modo semplice e veloce golosi spaghetti di verdura|2017/12/temperino-julienne|data.oliviero.it/imgprodotto/temperino-julienne-422060_157889",
"Sbucciatore Julienne con Lama Laterale|Ami le verdure alla julienne? Questo sbucciatore è leggerissimo|2017/12/sbucciatore-julienne-con-lama-laterale|data.oliviero.it/imgprodotto/sbucciatore-julienne-con-lama-laterale-421022_155129",
"Bollitore Elettrico 1.7 litri acciaio 90.351N|90.351A Bollitore Elettrico 1.7 litri acciaio Corpo in acciaio|2017/12/bollitore-elettrico-1-7-litri-acciaio-90-351n|data.oliviero.it/imgprodotto/bollitore-elettrico-1-7-litri-acciaio-90-351n_165162",
"Accessorio Reginette Atlas 150|Accessorio per macchina Atlas 150 per reginette. Progettato per|2017/12/accessorio-reginette-atlas-150|data.oliviero.it/imgprodotto/accessorio-reginette-atlas-150_156425",
"Bollitore 1.7 L|Caratteristiche: Plastica / capacità di 1,7 litro coperchio di|2017/12/bollitore-1-7-l|data.oliviero.it/imgprodotto/bollitore-1-7-l_156186",
"Grattugia e Affettaverdura|Grattugia e Affettaverdura Codice: 90.055 colore bianco e rosso|2017/12/grattugia-e-affettaverdura|data.oliviero.it/imgprodotto/grattugia-e-affettaverdura-90-055_89042",
"Robot da cucina 500W|Robot da cucina 500W - AZZURRO - 90.470A Descrizione: Potenza: 500|2017/12/robot-da-cucina-500w|data.oliviero.it/imgprodotto/robot-da-cucina-500w-azzurro-90-470a_160690",
"Bollitore BL20|Bollitore da 1,7 L per tisane e bevande calde. Molto pratico da usare|2017/12/bollitore-bl20|data.oliviero.it/imgprodotto/bollitore-bl20_156337",
"Affetta Uovo|Se devi preparare sfiziose tartine o affettare le uova per guarnire|2017/12/affetta-uovo|data.oliviero.it/imgprodotto/affetta-uovo-420644_155103",
"Passaverdura cm 19|Professionale maneggievole e pratico il Passaverdure I cucinieri|2017/12/passaverdura-cm-19|data.oliviero.it/imgprodotto/passaverdura-cm-19_156149",
"Vaporiera multicottura|Vaporiera multicottura con spegnimento automatico|2017/10/vaporiera-multicottura|data.oliviero.it/imgprodotto/vaporiera-multicottura_88965",
"Essiccatore per frutta e Verdura|Essiccazione rapida e sicura con flusso continuo di aria calda|2017/10/essiccatore-per-frutta-e-verdura|data.oliviero.it/imgprodotto/essiccatore-per-frutta-e-verdura-90-506_130752",
];
