Gr = [
"I 10 lettori DVD portatili che piacciono di più: settembre 2016|I 10 lettori DVD portatili che incontrano il maggiore gradimento|2016/09/i-10-lettori-dvd-portatili-che-piacciono-di-piu-settembre-2016|AZ_51goQGh83lL",
"Le 15 action camera migliori: agosto 2016|La top 15 delle migliori action camera sul mercato a agosto 2016|2016/08/le-15-action-camera-migliori-agosto-2016|AZ_416Imqx-2CL",
"Le 16 migliori videocamere subacquee: luglio 2016|Le 16 videocamere subacquee più apprezzate oggi disponibili: luglio 2016|2016/07/le-16-migliori-videocamere-subacquee-luglio-2016.html?t=videocamere-subacquee,videocamere,sub,subacquea,videocamere-sportive,action-camera,elettronica,telecamere,fotografia,sport,mare,lago,nuoto,video,tempo-libero,full-hd,wireless,wi-fi,dbpower,nikon&amp;d=6|AZ_41ng7MQnRcL",
"Le 13 migliori videocamere sportive: luglio 2016|Le 13 videocamere sportive migliori oggi sul mercato: luglio 2016|2016/07/le-13-migliori-videocamere-sportive-luglio-2016.html?t=videocamere,videocamere-sportive,action-camera,videocamere-subacquee,elettronica,video,tempo-libero,full-hd,wireless,wi-fi,telecamere,hardware,fotografia,bicicletta,mountain-bike,sport,ciclismo,dbpower,polaroid&amp;d=4|AZ_41pUP6jUj5L",
"Maggio 2016: le migliori telecamere di sorveglianza|Ecco la classifica aggiornata a maggio 2016 del meglio delle telecamere di sorveglianza|2016/05/maggio-2016-le-migliori-telecamere-di-sorveglianza.html?t=sicurezza,telecamere-sorveglianza,elettronica,video,videocamere,sorveglianza,casa,antifurto,furto,allarme,sistema-di-allarme,smartphone,telecamere,wireless,wi-fi,d-link,dbpower&amp;d=3|AZ_41gdzyxjU8L",
"I proiettori più quotati: la guida all'acquisto di aprile 2016|Il meglio dei proiettori disponibili per l'acquisto|2016/04/i-proiettori-piu-quotati-la-guida-all-acquisto-di-aprile-2016.html?t=proiettori,elettronica,video,tempo-libero,full-hd,televisori,tv,film,home-cinema,home-video,dvd,blu-ray,videogiochi,console-videogiochi,dbpower,tronfy,excelvan,benq,epson,acer&amp;d=25|AZ_31soCGu+0EL",
"Aprile 2016: le action camera più interessanti per l'acquisto|Tutto il meglio delle action camera: guida all'acquisto|2016/04/aprile-2016-le-action-camera-piu-interessanti-per-l-acquisto.html?t=elettronica,action-camera,video,tempo-libero,full-hd,youtube,mountain-bike,sport,allenamento,bicicletta,ciclismo,corsa,correre,wi-fi,wireless,dbpower,andoer,gopro,sony&amp;d=21|AZ_51uqN+lHsEL",
];
