Gr = [
"I 10 Apparecchi Misura-Pressione migliori, a gennaio 2017|I 10 Apparecchi Misura-Pressione più richiesti, disponibili subito!|2017/01/i-10-apparecchi-misura-pressione-migliori-a-gennaio-2017|AZ_41T6dt7WWXL",
"I 10 stepper più acquistati: ottobre 2016|I 10 stepper più utilizzati disponibili da subito: ottobre 2016|2016/10/i-10-stepper-piu-acquistati-ottobre-2016|AZ_31AX+PXInWL",
"Ellittiche, Cyclette: i 5 migliori di settembre 2016|I 5 migliori prodotti di settembre 2016 in Ellittiche, Cyclette|2016/09/ellittiche-cyclette-i-5-migliori-di-settembre-2016|AZ_4122QB+LjVL",
"Le 12 migliori ellittiche: agosto 2016|Le 12 ellittiche più consigliate: la classifica aggiornata a agosto 2016|2016/08/le-12-migliori-ellittiche-agosto-2016|AZ_41NmOnUBHGL",
"Maggio 2016: le 12 ellittiche più interessanti per l'acquisto|Ecco il meglio delle ellittiche sul mercato|2016/05/maggio-2016-le-12-ellittiche-piu-interessanti-per-l-acquisto.html?t=dimagrire,palestra,tempo-libero,sport,allenamento,training,ellittiche,fitness,corsa,correre,cuore,salute,obesita,benessere,ginnastica,peso-corporeo,muscoli,diadora&amp;d=5|AZ_41rA15e31XL",
"La classifica aggiornata a maggio 2016 degli activity tracker più acquistati|Il meglio degli activity tracker: guida all'acquisto|2016/05/la-classifica-aggiornata-a-maggio-2016-degli-activity-tracker-piu-acquistati.html?t=tempo-libero,activity-tracker,cardiofrequenzimetri,sport,allenamento,training,dimagrire,palestra,fitness,bicicletta,ciclismo,tennis,corsa,correre,cuore,salute,garmin,fitbit,xiaomi,polar,sony&amp;d=3|AZ_41uW9OppOWL",
"Aprile 2016: i misuratori di pressione più interessanti per l'acquisto|La classifica del meglio dei misuratori di pressione|2016/04/aprile-2016-i-misuratori-di-pressione-piu-interessanti-per-l-acquisto.html?t=salute,misura-pressione,benessere,ipertensione,pressione-arteriosa,farmacia,medicina,sangue,cuore,laica&amp;d=14|AZ_41T6dt7WWXL",
"I 15 cardiofrequenzimetri più quotati: aprile 2016|Il meglio dei cardiofrequenzimetri in commercio|2016/04/i-15-cardiofrequenzimetri-piu-quotati-aprile-2016.html?t=tempo-libero,cardiofrequenzimetri,sport,allenamento,training,dimagrire,palestra,fitness,bicicletta,ciclismo,tennis,corsa,correre,cuore,salute,sigma,polar&amp;d=11|AZ_31GxSUMX7dL",
"Video - Cuocere un uovo a forma di cuore?|Perfetto per un'occasione speciale, per un compleanno o per San Valentino!|2016/01/video-cuocere-un-uovo-a-forma-di-cuore.html?t=alimentazione,cucina,cibo,cuore,san-valentino,compleanno,uovo,trucchi,gastronomia&amp;d=6|YT_4lCAqRzMtVM",
"Dormire troppo aumenta il rischio di ictus?|Un nuovo studio dell'Università di Cambridge ipotizza una correlazione tra il dormire troppo e il rischio di ictus|2015/05/dormire-troppo-aumenta-il-rischio-di-ictus.html?t=sonno,ictus,memoria,cuore,ipertensione,medicina,salute,scienza,anziani,cambridge&amp;d=1|stroke",
"Bere troppa acqua fa male alla salute? E la regola dei due litri?|L'aquaholism è una vera e propria dipendenza da acqua. Bere troppa acqua affaticherebbe i reni, e avrebbe perfino ripercussioni psicologiche|2015/04/bere-troppa-acqua-fa-male-alla-salute-e-la-regola-dei-due-litri.html?t=salute,acqua,dieta,alimentazione,insonnia,sudorazione,reni,dipendenza,sete,nervosismo,ansia,cuore,londra,foto-divertenti&amp;d=1|water-tap-sculpture",
];
