Gr = [
"Grattugia a fori piccoli e medi|Eleganti ed incredibilmente funzionali le nuove grattugie della linea|2017/12/grattugia-a-fori-piccoli-e-medi|data.oliviero.it/imgprodotto/grattugia-a-fori-piccoli-e-medi_74071",
"Anello Regolabile rettangolare|Realizza dolci di dimensioni diverse con un'unica tortiera! Lo stampo|2017/12/anello-regolabile-rettangolare|data.oliviero.it/imgprodotto/anello-regolabile-rettangolare_75868",
"Stampo cioccolatini cucchiaini|Lascia a bocca aperta i tuoi invitati! Servi il caffè sostituendo al|2017/12/stampo-cioccolatini-cucchiaini|data.oliviero.it/imgprodotto/stampo-cioccolatini-cucchiaini-629370_157786",
"Rullo Taglia Raviolini Tondi diam. 7 cm|Per ottenere da un impasto file di cerchi perfetti con uno scarto|2017/12/rullo-taglia-raviolini-tondi-diam-7-cm|data.oliviero.it/imgprodotto/rullo-taglia-raviolini-tondi-diam-7-cm_144200",
"Temperino Julienne|Per preparare in modo semplice e veloce golosi spaghetti di verdura|2017/12/temperino-julienne|data.oliviero.it/imgprodotto/temperino-julienne-422060_157889",
"Sbucciatore Julienne con Lama Laterale|Ami le verdure alla julienne? Questo sbucciatore è leggerissimo|2017/12/sbucciatore-julienne-con-lama-laterale|data.oliviero.it/imgprodotto/sbucciatore-julienne-con-lama-laterale-421022_155129",
"Stampo cioccolatini per 18 chicchi caffè|Stupisci i tuoi ospiti accompagnando il caffè con dei simpatici|2017/12/stampo-cioccolatini-per-18-chicchi-caffe|data.oliviero.it/imgprodotto/stampo-cioccolatini-per-18-chicchi-caff%C3%A8-629373_157780",
"3 Coltelli da Bistecca|Completa la tavola informale con delle posate divertenti: quelle|2017/12/3-coltelli-da-bistecca|data.oliviero.it/imgprodotto/3-coltelli-da-bistecca-863142_155107",
"Ciotoline Graduate 3 pz|Ciotoline graduate in plastica resistente colorata, sono pensate per|2017/12/ciotoline-graduate-3-pz|data.oliviero.it/imgprodotto/ciotoline-graduate-3-pz-_74082",
"Pirottini in Silicone|La mandolina multifunzione è un pezzo forte nelle preparazioni in|2017/12/pirottini-in-silicone|data.oliviero.it/imgprodotto/pirottini-in-silicone-630650_155159",
"Griglia per dolci|Se quando decori torte e biscotti con glassa, cacao e zuccherini|2017/12/griglia-per-dolci|data.oliviero.it/imgprodotto/griglia-per-dolci-630350_157895",
"Borsa Porta Bottiglie Refrigerante|Mantiene a lungo la temperatura delle bevande refrigerate durante la|2017/12/borsa-porta-bottiglie-refrigerante|data.oliviero.it/imgprodotto/borsa-porta-bottiglie-refrigerante-308846_155233",
"Stampo per Croissant|Croissant perfetti come in pasticceria? Con questo stampo|2017/12/stampo-per-croissant|data.oliviero.it/imgprodotto/stampo-per-croissant_74086",
"3 Coppapasta Triangolo|Vuoi impiattare da vero professionista? Con i coppapasta|2017/12/3-coppapasta-triangolo|data.oliviero.it/imgprodotto/3-coppapasta-triangolo-422216_155185",
"Portavivande Termico 2,5 lt|Con i nuovi elegantissimi contenitori termici puoi organizzare una|2017/12/portavivande-termico-2-5-lt|data.oliviero.it/imgprodotto/portavivande-termico-2-5-lt_93332",
"Porta cucchiai|Porta cucchiai in acciaio con finiture cromo, ideale per appoggiare|2017/12/porta-cucchiai|data.oliviero.it/imgprodotto/porta-cucchiai_74104",
"Affetta Uovo|Se devi preparare sfiziose tartine o affettare le uova per guarnire|2017/12/affetta-uovo|data.oliviero.it/imgprodotto/affetta-uovo-420644_155103",
"Tagliabiscotti per frollini tradizionali|Con questi tagliabiscotti potrai preparare frollini dalle forme|2017/12/tagliabiscotti-per-frollini-tradizionali|data.oliviero.it/imgprodotto/tagliabiscotti-per-frollini-tradizionali-630932_157768",
"Caffettiera 6 Tazze|Caffettiera prodotta in speciale alluminio alimentare con guarnizione|2017/12/caffettiera-6-tazze|data.oliviero.it/imgprodotto/caffettiera-6-tazze_74162",
"Porta Torte con tavoletta refrigerante|Le torte sono la tua passione? Ecco un comodissimo portatorte!|2017/10/porta-torte-con-tavoletta-refrigerante|data.oliviero.it/imgprodotto/porta-torte-630842_155105",
"Scolaposate in acciaio con finiture cromo|Scolaposate con cassettino per raccogliere e svuotare l'acqua di scolo|2017/06/scolaposate-in-acciaio-con-finiture-cromo|data.oliviero.it/imgprodotto/scolaposate_73996",
"Colino 12 cm maglie fini|Ha le maglie fini ed è perfetto per setacciare liquidi o ingredienti...|2017/04/colino-12-cm-maglie-fini|data.oliviero.it/imgprodotto/colino-12-cm-428046_157815",
];
