Gr = [
"La top 10 dei migliori Telescopi: gennaio 2017|I 10 Telescopi più venduti: la guida all'acquisto di gennaio 2017|2017/01/la-top-10-dei-migliori-telescopi-gennaio-2017|AZ_41qtiPiLgNL",
"Video - Giove domina il cielo di luglio 2016|Si può vedere a occhio nudo, scopriamo come con questo bel video!|2016/07/video-giove-domina-il-cielo-di-luglio-2016.html?t=astronomia,scienza,astrofisica,spazio,inaf,pianeta,giove,stella,costellazione,natura,cielo,notte&amp;d=2|YT_Y152OugSwpw",
"Video - Se hai perso il transito di Mercurio e ora vuoi ammazzarti|ASPETTA, non tutto è perduto!|2016/05/video-se-hai-perso-il-transito-di-mercurio-e-ora-vuoi-ammazzarti.html?t=scienza,astronomia,astrofisica,spazio,inaf,pianeta,mercurio,sole,napoli,pink-floyd,queen,canzoni&amp;d=11|YT__uuVDA0FLlU",
"Aprile 2016: tutti i telescopi più venduti!|Il meglio dei telescopi nella nostra guida all'acquisto|2016/04/aprile-2016-tutti-i-telescopi-piu-venduti.html?t=scienza,astronomia,astrofisica,spazio,telescopio,via-lattea,galassia,pianeta,plutone,giove,stella,costellazione,ammasso-globulare,ammasso-stellare,catalogo-messier,marte,national-geographic&amp;d=18|AZ_41Y9zq9XAbL",
"Video - Il mistero del pianeta nano Plutone|Plutone è stato un mistero per anni, anzi per decenni|2016/04/video-il-mistero-del-pianeta-nano-plutone.html?t=astronomia,astrofisica,spazio,scienza,inaf,nasa,pianeta,plutone,caronte,new-horizons,sonda-spaziale&amp;d=1|YT_AUjhYS9Zym0",
"Video - Il mistero delle tavolette Babilonesi e il pianeta Giove|Il fantastico senso dei Babilonesi per la geometria e l'astronomia|2016/01/video-il-mistero-delle-tavolette-babilonesi-e-il-pianeta-giove.html?t=astronomia,spazio,scienza,pianeta,giove,matematica,geometria,inaf,babilonesi,berlino&amp;d=31|YT_P9Neav5PTjo",
"Video - Le meraviglie del cielo di gennaio|Tante cose bellissime nel cielo di questo nuovo anno appena iniziato|2016/01/video-le-meraviglie-del-cielo-di-gennaio.html?t=astronomia,astrofisica,spazio,scienza,stella,pianeta,costellazione,ammasso-globulare,ammasso-stellare,catalogo-messier,inaf&amp;d=3|YT_IAopwgYUhgg",
"Video - Cosa è possibile osservare nel cielo di ottobre?|Ce lo svela questo video dell'INAF, l'Istituto Nazionale di AstroFisica|2015/10/video-cosa-e-possibile-osservare-nel-cielo-di-ottobre.html?t=astronomia,stella,pianeta,costellazione,ammasso-globulare,catalogo-messier,scienza&amp;d=8|YT_saG8lrdHNss",
];
