Tt = "Società";
Gr = [
"I 10 Alberi di Natale più belli: novembre 2016|I 10 Alberi di Natale che incontrano il maggiore gradimento|2016/11/i-10-alberi-di-natale-piu-belli-novembre-2016|AZ_41LBD+ML-7L",
"Nome amante obbligatorio, animali investiti e cinture di sicurezza|Una legge per costringere la partner a svelare il nome dell'amante?|2016/09/nome-amante-obbligatorio-animali-investiti-e-cinture-di-sicurezza|love-elephant",
"Video - Il ristorante dove è vietato mangiare|In questo ristorante si fanno solo SelFoods|2016/04/video-il-ristorante-dove-e-vietato-mangiare.html?t=video-divertenti,umorismo,youtube,maccio-capatonda,societa,social-network,facebook,twitter,internet,web,selfie,ristorante,nerd,geek&amp;d=22|YT_4xAa_huweR0",
"Video - Una bella chiacchierata tecnologica|David Orban su algoritmi e intelligenza artificiale|2016/04/video-una-bella-chiacchierata-tecnologica.html?t=intelligenza-artificiale,societa,internet-degli-oggetti,david-orban,scienza,ingegneria,informatica,software,teoria-dei-giochi,gioco-a-somma-zero,algoritmo,internet-delle-cose&amp;d=3|YT__lXfk2KSIH4",
"Video - Va bene lo Slow Food, ma qui si esagera!|Non irritiamoci, manteniamo una composta calma, lentamente|2016/04/video-va-bene-lo-slow-food-ma-qui-si-esagera.html?t=video-divertenti,umorismo,the-jackal,napoli,youtube,societa,candid-camera,lentezza,fretta,stress,scherzi&amp;d=3|YT_Wj7XgOxG2fM",
"Video - La faccia che faccia-mo è sempre quella vera?|A volte si è apprezzati anche maggiormente se ci si contiene un attimino|2016/03/video-la-faccia-che-faccia-mo-e-sempre-quella-vera.html?t=video-divertenti,umorismo,the-jackal,societa,youtube,napoli&amp;d=26|YT_gyMDi-Kjvk0",
"Video - La scomparsa di Marco Bomber Putacaso|Un nuovo sconvolgente caso di cronaca nera per Neri Pupazzo|2016/03/video-la-scomparsa-di-marco-bomber-putacaso.html?t=video-divertenti,umorismo,youtube,societa,maccio-capatonda,social-network,facebook,twitter,internet&amp;d=25|YT_BzOD5p9nBSA",
"Video - È Natale! Mi ammazzo!|Aspetta che giorno è oggi? Zitto zitto forse anche quest'anno è andata|2015/12/video-e-natale-mi-ammazzo.html?t=video-divertenti,umorismo,the-jackal,societa,natale&amp;d=27|atomic-bomb",
"Video - Se i tuoi genitori stanno ancora insieme|Coraggio, ci sono qui i ragazzi di The Pills a condividere con te la sofferenza|2015/12/video-se-i-tuoi-genitori-stanno-ancora-insieme.html?t=video-divertenti,umorismo,amore,matrimonio,societa,viaggio-nel-tempo,the-pills&amp;d=25|YT_z1Kcqhder6s",
"Bumble, il social di incontri dove sono le donne a comandare|Al momento l'app, in Italia, è stata scaricata da circa 10mila utenti|2015/06/bumble-il-social-di-incontri-dove-sono-le-donne-a-comandare.html?t=amore,social-network,dating,incontri,tinder,societa,donna,smartphone,app,geolocalizzazione&amp;d=5|smartphone-woman",
"Gli uomini preferiscono le donne mature? O erano le bionde?|Molti giovani  sembrano affascinati dall'esperienza e dalla posizione sociale offerta dalla fascia più matura dell'altro sesso|2015/02/gli-uomini-preferiscono-le-donne-mature-o-erano-le-bionde.html?t=amore,dating,societa,donna,giovani&amp;d=9|marilyn-monroe",
];
