Gr = [
"Guanti MMA KIMURA MX|Caratteristiche: GENUINE LEATHER pelle ultra morbida e liscia|2017/12/guanti-mma-kimura-mx|data.oliviero.it/imgprodotto/guanti-mma-kimura-mx_65961",
"Guantoni BLACKSTORM Skull Nero 10 oz|Caratteristiche Prodotto: -Prestazione 3/5 -Qualità 4/5 -Sistema di|2017/12/guantoni-blackstorm-skull-nero-10-oz|data.oliviero.it/imgprodotto/guantoni-blackstorm-skull-nero-10-oz_159705",
"Guantoni Cyclone Restyling 10 oz|Caratteristiche: Guantoni Sphinx Cyclone Restyling: Class essential|2017/12/guantoni-cyclone-restyling-10-oz|data.oliviero.it/imgprodotto/guantoni-cyclone-restyling-10-oz_159704",
"Paratibia NAKAMURA|Caratteristiche : Paratibia omologato gara FULL-Kick COMPETITION|2017/12/paratibia-nakamura|data.oliviero.it/imgprodotto/paratibia-nakamura_159730",
"Guanti BLACKHAWK Evo Nero 10 oz|Caratteristiche: GENUINE LEATHER pelle ultra morbida e liscia|2017/12/guanti-blackhawk-evo-nero-10-oz|data.oliviero.it/imgprodotto/guanti-blackhawk-evo-nero-10-oz_73216",
"Guanto PRO-FIGHT Kombat FHX 8 oz|Caratteristiche: PRO-FIGHT KOMBAT FHX Competition Fight Glove Genuine|2017/12/guanto-pro-fight-kombat-fhx-8-oz|data.oliviero.it/imgprodotto/guanto-pro-fight-kombat-fhx-8-oz_159694",
"Pantaloni Full contact Breath-tech|Caratteristiche: Pantaloncino full-kick Hi-tech satin, morbido|2017/12/pantaloni-full-contact-breath-tech|data.oliviero.it/imgprodotto/pantaloni-full-contact-breath-tech_159733",
"Guantoni Ultimate Warrior Blood 10 oz|Caratteristiche: Ultimate Warrior Syntex PU: materiale composito|2017/12/guantoni-ultimate-warrior-blood-10-oz|data.oliviero.it/imgprodotto/guantoni-ultimate-warrior-blood-10-oz_159713",
"Guanto VIPER Fxx Tiger Edition 10oz|Caratteristiche: Genuine Leather pelle ultra morbida e liscia|2017/12/guanto-viper-fxx-tiger-edition-10oz|data.oliviero.it/imgprodotto/guanto-viper-fxx-tiger-edition-10oz_159700",
"Guanti BLACKHAWK Training 14 oz|Caratteristiche: GENUINE LEATHER pelle ultra morbida e liscia|2017/12/guanti-blackhawk-training-14-oz|data.oliviero.it/imgprodotto/guanti-blackhawk-training-14-oz_165109",
"Casco Steel Protezione zigomi|Caratteristiche: SYNTEX TECH materiale composito finitura pelle, alta|2017/12/casco-steel-protezione-zigomi|data.oliviero.it/imgprodotto/casco-steel-protezione-zigomi_159680",
"Guanto VIPER Fxx Bushido Edition 10oz|Caratteristiche: Genuine Leather pelle ultra morbida e liscia|2017/12/guanto-viper-fxx-bushido-edition-10oz|data.oliviero.it/imgprodotto/guanto-viper-fxx-bushido-edition-10oz_159697",
"Guantoni Cyclone Restyling 6 oz|Caratteristiche: Guantoni Sphinx Cyclone Restyling: Class essential|2017/12/guantoni-cyclone-restyling-6-oz|data.oliviero.it/imgprodotto/guantoni-cyclone-restyling-6-oz_159702",
"Guanti BLACKHAWK Training 16 oz|Caratteristiche: GENUINE LEATHER pelle ultra morbida e liscia|2017/12/guanti-blackhawk-training-16-oz|data.oliviero.it/imgprodotto/guanti-blackhawk-training-16-oz_159683",
"Guanto PRO-FIGHT Kombat FHX 10 oz|Caratteristiche: PRO-FIGHT KOMBAT FHX Competition Fight Glove Genuine|2017/12/guanto-pro-fight-kombat-fhx-10-oz|data.oliviero.it/imgprodotto/guanto-pro-fight-kombat-fhx-10-oz_159692",
"Guanto Ultimate Trainer IV|Caratteristiche: BUFFALO LEATHER pelle ultra morbida e liscia|2017/12/guanto-ultimate-trainer-iv|data.oliviero.it/imgprodotto/guanto-ultimate-trainer-iv_159696",
"Guanto PRO-FIGHT Kombat FHX 8oz|Caratteristiche: PRO-FIGHT KOMBAT FHX Competition Fight Glove Genuine|2017/12/guanto-pro-fight-kombat-fhx-8oz|data.oliviero.it/imgprodotto/guanto-pro-fight-kombat-fhx-8oz_159695",
"Paratibia PRO-AM neoprene-gel, PHOENIX II|Caratteristiche : SYNTEX TECH G3 e NEOPRENE LIGHT II, alta durata|2017/12/paratibia-pro-am-neoprene-gel-phoenix-ii|data.oliviero.it/imgprodotto/paratibia-pro-am-neoprene-gel-phoenix-ii_159724",
"Guanti da passata veloce STRYKER|Caratteristiche : Guanti da passata veloce STRYKER SYNTEX TECH G3|2017/12/guanti-da-passata-veloce-stryker|data.oliviero.it/imgprodotto/guanti-da-passata-veloce-stryker_159684",
"Calzari NAKAMURA|Caratteristiche : Calzare gara FULL-Kick COMPETITION SYNTEX FHX|2017/12/calzari-nakamura|data.oliviero.it/imgprodotto/calzari-nakamura_159675",
"Pantaloncini Boxe Breath-Tech|Caratteristiche: Pantaloncino boxe pro series Hi tech Satin, morbido|2017/12/pantaloncini-boxe-breath-tech|data.oliviero.it/imgprodotto/pantaloncini-boxe-breath-tech_159716",
"Guantoni DYNAMIC FXX PRO Rosso 10 oz|Caratteristiche: GENUINE LEATHER pelle ultra morbida e liscia|2017/12/guantoni-dynamic-fxx-pro-rosso-10-oz|data.oliviero.it/imgprodotto/guantoni-dynamic-fxx-pro-rosso-10-oz_159711",
"Protezioni braccia Pao PRO|Caratteristiche : Pao PRO, VANGARD MMX protezione braccio DURA HIGH|2017/12/protezioni-braccia-pao-pro|data.oliviero.it/imgprodotto/protezioni-braccia-pao-pro_159723",
"Guantoni Ultimate Warrior Thai 10 oz|Caratteristiche: Ultimate Warrior Syntex PU: materiale composito|2017/12/guantoni-ultimate-warrior-thai-10-oz|data.oliviero.it/imgprodotto/guantoni-ultimate-warrior-thai-10-oz_159714",
"Paratibia PRO SHADOW RFD Bushido Edition|Caratteristiche : SYNTEX TECH G3 materiale composito finitura pelle|2017/12/paratibia-pro-shadow-rfd-bushido-edition|data.oliviero.it/imgprodotto/paratibia-pro-shadow-rfd-bushido-edition_159728",
"Paratibia PRO SHADOW RFD Thailand Edition|Caratteristiche : SYNTEX TECH G3 materiale composito finitura pelle|2017/12/paratibia-pro-shadow-rfd-thailand-edition|data.oliviero.it/imgprodotto/paratibia-pro-shadow-rfd-thailand-edition_159725",
"Conchiglia PRO pugilato in pelle|Caratteristiche : American D-Luxe conchiglia omologata pugilato|2017/12/conchiglia-pro-pugilato-in-pelle|data.oliviero.it/imgprodotto/conchiglia-pro-pugilato-in-pelle_159682",
"Guantoni BLACKSTORM Skull Bianco 10 oz|Caratteristiche Prodotto: -Prestazione 3/5 -Qualità 4/5 -Sistema di|2017/12/guantoni-blackstorm-skull-bianco-10-oz|data.oliviero.it/imgprodotto/guantoni-blackstorm-skull-bianco-10-oz_159706",
"Guanti semicontact PRO FIGHT II|Caratteristiche: SYBTEX TECH G3 materiale composito finitura pelle|2017/12/guanti-semicontact-pro-fight-ii|data.oliviero.it/imgprodotto/guanti-semicontact-pro-fight-ii_159689",
"Guanti Fit Boxe e KICK-FIT|Caratteristiche: SYNTEX TECH G3 e neoprene alta durata e resistenza|2017/12/guanti-fit-boxe-e-kick-fit|data.oliviero.it/imgprodotto/guanti-fit-boxe-e-kick-fit_159685",
"Sacco Boxe e Arti Marziali Training 30 kg Nero|Pelle sintetica, riempitura a stracci triturati, certificati|2017/05/sacco-boxe-e-arti-marziali-training-30-kg-nero|data.oliviero.it/imgprodotto/sacco-training-30-kg-nero_159670",
];
