Gr = [
"Guanti da moto G-Flash Tex Lady|Guanti in tessuto tecnico con inserti in microfibra e zone|2017/12/guanti-da-moto-g-flash-tex-lady|data.oliviero.it/imgprodotto/guanti-da-moto-g-flash-tex-lady_165750",
"Guanti da Moto Wake Evo|Spidi Wake EVO è la perfetta combinazione tra ergonomia, stile|2017/12/guanti-da-moto-wake-evo|data.oliviero.it/imgprodotto/guanti-da-moto-wake-evo_165740",
"Guanti da Moto STS R Glove|STS-R è un guanto sportivo adatto tanto all'utilizzo sportivo, quanto|2017/12/guanti-da-moto-sts-r-glove|data.oliviero.it/imgprodotto/guanti-da-moto-sts-r-glove_165742",
"Copriscarpe HV-Cover|Pratico copristivale ad alta visibilit, realizzato in Nylon Pu ad|2017/12/copriscarpe-hv-cover|data.oliviero.it/imgprodotto/copriscarpe-hv-cover_165778",
"Giacca da Moto Flash Tex Uomo|Flash è un giubbino dal taglio sportivo, ideale per le escursioni nei|2017/12/giacca-da-moto-flash-tex-uomo|data.oliviero.it/imgprodotto/giacca-da-moto-flash-tex-uomo-t197-010_149754",
"Guanti da Moto TX-2|Spidi TX-2 è la nuova frontiera del guanto per il turismo avventura|2017/12/guanti-da-moto-tx-2|data.oliviero.it/imgprodotto/guanti-da-moto-tx-2-c69-026_149836",
"Giubbotto Moto Rogue Tex Lady|Collezione: Primavera Estate Tipologia: Giacca Moto da donna Tessuto:|2017/12/giubbotto-moto-rogue-tex-lady|data.oliviero.it/imgprodotto/giubbotto-moto-rogue-tex-lady_83604",
"Protezioni Moto Warrior Belt Low|Questo protettore lombare utilizza la tecnologia Warrior|2017/12/protezioni-moto-warrior-belt-low|data.oliviero.it/imgprodotto/protezioni-moto-warrior-belt-low_83697",
"Guanti da Moto TXR|TXR di Spidi è un guanto studiato per assecondare diversi stili di|2017/12/guanti-da-moto-txr|data.oliviero.it/imgprodotto/guanti-da-moto-txr_165747",
"Pantalone da Moto in tessuto Ronin|Ronin è un pantalone tecnico da moto studiato per offrire ai|2017/12/pantalone-da-moto-in-tessuto-ronin|data.oliviero.it/imgprodotto/pantalone-da-moto-in-tessuto-ronin-j51-026_149847",
"Giacca da Moto Fandango|Nata da una collaborazione con la celebre rivista francese Café|2017/12/giacca-da-moto-fandango|data.oliviero.it/imgprodotto/giacca-da-moto-fandango-p136-026_149805",
"Giacca da Moto H2Out Traveler|Traveler è una giacca impermeabile e termica da moto che, grazie al|2017/12/giacca-da-moto-h2out-traveler|data.oliviero.it/imgprodotto/giacca-da-moto-h2out-traveler-d147-087_164820",
"Giacca da Moto in Tessuto 448 Lady|Un giacca leggera ideale per la bella stagione, e sviluppata per un|2017/12/giacca-da-moto-in-tessuto-448-lady|data.oliviero.it/imgprodotto/giacca-da-moto-in-tessuto-448-lady-t151-026_150508",
"Guanti da moto STR 5|STR-5 è l'evoluzione del guanto ideato per coniugare le|2017/12/guanti-da-moto-str-5|data.oliviero.it/imgprodotto/guanti-da-moto-str-5-a175-026_164806",
"Guanti da Moto STS-S|STS-S è un tradizionale guanto racing che ben si adatta alle sportive|2017/12/guanti-da-moto-sts-s|data.oliviero.it/imgprodotto/guanti-da-moto-sts-s_165738",
"Giacca da Moto Net Stream Uomo|Netstream è una giacca da moto in rete 3D ad altissimo coefficiente|2017/12/giacca-da-moto-net-stream-uomo|data.oliviero.it/imgprodotto/giacca-da-moto-net-stream-uomo-t199-486_149780",
"Giubbotto Moto Elite P108|Collezione: Primavera Estate Tipologia: Giacca Moto da donna Tessuto:|2017/12/giubbotto-moto-elite-p108|data.oliviero.it/imgprodotto/giubbotto-moto-elite-p108_83608",
"Giacca da Moto Trk Evo|SPIDI TRK-EVO è una giacca in pelle da moto per il motociclista|2017/12/giacca-da-moto-trk-evo|data.oliviero.it/imgprodotto/giacca-da-moto-trk-evo-p141-022_164828",
"Giubbino da Moto Scout H2Out|SPIDI Scout H2Out una giacca impermeabile da moto dall'aspetto|2017/12/giubbino-da-moto-scout-h2out|data.oliviero.it/imgprodotto/giubbino-da-moto-scout-h2out-d146-026_164826",
"Giacca da Moto in Tessuto 608 Uomo|Giacca realizzata in tessuto ad alta tenacità, caratterizzato da un|2017/12/giacca-da-moto-in-tessuto-608-uomo|data.oliviero.it/imgprodotto/giacca-da-moto-in-tessuto-608-uomo-t162-265_149818",
"Jeans da Moto J Strong|J-Strong è un jeans tecnico da moto con vestibilità Slim Fit|2017/12/jeans-da-moto-j-strong|data.oliviero.it/imgprodotto/jeans-da-moto-j-strong-j53-804_164808",
"Giacca da Moto Tronik Tex|Caratteristiche Capo impermeabile 50% Fodera removibile con ovatta da|2017/12/giacca-da-moto-tronik-tex|data.oliviero.it/imgprodotto/giacca-da-moto-tronik-tex-t210-011_164810",
"Giacca da Moto Flash Tex Lady|Flash Lady è un giubbino dal taglio sportivo, ideale per le|2017/12/giacca-da-moto-flash-tex-lady|data.oliviero.it/imgprodotto/giacca-da-moto-flash-tex-lady-t198-010_149761",
"Guanti da Moto Mega X Lady|Mega-X Lady il guanto espressamente sviluppato per il motocross da|2017/12/guanti-da-moto-mega-x-lady|data.oliviero.it/imgprodotto/guanti-da-moto-mega-x-lady_165754",
"Giacca da Moto Roadrunner|SPIDI Roadrunner è una giacca in pelle dal design sobrio e senza|2017/12/giacca-da-moto-roadrunner|data.oliviero.it/imgprodotto/giacca-da-moto-roadrunner-p142-341_164831",
"Completo Moto Antipioggia Sirena|Completo da moto antipioggia da donna. 100% impermeabile. Nella|2017/12/completo-moto-antipioggia-sirena|data.oliviero.it/imgprodotto/completo-moto-antipioggia-sirena-x45_83616",
"Protezione Schiena Warrior L2|Warrior L2 è un compatto paraschiena studiato per l'utilizzo urbano|2017/12/protezione-schiena-warrior-l2|data.oliviero.it/imgprodotto/protezione-schiena-warrior-l2_165774",
"Guanti da moto Squared|Il guanto da moto Squared è il frutto di un accurato studio sulle|2017/12/guanti-da-moto-squared|data.oliviero.it/imgprodotto/guanti-da-moto-squared_165746",
"Giacca da Moto Evorider Tex Uomo|Evorider Tex è una giacca corta da moto ideale con i modelli naked|2017/12/giacca-da-moto-evorider-tex-uomo|data.oliviero.it/imgprodotto/giacca-da-moto-evorider-tex-uomo-t205-021_149741",
"Giacca da Moto Summernet Lady|SPIDI Summernet Lady è una fresca giacca da moto per l'utilizzo|2017/12/giacca-da-moto-summernet-lady|data.oliviero.it/imgprodotto/giacca-da-moto-summernet-lady-t188-026_149796",
"Giubbotto Moto Performance|Collezione: Primavera Estate Tipologia: Giacca Moto in tessuto da|2017/12/giubbotto-moto-performance|data.oliviero.it/imgprodotto/giubbotto-moto-performance_83573",
"Jeans da Moto J Max Denim|J-Max rappresenta l'evoluzione del concetto di jeans tecnico da moto|2017/12/jeans-da-moto-j-max-denim|data.oliviero.it/imgprodotto/jeans-da-moto-j-max-denim-j147-806_149844",
"Guanti Moto Acid Glove|Un guanto giovane, dinamico e perfetto per l'utilizzo con moto naked|2017/12/guanti-moto-acid-glove|data.oliviero.it/imgprodotto/guanti-moto-acid-glove_83720",
"Jeans da Moto J Flex Denim|Spidi J-Flex è denim da moto molto confortevole, confezionato con|2017/12/jeans-da-moto-j-flex-denim|data.oliviero.it/imgprodotto/jeans-da-moto-j-flex-denim-j36-806_149842",
"Scaldacollo Neck Warmer|Spidi Neck Warmer un comodo collare termico, idoneo per l'utilizzo|2017/12/scaldacollo-neck-warmer|data.oliviero.it/imgprodotto/scaldacollo-neck-warmer_165780",
"Giacca da Moto Worker H2Out Lady|Worker H2Out Lady è l'evoluzione femminile della giacca capace di|2017/12/giacca-da-moto-worker-h2out-lady|data.oliviero.it/imgprodotto/giacca-da-moto-worker-h2out-lady-d153-315_164822",
"Antiacqua Pacific Wp Kit|Il completo antipioggia SPIDI Pacific è composto da una lunga giacca|2017/12/antiacqua-pacific-wp-kit|data.oliviero.it/imgprodotto/antiacqua-pacific-wp-kit_165781",
];
