Gr = [
"Giubbino da Moto Scout H2Out|SPIDI Scout H2Out una giacca impermeabile da moto dall'aspetto|2017/12/giubbino-da-moto-scout-h2out|data.oliviero.it/imgprodotto/giubbino-da-moto-scout-h2out-d146-026_164826",
"Giacca da Moto in Tessuto 608 Uomo|Giacca realizzata in tessuto ad alta tenacità, caratterizzato da un|2017/12/giacca-da-moto-in-tessuto-608-uomo|data.oliviero.it/imgprodotto/giacca-da-moto-in-tessuto-608-uomo-t162-265_149818",
"Jeans da Moto J Strong|J-Strong è un jeans tecnico da moto con vestibilità Slim Fit|2017/12/jeans-da-moto-j-strong|data.oliviero.it/imgprodotto/jeans-da-moto-j-strong-j53-804_164808",
"Giacca da Moto Tronik Tex|Caratteristiche Capo impermeabile 50% Fodera removibile con ovatta da|2017/12/giacca-da-moto-tronik-tex|data.oliviero.it/imgprodotto/giacca-da-moto-tronik-tex-t210-011_164810",
"Giacca da Moto Flash Tex Lady|Flash Lady è un giubbino dal taglio sportivo, ideale per le|2017/12/giacca-da-moto-flash-tex-lady|data.oliviero.it/imgprodotto/giacca-da-moto-flash-tex-lady-t198-010_149761",
"Guanti da Moto Mega X Lady|Mega-X Lady il guanto espressamente sviluppato per il motocross da|2017/12/guanti-da-moto-mega-x-lady|data.oliviero.it/imgprodotto/guanti-da-moto-mega-x-lady_165754",
"Giacca da Moto Roadrunner|SPIDI Roadrunner è una giacca in pelle dal design sobrio e senza|2017/12/giacca-da-moto-roadrunner|data.oliviero.it/imgprodotto/giacca-da-moto-roadrunner-p142-341_164831",
"Completo Moto Antipioggia Sirena|Completo da moto antipioggia da donna. 100% impermeabile. Nella|2017/12/completo-moto-antipioggia-sirena|data.oliviero.it/imgprodotto/completo-moto-antipioggia-sirena-x45_83616",
"Protezione Schiena Warrior L2|Warrior L2 è un compatto paraschiena studiato per l'utilizzo urbano|2017/12/protezione-schiena-warrior-l2|data.oliviero.it/imgprodotto/protezione-schiena-warrior-l2_165774",
"Guanti da moto Squared|Il guanto da moto Squared è il frutto di un accurato studio sulle|2017/12/guanti-da-moto-squared|data.oliviero.it/imgprodotto/guanti-da-moto-squared_165746",
"Giacca da Moto Evorider Tex Uomo|Evorider Tex è una giacca corta da moto ideale con i modelli naked|2017/12/giacca-da-moto-evorider-tex-uomo|data.oliviero.it/imgprodotto/giacca-da-moto-evorider-tex-uomo-t205-021_149741",
"Giacca da Moto Summernet Lady|SPIDI Summernet Lady è una fresca giacca da moto per l'utilizzo|2017/12/giacca-da-moto-summernet-lady|data.oliviero.it/imgprodotto/giacca-da-moto-summernet-lady-t188-026_149796",
"Giubbotto Moto Performance|Collezione: Primavera Estate Tipologia: Giacca Moto in tessuto da|2017/12/giubbotto-moto-performance|data.oliviero.it/imgprodotto/giubbotto-moto-performance_83573",
"Jeans da Moto J Max Denim|J-Max rappresenta l'evoluzione del concetto di jeans tecnico da moto|2017/12/jeans-da-moto-j-max-denim|data.oliviero.it/imgprodotto/jeans-da-moto-j-max-denim-j147-806_149844",
"Guanti Moto Acid Glove|Un guanto giovane, dinamico e perfetto per l'utilizzo con moto naked|2017/12/guanti-moto-acid-glove|data.oliviero.it/imgprodotto/guanti-moto-acid-glove_83720",
"Jeans da Moto J Flex Denim|Spidi J-Flex è denim da moto molto confortevole, confezionato con|2017/12/jeans-da-moto-j-flex-denim|data.oliviero.it/imgprodotto/jeans-da-moto-j-flex-denim-j36-806_149842",
"Scaldacollo Neck Warmer|Spidi Neck Warmer un comodo collare termico, idoneo per l'utilizzo|2017/12/scaldacollo-neck-warmer|data.oliviero.it/imgprodotto/scaldacollo-neck-warmer_165780",
"Giacca da Moto Worker H2Out Lady|Worker H2Out Lady è l'evoluzione femminile della giacca capace di|2017/12/giacca-da-moto-worker-h2out-lady|data.oliviero.it/imgprodotto/giacca-da-moto-worker-h2out-lady-d153-315_164822",
"Antiacqua Pacific Wp Kit|Il completo antipioggia SPIDI Pacific è composto da una lunga giacca|2017/12/antiacqua-pacific-wp-kit|data.oliviero.it/imgprodotto/antiacqua-pacific-wp-kit_165781",
];
