Gr = [
"Video - Alan Walker sbarca in Grand Theft Auto|Un machinima di Faded girato completamente in Grand Theft Auto|2016/07/video-alan-walker-sbarca-in-grand-theft-auto.html?t=musica,canzoni,alan-walker,youtube,social-network,facebook,gaming,videogiochi,geek,nerd,machinima,grand-theft-auto&amp;d=22|grand-theft-auto",
"Video - Il ristorante dove è vietato mangiare|In questo ristorante si fanno solo SelFoods|2016/04/video-il-ristorante-dove-e-vietato-mangiare.html?t=video-divertenti,umorismo,youtube,maccio-capatonda,societa,social-network,facebook,twitter,internet,web,selfie,ristorante,nerd,geek&amp;d=22|YT_4xAa_huweR0",
"Video - La scomparsa di Marco Bomber Putacaso|Un nuovo sconvolgente caso di cronaca nera per Neri Pupazzo|2016/03/video-la-scomparsa-di-marco-bomber-putacaso.html?t=video-divertenti,umorismo,youtube,societa,maccio-capatonda,social-network,facebook,twitter,internet&amp;d=25|YT_BzOD5p9nBSA",
"Video - Limoni nel naso, gatti o meccanica quantistica?|Per vostra e per mia fortuna, l'entanglement quantistico non ricorre spesso nelle conversazioni|2016/01/video-limoni-nel-naso-gatti-o-meccanica-quantistica.html?t=scienza,fisica,meccanica-quantistica,entanglement,douglas-adams,facebook,inaf&amp;d=19|YT_r2vnaGEaD0E",
"Belen si dissocia dalle diete miracolose|Sulla bacheca Facebook della showgirl argentina erano comparsi centinaia di messaggi che pubblicizzavano dubbi prodotti dietetici|2015/04/belen-si-dissocia-dalle-diete-miracolose.html?t=belen-rodriguez,attrici,modelle,facebook,social-network,dieta,dimagrire&amp;d=22|belen-rodriguez",
"Video - Come diventare uno scrittore di successo sfruttando le reti sociali|E magari vivere felici? Non lo sappiamo, e non è neanche facile, però nel frattempo vedere questo interessante panel male non fa|2015/03/video-come-diventare-uno-scrittore-di-successo-sfruttando-le-reti-sociali.html?t=libri,social-network,facebook,twitter,social-media-week,milano,blog,scrivere,foto-divertenti&amp;d=8|writers-block",
"Il primo corto di 5 minuti realizzato interamente in realtà virtuale|Il progetto è stato realizzato da Oculus VR, società acquisita nel 2014 da Facebook per 2 miliardi di dollari|2015/01/il-primo-corto-di-5-minuti-realizzato-interamente-in-realta-virtuale.html?t=oculus-rift,facebook,realta-virtuale,sundance,pixar,lucasfilm&amp;d=28|oculus-rift",
"Twitter si trasforma in stile WhatsApp|Una svolta epocale che rende di fatto possibile le cosiddette \"chat di gruppo\"|2015/01/twitter-si-trasforma-in-stile-whatsapp.html?t=twitter,whatsapp,facebook,vine,instagram,chat,internet&amp;d=27|twitter-key",
"Rembrandt contro Facebook|Rembrandt da una parte con uno dei dipinti più famosi al mondo, Facebook dall'altra. Chi la spunterà?|2014/12/rembrandt-contro-facebook.html?t=foto-divertenti,facebook,rembrandt,amsterdam,olanda&amp;d=26|facepalm",
];
