Gr = [
"11 luglio 1958: Heinlein scrive il più bel racconto di sempre sui paradossi temporali|Oggi Robert A. Heinlein scrive in un solo giorno All You Zombies (Tutti voi zombie)|2016/07/11-luglio-1958-heinlein-scrive-il-piu-bel-racconto-di-sempre-sui-paradossi-temporali.html?t=fantascienza,robert-a-heinlein,viaggio-nel-tempo,scrittori,premio-hugo,geek&amp;d=11|robert-a-heinlein",
"Prepariamoci a nuove esistenze: siete pronti per la prossima iterazione?|Ciò che deve accadere accadrà, perché è già accaduto|2016/06/prepariamoci-a-nuove-esistenze-siete-pronti-per-la-prossima-iterazione.html?t=fantascienza,geek,scrittori,ted-chiang,musica,canzoni,cantanti,franco-battiato,mondo-virtuale,realta-virtuale,metaverso,scienza,nick-bostrom&amp;d=10|recursion",
"Video - Gameplay in italiano di Adr1ft, per Oculus Rift e PC|Pensate a cosa dev'essere giocato con un visore per la realtà virtuale!|2016/03/video-gameplay-in-italiano-di-adr1ft-per-oculus-rift-e-pc.html?t=videogiochi,adr1ft,oculus-rift,realta-virtuale,fantascienza,spazio,claude-debussy,gameplay&amp;d=31|YT_UR8hMNkiOhU",
"Video - Uncanny Valley, un corto che non parla di robotica|Nei ghetti del futuro, drogati di realtà virtuale soddisfano gli istinti più violenti immersi in un mondo online|2016/03/video-uncanny-valley-un-corto-che-non-parla-di-robotica.html?t=realta-virtuale,mondo-virtuale,fantascienza,intelligenza-artificiale,avatar,geek,metaverso,videogiochi,uncanny-valley&amp;d=2|YT_UXX0TRtg5Vk",
"Video - La prossima generazione di robot umanoidi|Non è fantascienza, è l'ultima creazione di Boston Dynamics, rilevata da Google nel 2013|2016/02/video-la-prossima-generazione-di-robot-umanoidi.html?t=robot,robotica,spazio,fantascienza,scienza,isaac-asimov,automa,boston-dynamics,google,intelligenza-artificiale&amp;d=25|YT_rVlhMGQgDkY",
"Per Carnevale, un costume a tema Star Wars!|Accidenti è solo per bambino. Sicuri non ce ne siano anche da grande?|2016/01/per-carnevale-un-costume-a-tema-star-wars.html?t=offerte,shopping,giochi,giocattoli,costumi,carnevale,star-wars,guerre-stellari,cinema,film,fantascienza,bambini,ragazzi&amp;d=23|AZ_41El2Tlv0SL",
"Video - Cerere e la fantascienza di The Expanse|Cerere è il pianeta nano più vicino alla Terra, e non conosce stagioni|2015/12/video-cerere-e-la-fantascienza-di-the-expanse.html?t=astronomia,astrofisica,spazio,fantascienza,scienza,marte,cerere,fascia-degli-asteroidi,syfy,space-opera,premio-hugo,inaf&amp;d=28|YT_kS6akT0YUlQ",
"Ma come può finire l'Eternità?|Per tutti gli amanti della fantascienza, e non solo|2015/11/ma-come-puo-finire-l-eternita.html?t=fantascienza,libri,isaac-asimov,scrittori,viaggio-nel-tempo,fringe,geek&amp;d=18|isaac-asimov",
"Video - Acqua su Marte: cosa c'è di diverso questa volta?|Scopriamolo insieme guardando questo video dell'Istituto Nazionale di AstroFisica|2015/10/video-acqua-su-marte-cosa-c-e-di-diverso-questa-volta.html?t=scienza,astronomia,astrofisica,spazio,marte,nasa,acqua,fantascienza,ray-bradbury&amp;d=2|ray-bradbury",
"Video - Abiogenesis: il corto di fantascienza che ha vinto tutto|Un corto fantascientifico del talentuoso Richard Mans ci fa vedere come potrebbe essere andata|2015/07/video-abiogenesis-il-corto-di-fantascienza-che-ha-vinto-tutto.html?t=fantascienza,spazio,nasa,vita,robot,sonda,video&amp;d=23|asteroid",
"Video - Interstellar, il film di Giancarlo Fontana|Una produzione di Inception. Ehi, aspetta un attimo!|2015/05/video-interstellar-il-film-di-giancarlo-fontana.html?t=video-divertenti,umorismo,cinema,film,fantascienza,interstellar,christopher-nolan,samantha-cristoforetti,spazio&amp;d=26|rocket-crash",
];
