Gr = [
"Ellittica ERX 90 + ricevitore Polar|Sistema di frenaggio magnetico con regolazione elettronica dello|2017/12/ellittica-erx-90-+-ricevitore-polar|data.oliviero.it/imgprodotto/ellittica-erx-90-ricevitore-polar_68842",
"Tapis Roulant TRX Active Compact|TRX ACTIVE COMPACT Garanzia a vita sul telaio. Pre-assemblato pronto|2017/12/tapis-roulant-trx-active-compact|data.oliviero.it/imgprodotto/tapis-roulant-trx-active-compact_159623",
"Tapis Roulant TRX Endurance|TRX ENDURANCE MOTORE AC. FASCIA CARDIO TOORX inclusa. Garanzia a vita|2017/12/tapis-roulant-trx-endurance|data.oliviero.it/imgprodotto/tapis-roulant-trx-endurance_159521",
"Recumbent ChronoLine BRX R300|La nuovissima cyclette Toorx BRX R 300 fa parte della nuova linea|2017/12/recumbent-chronoline-brx-r300|data.oliviero.it/imgprodotto/recumbent-chronoline-brx-r300_153878",
"Tapis Roulant TRX Marathon|Il tappeto TRX Marathon ha un motore da 4 cavalli con un picco di|2017/12/tapis-roulant-trx-marathon|data.oliviero.it/imgprodotto/tapis-roulant-trx-marathon_149166",
"Tapis Roulant TRX 40 S EVO|Tapis Roulant pre-assemblato, 2 ruote di trasporto. AIR CUSHIONS|2017/12/tapis-roulant-trx-40-s-evo|data.oliviero.it/imgprodotto/tapis-roulant-trx-40-s-evo_159597",
"Rullo massaggio 3 in 1|Il rullo massaggio 3 in 1 è composto da tre rulli con dimensioni|2017/12/rullo-massaggio-3-in-1|data.oliviero.it/imgprodotto/rullo-massaggio-3-in-1-ahf061_151344",
"Gym bike SRX 60|La gym bike SRX 60. Trasmissione a cinghia con pignone fisso Sistema|2017/12/gym-bike-srx-60|data.oliviero.it/imgprodotto/gym-bike-srx-60_94019",
"Gym bike SRX 80 con ricevitore Polar|Caratteristiche SRX-80 Trasmissione a cinghia con pignone fisso|2017/12/gym-bike-srx-80-con-ricevitore-polar|data.oliviero.it/imgprodotto/gym-bike-srx-80-con-ricevitore-polar_90133",
"Tapis Roulant Trx 65 S EVO con App Ready|Caratteristiche Motore: 3/4 (Peak) HP DC - Garanzia 3 anni Velocità:|2017/12/tapis-roulant-trx-65-s-evo-con-app-ready|data.oliviero.it/imgprodotto/tapis-roulant-trx-65-s-evo-con-app-ready_142170",
"Cyclette BRX Comfort Accesso facilitato|Sistema di frenaggio magnetico su 8 posizioni. Volano peso 6 kg. Peso|2017/12/cyclette-brx-comfort-accesso-facilitato|data.oliviero.it/imgprodotto/cyclette-brx-comfort-accesso-facilitato_68808",
"Tapis Roulant TRX 60 S EVO|TRX-60 S EVO Garanzia a vita sul telaio. Pre-assemblato. HRC-Heart|2017/12/tapis-roulant-trx-60-s-evo|data.oliviero.it/imgprodotto/tapis-roulant-trx-60-s-evo_159607",
"Cyclette BRX R Compact recumbent|Toorx Cyclette BRX R-Compact Recumbent è la nuova Ciclocamera|2017/12/cyclette-brx-r-compact-recumbent|data.oliviero.it/imgprodotto/cyclette-brx-r-compact-recumbent_91891",
"Power Tower WBX 70|I power tower, o dip and chin up station, consentono di allenare la|2017/12/power-tower-wbx-70|data.oliviero.it/imgprodotto/power-tower-wbx-70_165249",
"Gym bike SRX 90 con fascia cardio|Trasmissione a cinghia con pignone fisso. Sistema di frenaggio|2017/12/gym-bike-srx-90-con-fascia-cardio|data.oliviero.it/imgprodotto/gym-bike-srx-90-con-fascia-cardio_68845",
"Tapis Roulant TRX 90 S HRC + Fascia Cardio|Il tappeto Toorx TRX90S è dotato di fascia cardio Polar T34, di|2017/12/tapis-roulant-trx-90-s-hrc-+-fascia-cardio|data.oliviero.it/imgprodotto/tapis-roulant-trx-90-s-hrc-fascia-cardio_91906",
"Ellittica ERX 80|Sistema di frenaggio magnetico con regolazione manuale dello sforzo|2017/12/ellittica-erx-80|data.oliviero.it/imgprodotto/ellittica-erx-80_157428",
"Vogatore Rower Compact|SALVASPAZIO. Caratteristiche tecniche: Computer con LCD numero|2017/12/vogatore-rower-compact|data.oliviero.it/imgprodotto/vogatore-rower-compact_60002",
"Recumbent BRX R Comfort|DATI TECNICI BRX-R COMFORT Sistema di frenaggio magnetico su|2017/12/recumbent-brx-r-comfort|data.oliviero.it/imgprodotto/recumbent-brx-r-comfort_84845",
"Fascia Cardio Toorx|FASCIA CARDIO TOORX Fascia Cardio per rilevazione wireless della|2017/12/fascia-cardio-toorx|data.oliviero.it/imgprodotto/fascia-cardio-toorx_84882",
"Gym bike SRX 40|Gym bike SRX 40. Trasmissione a catena con pignone fisso Sistema di|2017/12/gym-bike-srx-40|data.oliviero.it/imgprodotto/gym-bike-srx-40_59927",
"Tapis Roulant TRX Grand Cruiser|Allenati piacevolmente a casa tua con le stesse prestazioni di un|2017/12/tapis-roulant-trx-grand-cruiser|data.oliviero.it/imgprodotto/tapis-roulant-trx-grand-cruiser_149174",
"Mattonella Yoga AHF025|Supporto ideale per esercizi di pilates, yoga e stiramento, fornisce|2017/12/mattonella-yoga-ahf025|data.oliviero.it/imgprodotto/mattonella-yoga-ahf025_151337",
"Cyclette BRX 85|Cyclette BRX 85 Sistema di frenaggio : magnetico con regolazione|2017/12/cyclette-brx-85|data.oliviero.it/imgprodotto/cyclette-brx-85_159750",
"Cyclette BRX Flexi|Sistema di frenaggio magnetico su 8 posizioni. Volano peso 6 kg. Peso|2017/12/cyclette-brx-flexi|data.oliviero.it/imgprodotto/cyclette-brx-flexi_68802",
"Tapis Roulant TRX Smart Compact|Tapis roulant pre-assemblato pronto all'uso. SALVASPAZIO. Innovativo|2017/12/tapis-roulant-trx-smart-compact|data.oliviero.it/imgprodotto/tapis-roulant-trx-smart-compact_153874",
"Sfera Tonificante|Ideale per il potenziamento muscolare di braccia spalle e gambe|2017/12/sfera-tonificante|data.oliviero.it/imgprodotto/sfera-tonificante_151342",
"Tapis Roulant TRX 100|DATI TECNICI TRX 100 Motore4/7 (Peak) HP AC - Garanzia 5 anni|2017/12/tapis-roulant-trx-100|data.oliviero.it/imgprodotto/tapis-roulant-trx-100_159583",
"Ruota doppia per addominali AHF047|Ideale per allenare e rafforzare addominali, schiena, spalle|2017/12/ruota-doppia-per-addominali-ahf047|data.oliviero.it/imgprodotto/ruota-doppia-per-addominali-ahf047_151339",
];
