Gr = [
"I 10 forni a microonde con grill migliori: ottobre 2016|I 10 forni a microonde con grill più utilizzati: la guida all'acquisto|2016/10/i-10-forni-a-microonde-con-grill-migliori-ottobre-2016|AZ_41TBAlGK7qL",
"I 10 forni combinati più venduti: ottobre 2016|I 10 forni combinati che vanno per la maggiore, disponibili da subito|2016/10/i-10-forni-combinati-piu-venduti-ottobre-2016|AZ_31TfGDPVl2L",
"I 10 forni elettrici più utilizzati: settembre 2016|La top 10 dei migliori forni elettrici disponibili da subito|2016/09/i-10-forni-elettrici-piu-utilizzati-settembre-2016|AZ_41tY5gafDjL",
"La top 10 dei migliori congelatori: agosto 2016|I 10 congelatori migliori: la classifica aggiornata a agosto 2016|2016/08/la-top-10-dei-migliori-congelatori-agosto-2016|AZ_31QbYwzzoSL",
"Le 12 lavatrici più amate: agosto 2016|Le 12 lavatrici più comprate all'agosto 2016|2016/08/le-12-lavatrici-piu-amate-agosto-2016|AZ_41lOC205qUL",
"I 14 piani cottura più acquistati: luglio 2016|La top 14 dei migliori piani cottura disponibili per l'acquisto: luglio 2016|2016/07/i-14-piani-cottura-piu-acquistati-luglio-2016.html?t=cucina,piani-cottura,casa,piastre-elettriche,griglie-elettriche,elettrodomestici,forni-elettrici,fornetti-elettrici,alimentazione,cibo,cottura,pentole,padelle,casseruole,tegami,candy,ariston,electrolux,bosch,smeg,whirlpool&amp;d=20|AZ_315rWK2ZXeL",
"I 12 congelatori più venduti: la classifica di maggio 2016|Il top dei congelatori: la guida all'acquisto di maggio 2016|2016/05/i-12-congelatori-piu-venduti-la-classifica-di-maggio-2016.html?t=elettrodomestici,congelatori,frigoriferi,casa,bar,cibo,cucina,alimentazione,alimenti,freddo,ghiaccio,beko,haier,bomann,sirge,whirlpool&amp;d=27|AZ_41rPkb0BL0L",
"I fornetti per pizza migliori: maggio 2016|Gli 11+1 fornetti per pizza che vanno per la maggiore!|2016/05/i-fornetti-per-pizza-migliori-maggio-2016.html?t=cucina,fornetti-pizza,pizza,casa,bar,elettrodomestici,forni,cibo,alimentazione,napoli,princess,melchioni,whirlpool,kemper,klarstein&amp;d=17|AZ_51J5MOcmr-L",
"I 15 forni a microonde più venduti: maggio 2016|La top 15 dei migliori forni a microonde attualmente in commercio|2016/05/i-15-forni-a-microonde-piu-venduti-maggio-2016.html?t=cucina,casa,elettrodomestici,forni,forni-a-microonde,grill,microonde,cibo,candy,samsung,panasonic,whirlpool,daewoo,lg,sharp,bosch&amp;d=14|AZ_41oAZScRM1L",
"Le vaporiere più acquistate di aprile 2016|La classifica di aprile delle vaporiere migliori|2016/04/le-vaporiere-piu-acquistate-di-aprile-2016.html?t=cucina,vaporiere,alimentazione,cibo,gastronomia,stoviglie,pentole,cottura,dieta,benessere,vitamine,calorie,vapore,russell,tefal,philips,braun,whirlpool&amp;d=14|AZ_51r90GvkoxL",
"19 marzo: i 14 forni a microonde migliori|Ecco la classifica dei migliori forni a microonde aggiornata alla data del 19 marzo|2016/03/19-marzo-i-14-forni-a-microonde-migliori.html?t=cucina,casa,elettrodomestici,forni,forni-a-microonde,grill,microonde,whirlpool,candy,daewoo,samsung,panasonic,g3ferrari,ariston,severin&amp;d=19|AZ_41oAZScRM1L",
];
