Gr = [
"TV 4K Ultra HD: le 10 migliori a ottobre 2016|Le 10 TV 4K Ultra HD al top, in commercio ora: ottobre 2016|2016/10/tv-4k-ultra-hd-le-10-migliori-a-ottobre-2016|AZ_5156yd609-L",
"I 10 lettori Blu-Ray migliori: settembre 2016|I 10 lettori Blu-Ray più quotati sul mercato a settembre 2016|2016/09/i-10-lettori-blu-ray-migliori-settembre-2016|AZ_31OnTBo9diL",
"I 15 robot aspirapolvere migliori: luglio 2016|La top 15 dei migliori robot aspirapolvere disponibili da subito: luglio 2016|2016/07/i-15-robot-aspirapolvere-migliori-luglio-2016.html?t=robot-aspirapolvere,aspirapolvere,casa,aspiratori,aspirapolvere-a-bidone,elettrodomestici,scope-elettriche,pulizia,igiene,pavimento,cucina,bagno,scopa,scope-vapore,lavapavimenti,vileda,haier,ariete,lg,samsung&amp;d=20|AZ_412ykReDMFL",
"Smartphone: i 15 migliori a luglio 2016|La top 15 dei migliori smartphone disponibili per l'acquisto: luglio 2016|2016/07/smartphone-i-15-migliori-a-luglio-2016.html?t=smartphone,cellulari,telefonia,telefono-cellulare,elettronica,dual-sim,android,app,sms,bluetooth,huawei,homtom,lg,motorola,samsung&amp;d=15|AZ_41XlgJ1gy+L",
"Le 10 Smart TV migliori e i 5 migliori Smart TV Box Android: giugno 2016|Le 10 Smart TV più consigliate e i 5 migliori Smart TV Box Android: la classifica di giugno 2016|2016/06/le-10-smart-tv-migliori-e-i-5-migliori-smart-tv-box-android-giugno-2016.html?t=elettronica,smart-tv,smart-tv-box,televisori,tv,video,tempo-libero,full-hd,film,home-cinema,home-video,dvd,blu-ray,telecomandi-tv,android,samsung,toshiba,telefunken,lg&amp;d=23|AZ_51A6wEwU5aL",
"I 15 forni a microonde più venduti: maggio 2016|La top 15 dei migliori forni a microonde attualmente in commercio|2016/05/i-15-forni-a-microonde-piu-venduti-maggio-2016.html?t=cucina,casa,elettrodomestici,forni,forni-a-microonde,grill,microonde,cibo,candy,samsung,panasonic,whirlpool,daewoo,lg,sharp,bosch&amp;d=14|AZ_41oAZScRM1L",
"Lettori DVD: la guida all'acquisto di aprile 2016|La classifica aggiornata a aprile 2016 dei lettori DVD più venduti|2016/04/lettori-dvd-la-guida-all-acquisto-di-aprile-2016.html?t=televisori,lettori-dvd,elettronica,tv,home-cinema,home-video,video,tempo-libero,full-hd,3d,dvd,samsung,lg,sony,philips&amp;d=20|AZ_31OnTBo9diL",
"Aprile 2016: i 14 migliori lettori blu-ray|Ecco i 14 lettori blu-ray più venduti|2016/04/aprile-2016-i-14-migliori-lettori-blu-ray.html?t=elettronica,lettori-blu-ray,blu-ray,televisori,tv,home-cinema,home-video,video,tempo-libero,full-hd,3d,sony,samsung,philips,lg&amp;d=9|AZ_214kB3JJ-zL",
"I telecomandi TV più acquistati: aprile 2016|Tutto il meglio dei telecomandi TV in commercio|2016/04/i-telecomandi-tv-piu-acquistati-aprile-2016.html?t=elettronica,telecomandi-tv,televisori,tv,video,meliconi,sony,lg,toshiba,android,apple-tv,samsung&amp;d=8|AZ_41awpK4PnrL",
"I 10 robot aspirapolvere migliori: aprile 2016|La classifica dei migliori robot aspirapolvere|2016/04/i-10-robot-aspirapolvere-migliori-aprile-2016.html?t=elettrodomestici,robot-aspirapolvere,casa,lavapavimenti,aspirapolvere,scope-elettriche,cucina,bagno,pulizia,igiene,pavimento,vileda,ariete,lg&amp;d=6|AZ_412ykReDMFL",
];
