Gr = [
"Collane: le 14 più belle di luglio 2016|Le 14 collane speciali che abbiamo scelto: la nostra guida all'acquisto|2016/07/collane-le-14-piu-belle-di-luglio-2016|AZ_518Fd0cu8TL",
"Guardaroba: i 13 migliori a luglio 2016|I 13 guardaroba più consigliati subito disponibili: luglio 2016|2016/07/guardaroba-i-13-migliori-a-luglio-2016.html?t=arredamento,guardaroba,armadio,arredo,casa,abitazione,ufficio,mobili,letto,camera-letto,stile,accessori,abbigliamento,vestito,abito,giacca,moda,songmics&amp;d=22|AZ_51xvsxm15GL",
"Le 13 borse a tracolla da donna che piacciono di più: luglio 2016|Le 13 borse a tracolla da donna più belle di luglio 2016|2016/07/le-13-borse-a-tracolla-da-donna-che-piacciono-di-piu-luglio-2016.html?t=moda,borse-tracolla-donna,borse,borse-tracolla,donna,stile,accessori,abbigliamento,vintage,vestito,abito,guardaroba,desigual,adidas&amp;d=4|AZ_51a5tbnK4UL",
"I 6 gilet sportivi da donna più belli di giugno 2016|6 gilet sportivi da donna da indossare in ogni occasione: giugno 2016|2016/06/i-6-gilet-sportivi-da-donna-piu-belli-di-giugno-2016.html?t=moda,gilet,donna,sport,abbigliamento,vestito,stile,abito,giacca,sartoria,guardaroba,tempo-libero,bicicletta,cicli,allenamento,training,palestra,fitness,corsa,correre,running,ciclismo,ultrasport,lixada&amp;d=22|AZ_419wwr+T-pL",
"Le 12+1 macchine da cucire migliori: giugno 2016|Il meglio delle macchine da cucire disponibili per l'acquisto a giugno 2016|2016/06/le-12+1-macchine-da-cucire-migliori-giugno-2016.html?t=donna,macchine-da-cucire,casa,fai-da-te,moda,stile,abito,abbigliamento,vestito,giacca,cucito,sartoria,singer,necchi,techwood,brother&amp;d=4|AZ_41HC4l0x8XL",
"Aprile 2016: il meglio delle macchine da cucire sul mercato|Le migliori macchine da cucire: guida all'acquisto|2016/04/aprile-2016-il-meglio-delle-macchine-da-cucire-sul-mercato.html?t=donna,macchine-da-cucire,casa,fai-da-te,moda,stile,abito,abbigliamento,vestito,giacca,cucito,sartoria,singer,necchi,brother,techwood&amp;d=1|AZ_31PnpuL7N4L",
"Video - Come portare una sciarpa in mille modi diversi|Un utile video per indossare con stile una sciarpa o uno scialle|2015/10/video-come-portare-una-sciarpa-in-mille-modi-diversi.html?t=donna,moda,stile,abito,abbigliamento,accessori,bellezza&amp;d=13|YT_aG3UNPP5b08",
"Video - Come è cambiato l'abito da sposa in 100 anni?|Una modella ci fa fare un viaggio negli abiti da sposa degli ultimi 100 anni, in soli tre minuti!|2015/10/video-come-e-cambiato-l-abito-da-sposa-in-100-anni.html?t=moda,matrimonio,nozze,sposa,abito,abbigliamento,vestito,capelli,acconciatura,accessori,trucco,make-up,bellezza,donna&amp;d=2|YT_rKegRnTimFs",
"Moda: 15 euro da spendere entro il 4 ottobre!|Un buono sconto spendibile sulla nuova collezione di abbigliamento per vestiti, scarpe, borse, orologi ...|2015/09/moda-15-euro-da-spendere-entro-il-4-ottobre.html?t=sconti,offerte,promozioni,coupon,codice-sconto,buono-sconto,moda,vestito,abito,giacca&amp;d=18|shop-handbag",
"I vestiti intelligenti di Google|Tecnologia letteralmente da indossare con i tessuti touch interattivi|2015/09/i-vestiti-intelligenti-di-google.html?t=google,levi-strauss,vestito,abito,giacca&amp;d=15|smartphone-dude",
];
