Gr = [
"TV 4K Ultra HD: le 10 migliori a ottobre 2016|Le 10 TV 4K Ultra HD al top, in commercio ora: ottobre 2016|2016/10/tv-4k-ultra-hd-le-10-migliori-a-ottobre-2016|AZ_5156yd609-L",
"I 10 proiettori consigliati: ottobre 2016|I 10 proiettori più apprezzati del mercato: ottobre 2016|2016/10/i-10-proiettori-consigliati-ottobre-2016|AZ_41wwTNF7eAL",
"I 10 lettori DVD portatili che piacciono di più: settembre 2016|I 10 lettori DVD portatili che incontrano il maggiore gradimento|2016/09/i-10-lettori-dvd-portatili-che-piacciono-di-piu-settembre-2016|AZ_51goQGh83lL",
"I 10 migliori telecomandi TV: agosto 2016|I 10 telecomandi TV universali più quotati: la classifica di agosto 2016|2016/08/i-10-migliori-telecomandi-tv-agosto-2016|AZ_41awpK4PnrL",
"Le 10 Smart TV migliori e i 5 migliori Smart TV Box Android: giugno 2016|Le 10 Smart TV più consigliate e i 5 migliori Smart TV Box Android: la classifica di giugno 2016|2016/06/le-10-smart-tv-migliori-e-i-5-migliori-smart-tv-box-android-giugno-2016.html?t=elettronica,smart-tv,smart-tv-box,televisori,tv,video,tempo-libero,full-hd,film,home-cinema,home-video,dvd,blu-ray,telecomandi-tv,android,samsung,toshiba,telefunken,lg&amp;d=23|AZ_51A6wEwU5aL",
"I proiettori più quotati: la guida all'acquisto di aprile 2016|Il meglio dei proiettori disponibili per l'acquisto|2016/04/i-proiettori-piu-quotati-la-guida-all-acquisto-di-aprile-2016.html?t=proiettori,elettronica,video,tempo-libero,full-hd,televisori,tv,film,home-cinema,home-video,dvd,blu-ray,videogiochi,console-videogiochi,dbpower,tronfy,excelvan,benq,epson,acer&amp;d=25|AZ_31soCGu+0EL",
"Video - Maccio Capatonda è meglio di Rambo!|Nel film un vero atto di bravura europea, anzi, internazionale!|2016/04/video-maccio-capatonda-e-meglio-di-rambo.html?t=video-divertenti,umorismo,youtube,maccio-capatonda,bingo,rambo,film&amp;d=12|YT_FNi68kfTZXU",
"Per Carnevale, un costume a tema Star Wars!|Accidenti è solo per bambino. Sicuri non ce ne siano anche da grande?|2016/01/per-carnevale-un-costume-a-tema-star-wars.html?t=offerte,shopping,giochi,giocattoli,costumi,carnevale,star-wars,guerre-stellari,cinema,film,fantascienza,bambini,ragazzi&amp;d=23|AZ_41El2Tlv0SL",
"Video - Interstellar, il film di Giancarlo Fontana|Una produzione di Inception. Ehi, aspetta un attimo!|2015/05/video-interstellar-il-film-di-giancarlo-fontana.html?t=video-divertenti,umorismo,cinema,film,fantascienza,interstellar,christopher-nolan,samantha-cristoforetti,spazio&amp;d=26|rocket-crash",
];
