Gr = [
"Le 5 T-Shirt Sportive Uomo che più ci piacciono: febbraio 2017|La top 5 delle migliori T-Shirt Sportive Uomo disponibili da subito|2017/02/le-5-t-shirt-sportive-uomo-che-piu-ci-piacciono-febbraio-2017|data.oliviero.it/imgprodotto/t-shirt-sportiva-uomo-squadron-blue-827021-464_158073",
"I 5 migliori Trampolini: febbraio 2017|La top 5 dei migliori Trampolini, subito disponibili: febbraio 2017|2017/02/i-5-migliori-trampolini-febbraio-2017|data.oliviero.it/imgprodotto/trampolino-olimpic-365_1210_big",
"Le 6 migliori Panche ad Inversione: febbraio 2017|Le 6 Panche ad Inversione più apprezzate, subito disponibili|2017/02/le-6-migliori-panche-ad-inversione-febbraio-2017|data.oliviero.it/imgprodotto/panca-inversione-jk-6010_88729",
"Tute Sportive da Uomo: le 10 migliori a febbraio 2017|La top 10 delle migliori Tute Sportive da Uomo sul mercato|2017/02/tute-sportive-da-uomo-le-10-migliori-a-febbraio-2017|data.oliviero.it/imgprodotto/tuta-sportiva-uomo-nero-e-bianco-832844-101_158090",
"I 10 Elettrostimolatori consigliati: gennaio 2017|La top 10 dei migliori Elettrostimolatori disponibili ora per l'acquisto|2017/01/i-10-elettrostimolatori-consigliati-gennaio-2017|data.oliviero.it/imgprodotto/elettrostimolatore-lipozero-excel_71106",
"I 10 Tapis Roulant migliori: gennaio 2017|I 10 Tapis Roulant al top, disponibili ora per l'acquisto: gennaio 2017|2017/01/i-10-tapis-roulant-migliori-gennaio-2017|data.oliviero.it/imgprodotto/tapis-roulant-home-run-1-0-camminatore_89515",
"La fitness band automatica, la più pratica|Vivosmart HR: rileva automaticamente il tipo di attività e movimento|2017/01/la-fitness-band-automatica-la-piu-pratica|data.oliviero.it/imgprodotto/vivosmart-hr-010-01955-00_157684",
"L'ellittica ideale per il dimagrimento|Ellittica Skylon 3 richiudibile: stimola tutti i gruppi muscolari|2017/01/l-ellittica-ideale-per-il-dimagrimento|data.oliviero.it/imgprodotto/ellittica-skylon-3-richiudibile_92212",
"Uno dei migliori Tapis Roulant in commercio|Movi Fitness Tapis Roulant MF199, ideale per tenersi in forma!|2017/01/uno-dei-migliori-tapis-roulant-in-commercio|data.oliviero.it/imgprodotto/tapis-roulant-mf199_148540",
"Panca Ginnica e Panca per Addominali tutto in uno!|Victoria Kit Panca Bench Trainer + Manubri + Pesi e trasporto gratis!|2017/01/panca-ginnica-e-panca-per-addominali-tutto-in-uno|data.oliviero.it/imgprodotto/kit-panca-bench-trainer-manubri-pesi_141090",
"Una delle migliori Panche a Inversione sul mercato|Panca inversione Inversion Comfort Pro, per tenersi in forma da casa|2017/01/una-delle-migliori-panche-a-inversione-sul-mercato|data.oliviero.it/imgprodotto/panca-inversione-inversion-comfort-pro_96358",
];
