Gr = [
"La top 10 delle Lampade da Tavolo: dicembre 2016|Le 10 Lampade da Tavolo che vanno per la maggiore, disponibili ora!|2016/12/la-top-10-delle-lampade-da-tavolo-dicembre-2016|AZ_31i7bnEmPTL",
"I 10 baby monitor più quotati: agosto 2016|I 10 baby monitor che piacciono di più subito disponibili: agosto 2016|2016/08/i-10-baby-monitor-piu-quotati-agosto-2016|AZ_519b3btxVJL",
"Registratori portatili: i 16 migliori a luglio 2016|La top 16 dei migliori registratori portatili subito disponibili: luglio 2016|2016/07/registratori-portatili-i-16-migliori-a-luglio-2016|AZ_412OrvvUSML",
"I 14 regolacapelli migliori: luglio 2016|I 14 regolacapelli più interessanti per l'acquisto disponibili da subito|2016/07/i-14-regolacapelli-migliori-luglio-2016.html?t=uomo,regolacapelli,tagliacapelli,capelli,barba,peli,baffi,basette,cura-della-persona,regolabarba,igiene,moda,acconciatura,benessere,philips,ghb,panasonic&amp;d=22|AZ_31BWsDktHyL",
"I 14 binocoli che vanno per la maggiore: luglio 2016|La top 14 dei migliori binocoli disponibili per l'acquisto: luglio 2016|2016/07/i-14-binocoli-che-vanno-per-la-maggiore-luglio-2016.html?t=binocoli,trekking,escursioni,natura,montagna,alpinismo,caccia,pesca,birdwatching,campeggio,camping,concerti,astronomia,golf,outdoor,aria-aperta,zaini,zaini-escursioni,olympus,ghb,bresser,polaris,bushnell,lixada&amp;d=21|AZ_41ZlFHfaB8L",
"Le 15 lampade da tavolo più apprezzate di maggio 2016|Il meglio delle lampade da tavolo: la guida all'acquisto di maggio 2016|2016/05/le-15-lampade-da-tavolo-piu-apprezzate-di-maggio-2016.html?t=casa,lampada,lampade-da-tavolo,illuminazione,materiale-elettrico,ufficio,studio,scrivanie,arredamento,arredo,lampadine,elettricita,ghb,albrillo,onite,honsel&amp;d=24|AZ_41+8GOFxJyL",
"I tagliacapelli più venduti: guida all'acquisto di aprile 2016|Il meglio dei tagliacapelli sul mercato|2016/04/i-tagliacapelli-piu-venduti-guida-all-acquisto-di-aprile-2016.html?t=cura-della-persona,tagliacapelli,capelli,moda,acconciatura,igiene,rasoio,rasatura,barba,uomo,philips,remington,panasonic,braun,ghb&amp;d=11|AZ_31-+OO54w5L",
"23 marzo: le 15 migliori lampade da tavolo|Ecco la classifica delle lampade da tavolo migliori aggiornata alla data del 23 marzo|2016/03/23-marzo-le-15-migliori-lampade-da-tavolo.html?t=casa,lampade-da-tavolo,lampada,illuminazione,lampadine,elettricita,materiale-elettrico,ufficio,arredamento,ghb,onite,aglaia,daffodil,honsel,albrillo&amp;d=23|AZ_31MfajZhMnL",
];
