Gr = [
"Borsa Portaracchette Racket Holder X6 Club|2 comparti racchette, Grande tasca laterale per sistemare gli|2017/12/borsa-portaracchette-racket-holder-x6-club|data.oliviero.it/imgprodotto/borsa-portaracchette-racket-holder-x6-club_94141",
"Racchetta Tennis Nadal Jr 25|Babolat Nadal 25 Junior Racchetta da tennis I giovani ammiratori di|2017/12/racchetta-tennis-nadal-jr-25|data.oliviero.it/imgprodotto/racchetta-tennis-nadal-jr-25_80034",
"Racchetta Pure Drive|RACCHETTA SENZA PIATTO CORDE Potenza e sensazioni allo stato puro|2017/12/racchetta-pure-drive|data.oliviero.it/imgprodotto/racchetta-pure-drive_169175",
"VS Origial My Overgrip|L'overgrip Babolat VS Original è estremamente sottile, questa|2017/12/vs-origial-my-overgrip|data.oliviero.it/imgprodotto/vs-origial-my-overgrip-653040-101_162203",
"Racchetta Tennis Aero Jr. 25|La Aero Junior 25 , molto leggera e più corta delle classiche|2017/12/racchetta-tennis-aero-jr-25|data.oliviero.it/imgprodotto/racchetta-tennis-aero-jr-25-140178_162196",
"Racchetta Boost Drive|Potenza e tolleranza sono le caratteristiche di questa Babolat Boost|2017/12/racchetta-boost-drive|data.oliviero.it/imgprodotto/racchetta-boost-drive-121183_161024",
"Racchetta Pure Aero|Babolat dona alla leggendaria AeroPro Drive un nuovo stile, iniziando|2017/12/racchetta-pure-aero|data.oliviero.it/imgprodotto/racchetta-pure-aero_147959",
"Borsa Portaracchette Racket Holder X3 Club|Borsa portaracchette ideale per 3 racchette Caratteristiche: Comparto|2017/12/borsa-portaracchette-racket-holder-x3-club|data.oliviero.it/imgprodotto/borsa-portaracchette-racket-holder-x3-club_164733",
"Zaino Tennis Pure Backpack|Lo zaino da tennis Babolat Pure Backpack è una valida alterntiva per|2017/12/zaino-tennis-pure-backpack|data.oliviero.it/imgprodotto/zaino-tennis-pure-backpack_169176",
"Racchetta Boost Aero|Leggerezza e maneggevolezza per la Baboat Boost Aero, una racchetta|2017/12/racchetta-boost-aero|data.oliviero.it/imgprodotto/racchetta-boost-aero-121182_161023",
"Borsa Pure X 12 2017|La borsa da tennis Babolat Pure x 12 può contenere fino a 12|2017/12/borsa-pure-x-12-2017|data.oliviero.it/imgprodotto/borsa-pure-x-12-2017_167544",
"Skin Feel Grip|Il grip Skin Feel è ultra sottile, grazie alla sua finezza consente|2017/12/skin-feel-grip|data.oliviero.it/imgprodotto/skin-feel-grip-670056-105_162206",
"Borsone Tennis X12 Pure Drive|Il design di questa nuova borsa da tennis Babolat Pure x 12|2017/12/borsone-tennis-x12-pure-drive|data.oliviero.it/imgprodotto/borsone-tennis-x12-pure-drive_169177",
"Pro Skin Overgrip|Nuovo nome per l'overgrip Pro Team Tacky Thin che conserva però tutte|2017/12/pro-skin-overgrip|data.oliviero.it/imgprodotto/pro-skin-overgrip-653036-105_162202",
"Racchetta Pure Drive Jr. 25|Look rinnovato per la nuova Pure Drive Junior 25 Girl! Per le|2017/12/racchetta-pure-drive-jr-25|data.oliviero.it/imgprodotto/racchetta-pure-drive-jr-25-140159_162191",
"Racchetta Boost Strike|Potenza e performance per questa racchetta 100% grafite con i colori|2017/12/racchetta-boost-strike|data.oliviero.it/imgprodotto/racchetta-boost-strike_172889",
"Zaino Club Blue|Questo zaino propone un compartimento specifico per racchette con|2017/12/zaino-club-blue|data.oliviero.it/imgprodotto/zaino-club-blue_167540",
"Racchetta Tennis Pure Junior 26|Questa racchetta in grafite composto è ideale per i giovani giocatori|2017/12/racchetta-tennis-pure-junior-26|data.oliviero.it/imgprodotto/racchetta-tennis-pure-junior-26_80027",
"Racchetta Pure Drive Team|Racchetta senza piatto corde Questa versione leggera e veloce del|2017/12/racchetta-pure-drive-team|data.oliviero.it/imgprodotto/racchetta-pure-drive-team-101300_162193",
"Borsa RH X 12 Team Line|La borsa tennis Babolat Team Line è pratica e resistente, che offre|2017/12/borsa-rh-x-12-team-line|data.oliviero.it/imgprodotto/borsa-rh-x-12-team-line_167543",
"Zaino Team Line|Lo zaino Babolat Team Line è pratico e comodo, adatto per chi vuole|2017/12/zaino-team-line|data.oliviero.it/imgprodotto/zaino-team-line_167545",
"Racchetta Tennis Pure Drive Lite 2015|Nuova Babolat Pure Drive: gioca con potenza, domina il gioco|2017/06/racchetta-tennis-pure-drive-lite-2015|data.oliviero.it/imgprodotto/racchetta-pure-drive-lite-2015_93596",
];
