Gr = [
"Orologi da uomo: i 10 migliori a settembre 2016|La top 10 dei migliori orologi da uomo venduti a settembre 2016|2016/09/orologi-da-uomo-i-10-migliori-a-settembre-2016|AZ_41D1NArVrnL",
"Orologi Sportivi, Seggiolini per Auto: i 5 migliori di settembre 2016|I 5 migliori prodotti in Orologi Sportivi, Seggiolini per Auto|2016/09/orologi-sportivi-seggiolini-per-auto-i-5-migliori-di-settembre-2016|AZ_51OQljMcpCL",
"Orologi Sportivi, Collane: i 5 migliori di agosto 2016|I 5 migliori prodotti di agosto 2016 in Orologi Sportivi, Collane|2016/08/orologi-sportivi-collane-i-5-migliori-di-agosto-2016|AZ_51OQljMcpCL",
"Orologi sportivi: i 13 migliori in commercio a luglio 2016|I 13 orologi sportivi che piacciono di più oggi sul mercato: luglio 2016|2016/07/orologi-sportivi-i-13-migliori-in-commercio-a-luglio-2016|AZ_41QZEjUGSoL",
"Orologi da donna: i 14 migliori a giugno 2016|La top 14 dei migliori orologi da donna: giugno 2016|2016/06/orologi-da-donna-i-14-migliori-a-giugno-2016.html?t=moda,orologi-donna,orologi,donna,stile,accessori,vintage,casio&amp;d=13|AZ_51X7hZ7-qwL",
"I 14 smartwatch più apprezzati a giugno 2016|I 14 smartwatch più quotati: la classifica aggiornata a giugno 2016|2016/06/i-14-smartwatch-piu-apprezzati-a-giugno-2016.html?t=smartphone,smartwatch,orologi,elettronica,android,telefono-cellulare,cellulari,telefonia,iphone,blackberry,bluetooth,sony,asus&amp;d=9|AZ_41Ws8bfi3ZL",
"I migliori smartwatch disponibili proprio ora (aprile 2016)|Il meglio degli smartwatch: guida all'acquisto|2016/04/i-migliori-smartwatch-disponibili-proprio-ora-aprile-2016.html?t=smartphone,smartwatch,orologi,elettronica,android,telefonia,iphone,blackberry,bluetooth,sony,alcatel&amp;d=2|AZ_51gPWV-dnaL",
"San Valentino - Codice sconto Amazon del 15%|Ancora fino a domani puoi risparmiare utilizzando un codice sconto Amazon del 15% su orologi e gioielli|2015/02/san-valentino-codice-sconto-amazon-del-15.html?t=san-valentino,codici-sconto,sconti,offerte,orologi,gioielli,smartphone,foto-divertenti&amp;d=7|love-elephant",
];
