Gr = [
"I 10 estrattori di succo migliori: ottobre 2016|I 10 estrattori di succo che incontrano il maggiore gradimento|2016/10/i-10-estrattori-di-succo-migliori-ottobre-2016|AZ_31C6dY5ej4L",
"I 16 bollitori elettrici più quotati: luglio 2016|La top 16 dei migliori bollitori elettrici subito disponibili: luglio 2016|2016/07/i-16-bollitori-elettrici-piu-quotati-luglio-2016.html?t=bollitori,bollitori-elettrici,cucina,teiere,elettrodomestici,casa,bar,colazione,te,infuso,tisana,decotto,alimentazione,viaggi,severin,russell-hobbs,domoclip,philips,koenig,black-and-decker&amp;d=20|AZ_41A2oJPwX8L",
"Le 13 macchine per cubetti di ghiaccio consigliate: luglio 2016|Le 13 macchine per cubetti di ghiaccio più comprate: luglio 2016|2016/07/le-13-macchine-per-cubetti-di-ghiaccio-consigliate-luglio-2016.html?t=macchine-cubetti-ghiaccio,ghiaccio,macchine-ghiaccio,cucina,elettrodomestici,casa,bar,alimenti,freddo,granita,bere,bevande,liquori,cocktail,tritaghiaccio,koenig,tectake,klarstein,princess&amp;d=12|AZ_41dqtsWNZFL",
"Vaporetto: i 15 migliori in commercio a luglio 2016|La top 15 dei migliori vaporetto sul mercato a luglio 2016|2016/07/vaporetto-i-15-migliori-in-commercio-a-luglio-2016.html?t=casa,vaporetto,pulitori-a-vapore,elettrodomestici,igiene,pulizia,vapore,pavimento,cucina,bagno,scope-elettriche,polti,clatronic,scopa,koenig,hoover&amp;d=8|AZ_41pLTthB5uL",
"Piastre elettriche: le 14 migliori a giugno 2016|Le 14 piastre elettriche più apprezzate: giugno 2016|2016/06/piastre-elettriche-le-14-migliori-a-giugno-2016.html?t=cucina,piastre-elettriche,casa,bistecchiere,alimentazione,cibo,cottura,elettrodomestici,forni-elettrici,fornetti-elettrici,griglie-elettriche,severin,duronic,russell-hobbs,tristar,rowenta,koenig&amp;d=13|AZ_41ObagJyrFL",
"Il meglio delle gelatiere in commercio: maggio 2016|Le 13 gelatiere al top oggi sul mercato: maggio 2016|2016/05/il-meglio-delle-gelatiere-in-commercio-maggio-2016.html?t=cibo,gelato,gelatiere,sorbetto,yogurt,fresco,ghiaccio,panna,elettrodomestici,risparmio,gastronomia,alimentazione,cucina,de-longhi,koenig,duronic,gaggia,ariete,princess,kenwood&amp;d=30|AZ_31v6RMtROAL",
"Maggio 2016: le 14 macchine per waffle migliori|Il top delle più quotate macchine per waffle disponibili|2016/05/maggio-2016-le-14-macchine-per-waffle-migliori.html?t=cucina,macchine-waffle,alimentazione,cibo,dolci,colazione,elettrodomestici,gastronomia,bar,casa,ariete,beper,howell,koenig,bomann,severin&amp;d=8|AZ_51lVmzS6s3L",
"Aprile 2016: il meglio dei cuocipappa in commercio|I cuocipappa migliori disponibili per l'acquisto|2016/04/aprile-2016-il-meglio-dei-cuocipappa-in-commercio.html?t=bambini,cuocipappa,neonati,allattamento,culla,carrozzine,baby-monitor,philips,chicco,koenig,klarstein&amp;d=20|AZ_41K5ZgBhOHL",
"Aprile 2016: la classifica dei migliori estrattori di succo|Tutti gli estrattori di succo più venduti!|2016/04/aprile-2016-la-classifica-dei-migliori-estrattori-di-succo.html?t=elettrodomestici,estrattori-di-succo,dieta,salute,alimentazione,benessere,vitamine,casa,cibo,cucina,risparmio,frutta,succo,panasonic,rgv,bosch,koenig,severin,philips,ariete&amp;d=6|AZ_41iY4xdDcnL",
"Il meglio dei ferri da stiro di aprile 2016: guida all'acquisto|I ferri da stiro migliori disponibili proprio ora|2016/04/il-meglio-dei-ferri-da-stiro-di-aprile-2016-guida-all-acquisto.html?t=elettrodomestici,casa,ferro-a-vapore,ferro-da-stiro,vestito,rowenta,imetec,philips,ariete,polti,de-longhi,koenig,termozeta,bosch&amp;d=4|AZ_41MqF2i2O2L",
];
