Gr = [
"I 10 dondoli da giardino migliori: settembre 2016|I 10 dondoli da giardino più comprati, subito disponibili|2016/09/i-10-dondoli-da-giardino-migliori-settembre-2016|AZ_51yAAd50ZJL",
"I 15 ventilatori da tavolo più acquistati: luglio 2016|I 15 ventilatori da tavolo che vanno per la maggiore: la classifica aggiornata a luglio 2016|2016/07/i-15-ventilatori-da-tavolo-piu-acquistati-luglio-2016|AZ_51yc+UHPAPL",
"I 14 ombrelloni da giardino più venduti: luglio 2016|La top 14 dei migliori ombrelloni da giardino disponibili per l'acquisto|2016/07/i-14-ombrelloni-da-giardino-piu-venduti-luglio-2016.html?t=giardino,ombrelloni-giardino,ombrelloni,ombra,casa,prato,campeggio,outdoor,aria-aperta,estate,amici,famiglia,tempo-libero,tectake&amp;d=5|AZ_41rRor+FeAL",
"I 14 gazebo più gettonati: giugno 2016|La top 14 dei migliori gazebo in commercio a giugno 2016|2016/06/i-14-gazebo-piu-gettonati-giugno-2016.html?t=giardino,gazebo,casa,prato,campeggio,ombrelloni,outdoor,aria-aperta,estate,amici,famiglia,ombra&amp;d=29|AZ_517LZl2Jg6L",
"Gommoni: gli 11 migliori a giugno 2016|Gli 11 gommoni più venduti: giugno 2016|2016/06/gommoni-gli-11-migliori-a-giugno-2016.html?t=mare,gommoni,canotto,tempo-libero,pesca,nuoto,sci-nautico,lago,spiaggia,estate,barca,imbarcazione,oceano,tender,nautica,playmobil&amp;d=28|AZ_517-kkQxR5L",
"12 ombrelloni da spiaggia per la tua estate: giugno 2016|I 12 migliori ombrelloni da spiaggia in commercio a giugno 2016|2016/06/12-ombrelloni-da-spiaggia-per-la-tua-estate-giugno-2016.html?t=mare,ombrelloni,ombrelloni-spiaggia,ombra,spiaggia,estate,giardino,tempo-libero,nuoto,sport,campeggio&amp;d=22|AZ_518n8qvXMaL",
"Le 14 piscine gonfiabili più acquistate: giugno 2016|Le 14 piscine gonfiabili che incontrano il maggiore gradimento|2016/06/le-14-piscine-gonfiabili-piu-acquistate-giugno-2016.html?t=giardino,piscine,piscine-gonfiabili,tempo-libero,giochi,bambini,ragazzi,famiglia,nuoto,sport,mare,estate,spiaggia&amp;d=8|AZ_51fE-fKCimL",
"Vinci un telo mare per l'estate!|È gratis: basta un account Facebook e un po' di fortuna|2015/05/vinci-un-telo-mare-per-l-estate.html?t=concorsi,premi,mare,estate,spiaggia&amp;d=28|marilyn-monroe-beach",
];
