Gr = [
"Abito Bambina Beige|Collezione Primavera Estate Abito intero da bambina. Il modello|2017/12/abito-bambina-beige|data.oliviero.it/imgprodotto/abito-bambina-beige-0s422_162157",
"Felpa Bambina Bianco|Collezione Primavera Estate Felpa casual da bambina. Il modello|2017/12/felpa-bambina-bianco|data.oliviero.it/imgprodotto/felpa-bambina-bianco-4s536-0113_158559",
"Pantalone Bambino Bianco|Collezione Primavera Estate Pantalone da bambino Il modello presenta|2017/12/pantalone-bambino-bianco|data.oliviero.it/imgprodotto/pantalone-bambino-bianco-0s341_159251",
"Camicia Bambino Blu|Collezione Primavera Estate Camicia da bambino con maniche lunghe. Il|2017/12/camicia-bambino-blu|data.oliviero.it/imgprodotto/camicia-bambino-blu-4s403-3641_158470",
"Felpa Bambino Verde Militare|Collezione Primavera Estate Felpa da bambino, full zip, due tasche in|2017/12/felpa-bambino-verde-militare|data.oliviero.it/imgprodotto/felpa-bambino-verde-militare-4s424-5553_158490",
"T-Shirt Jr. Bianco|Collezione Autunno Inverno/2018 Metti in mostra lo stile audace del|2017/12/t-shirt-jr-bianco|data.oliviero.it/imgprodotto/t-shirt-jr-bianco_167578",
"Giacca Bambino Tortora|Collezione Primavera Estate Giacca casual da bambino ideale per le|2017/12/giacca-bambino-tortora|data.oliviero.it/imgprodotto/giacca-bambino-tortora-0s361_162146",
"Pantalone in Felpa Bambino|Collezione Primavera Estate In leggerissima felpa indaco Elastico|2017/12/pantalone-in-felpa-bambino|data.oliviero.it/imgprodotto/pantalone-in-felpa-bambino-171mhbm008_163684",
"Felpa Bambino Giallo|Collezione Primavera Estate In morbida felpa Stampa allover|2017/12/felpa-bambino-giallo|data.oliviero.it/imgprodotto/felpa-bambino-giallo-171mhfc011_163705",
"Sciarpa Bambina Corallo|Collezione Primavera Estate Sciarpa da bambina ideale per la stagione|2017/12/sciarpa-bambina-corallo|data.oliviero.it/imgprodotto/sciarpa-bambina-corallo-0s861_159327",
"Papillon Bambino Avion Blu|Collezione Primavera Estate Ideale per sentirsi eleganti. Questo|2017/12/papillon-bambino-avion-blu|data.oliviero.it/imgprodotto/papillon-bambino-avion-blu-0s848_159326",
"Camicia Bambino Azzurro|Collezione Primavera Estate Manica lunga In popeline fil a fil|2017/12/camicia-bambino-azzurro|data.oliviero.it/imgprodotto/camicia-bambino-azzurro-171mhdc007-140_163613",
"Giubbino Bambino in Felpa|Collezione Primavera Estate In morbida felpa indigo Due tasche|2017/12/giubbino-bambino-in-felpa|data.oliviero.it/imgprodotto/giubbino-bambino-in-felpa-171mhaa002_163682",
"Felpa Jr Grigio|Collezione Autunno Inverno/2018 L'accattivante struttura in tricot|2017/12/felpa-jr-grigio|data.oliviero.it/imgprodotto/felpa-jr-grigio_166837",
"T-Shirt Jr. Nero|Collezione Autunno Inverno/2018 Uno dei design più amati sfoggia un|2017/12/t-shirt-jr-nero|data.oliviero.it/imgprodotto/t-shirt-jr-nero_167576",
"Pantalone Bambino Tortora|Collezione Primavera Estate Pantalone da bambino con allacciatura|2017/12/pantalone-bambino-tortora|data.oliviero.it/imgprodotto/pantalone-bambino-tortora-0s342_162148",
"Pantalone Bambino Rosso|Collezione Primavera Estate Pantalone da bambino con allacciatura|2017/12/pantalone-bambino-rosso|data.oliviero.it/imgprodotto/pantalone-bambino-rosso-4s438_164042",
"T-Shirt Bambina Fluo|Collezione Primavera Estate In morbido jersey Maniche corte|2017/12/t-shirt-bambina-fluo|data.oliviero.it/imgprodotto/t-shirt-bambina-fluo-171mifn019_163711",
"Leggings Lungo Ragazza Panna|Collezione Primavera Estate Leggings da ragazza con elastico in vita|2017/12/leggings-lungo-ragazza-panna|data.oliviero.it/imgprodotto/leggings-lungo-ragazza-panna-0s404_159245",
"Giacca Sci Junior Ferrari|Collezione Autunno Inverno/2018 Chi desidera una giacca che|2017/12/giacca-sci-junior-ferrari|data.oliviero.it/imgprodotto/giacca-sci-junior-ferrari_169281",
];
