Gr = [
"I 7 acquari consigliati: ottobre 2016|I 7 acquari che vanno per la maggiore: la classifica aggiornata|2016/10/i-7-acquari-consigliati-ottobre-2016|AZ_51abTE3b0BL",
"Le 10 caraffe filtranti più vendute: ottobre 2016|La top 10 delle migliori caraffe filtranti in commercio a ottobre 2016|2016/10/le-10-caraffe-filtranti-piu-vendute-ottobre-2016|AZ_41AELXquWML",
"Le 10 migliori caraffe filtranti in commercio a giugno 2016|Le 10 migliori caraffe filtranti, subito disponibili per l'acquisto|2016/06/le-10-migliori-caraffe-filtranti-in-commercio-a-giugno-2016.html?t=acqua,caraffe-filtranti,casa,cucina,sete,salute,alimentazione,dieta,reni,elettrodomestici,brita,laica,kenwood,imetec&amp;d=1|AZ_41sZpxF2UDL",
"Marzo 2016: la classifica delle 10 migliori caraffe filtranti|Aggiornate al marzo 2016, ecco le 10 migliori caraffe filtranti|2016/03/marzo-2016-la-classifica-delle-10-migliori-caraffe-filtranti.html?t=acqua,caraffe-filtranti,sete,salute,alimentazione,dieta,reni,brita,laica,kenwood,imetec&amp;d=31|AZ_4150h5T3ZlL",
"Video - Scoperta acqua in un cratere di Cerere, e forse ai poli|Importante in questa scoperta il ruolo dello spettrometro italiano VIR|2016/03/video-scoperta-acqua-in-un-cratere-di-cerere-e-forse-ai-poli.html?t=astronomia,astrofisica,spazio,scienza,cerere,inaf,acqua,nasa,fascia-degli-asteroidi&amp;d=30|YT__4A3UBr6YKI",
"Video - Il mosaico di acqua piovana più grande del mondo|Per aumentare la consapevolezza sulla crisi idrica mondiale|2016/01/video-il-mosaico-di-acqua-piovana-piu-grande-del-mondo.html?t=acqua,sete,ambiente,ecologia,salute,alimentazione,mosaico,feto,utero&amp;d=9|YT_WkfA7dpoUMM",
"Video - Acqua su Marte: cosa c'è di diverso questa volta?|Scopriamolo insieme guardando questo video dell'Istituto Nazionale di AstroFisica|2015/10/video-acqua-su-marte-cosa-c-e-di-diverso-questa-volta.html?t=scienza,astronomia,astrofisica,spazio,marte,nasa,acqua,fantascienza,ray-bradbury&amp;d=2|ray-bradbury",
"Bere troppa acqua fa male alla salute? E la regola dei due litri?|L'aquaholism è una vera e propria dipendenza da acqua. Bere troppa acqua affaticherebbe i reni, e avrebbe perfino ripercussioni psicologiche|2015/04/bere-troppa-acqua-fa-male-alla-salute-e-la-regola-dei-due-litri.html?t=salute,acqua,dieta,alimentazione,insonnia,sudorazione,reni,dipendenza,sete,nervosismo,ansia,cuore,londra,foto-divertenti&amp;d=1|water-tap-sculpture",
];
