Gr = [
"Scarpe con Ruote CruzX2|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-cruzx2|data.oliviero.it/imgprodotto/scarpe-con-ruote-cruzx2-770498k_139610",
"Scarpe con Ruote Dual Up X2|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-dual-up-x2|data.oliviero.it/imgprodotto/scarpe-con-ruote-dual-up-x2-770947k_164208",
"Scarpe con Ruote Force|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-force|data.oliviero.it/imgprodotto/scarpe-con-ruote-force-770836_157596",
"Pattini Rookie Fruits|Pattini dallo stile retro e dalla struttura moderna Tomaia in mesh|2017/12/pattini-rookie-fruits|data.oliviero.it/imgprodotto/pattini-rookie-fruits_165824",
"Scarpe con Ruote|Tomaia in pelle sintetica con linguetta e collo imbottiti per un|2017/12/scarpe-con-ruote|data.oliviero.it/imgprodotto/scarpe-con-ruote-premium-1-lo_173202",
"Scarpe con Ruote X2 Pow Lighted|Tomaia sintetica con linguetta e colletto imbottiti per un comfort|2017/12/scarpe-con-ruote-x2-pow-lighted|data.oliviero.it/imgprodotto/scarpe-con-ruote-x2-pow-lighted_173204",
"Scarpe con Ruote Launch 2.0|Utilizzo : scarpe munite di ruote Tomaia : Tessuto Battistrada|2017/12/scarpe-con-ruote-launch-2-0|data.oliviero.it/imgprodotto/scarpe-con-ruote-launch-2-0-770252h_91898",
"Scarpe con Ruote Speed X2|Caratteristiche Tecniche : Le Heelys sono scarpe munite di ruote con|2017/12/scarpe-con-ruote-speed-x2|data.oliviero.it/imgprodotto/scarpe-con-ruote-speed-x2-770047k_153466",
"Scarpe con Ruote X2 Bolt|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-x2-bolt|data.oliviero.it/imgprodotto/scarpe-con-ruote-x2-bolt-770797_157595",
"Scarpe con Ruote Veloz|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-veloz|data.oliviero.it/imgprodotto/scarpe-con-ruote-veloz-770557h_131810",
"Scarpe con Ruote Launch|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-launch|data.oliviero.it/imgprodotto/scarpe-con-ruote-launch-771027h_164213",
"Scarpe con Ruote Motion Plus|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-motion-plus|data.oliviero.it/imgprodotto/scarpe-con-ruote-motion-plus-770629h_164211",
"Pattini Rookie Hype Hi Top Trainer|I pattini Retro Hype Hi Top Trainer hanno un elegante tocco vintage|2017/12/pattini-rookie-hype-hi-top-trainer|data.oliviero.it/imgprodotto/pattini-rookie-hype-hi-top-trainer_157613",
"Pattini Rookie Retro V2.1|Pattini dallo stile retro e dalla struttura moderna Tomaia in mesh|2017/12/pattini-rookie-retro-v2-1|data.oliviero.it/imgprodotto/pattini-rookie-retro-v2-1-rke-ska-0402_164281",
"Scarpe con ruote Propel 2.0|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-propel-2-0|data.oliviero.it/imgprodotto/scarpe-con-ruote-propel-2-0-770603h_146320",
"Scarpe con Ruote Helix|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/12/scarpe-con-ruote-helix|data.oliviero.it/imgprodotto/scarpe-con-ruote-helix-7764_132725",
"Pattini Rookie Rainbow Pink|Pattini dallo stile retro e dalla struttura moderna Tomaia in mesh|2017/12/pattini-rookie-rainbow-pink|data.oliviero.it/imgprodotto/pattini-rookie-rainbow-pink_165827",
"Scarpe con Ruote Thunder X2|Le Heelys sono scarpe munite di ruote con cui, grazie ad un semplice|2017/11/scarpe-con-ruote-thunder-x2|data.oliviero.it/imgprodotto/scarpe-con-ruote-thunder-x2-770480k_131811",
];
