Gr = [
"I 10 pulitori a vapore migliori: ottobre 2016|Pulitori a vapore: i 10 migliori in commercio a ottobre 2016|2016/10/i-10-pulitori-a-vapore-migliori-ottobre-2016|AZ_41pLTthB5uL",
"Scope Elettriche, Vasche Idromassaggio: i 5 migliori di settembre 2016|I 5 migliori prodotti in Scope Elettriche, Vasche Idromassaggio|2016/09/scope-elettriche-vasche-idromassaggio-i-5-migliori-di-settembre-2016|AZ_31CYx0WOIHL",
"La top 10 delle migliori scope elettriche: agosto 2016|Le 10 scope elettriche che vanno per la maggiore disponibili da subito|2016/08/la-top-10-delle-migliori-scope-elettriche-agosto-2016|AZ_31-hrBF1dAL",
"I 15 robot aspirapolvere migliori: luglio 2016|La top 15 dei migliori robot aspirapolvere disponibili da subito: luglio 2016|2016/07/i-15-robot-aspirapolvere-migliori-luglio-2016.html?t=robot-aspirapolvere,aspirapolvere,casa,aspiratori,aspirapolvere-a-bidone,elettrodomestici,scope-elettriche,pulizia,igiene,pavimento,cucina,bagno,scopa,scope-vapore,lavapavimenti,vileda,haier,ariete,lg,samsung&amp;d=20|AZ_412ykReDMFL",
"Vaporetto: i 15 migliori in commercio a luglio 2016|La top 15 dei migliori vaporetto sul mercato a luglio 2016|2016/07/vaporetto-i-15-migliori-in-commercio-a-luglio-2016.html?t=casa,vaporetto,pulitori-a-vapore,elettrodomestici,igiene,pulizia,vapore,pavimento,cucina,bagno,scope-elettriche,polti,clatronic,scopa,koenig,hoover&amp;d=8|AZ_41pLTthB5uL",
"Aspirapolvere a bidone: i 13 migliori a giugno 2016|I 13 aspirapolvere a bidone più venduti: giugno 2016|2016/06/aspirapolvere-a-bidone-i-13-migliori-a-giugno-2016.html?t=casa,aspirapolvere,aspiratori,aspirapolvere-a-bidone,elettrodomestici,scope-elettriche,pulizia,igiene,pavimento,cucina,bagno,robot-aspirapolvere,scopa,einhell,dpe,klarstein,melchioni&amp;d=21|AZ_419FJYc+R6L",
"La potenza di un aspirapolvere con le dimensioni di una scopa elettrica!|Questa potente scopa elettrica senza filo è tra le più vendute in assoluto|2016/05/la-potenza-di-un-aspirapolvere-con-le-dimensioni-di-una-scopa-elettrica.html?t=casa,scope-elettriche,elettrodomestici,scopa,aspirapolvere,robot-aspirapolvere,cucina,bagno,pulizia,igiene,pavimento,rowenta&amp;d=10|AZ_71wY3Ni58OL",
"Le scope elettriche più vendute: maggio 2016|Il top delle scope elettriche in commercio|2016/05/le-scope-elettriche-piu-vendute-maggio-2016.html?t=elettrodomestici,scope-elettriche,scopa,aspirapolvere,robot-aspirapolvere,casa,cucina,bagno,pulizia,igiene,pavimento,imetec,ariete,hoover,vileda,de-longhi,rowenta,olimpic&amp;d=7|AZ_31-hrBF1dAL",
];
