Gr = [
"La top 10 delle Lavastoviglie: novembre 2016|Le 10 Lavastoviglie più comprate disponibili da subito: novembre 2016|2016/11/la-top-10-delle-lavastoviglie-novembre-2016|AZ_41JJbClg3PL",
"I 10 forni da incasso top: agosto 2016|La top 10 dei migliori forni da incasso disponibili da subito: agosto 2016|2016/08/i-10-forni-da-incasso-top-agosto-2016|AZ_31UdW8LJhwL",
"I 14 frigoriferi doppia porta più venduti: agosto 2016|La top 14 dei migliori frigoriferi doppia porta subito disponibili|2016/08/i-14-frigoriferi-doppia-porta-piu-venduti-agosto-2016|AZ_41EhilJrcFL",
"Gli 8 frigoriferi combinati più acquistati: giugno 2016|I migliori 8 frigoriferi combinati sul mercato a giugno 2016|2016/06/gli-8-frigoriferi-combinati-piu-acquistati-giugno-2016.html?t=cucina,frigoriferi-combinati,frigoriferi,congelatori,elettrodomestici,casa,bar,cibo,alimentazione,alimenti,freddo,ghiaccio,candy,indesit,bosch,beko,ariston,samsung,iberna&amp;d=30|AZ_21ph8B6dYlL",
"Le 10 lavastoviglie più comprate: giugno 2016|La top 10 delle migliori lavastoviglie sul mercato a giugno 2016|2016/06/le-10-lavastoviglie-piu-comprate-giugno-2016.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,pulizia,igiene,stoviglie,piatti,pentole,beko,electrolux,klarstein,bosch,ariston,indesit,smeg&amp;d=2|AZ_41tdMsxE9QL",
"La classifica dei frigoriferi più venduti: maggio 2016|Tutto il meglio dei frigoriferi in questa piccola ma mirata classifica|2016/05/la-classifica-dei-frigoriferi-piu-venduti-maggio-2016.html?t=elettrodomestici,frigoriferi,congelatori,casa,bar,cibo,cucina,alimentazione,alimenti,freddo,ghiaccio,beko,klarstein,indesit&amp;d=14|AZ_31rKZlv31cL",
"Al marzo 2016, ecco le 9 lavastoviglie migliori|La nostra classifica delle 9 migliori lavastoviglie|2016/03/al-marzo-2016-ecco-le-9-lavastoviglie-migliori.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,igiene,stoviglie,klarstein,beko,indesit,bosch,smeg,electrolux&amp;d=31|AZ_51zRVIL8yqL",
"Al 19 marzo, ecco i 10 migliori frigoriferi|La classifica dei frigoriferi migliori alla data del 19 marzo|2016/03/al-19-marzo-ecco-i-10-migliori-frigoriferi.html?t=elettrodomestici,frigoriferi,casa,cibo,cucina,alimentazione,klarstein,beko,haier,indesit,ariston,candy&amp;d=19|AZ_31rKZlv31cL",
];
