Gr = [
"Video - Tutti i tentativi di atterraggio e i test di SpaceX|Un bel montaggio opera di un fan del programma spaziale di Elon Musk|2016/04/video-tutti-i-tentativi-di-atterraggio-e-i-test-di-spacex.html?t=spazio,scienza,elon-musk,spacex,ingegneria,ingegneria-aerospaziale,razzo,tecnologia,veicolo-spaziale&amp;d=11|YT_ikJ3S1J9P7k",
"Video - Come fare atterrare un razzo in mezzo al mare|SpaceX ha fatto atterrare il primo stadio del suo vettore su una piattaforma marina|2016/04/video-come-fare-atterrare-un-razzo-in-mezzo-al-mare.html?t=spazio,scienza,elon-musk,spacex,ingegneria,ingegneria-aerospaziale,razzo,tecnologia,veicolo-spaziale&amp;d=9|YT_sYmQQn_ZSys",
"Video - Nuovo robot bipede presentato ieri a Tokyo|La Schaft Robotics di Google ha svelato la sua creazione robotica|2016/04/video-nuovo-robot-bipede-presentato-ieri-a-tokyo.html?t=scienza,robot,robotica,automa,google,ingegneria,automazione,informatica,tokyo,geek&amp;d=9|YT_iyZE0psQsX0",
"Video - Una bella chiacchierata tecnologica|David Orban su algoritmi e intelligenza artificiale|2016/04/video-una-bella-chiacchierata-tecnologica.html?t=intelligenza-artificiale,societa,internet-degli-oggetti,david-orban,scienza,ingegneria,informatica,software,teoria-dei-giochi,gioco-a-somma-zero,algoritmo,internet-delle-cose&amp;d=3|YT__lXfk2KSIH4",
"Video - La Tesla entra ed esce da sola dal garage|Parcheggiare e richiamare l'automobile senza bisogno di stare al suo interno|2016/01/video-la-tesla-entra-ed-esce-da-sola-dal-garage.html?t=auto,automobile,autovettura,motori,tesla-motors,ingegneria,video&amp;d=11|YT_nHLqjdAfDUQ",
"Video - Il tuo genoma sequenziato in tempo reale con 1 cent|Sarà possibile tra 5 anni. David Orban ne ha parlato, insieme a molte altre cose, presso Google Italia|2015/10/video-il-tuo-genoma-sequenziato-in-tempo-reale-con-1-cent.html?t=genetica,genoma-umano,genomica,dna,david-orban,singolarita-tecnologica,scienza,ingegneria&amp;d=10|vials",
"Video - Il futuro della tecnologia, dell'umanità e tutto quanto|David Orban ci accompagna in un interessantissimo viaggio nel futuro che forse è già qui|2015/05/video-il-futuro-della-tecnologia-dell-umanita-e-tutto-quanto.html?t=intelligenza-artificiale,internet-degli-oggetti,genoma-umano,stampa-3d,david-orban,scienza,ingegneria&amp;d=28|william-gibson",
];
