Gr = [
"Tavolo Ping Pong 700m Crossover Outdoor|Tavolo Ping Pong 700m Crossover Outdoor COLORE GRIGIO PIANO RESINA|2017/12/tavolo-ping-pong-700m-crossover-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-700m-crossover-outdoor_130149",
"Tavolo Ping Pong Pro 510 Outdoor|Tavolo Ping Pong Pro 510 Outdoor Caratteristiche Piano in resina|2017/12/tavolo-ping-pong-pro-510-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-pro-510-outdoor_136303",
"Tavolo Ping Pong Tecto Indoor|Tectonic è la linea di ping-pong entry level di Cornilleau, azienda|2017/12/tavolo-ping-pong-tecto-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-tecto-indoor_83021",
"Racchette da ping pong Pack Sport Duo 432|Racchette da Ping Pong Pack Sport Duo 432. La confezione comprende|2017/12/racchette-da-ping-pong-pack-sport-duo-432|data.oliviero.it/imgprodotto/racchette-da-ping-pong-pack-sport-duo-432_58096",
"Tavolo Ping Pong Sport 100 Indoor|Tavolo Ping Pong Sport 100 Indoor PIANO AGGLOMERATO 19 mm SKILTOP|2017/12/tavolo-ping-pong-sport-100-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-sport-100-indoor_147306",
"Tavolo Ping Pong Competition 740 ITTF|Tavolo Ping Pong Competition 740 ITTF Caratteristiche PIANO|2017/12/tavolo-ping-pong-competition-740-ittf|data.oliviero.it/imgprodotto/tavolo-ping-pong-competition-740-ittf_136312",
"Tavolo Ping Pong Competition 850 wood ITTF Indoor|Tavolo Ping Pong Competition 850 wood ITTF Indoor COLORE GRIGIO PIANO|2017/12/tavolo-ping-pong-competition-850-wood-ittf-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-competition-850-wood-ittf-indoor_130135",
"Tavolo Ping Pong Competition 610 ITTF|Il tavolo ping pong Cornilleau 610 Indoor é indicato per un utilizzo|2017/12/tavolo-ping-pong-competition-610-ittf|data.oliviero.it/imgprodotto/tavolo-ping-pong-competition-610-ittf_147266",
"Tavolo Ping Pong Sport 250 Indoor|La gamma dei tavoli ping pong Cornilleau SPORT raggruppa dei tavoli|2017/12/tavolo-ping-pong-sport-250-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-sport-250-indoor_145216",
"Tavolo Ping Pong 540 Competition ITTF Indoor|Il tavolo ping pong Cornilleau 540 indoor é indicato per un utilizzo|2017/12/tavolo-ping-pong-540-competition-ittf-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-540-competition-ittf-indoor_58075",
"Tavolo ping Pong Park da esterno|Tavolo da ping pong Park Outdoor Caratteristiche tecniche: Tavolo|2017/12/tavolo-ping-pong-park-da-esterno|data.oliviero.it/imgprodotto/tavolo-ping-pong-park-da-esterno_63316",
"Tavolo Ping Pong 500M Crossover Outdoor|Tavolo Ping Pong 500M Crossover Outdoor SPESSORE PANNELLO 7 mm MATTOP|2017/12/tavolo-ping-pong-500m-crossover-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-500m-crossover-outdoor_147271",
"Tavolo Ping Pong Tecto da esterno|Caratteristiche tecniche: La linea dei tavoli ping pong Tectonic by|2017/12/tavolo-ping-pong-tecto-da-esterno|data.oliviero.it/imgprodotto/tavolo-ping-pong-tecto-da-esterno_58606",
];
