Gr = [
"Trapani a percussione: i 10 migliori a ottobre 2016|I 10 trapani a percussione più consigliati, subito disponibili|2016/10/trapani-a-percussione-i-10-migliori-a-ottobre-2016|AZ_419befu9SfL",
"Compressori, Schede di Memoria: i 5 migliori di settembre 2016|I 5 migliori prodotti in Compressori, Schede di Memoria|2016/09/compressori-schede-di-memoria-i-5-migliori-di-settembre-2016|AZ_51GfHhitsxL",
"Motozappe, Chitarre Elettriche: i 5 migliori di settembre 2016|I 5 migliori prodotti in Motozappe, Chitarre Elettriche|2016/09/motozappe-chitarre-elettriche-i-5-migliori-di-settembre-2016|AZ_31+U4v4Nr+L",
"Carrelli Da Portata, Smerigliatrici Angolari: i 5 migliori di settembre 2016|I 5 migliori prodotti in Carrelli Da Portata, Smerigliatrici Angolari|2016/09/carrelli-da-portata-smerigliatrici-angolari-i-5-migliori-di-settembre-2016|AZ_41ESs4BCouL",
"Compressori: i 10 migliori a agosto 2016|I 10 compressori consigliati oggi sul mercato: agosto 2016|2016/08/compressori-i-10-migliori-a-agosto-2016|AZ_4193YCv2xZL",
"La top 10 delle motozappe migliori: agosto 2016|Le 10 motozappe più consigliate: la guida all'acquisto di agosto 2016|2016/08/la-top-10-delle-motozappe-migliori-agosto-2016|AZ_41ZKH8cw1nL",
"Le 10 smerigliatrici angolari più quotate: agosto 2016|La top 10 delle migliori smerigliatrici angolari in commercio a agosto 2016|2016/08/le-10-smerigliatrici-angolari-piu-quotate-agosto-2016|AZ_418DTxLZWnL",
"I 16 avvitatori consigliati: luglio 2016|I 16 avvitatori più gettonati: la classifica di luglio 2016|2016/07/i-16-avvitatori-consigliati-luglio-2016|AZ_51KgxEPv6cL",
"Il meglio dei trapani sul mercato: maggio 2016|La top 12 dei migliori trapani disponibili per l'acquisto|2016/05/il-meglio-dei-trapani-sul-mercato-maggio-2016.html?t=casa,trapano,fai-da-te,trapano-avvitatore,avvitatore,utensili,abitazione,garage,officina,bosch,black-and-decker,bavaria&amp;d=19|AZ_51k80TK9-JL",
"Il meglio dei compressori all'aprile 2016|Aprile 2016: tutti i compressori più interessanti per l'acquisto|2016/04/il-meglio-dei-compressori-all-aprile-2016.html?t=fai-da-te,compressori,black-and-decker,casa,utensili,attrezzi,pompe,automobile,autovettura,auto,moto,motocicletta,tempo-libero,bicicletta,ciclismo,pneumatici,verniciatura,garage,mannesmann,stanley&amp;d=7|AZ_4193YCv2xZL",
"Il migliore trapano-avvitatore a percussione|Questo trapano Black and Decker è il trapano più venduto su Amazon!|2016/02/il-migliore-trapano-avvitatore-a-percussione.html?t=casa,fai-da-te,shopping,trapano,avvitatore,utensili,offerte,promozioni,black-and-decker&amp;d=28|AZ_71Jl6KOCW1L",
"Un utile termometro ad infrarossi che si usa da lontano|Misura la temperatura in superficie di qualunque oggetto senza contatto|2016/02/un-utile-termometro-ad-infrarossi-che-si-usa-da-lontano.html?t=casa,fai-da-te,utensili,strumenti-di-misura,termometro,infrarossi,temperatura,dr-meter&amp;d=15|AZ_61SenQ8YzRL",
];
