Gr = [
"Felpa Donna con Cappuccio Grigio|Collezione Autunno Inverno/2018 Questa felpa da donna con cappuccio|2017/12/felpa-donna-con-cappuccio-grigio|data.oliviero.it/imgprodotto/felpa-donna-con-cappuccio-grigio_166906",
"Felpa Taglie Forti Uomo|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-taglie-forti-uomo|data.oliviero.it/imgprodotto/felpa-taglie-forti-uomo_170218",
"Felpa Essentials 3 Stripes|Collezione Autunno Inverno/2018 Una felpa casual perfetta da|2017/12/felpa-essentials-3-stripes|data.oliviero.it/imgprodotto/felpa-essentials-3-stripes_167638",
"Felpa Taglie Forti Uomo Fango|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-taglie-forti-uomo-fango|data.oliviero.it/imgprodotto/felpa-taglie-forti-uomo-fango_171863",
"Felpa Uomo Blu Obsidian|Collezione Autunno Inverno/2018 Felpa di Nike, In morbida felpa|2017/12/felpa-uomo-blu-obsidian|data.oliviero.it/imgprodotto/felpa-uomo-blu-obsidian_167657",
"Felpa Girocollo Uomo Nero|Collezione Autunno Inverno/2018 Una felpa casual perfetta da|2017/12/felpa-girocollo-uomo-nero|data.oliviero.it/imgprodotto/felpa-girocollo-uomo-nero_166966",
"Gilet felpa Uomo Taglie Forti Nero|Collezione Primavera Estate Gilet uomo taglie forti. Il modello|2017/12/gilet-felpa-uomo-taglie-forti-nero|data.oliviero.it/imgprodotto/gilet-felpa-uomo-taglie-forti-nero_163728",
"Gilet Sportivo Taglie Forti Uomo Blu|Collezione Autunno Inverno/2018 Gilet sportivo da uomo. Il modello|2017/12/gilet-sportivo-taglie-forti-uomo-blu|data.oliviero.it/imgprodotto/gilet-sportivo-taglie-forti-uomo-blu_169310",
"Felpa Donna Grigio Scuro|Collezione Autunno Inverno/2018 giacca con davanti in lana bouclè|2017/12/felpa-donna-grigio-scuro|data.oliviero.it/imgprodotto/felpa-donna-grigio-scuro_170393",
"Felpa Uomo Verdone|Confortevole, classica e sportiva: questa felpa con cappuccio da uomo|2017/12/felpa-uomo-verdone|data.oliviero.it/imgprodotto/felpa-uomo-verdone_167997",
"Felpa Logo Popover Hoodie|Collezione Autunno Inverno/2018 Felpa nera con logo Wrangler, con|2017/12/felpa-logo-popover-hoodie|data.oliviero.it/imgprodotto/felpa-logo-popover-hoodie_170573",
"Felpa Taglie Forti Uomo Grafite|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. ll modello|2017/12/felpa-taglie-forti-uomo-grafite|data.oliviero.it/imgprodotto/felpa-taglie-forti-uomo-grafite_172138",
"Felpa Uomo Taglie Forti Grigio Melange|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-uomo-taglie-forti-grigio-melange|data.oliviero.it/imgprodotto/felpa-uomo-taglie-forti-grigio-melange_167834",
"Felpa Uomo Panna|Collezione Autunno Inverno/2018 Felpa da uomo di Champion, ideale per|2017/12/felpa-uomo-panna|data.oliviero.it/imgprodotto/felpa-uomo-panna_169781",
"Felpa Uomo Blu|Felpa con zip e collo alto di Adidas Originals, classicissima, con|2017/12/felpa-uomo-blu|data.oliviero.it/imgprodotto/felpa-uomo-blu_168181",
"Felpa Uomo Charcoal|Collezione Autunno Inverno/2018 La felpa con cappuccio Nike|2017/12/felpa-uomo-charcoal|data.oliviero.it/imgprodotto/felpa-uomo-charcoal_169409",
"Felpa Donna Bianco|Collezione Autunno Inverno/2018 La felpa con cappuccio Nike|2017/12/felpa-donna-bianco|data.oliviero.it/imgprodotto/felpa-donna-bianco_169394",
"Felpa Donna Nero|Collezione Autunno Inverno/2018 Felpa da donna di Champion, della|2017/12/felpa-donna-nero|data.oliviero.it/imgprodotto/felpa-donna-nero_169768",
"Felpa Uomo Taglie Forti Grigio 26700 250|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-uomo-taglie-forti-grigio-26700-250|data.oliviero.it/imgprodotto/felpa-uomo-taglie-forti-grigio-26700-250_168557",
"Felpa Uomo Nero|Una morbida giacca perfetta da indossare sopra l'abbigliamento da|2017/12/felpa-uomo-nero|data.oliviero.it/imgprodotto/felpa-uomo-nero_168033",
"Felpa Uomo Taglie Forti Verde|Collezione Autunno Inverno/2018 Felpa da uomo taglie forti. Il|2017/12/felpa-uomo-taglie-forti-verde|data.oliviero.it/imgprodotto/felpa-uomo-taglie-forti-verde_167951",
"Felpa Taglie Forti Uomo Blu|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-taglie-forti-uomo-blu|data.oliviero.it/imgprodotto/felpa-taglie-forti-uomo-blu_172140",
"Felpa Uomo Rosso|Collezione Autunno Inverno/2018 La grafica stampata sul petto di|2017/12/felpa-uomo-rosso|data.oliviero.it/imgprodotto/felpa-uomo-rosso_171031",
"Felpa Donna Dark Grey Melange|Collezione Autunno Inverno/2018 giacca lunga con zip leggermente|2017/12/felpa-donna-dark-grey-melange|data.oliviero.it/imgprodotto/felpa-donna-dark-grey-melange_170350",
"Felpa Uomo Royal|Collezione Autunno Inverno/2018 Felpa da uomo di Champion della|2017/12/felpa-uomo-royal|data.oliviero.it/imgprodotto/felpa-uomo-royal_169778",
"Felpa Uomo Antracite|Collezione Autunno Inverno/2018 La felpa da allenamento con cappuccio|2017/12/felpa-uomo-antracite|data.oliviero.it/imgprodotto/felpa-uomo-antracite_169422",
"Felpa Biker Donna Dark Grey Melange|Collezione Autunno Inverno/2018 felpa pesante con zip diagonale|2017/12/felpa-biker-donna-dark-grey-melange|data.oliviero.it/imgprodotto/felpa-biker-donna-dark-grey-melange_170342",
"Felpa Uomo Rossa|Collezione Primavera Estate Felpa da uomo con cappuccio e chiusura zip|2017/06/felpa-uomo-rossa|data.oliviero.it/imgprodotto/felpa-uomo-rosso_165064",
"Felpa Uomo Nero Adidas Essentials 3 Stripes|Felpa Uomo perfetta per le giornate più fresche, polsini e orlo a coste|2017/05/felpa-uomo-nero-adidas-essentials-3-stripes|data.oliviero.it/imgprodotto/felpa-uomo-nero-essentials-3-stripes-s98803_160228",
];
