Gr = [
"Tappetino Pieghevole Oxford|Tappetino pieghevole Gommapiuma interna Realizzato in materiale|2017/12/tappetino-pieghevole-oxford|data.oliviero.it/imgprodotto/tappetino-pieghevole-oxford_74531",
"Tapis Roulant St 5000|SCOPRI IL NUOVO VIC 7000 DISPLAY TOUCH SCREEN E WiFi CLICCA QUI Tapis|2017/12/tapis-roulant-st-5000|data.oliviero.it/imgprodotto/tapis-roulant-st-5000_127097",
"Borsone Sportivo BO7111 Nero|Borsa sportiva doppia maniglia per appendere e tasca frontale con|2017/12/borsone-sportivo-bo7111-nero|data.oliviero.it/imgprodotto/borsone-sportivo-bo7111-nero_152109",
"Materassino Tappetino per Esercizi a terra|Tappetino per il fitness ripieghevole Imbottito e rifinito in|2017/12/materassino-tappetino-per-esercizi-a-terra|data.oliviero.it/imgprodotto/materassino-tappetino-per-esercizi-a-terra_142887",
"Gym Ball Antiscoppio 65 cm|Victoria , il nuovo marchio di proprietà Oliviero, vi propone la|2017/12/gym-ball-antiscoppio-65-cm|data.oliviero.it/imgprodotto/gym-ball-antiscoppio-65-cm_74500",
"Disco in ghisa 1 2 5 10 kg|Disco in ghisa verniciato nero. Ideale per bilancieri e manubri per|2017/12/disco-in-ghisa-1-2-5-10-kg|data.oliviero.it/imgprodotto/disco-in-ghisa-1-2-5-10-kg_145896",
"Fascia elastica Medium|Fascia elastica con resistenza media per esercizi di gambe e braccia|2017/12/fascia-elastica-medium|data.oliviero.it/imgprodotto/fascia-elastica-medium_157966",
"Borsone Sportivo BO7111 Blu|Borsa sportiva doppia maniglia per appendere e tasca frontale con|2017/12/borsone-sportivo-bo7111-blu|data.oliviero.it/imgprodotto/borsone-sportivo-bo7111-blu_152111",
"Tappetino Insonorizzante 180x90|Tappeto in PVC, fonoassorbente ad alta densità perfetto per|2017/12/tappetino-insonorizzante-180x90|data.oliviero.it/imgprodotto/tappetino-insonorizzante-180x90_140806",
"Kit Manubri Cromati + 32 kg Pesi|L'offerta comprende i manubri Victoria e 4 dischi in ghisa da 1 kg,|2017/12/kit-manubri-cromati-+-32-kg-pesi|data.oliviero.it/imgprodotto/kit-manubri-cromati-32-kg-pesi_147204",
"Tappetino Pieghevole|Tappetino pieghevole &bull; Superficie antiscivolo in ecopelle|2017/12/tappetino-pieghevole|data.oliviero.it/imgprodotto/tappetino-pieghevole_153869",
"Panca Multifunzione Black Gym|Panca Multifunzione ideale per l'utilizzo domestico. Pacco pesi di|2017/12/panca-multifunzione-black-gym|data.oliviero.it/imgprodotto/panca-multifunzione-black-gym_124134",
"Fascia elastica Light|Fascia elastica con resistenza leggera per esercizi di gambe|2017/12/fascia-elastica-light|data.oliviero.it/imgprodotto/fascia-elastica-light_157967",
"Barra per Trazioni Entroporta Isometrica|Victoria, il nuovo marchio di proprietà Oliviero, vi propone la Barra|2017/12/barra-per-trazioni-entroporta-isometrica|data.oliviero.it/imgprodotto/barra-per-trazioni-entroporta-isometrica_1201_big",
"Sacca Oliviero|Caratterizzata da un design semplice e leggero, questa sacca sportiva|2017/12/sacca-oliviero|data.oliviero.it/imgprodotto/sacca-oliviero_165201",
"Cyclette ST 105|La cyclette ST 105 è la soluzione ideale per l'home fitness con un|2017/12/cyclette-st-105|data.oliviero.it/imgprodotto/cyclette-st-105_142882",
"Kit 180 Bilanciere + Manubri + 32 kg Pesi|Pacchetto Offerta composto da: Bilanciere 180 cm + Coppia di Manubri|2017/12/kit-180-bilanciere-+-manubri-+-32-kg-pesi|data.oliviero.it/imgprodotto/kit-180-bilanciere-manubri-32-kg-pesi_92918",
"Pacchetto Pilates|Il Pacchetto Pilates comprende: Balance Board Regolabile, Balance|2017/12/pacchetto-pilates|data.oliviero.it/imgprodotto/pacchetto-pilates_158872",
"Bilanciere cromato 150 cm|Bilanciere cromato creato per lo sviluppo di bicipiti e tricipiti|2017/12/bilanciere-cromato-150-cm|data.oliviero.it/imgprodotto/bilanciere-cromato-150-cm_151884",
"Kettlebells 15KG|Le Kettlebells sono sfere in ghisa con una maniglia fissa. Questi|2017/12/kettlebells-15kg|data.oliviero.it/imgprodotto/kettlebells-15kg_52230",
"Kit Tonificazione|Il pacchetto esercizi di tonificazione comprende: Thigh Master|2017/12/kit-tonificazione|data.oliviero.it/imgprodotto/kit-tonificazione_142906",
"Panca Ginnica Bench Pro|Panca Ginnica Bench Pro con SUPPORTO BILANCIERE, LEG CURL, LEG|2017/12/panca-ginnica-bench-pro|data.oliviero.it/imgprodotto/panca-ginnica-bench-pro_143359",
"Disco ghisa 10Kg|Disco peso in ghisa verniciata. Unica colorazione nero come da|2017/12/disco-ghisa-10kg|data.oliviero.it/imgprodotto/disco-ghisa-10kg_145897",
"Pacchetto Tonifico e Rilasso|Il pacchetto tonifico e Rilasso comprende: Materassino per esercizi|2017/12/pacchetto-tonifico-e-rilasso|data.oliviero.it/imgprodotto/pacchetto-tonifico-e-rilasso_158874",
"Cyclette ST 600|Cyclette St 600, particolarmente adatta per uso domestico.Il computer|2017/12/cyclette-st-600|data.oliviero.it/imgprodotto/cyclette-st-600_127093",
"Pacchetto Sviluppo Bicipiti|La promozione Pacchetto Sviluppo Bicipiti comprende: 1 Coppia pinze|2017/12/pacchetto-sviluppo-bicipiti|data.oliviero.it/imgprodotto/pacchetto-sviluppo-bicipiti_164700",
"Kit Panca Bench Pro Deluxe + Bilanciere + Pesi|Pacchetto Offerta Victoria composto da: Panca Ginnica Bench Pro|2017/12/kit-panca-bench-pro-deluxe-+-bilanciere-+-pesi|data.oliviero.it/imgprodotto/kit-panca-bench-pro-deluxe-bilanciere-pesi_164698",
"Kit Easy Fitness 2.0|Il pacchetto Easy Fitness comprende: Fascia Elastica Strong - Gym|2017/12/kit-easy-fitness-2-0|data.oliviero.it/imgprodotto/kit-easy-fitness-2-0_151462",
"Panca Addominali Ginnica Bench Trainer|Panca Addominali Ginnica Bench Trainer , particolarmente adatta per|2017/12/panca-addominali-ginnica-bench-trainer|data.oliviero.it/imgprodotto/panca-addominali-ginnica-bench-trainer_141085",
"Gym Bike VIC8000|Gym Bike VIC8000, particolarmente adatto per uso domestico.Il|2017/12/gym-bike-vic8000|data.oliviero.it/imgprodotto/gym-bike-vic8000_169089",
"Balance Board Regolabile|Balance Board: Diametro 41 cm. L'attrezzo ginnico ideale per|2017/12/balance-board-regolabile|data.oliviero.it/imgprodotto/balance-board-regolabile-w1352_158863",
"Kit Bilanciere + Manubri + 52 kg Pesi|Pacchetto offerta composto da: Bilanciere 150 cm + Coppia di Manubri|2017/12/kit-bilanciere-+-manubri-+-52-kg-pesi|data.oliviero.it/imgprodotto/kit-bilanciere-manubri-52-kg-pesi_92915",
"Disco ghisa 2Kg|Disco peso in ghisa verniciata. Unica colorazione nero come da|2017/12/disco-ghisa-2kg|data.oliviero.it/imgprodotto/disco-ghisa-2kg_145899",
"Cilindro Foam Roll con PVC Core|I foam roller sono rotoli di gomma, liscia o levigata, sempre più|2017/12/cilindro-foam-roll-con-pvc-core|data.oliviero.it/imgprodotto/cilindro-foam-roll-con-pvc-core_158870",
"Fascia elastica Strong|Fascia elastica con resistenza media per esercizi di gambe e braccia|2017/12/fascia-elastica-strong|data.oliviero.it/imgprodotto/fascia-elastica-strong_157965",
"Kettlebells 10KG|Le Kettlebells sono sfere in ghisa con una maniglia fissa. Questi|2017/12/kettlebells-10kg|data.oliviero.it/imgprodotto/kettlebells-10kg_52231",
"Gym Ball 75 cm|Victoria , il nuovo marchio di proprietà Oliviero, vi propone la|2017/12/gym-ball-75-cm|data.oliviero.it/imgprodotto/gym-ball-75-cm_74499",
"Tapis Roulant VIC 7000|Tapis roulant VIC 7000 adatto per uso domestico.Il computer|2017/12/tapis-roulant-vic-7000|data.oliviero.it/imgprodotto/tapis-roulant-vic-7000_169508",
"Disco ghisa 1kg|Disco peso in ghisa verniciata. Unica colorazione nero come da|2017/12/disco-ghisa-1kg|data.oliviero.it/imgprodotto/disco-ghisa-1kg_145898",
"Kit Panca Bench Pro + Bilanciere + Pesi|Pacchetto Offerta Victoria composto da: Panca Ginnica Bench Pro|2017/12/kit-panca-bench-pro-+-bilanciere-+-pesi|data.oliviero.it/imgprodotto/kit-panca-bench-pro-bilanciere-pesi_143360",
"Barra Entroporta Advance|Barra entroporta isometrica ideale per allenamento di forza, per|2017/12/barra-entroporta-advance|data.oliviero.it/imgprodotto/barra-entroporta-advance_101193",
"Cyclette ST 405 accesso facilitato|Cyclette St 405 è una cyclette adatta a tutti grazie al comodo|2017/12/cyclette-st-405-accesso-facilitato|data.oliviero.it/imgprodotto/cyclette-st-405-accesso-facilitato_142097",
"Kit Dumbell Set 20 Kg|Kit pesi Manubri composto da: 2 manubri filettati da 2,5 kg in cromo|2017/12/kit-dumbell-set-20-kg|data.oliviero.it/imgprodotto/kit-dumbell-set-20-kg_14255_big",
"Panca addominali Vic 100|Panca addominali regolabile in altezza. La possibilità di regolare la|2017/12/panca-addominali-vic-100|data.oliviero.it/imgprodotto/panca-addominali-vic-100_150165",
"Tapis Roulant VIC 2020 PRO|Caratteristiche tecniche: Motore: 1,75 HP DC Velocità: 1,0 - 14,0|2017/12/tapis-roulant-vic-2020-pro|data.oliviero.it/imgprodotto/tapis-roulant-vic-2020-pro_165869",
"Panca Bench Pro Deluxe|La Panca Ginnica Bench Pro Deluxe di alto design e curata al massimo|2017/12/panca-bench-pro-deluxe|data.oliviero.it/imgprodotto/panca-bench-pro-deluxe_147081",
"Tapis Roulant Elettrico VIC 1500|Caratteristiche tecniche: Motore: 1,75 HP DC Velocità: 1,0 - 14,0|2017/12/tapis-roulant-elettrico-vic-1500|data.oliviero.it/imgprodotto/tapis-roulant-elettrico-vic-1500_165875",
"Thigh Master interno coscia|Ideale per l'allenamento delle gambe ma anche per le braccia. Morbido|2017/12/thigh-master-interno-coscia|data.oliviero.it/imgprodotto/thigh-master-interno-coscia_52226",
"Rotating Push Up Bar|Victoria , il nuovo marchio di proprietà Oliviero, vi propone|2017/12/rotating-push-up-bar|data.oliviero.it/imgprodotto/rotating-push-up-bar_74505",
"Bilanciere cromato 180 cm|Bilanciere cromato creato per lo sviluppo di bicipiti e tricipiti|2017/12/bilanciere-cromato-180-cm|data.oliviero.it/imgprodotto/bilanciere-cromato-180-cm_22204_big",
"Pacchetto Tonificazione 2.0|Il pacchetto tonificazione 2.0 comprende Fascia Elastica Strong|2017/12/pacchetto-tonificazione-2-0|data.oliviero.it/imgprodotto/pacchetto-tonificazione-2-0_158875",
"Tappetino Arrotolabile 180x50|Tappetino per il fitness arrotolabile &bull; Superficie antiscivolo|2017/12/tappetino-arrotolabile-180x50|data.oliviero.it/imgprodotto/tappetino-arrotolabile-180x50_14309_big",
"Kit Dumbell Set 15 Kg|Kit Portatile comprendente: 2 manubri a vite da 2,5kg 4 dischi da|2017/12/kit-dumbell-set-15-kg|data.oliviero.it/imgprodotto/kit-dumbell-set-15-kg_14259_big",
"Tapis Roulant St 1500|Tapis Roulant con chiave di sicurezza per lo spegnimento di emergenza|2017/10/tapis-roulant-st-1500|data.oliviero.it/imgprodotto/tapis-roulant-st-1500_90737",
"Cuscino Equilibrio per Pilates|Il Cuscino per Pilates, per creare esercizi di Pilates variati|2017/06/cuscino-equilibrio-per-pilates|data.oliviero.it/imgprodotto/cuscino-equilibrio_158869",
];
