Gr = [
"Le 10 Bistecchiere più quotate: dicembre 2016|Le 10 Bistecchiere che piacciono di più, disponibili da subito|2016/12/le-10-bistecchiere-piu-quotate-dicembre-2016|AZ_41PkSDq-ECL",
"I 10 barbecue elettrici migliori: ottobre 2016|I 10 barbecue elettrici che vanno per la maggiore, disponibili subito|2016/10/i-10-barbecue-elettrici-migliori-ottobre-2016|AZ_41yWuU5ChaL",
"Griglie elettriche: le 10 migliori a ottobre 2016|Le 10 griglie elettriche più premiate dal mercato: ottobre 2016|2016/10/griglie-elettriche-le-10-migliori-a-ottobre-2016|AZ_41KC-RnF74L",
"Bistecchiere, Portabici per Auto: i 5 migliori di settembre 2016|I 5 migliori prodotti in Bistecchiere, Portabici per Auto|2016/09/bistecchiere-portabici-per-auto-i-5-migliori-di-settembre-2016|AZ_31u8vcGWCOL",
"Action Camera, Presse per Hamburger: i 5 migliori di settembre 2016|I 5 migliori prodotti in Action Camera, Presse per Hamburger|2016/09/action-camera-presse-per-hamburger-i-5-migliori-di-settembre-2016|AZ_41vr83h45YL",
"Le 10 presse per hamburger più acquistate: settembre 2016|La top 10 delle migliori presse per hamburger disponibili da subito|2016/09/le-10-presse-per-hamburger-piu-acquistate-settembre-2016|AZ_41K3nr9p+fL",
"Bistecchiere: le 14 migliori a luglio 2016|La top 14 delle migliori bistecchiere in commercio a luglio 2016|2016/07/bistecchiere-le-14-migliori-a-luglio-2016|AZ_41ObagJyrFL",
"Le 8 pentole in alluminio più vendute a luglio 2016|Le 8 migliori pentole in alluminio sul mercato: luglio 2016|2016/07/le-8-pentole-in-alluminio-piu-vendute-a-luglio-2016.html?t=cucina,pentole-alluminio,bistecchiere,alimentazione,cibo,cottura,pentole,padelle,casseruole,tegami,dolci,ristorante&amp;d=18|AZ_41a0cEWQUsL",
"Piastre elettriche: le 14 migliori a giugno 2016|Le 14 piastre elettriche più apprezzate: giugno 2016|2016/06/piastre-elettriche-le-14-migliori-a-giugno-2016.html?t=cucina,piastre-elettriche,casa,bistecchiere,alimentazione,cibo,cottura,elettrodomestici,forni-elettrici,fornetti-elettrici,griglie-elettriche,severin,duronic,russell-hobbs,tristar,rowenta,koenig&amp;d=13|AZ_41ObagJyrFL",
"Le 13 pentole e padelle in pietra più acquistate: maggio 2016|La classifica di maggio 2016 delle migliori pentole e padelle in pietra|2016/05/le-13-pentole-e-padelle-in-pietra-piu-acquistate-maggio-2016.html?t=cucina,casa,pentole,pentole-pietra,padelle,padelle-pietra,casseruole,bistecchiere,tegami,alimentazione,cibo,gastronomia,bialetti,ballarini&amp;d=11|AZ_41RjQCYwYOL",
"Il meglio delle bistecchiere: la guida all'acquisto di aprile 2016|Le migliori bistecchiere disponibili|2016/04/il-meglio-delle-bistecchiere-la-guida-all-acquisto-di-aprile-2016.html?t=bistecchiere,cucina,alimentazione,cibo,gastronomia,cottura,dieta,rowenta,imetec,ballarini,ariete,tefal,tristar,russell,bosch,severin&amp;d=18|AZ_41q5q4vUqBL",
];
