Gr = [
"Tavolo Ping Pong Expert Roller CSS Indoor|Modello da competizione per interno, della massima stabilità|2017/12/tavolo-ping-pong-expert-roller-css-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-expert-roller-css-indoor_2021_big",
"Tavolo Ping Pong Privat Roller CSS Indoor|Modello per interno, di notevole stabilità e robustezza e di qualità|2017/12/tavolo-ping-pong-privat-roller-css-indoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-privat-roller-css-indoor_2017_big",
"Calcio da Tavolo World Champs|Caratteristiche tecniche: Tutti i giocatori sono tridimensionali ed|2017/12/calcio-da-tavolo-world-champs|data.oliviero.it/imgprodotto/calcio-da-tavolo-world-champs_11186_big",
"Racchetta Charger Tube 3 Stelle|Racchetta Ping Pong Stiga Charger Racchetta Ping Pong è una racchetta|2017/12/racchetta-charger-tube-3-stelle|data.oliviero.it/imgprodotto/racchetta-charger-tube-3-stelle_8334_big",
"Set Venture WRB|Set ping pong composto da 1 racchetta e 3 palline con custodia) Set|2017/12/set-venture-wrb|data.oliviero.it/imgprodotto/set-venture-wrb_8355_big",
"Set di 2 racchette Hobby Senior|Set hobby composto da 2 racchette, 3 volani e custodia. Set completo|2017/12/set-di-2-racchette-hobby-senior|data.oliviero.it/imgprodotto/set-di-2-racchette-hobby-senior_8371_big",
"Racchetta Premier NCT 5 Stelle|Racchetta Ping Pong Racchetta da Ping Pong Premier NCT (5 stelle) di|2017/12/racchetta-premier-nct-5-stelle|data.oliviero.it/imgprodotto/racchetta-premier-nct-5-stelle_8345_big",
"Bob Pacer Duo con freni|Il nuovissimo bob biposto di Stiga, permette di accogliere un adulto|2017/12/bob-pacer-duo-con-freni|data.oliviero.it/imgprodotto/bob-pacer-duo-con-freni_160176",
"Bob Pacer con freni|Bob di semplice utilizzo e durevole nel tempo per il divertimento di|2017/12/bob-pacer-con-freni|data.oliviero.it/imgprodotto/bob-pacer-con-freni_68449",
"Racchetta Impax ACS 2 Stelle|Racchetta Ping Pong Caratteristiche tecniche Struttura in compensato|2017/12/racchetta-impax-acs-2-stelle|data.oliviero.it/imgprodotto/racchetta-impax-acs-2-stelle_8328_big",
"Racchetta ping pong React|REACT WRB RACCHETTA DA PING PONG STIGA COD.2C4-501 React WRB combina|2017/12/racchetta-ping-pong-react|data.oliviero.it/imgprodotto/racchetta-ping-pong-react_59698",
"Set di 4 racchette Family|L'attrezzatura ideale per organizzare tornei di famiglia in giardino|2017/12/set-di-4-racchette-family|data.oliviero.it/imgprodotto/set-di-4-racchette-family_8373_big",
"Hockey da Tavolo Play Off|L'Hockey su tavolo, dinamico gioco di origine nordica, offre puro|2017/12/hockey-da-tavolo-play-off|data.oliviero.it/imgprodotto/hockey-da-tavolo-play-off_8356_big",
"Racchetta Cosmo WRB 3 Stelle|Racchetta Ping Pong Grazie all'uso della tecnologia WRB, Cosmo ha una|2017/12/racchetta-cosmo-wrb-3-stelle|data.oliviero.it/imgprodotto/racchetta-cosmo-wrb-3-stelle_8332_big",
"Set Solara|Set Solara composto da 2 racchette e 3 palline + tendirete e rete Set|2017/12/set-solara|data.oliviero.it/imgprodotto/set-solara_8353_big",
"Tavolo Ping Pong Winner Outdoor|Modello per esterno, perfetto per l'uso hobbistico e ricreativo|2017/12/tavolo-ping-pong-winner-outdoor|data.oliviero.it/imgprodotto/tavolo-ping-pong-winner-outdoor_8322_big",
];
