Gr = [
"La top 10 delle Lavastoviglie: novembre 2016|Le 10 Lavastoviglie più comprate disponibili da subito: novembre 2016|2016/11/la-top-10-delle-lavastoviglie-novembre-2016|AZ_41JJbClg3PL",
"Pentole a Pressione, Mouse: i 5 migliori di settembre 2016|I 5 migliori prodotti di settembre 2016 in Pentole a Pressione, Mouse|2016/09/pentole-a-pressione-mouse-i-5-migliori-di-settembre-2016|AZ_41j0sjBu0ML",
"Le 10 pentole a pressione più amate: agosto 2016|La top 10 delle migliori pentole a pressione, disponibili subito!|2016/08/le-10-pentole-a-pressione-piu-amate-agosto-2016|AZ_41Ap3pF2FmL",
"Le 10 lavastoviglie più comprate: giugno 2016|La top 10 delle migliori lavastoviglie sul mercato a giugno 2016|2016/06/le-10-lavastoviglie-piu-comprate-giugno-2016.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,pulizia,igiene,stoviglie,piatti,pentole,beko,electrolux,klarstein,bosch,ariston,indesit,smeg&amp;d=2|AZ_41tdMsxE9QL",
"Le vaporiere più acquistate di aprile 2016|La classifica di aprile delle vaporiere migliori|2016/04/le-vaporiere-piu-acquistate-di-aprile-2016.html?t=cucina,vaporiere,alimentazione,cibo,gastronomia,stoviglie,pentole,cottura,dieta,benessere,vitamine,calorie,vapore,russell,tefal,philips,braun,whirlpool&amp;d=14|AZ_51r90GvkoxL",
"Aprile 2016: la classifica delle pentole a pressione più vendute|Tutte le migliori pentole a pressione|2016/04/aprile-2016-la-classifica-delle-pentole-a-pressione-piu-vendute.html?t=cucina,pentole-a-pressione,casa,alimentazione,cibo,gastronomia,stoviglie,pentole,cottura,lagostina,bialetti&amp;d=11|AZ_41H9QnBbHlL",
"Al marzo 2016, ecco le 9 lavastoviglie migliori|La nostra classifica delle 9 migliori lavastoviglie|2016/03/al-marzo-2016-ecco-le-9-lavastoviglie-migliori.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,igiene,stoviglie,klarstein,beko,indesit,bosch,smeg,electrolux&amp;d=31|AZ_51zRVIL8yqL",
];
