Gr = [
"La top 10 dei migliori Telescopi: gennaio 2017|I 10 Telescopi più venduti: la guida all'acquisto di gennaio 2017|2017/01/la-top-10-dei-migliori-telescopi-gennaio-2017|AZ_41qtiPiLgNL",
"Video - Giove domina il cielo di luglio 2016|Si può vedere a occhio nudo, scopriamo come con questo bel video!|2016/07/video-giove-domina-il-cielo-di-luglio-2016.html?t=astronomia,scienza,astrofisica,spazio,inaf,pianeta,giove,stella,costellazione,natura,cielo,notte&amp;d=2|YT_Y152OugSwpw",
"Video - Se hai perso il transito di Mercurio e ora vuoi ammazzarti|ASPETTA, non tutto è perduto!|2016/05/video-se-hai-perso-il-transito-di-mercurio-e-ora-vuoi-ammazzarti.html?t=scienza,astronomia,astrofisica,spazio,inaf,pianeta,mercurio,sole,napoli,pink-floyd,queen,canzoni&amp;d=11|YT__uuVDA0FLlU",
"Aprile 2016: tutti i telescopi più venduti!|Il meglio dei telescopi nella nostra guida all'acquisto|2016/04/aprile-2016-tutti-i-telescopi-piu-venduti.html?t=scienza,astronomia,astrofisica,spazio,telescopio,via-lattea,galassia,pianeta,plutone,giove,stella,costellazione,ammasso-globulare,ammasso-stellare,catalogo-messier,marte,national-geographic&amp;d=18|AZ_41Y9zq9XAbL",
"Video - Cosa si nasconde dietro Sagittarius A?|Un'immagine che toglie il fiato|2016/04/video-cosa-si-nasconde-dietro-sagittarius-a.html?t=scienza,astronomia,astrofisica,spazio,inaf,nasa,infrarossi,hubble,telescopio,esa,via-lattea,galassia&amp;d=14|YT_p19fsfSfzRA",
"Video - Il mistero del pianeta nano Plutone|Plutone è stato un mistero per anni, anzi per decenni|2016/04/video-il-mistero-del-pianeta-nano-plutone.html?t=astronomia,astrofisica,spazio,scienza,inaf,nasa,pianeta,plutone,caronte,new-horizons,sonda-spaziale&amp;d=1|YT_AUjhYS9Zym0",
"Video - Scoperta acqua in un cratere di Cerere, e forse ai poli|Importante in questa scoperta il ruolo dello spettrometro italiano VIR|2016/03/video-scoperta-acqua-in-un-cratere-di-cerere-e-forse-ai-poli.html?t=astronomia,astrofisica,spazio,scienza,cerere,inaf,acqua,nasa,fascia-degli-asteroidi&amp;d=30|YT__4A3UBr6YKI",
"Video - Le meraviglie del cielo di gennaio|Tante cose bellissime nel cielo di questo nuovo anno appena iniziato|2016/01/video-le-meraviglie-del-cielo-di-gennaio.html?t=astronomia,astrofisica,spazio,scienza,stella,pianeta,costellazione,ammasso-globulare,ammasso-stellare,catalogo-messier,inaf&amp;d=3|YT_IAopwgYUhgg",
"Video - Cerere e la fantascienza di The Expanse|Cerere è il pianeta nano più vicino alla Terra, e non conosce stagioni|2015/12/video-cerere-e-la-fantascienza-di-the-expanse.html?t=astronomia,astrofisica,spazio,fantascienza,scienza,marte,cerere,fascia-degli-asteroidi,syfy,space-opera,premio-hugo,inaf&amp;d=28|YT_kS6akT0YUlQ",
"Video - Acqua su Marte: cosa c'è di diverso questa volta?|Scopriamolo insieme guardando questo video dell'Istituto Nazionale di AstroFisica|2015/10/video-acqua-su-marte-cosa-c-e-di-diverso-questa-volta.html?t=scienza,astronomia,astrofisica,spazio,marte,nasa,acqua,fantascienza,ray-bradbury&amp;d=2|ray-bradbury",
];
