Gr = [
"I 10 frullatori ad immersione migliori: ottobre 2016|La top 10 dei migliori frullatori ad immersione sul mercato|2016/10/i-10-frullatori-ad-immersione-migliori-ottobre-2016|AZ_41Iujy8jDmL",
"Frigoriferi, Tritatutto: i 5 migliori di settembre 2016|I 5 migliori prodotti di settembre 2016 in Frigoriferi, Tritatutto|2016/09/frigoriferi-tritatutto-i-5-migliori-di-settembre-2016|AZ_31OeCJ6YGHL",
"Tritatutto, Macchine da Caffè a Cialde: i 5 migliori di settembre 2016|I 5 migliori prodotti in Tritatutto, Macchine Da Caffè A Cialde|2016/09/tritatutto-macchine-da-caffe-a-cialde-i-5-migliori-di-settembre-2016|AZ_41mp4dhS5rL",
"I 15 migliori tritatutto: agosto 2016|I 15 tritatutto più interessanti per l'acquisto ad agosto 2016|2016/08/i-15-migliori-tritatutto-agosto-2016|AZ_31mbYWmbLNL",
"I 16 robot da cucina più amati: luglio 2016|I 16 robot da cucina più quotati disponibili da subito: luglio 2016|2016/07/i-16-robot-da-cucina-piu-amati-luglio-2016.html?t=robot-da-cucina,cucina,tritatutto,elettrodomestici,cibo,alimentazione,casa,impastatrici,pasta,frullatori,mixer,spremiagrumi,spremiagrumi-elettrici,frutta,verdura,tritacarne,philips,kenwood,black-and-decker,bosch,imetec,moulinex,russell-hobbs,bomann&amp;d=14|AZ_4144t1M2n9L",
"La top 13 dei migliori frullatori da tavolo: luglio 2016|I 13 frullatori da tavolo più apprezzati da chi lavora davvero in cucina|2016/07/la-top-13-dei-migliori-frullatori-da-tavolo-luglio-2016.html?t=cucina,frullatori-tavolo,frullatori,elettrodomestici,mixer,casa,bar,cibo,alimentazione,alimenti,gastronomia,tritatutto,duronic,electrolux,philips,black-and-decker,kenwood,princess,klarstein,tristar,imetec&amp;d=6|AZ_51plaqbLv0L",
"I 15 mixer ad immersione migliori: la classifica di maggio 2016|Il top dei mixer ad immersione in commercio a maggio 2016|2016/05/i-15-mixer-ad-immersione-migliori-la-classifica-di-maggio-2016.html?t=elettrodomestici,mixer,mixer-ad-immersione,frullatori,frullatori-ad-immersione,casa,cucina,bar,cibo,alimentazione,alimenti,gastronomia,bosch,kenwood,imetec,russell-hobbs,braun,ariete&amp;d=18|AZ_41Iujy8jDmL",
"La classifica dei frullatori e mixer ad immersione migliori, valutati al 20 marzo|Ecco i 16 migliori frullatori e mixer ad immersione alla data del 20 marzo|2016/03/la-classifica-dei-frullatori-e-mixer-ad-immersione-migliori-valutati-al-20-marzo.html?t=cucina,casa,frullatori,frullatori-ad-immersione,mixer-ad-immersione,mixer,elettrodomestici,cibo,alimentazione,bar,imetec,bosch,braun,kenwood,russell&amp;d=20|AZ_21ZnYrbUa8L",
];
