Gr = [
"Felpa Uomo Taglie Forti Grigio|Collezione Primavera Estate Felpa da uomo taglie forti con cappuccio|2017/12/felpa-uomo-taglie-forti-grigio|data.oliviero.it/imgprodotto/felpa-uomo-taglie-forti-grigio_163724",
"2 T-shirt taglie forti uomo 99110|Confezione composta da 2 T-Shirt corpo uomo realizzata in puro|2017/12/2-t-shirt-taglie-forti-uomo-99110|data.oliviero.it/imgprodotto/2-t-shirt-taglie-forti-uomo-99110_11936_big",
"Giubbotto Uomo Taglie Forti Grigio|Collezione Autunno Inverno/2018 Gilet imbottito da uomo taglie forti|2017/12/giubbotto-uomo-taglie-forti-grigio|data.oliviero.it/imgprodotto/giubbotto-uomo-taglie-forti-grigio_168590",
"Bermuda Uomo Taglie Forti Grigio|Collezione Primavera Estate Bermuda uomo taglie forti. Il modello|2017/12/bermuda-uomo-taglie-forti-grigio|data.oliviero.it/imgprodotto/bermuda-uomo-taglie-forti-grigio_165632",
"Felpa Taglie Forti Uomo Grigio|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-taglie-forti-uomo-grigio|data.oliviero.it/imgprodotto/felpa-taglie-forti-uomo-grigio_169610",
"2 T-Shirt taglie forti uomo bianca|Confezione composta da 2 T-Shirt. Modello maglia realizzato per le|2017/12/2-t-shirt-taglie-forti-uomo-bianca|data.oliviero.it/imgprodotto/2-t-shirt-taglie-forti-uomo-bianca_10380_big",
"Giubbotto Taglie Forti Uomo Nero|Collezione Autunno Inverno/2018 Giubbotto in pelle da uomo taglie|2017/12/giubbotto-taglie-forti-uomo-nero|data.oliviero.it/imgprodotto/giubbotto-taglie-forti-uomo-nero_171900",
"Giubbotto Uomo Taglie Forti Navy|Collezione Autunno Inverno/2018 Giubbotto da uomo taglie Forti. Il|2017/12/giubbotto-uomo-taglie-forti-navy|data.oliviero.it/imgprodotto/giubbotto-uomo-taglie-forti-navy_168591",
"Giubbotto Uomo Taglie Forti Blu|Collezione Primavera Estate Giubbotto da uomo taglie forti. Il|2017/12/giubbotto-uomo-taglie-forti-blu|data.oliviero.it/imgprodotto/giubbotto-uomo-taglie-forti-blu-71311-0580_161462",
"Felpa Taglie Forti Uomo|Collezione Autunno Inverno/2018 Felpa uomo taglie forti. Il modello|2017/12/felpa-taglie-forti-uomo|data.oliviero.it/imgprodotto/felpa-taglie-forti-uomo_170218",
"T-Shirt Uomo Taglie Forti Melange|Collezione Primavera Estate T-Shirt mezza manica con stampa frontale|2017/12/t-shirt-uomo-taglie-forti-melange|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-melange-71395-045_162589",
"Maglia Uomo Taglie Forti|Collezione Autunno Inverno/2018 Maglia uomo taglie forti. Il modello|2017/12/maglia-uomo-taglie-forti|data.oliviero.it/imgprodotto/maglia-uomo-taglie-forti_167836",
"T-Shirt Uomo Taglie Forti Navy|Collezione Autunno Inverno/2018 T-shirt uomo taglie forti con|2017/12/t-shirt-uomo-taglie-forti-navy|data.oliviero.it/imgprodotto/t-shirt-uomo-taglie-forti-navy_167819",
"Camicia Uomo Taglie Forti a Righe|Collezione Primavera Estate Camicia uomo taglie forti. Il modello|2017/12/camicia-uomo-taglie-forti-a-righe|data.oliviero.it/imgprodotto/camicia-uomo-taglie-forti-a-righe_164498",
];
