Gr = [
"Macchine per Waffle: le 10 migliori in commercio a gennaio 2017|Le 10 Macchine per Waffle più apprezzate oggi sul mercato: gennaio 2017|2017/01/macchine-per-waffle-le-10-migliori-in-commercio-a-gennaio-2017|AZ_51wpxM5nAKL",
"Caricabatterie per Cellulari da Auto: i 10 migliori a novembre 2016|I 10 Caricabatterie per Cellulari da Auto migliori, subito disponibili|2016/11/caricabatterie-per-cellulari-da-auto-i-10-migliori-a-novembre-2016|AZ_41evr9FwwlL",
"I 10 piumoni migliori: ottobre 2016|La top 10 dei migliori piumoni: ottobre 2016|2016/10/i-10-piumoni-migliori-ottobre-2016|AZ_41l6JU5noRL",
"Cucce per cani: le 10 migliori a settembre 2016|Le 10 cucce per cani che piacciono di più: la classifica aggiornata|2016/09/cucce-per-cani-le-10-migliori-a-settembre-2016|AZ_31PPnBYaIIL",
"Distruggidocumenti: i 10 migliori a settembre 2016|I 10 distruggidocumenti migliori disponibili da subito: settembre 2016|2016/09/distruggidocumenti-i-10-migliori-a-settembre-2016|AZ_41toz-SkdhL",
"Plastificatrici: le 10 migliori a settembre 2016|Le 10 plastificatrici migliori disponibili ora per l'acquisto|2016/09/plastificatrici-le-10-migliori-a-settembre-2016|AZ_31tRpbzQvkL",
"I 10 migliori zaini per la scuola: settembre 2016|I 10 zaini per la scuola più alla moda: la classifica aggiornata|2016/09/i-10-migliori-zaini-per-la-scuola-settembre-2016|AZ_5177Lj2lMFL",
"I 10 zaini per la scuola più trendy: agosto 2016|I 10 zaini per la scuola che incontrano il maggiore gradimento|2016/08/i-10-zaini-per-la-scuola-piu-trendy-agosto-2016|AZ_5177Lj2lMFL",
"Borse per PC portatili: le 16 migliori a luglio 2016|Le 16 borse per PC portatili migliori subito disponibili: luglio 2016|2016/07/borse-per-pc-portatili-le-16-migliori-a-luglio-2016.html?t=borse-pc-portatili,pc,zaini,pc-portatili,computer,computer-portatili,ultrabook,notebook,laptop,informatica,personal-computer,tablet,tablet-computer,moda,borse,borse-tracolla,stile,accessori,abbigliamento,viaggi,lavoro,ufficio,bagagli,belkin,hp,hewlett-packard,amazonbasics,trust&amp;d=21|AZ_41+KmR+iX7L",
"I 9 navigatori GPS al top: luglio 2016|I 9 migliori navigatori GPS subito disponibili: luglio 2016|2016/07/i-9-navigatori-gps-al-top-luglio-2016.html?t=navigatori-gps,gps,autovelox,navigatore-satellitare,mp3,auto,autovettura,automobile,moto,motocicletta,scooter,camion,camper,veicolo,motori,traffico,viaggi,vacanze,elettronica,geolocalizzazione,tomtom,amazonbasics,garmin&amp;d=15|AZ_51no2x2t99L",
"I 16 altoparlanti portatili migliori: luglio 2016|I 16 altoparlanti portatili che vanno per la maggiore: luglio 2016|2016/07/i-16-altoparlanti-portatili-migliori-luglio-2016.html?t=altoparlanti,altoparlanti-portatili,musica,elettronica,casse-bluetooth,bluetooth,tempo-libero,audio,hi-fi,alta-fedelta,telefono-cellulare,smartphone,stereo,suono,wireless,wi-fi,android,ios,aukey,philips,amazonbasics&amp;d=11|AZ_41Od1kDNw8L",
"Pile ricaricabili: le 14 più comprate a luglio 2016|La top 14 delle migliori pile ricaricabili sul mercato a luglio 2016|2016/07/pile-ricaricabili-le-14-piu-comprate-a-luglio-2016.html?t=caricabatterie,pile-ricaricabili,pile,batteria,philips,amazonbasics,duracell,varta,energizer&amp;d=5|AZ_513vLcEPa5L",
];
