Gr = [
"Grembiule Madeira Zip|Colore : Grigio Composizione : tessuto 100% poliestere Dimensioni :|2017/12/grembiule-madeira-zip|data.oliviero.it/imgprodotto/grembiule-madeira-zip_24720_big",
"Giacca Cuoco Bottoni a Pressione|Colore : Grigio e bianco Composizione : tessuto 100% cotone|2017/12/giacca-cuoco-bottoni-a-pressione|data.oliviero.it/imgprodotto/giacca-cuoco-bottoni-a-pressione_2591_big",
"Grembiule Pub Liverpool|Colore : Gessato nero Composizione : tessuto 100% poliestere|2017/12/grembiule-pub-liverpool|data.oliviero.it/imgprodotto/grembiule-pub-liverpool_1661_big",
"Pantalone Cuoco Nero|Pantalone nero ufficiale della Federazione Italiana Cuochi. Passanti|2017/12/pantalone-cuoco-nero|data.oliviero.it/imgprodotto/pantalone-cuoco-nero-064197_159014",
"Bandana cuoco tortuga|Colore : Tortuga Composizione : tessuto 100% cotone Dimensioni :|2017/12/bandana-cuoco-tortuga|data.oliviero.it/imgprodotto/bandana-cuoco-tortuga_24493_big",
"Grembiule Bistrò Rosso|Colore : Rosso Composizione : tessuto 100% poliestere Dimensioni :|2017/12/grembiule-bistro-rosso|data.oliviero.it/imgprodotto/grembiule-bistro-rosso_1669_big",
"Grembiule Pub Lincoln|Colore : Gessato grigio Composizione : tessuto 100% poliestere|2017/12/grembiule-pub-lincoln|data.oliviero.it/imgprodotto/grembiule-pub-lincoln_24468_big",
"Giacca Cuoco Enrica|Colore : Bianco Composizione : tessuto 100% cotone Dimensioni :|2017/12/giacca-cuoco-enrica|data.oliviero.it/imgprodotto/giacca-cuoco-enrica_150970",
"Grembiule Asilo Bambino quadretti|Grembiule Asilo da bambino con allacciatura tramite bottoncini, due|2017/12/grembiule-asilo-bambino-quadretti|data.oliviero.it/imgprodotto/grembiule-asilo-bambino-quadretti-000266_151008",
"Bandana cuoco rossa|Colore : Rosso Composizione : tessuto 100% cotone Dimensioni : / Peso|2017/12/bandana-cuoco-rossa|data.oliviero.it/imgprodotto/bandana-cuoco-rossa_24490_big",
"Cappello Cuoco|Colore : Pepper Composizione : tessuto 100% cotone Dimensioni :|2017/12/cappello-cuoco|data.oliviero.it/imgprodotto/cappello-cuoco_24503_big",
"Pantachef taglie forti uomo|Colore : Gessato nero e bianco Composizione : tessuto 65% poliestere|2017/12/pantachef-taglie-forti-uomo|data.oliviero.it/imgprodotto/pantachef-taglie-forti-uomo_24733_big",
"Pantaloni Cuoco pied de poule|Modello con passanti in vita chiusura con due bottoni e zip. due|2017/12/pantaloni-cuoco-pied-de-poule|data.oliviero.it/imgprodotto/pantaloni-cuoco-pied-de-poule-064000_151129",
"Casacca Alberville|Colore : Azzurro Composizione : tessuto 65% poliestere e 35% cotone|2017/12/casacca-alberville|data.oliviero.it/imgprodotto/casacca-alberville_73548",
"Grembiule Bistrò|Colore : Nero Composizione : tessuto 100% poliestere Dimensioni :|2017/12/grembiule-bistro|data.oliviero.it/imgprodotto/grembiule-bistro_24701_big",
"Grembiule Pettorina|Grembiule pettorina corto con tasca Caratteristiche: Colore: Bianco|2017/12/grembiule-pettorina|data.oliviero.it/imgprodotto/grembiule-pettorina-087097_159017",
"Grembiule Orleans|Colore : Gessato Composizione : tessuto 100% poliestere Dimensioni|2017/12/grembiule-orleans|data.oliviero.it/imgprodotto/grembiule-orleans_24474_big",
"Bandana cuoco San Francisco|Colore : San Francisco Composizione : tessuto 100% cotone Dimensioni|2017/12/bandana-cuoco-san-francisco|data.oliviero.it/imgprodotto/bandana-cuoco-san-francisco_24489_big",
"Pantaloni Cuoco Nero|Modello con passanti in vita chiusura con due bottoni e zip. due|2017/12/pantaloni-cuoco-nero|data.oliviero.it/imgprodotto/pantaloni-cuoco-nero-064101_151131",
"Polo Manica Corta|Polo unisex mezza manica con colletto e allacciatura ad altezza petto|2017/12/polo-manica-corta|data.oliviero.it/imgprodotto/polo-manica-corta_24286_big",
"Pettorina Colours|Colore : Rosso Composizione : tessuto 65% poliestere e 35% cotone|2017/12/pettorina-colours|data.oliviero.it/imgprodotto/pettorina-colours_24659_big",
"Grembiule Versailles|Colore : Nero Composizione : tessuto 100% poliestere Dimensioni|2017/12/grembiule-versailles|data.oliviero.it/imgprodotto/grembiule-versailles_24691_big",
"Bolero Unisex Antracite|Bolero unisex, ideale per sale e ricevimento 100% poliestere Antracite|2017/12/bolero-unisex-antracite|data.oliviero.it/imgprodotto/bolero-unisex-antracite-035087_151460",
"Pantaloni Cuoco Pantalaccio Bluette|35% cotone 65% poliestere Colore Bluette|2017/12/pantaloni-cuoco-pantalaccio-bluette|data.oliviero.it/imgprodotto/pantaloni-cuoco-pantalaccio-bluette-044606_151031",
"Camicia donna bianca Tenerife Stretch|Colore :Bianco Composizione : tessuto 97% cotone e 3% spandex|2017/12/camicia-donna-bianca-tenerife-stretch|data.oliviero.it/imgprodotto/camicia-donna-bianca-tenerife-stretch_2340_big",
"Casacca Collo A V|Colore : Lilla Composizione : tessuto 65% poliestere e 35% cotone|2017/12/casacca-collo-a-v|data.oliviero.it/imgprodotto/casacca-collo-a-v_1630_big",
"Pettorina Pied de Poule|Pettorina unisex realizzata in 100% cotone. Modello con laccio in|2017/12/pettorina-pied-de-poule|data.oliviero.it/imgprodotto/pettorina-pied-de-poule_1643_big",
"Giacca Cuoco Coreana Bianco|100% cotton Bianco con profili colorati|2017/12/giacca-cuoco-coreana-bianco|data.oliviero.it/imgprodotto/giacca-cuoco-coreana-bianco-056022_151019",
"Giacca Cuoco Alicante|65% poliestere e 35% cotone Mezza manica Nero e rosso|2017/12/giacca-cuoco-alicante|data.oliviero.it/imgprodotto/giacca-cuoco-alicante-056907_150965",
"Grembiule Rondin|Colore : Optical Royal Composizione : tessuto 100% cotone Dimensioni|2017/12/grembiule-rondin|data.oliviero.it/imgprodotto/grembiule-rondin_1654_big",
"Camice odontotecnico 043200|Camice da dentista di colore verde Tessuto 100% cotone|2017/12/camice-odontotecnico-043200|data.oliviero.it/imgprodotto/camice-odontotecnico-043200_154613",
"Grembiule Vita|Falda vita con tasca Caratteristiche: Colore: Bianco|2017/12/grembiule-vita|data.oliviero.it/imgprodotto/grembiule-vita-086397_159022",
"Grembiule Sommelier|Colore : Sole Composizione : tessuto 100% poliestere|2017/12/grembiule-sommelier|data.oliviero.it/imgprodotto/grembiule-sommelier_24708_big",
"Divise da Lavoro: Grembiule Versailles|Allacciatura dietro, due tasche laterali e spacco centrale|2017/06/divise-da-lavoro-grembiule-versailles|data.oliviero.it/imgprodotto/grembiule-versailles_1662_big",
"Grembiule Sommelier|Modello con due bottoni al collo allacciatura dietro e due tasche laterali|2017/04/grembiule-sommelier|data.oliviero.it/imgprodotto/grembiule-sommelier_24711_big",
"Pantaloni con Elastico Azzurro - 044042|Pantalone unisex realizzato in 35% cotone e 65% poliestere|2017/04/pantaloni-con-elastico-azzurro-044042|data.oliviero.it/imgprodotto/pantaloni-con-elastico-azzurro-044042_24257_big",
"Giacca Lady Snaps - 057797|Divisa ufficiale Federazione Italiana Cuochi Giacca cuoca a manica...|2017/04/giacca-lady-snaps-057797|data.oliviero.it/imgprodotto/giacca-lady-snaps-057797_159002",
];
