Gr = [
"Pullover Donna Nero|Collezione Autunno Inverno/2018 Maglia nera brillante da donna dal|2017/12/pullover-donna-nero|data.oliviero.it/imgprodotto/pullover-donna-nero_170661",
"Borsa Dallas Metal Splatter|Collezione Autunno Inverno/2018 Borsa a tracolla blu da donna in|2017/12/borsa-dallas-metal-splatter|data.oliviero.it/imgprodotto/borsa-dallas-metal-splatter_170813",
"T-Shirt Donna Sami|Collezione Autunno Inverno/2018 Maglietta leggera a manica lunga da|2017/12/t-shirt-donna-sami|data.oliviero.it/imgprodotto/t-shirt-donna-sami_170866",
"Borsa Lisboa Eternal|Borsa a tracolla nera di forma arrotondata con ricami e strass|2017/12/borsa-lisboa-eternal|data.oliviero.it/imgprodotto/borsa-lisboa-eternal-67x51j24009_155386",
"Maglia Masi Nero|Collezione Autunno Inverno/2018 Maglietta nera da donna con maniche|2017/12/maglia-masi-nero|data.oliviero.it/imgprodotto/maglia-masi-nero_170868",
"Borsa Florida Snake|Collezione Autunno Inverno/2018 Borsa nera da donna tipo shopper con|2017/12/borsa-florida-snake|data.oliviero.it/imgprodotto/borsa-florida-snake_170786",
"Borsa Shopper Cuenca Metal Nero|Collezione Autunno Inverno/2018 Borsa nera da donna tipo shopper in|2017/12/borsa-shopper-cuenca-metal-nero|data.oliviero.it/imgprodotto/borsa-shopper-cuenca-metal-nero_170784",
"Borsa Reversibile Capri Alice|Collezione Autunno Inverno/2018 Borsa reversibile da donna stile|2017/12/borsa-reversibile-capri-alice|data.oliviero.it/imgprodotto/borsa-reversibile-capri-alice_170802",
"Borsa Charlotte Snake Patch|Collezione Autunno Inverno/2018 Borsa a tracolla nera da donna con|2017/12/borsa-charlotte-snake-patch|data.oliviero.it/imgprodotto/borsa-charlotte-snake-patch_170827",
"Borsa Lucerna Anabella|Collezione Autunno Inverno/2018 Borsa nera da donna con dettagli tono|2017/12/borsa-lucerna-anabella|data.oliviero.it/imgprodotto/borsa-lucerna-anabella_170792",
"Cappotto Selena|Collezione Autunno Inverno/2018 Cappotto grigio da donna a maniche|2017/12/cappotto-selena|data.oliviero.it/imgprodotto/cappotto-selena_170757",
"T-Shirt Aire Nero|Collezione Autunno Inverno/2018 T-shirt nera a manica lunga con|2017/12/t-shirt-aire-nero|data.oliviero.it/imgprodotto/t-shirt-aire-nero_170879",
"Maglia Donna Silverhalis|Collezione Autunno Inverno/2018 Maglia oversize da donna con diverse|2017/12/maglia-donna-silverhalis|data.oliviero.it/imgprodotto/maglia-donna-silverhalis_170672",
"Borsa Reversibile Capri Cougar|Collezione Autunno Inverno/2018 Borsa tipo shopper double face, nera|2017/12/borsa-reversibile-capri-cougar|data.oliviero.it/imgprodotto/borsa-reversibile-capri-cougar_170800",
"Borsa Cracovia Alice|Collezione Autunno Inverno/2018 Mini borsa a tracolla con leggeri|2017/12/borsa-cracovia-alice|data.oliviero.it/imgprodotto/borsa-cracovia-alice_170842",
"Cardigan Donna Aaron|Collezione Autunno Inverno/2018 Cardigan tricot da donna con|2017/12/cardigan-donna-aaron|data.oliviero.it/imgprodotto/cardigan-donna-aaron_170641",
"Cardigan Donna Adeline|Collezione Autunno Inverno/2018 Cardigan nero da donna con stampa|2017/12/cardigan-donna-adeline|data.oliviero.it/imgprodotto/cardigan-donna-adeline_170645",
"Maglia Donna Basic Carlin|Collezione Autunno Inverno/2018 Maglia blu con scollo a barca, con|2017/12/maglia-donna-basic-carlin|data.oliviero.it/imgprodotto/maglia-donna-basic-carlin_170651",
"Maglia Donna Sami|Collezione Autunno Inverno/2018 Maglia tricot da donna con patchwork|2017/12/maglia-donna-sami|data.oliviero.it/imgprodotto/maglia-donna-sami_170658",
"Borsa Somalia Anabella|Collezione Autunno Inverno/2018 Borsa a tracolla nera da donna con|2017/12/borsa-somalia-anabella|data.oliviero.it/imgprodotto/borsa-somalia-anabella_170831",
"Zaino Lima Viversnake|Collezione Autunno Inverno/2018 Zaino nero da donna con stampa|2017/12/zaino-lima-viversnake|data.oliviero.it/imgprodotto/zaino-lima-viversnake_170797",
"Foulard Caribou Nero|Collezione Autunno Inverno/2018 Foulard rettangolare nero con una|2017/12/foulard-caribou-nero|data.oliviero.it/imgprodotto/foulard-caribou-nero_170709",
"Maglia Donna Sorpresa|Collezione Autunno Inverno/2018 Maglia nera da donna con pizzo sul|2017/12/maglia-donna-sorpresa|data.oliviero.it/imgprodotto/maglia-donna-sorpresa_170677",
"Zaino Reversibile Madeira Cougar|Collezione Autunno Inverno/2018 Zaino reversibile, nero da un lato|2017/12/zaino-reversibile-madeira-cougar|data.oliviero.it/imgprodotto/zaino-reversibile-madeira-cougar_170824",
"Cappotto Melan|Collezione Autunno Inverno/2018 Caldo cappotto da donna in due|2017/12/cappotto-melan|data.oliviero.it/imgprodotto/cappotto-melan_170743",
"Borsa Charlotte Viversnake|Collezione Autunno Inverno/2018 Borsa a tracolla sottile di ecopelle|2017/12/borsa-charlotte-viversnake|data.oliviero.it/imgprodotto/borsa-charlotte-viversnake_170821",
"T-Shirt Donna Nero Leni|Collezione Primavera Estate T-shirt bianca a manica corta a righe|2017/07/t-shirt-donna-nero-leni|data.oliviero.it/imgprodotto/t-shirt-donna-nero-leni-72t2yb22000_161387",
"Jeans aderenti con strappi, toppe, pied de poule|Jeans Donna Desigual Denim Dina: la moda giovane|2017/01/jeans-aderenti-con-strappi-toppe-pied-de-poule|data.oliviero.it/imgprodotto/jeans-donna-denim-dina-67d26d15008_155343",
];
