Gr = [
"Cardigan Donna Aaron|Collezione Autunno Inverno/2018 Cardigan tricot da donna con|2017/12/cardigan-donna-aaron|data.oliviero.it/imgprodotto/cardigan-donna-aaron_170641",
"Cardigan Donna Adeline|Collezione Autunno Inverno/2018 Cardigan nero da donna con stampa|2017/12/cardigan-donna-adeline|data.oliviero.it/imgprodotto/cardigan-donna-adeline_170645",
"Maglia Donna Basic Carlin|Collezione Autunno Inverno/2018 Maglia blu con scollo a barca, con|2017/12/maglia-donna-basic-carlin|data.oliviero.it/imgprodotto/maglia-donna-basic-carlin_170651",
"Maglia Donna Sami|Collezione Autunno Inverno/2018 Maglia tricot da donna con patchwork|2017/12/maglia-donna-sami|data.oliviero.it/imgprodotto/maglia-donna-sami_170658",
"Borsa Somalia Anabella|Collezione Autunno Inverno/2018 Borsa a tracolla nera da donna con|2017/12/borsa-somalia-anabella|data.oliviero.it/imgprodotto/borsa-somalia-anabella_170831",
"Zaino Lima Viversnake|Collezione Autunno Inverno/2018 Zaino nero da donna con stampa|2017/12/zaino-lima-viversnake|data.oliviero.it/imgprodotto/zaino-lima-viversnake_170797",
"Foulard Caribou Nero|Collezione Autunno Inverno/2018 Foulard rettangolare nero con una|2017/12/foulard-caribou-nero|data.oliviero.it/imgprodotto/foulard-caribou-nero_170709",
"Maglia Donna Sorpresa|Collezione Autunno Inverno/2018 Maglia nera da donna con pizzo sul|2017/12/maglia-donna-sorpresa|data.oliviero.it/imgprodotto/maglia-donna-sorpresa_170677",
"Zaino Reversibile Madeira Cougar|Collezione Autunno Inverno/2018 Zaino reversibile, nero da un lato|2017/12/zaino-reversibile-madeira-cougar|data.oliviero.it/imgprodotto/zaino-reversibile-madeira-cougar_170824",
"Cappotto Melan|Collezione Autunno Inverno/2018 Caldo cappotto da donna in due|2017/12/cappotto-melan|data.oliviero.it/imgprodotto/cappotto-melan_170743",
"Borsa Charlotte Viversnake|Collezione Autunno Inverno/2018 Borsa a tracolla sottile di ecopelle|2017/12/borsa-charlotte-viversnake|data.oliviero.it/imgprodotto/borsa-charlotte-viversnake_170821",
"T-Shirt Donna Nero Leni|Collezione Primavera Estate T-shirt bianca a manica corta a righe|2017/07/t-shirt-donna-nero-leni|data.oliviero.it/imgprodotto/t-shirt-donna-nero-leni-72t2yb22000_161387",
"Jeans aderenti con strappi, toppe, pied de poule|Jeans Donna Desigual Denim Dina: la moda giovane|2017/01/jeans-aderenti-con-strappi-toppe-pied-de-poule|data.oliviero.it/imgprodotto/jeans-donna-denim-dina-67d26d15008_155343",
];
