Gr = [
"Samsung Maldives: condizionatore potente, silenzioso, dai consumi ridotti|Un Condizionatore/Climatizzatore INVERTER davvero professionale e potente|2016/07/samsung-maldives-condizionatore-potente-silenzioso-dai-consumi-ridotti.html?t=condizionatori,climatizzatori-inverter,climatizzatori,deumidificatori,aria-condizionata,climatizzazione,casa,cucina,bagno,letto,ufficio,aria,vento,fresco,elettrodomestici,pompa-di-calore,inverter,samsung,benessere&amp;d=23|AZ_41bbkSF6JhL",
"I 6 migliori climatizzatori inverter: luglio 2016|La top 6 dei migliori climatizzatori inverter subito disponibili: luglio 2016|2016/07/i-6-migliori-climatizzatori-inverter-luglio-2016.html?t=climatizzatori-inverter,climatizzatori,condizionatori,deumidificatori,aria-condizionata,climatizzazione,casa,cucina,bagno,letto,ufficio,aria,vento,fresco,elettrodomestici,pompa-di-calore,inverter,telecomandi-condizionatori,samsung,mitsubishi&amp;d=13|AZ_51iX93R-MsL",
"Condizionatori portatili: oneConcept CTR-1 VS Pinguino De'Longhi PAC AN97|Condizionatori portatili a confronto: oneConcept CTR-1 VS Pinguino De'Longhi PAC AN97|2016/07/condizionatori-portatili-oneconcept-ctr-1-vs-pinguino-de-longhi-pac-an97.html?t=condizionatori,climatizzatori,deumidificatori,aria-condizionata,climatizzazione,casa,cucina,bagno,letto,ufficio,aria,vento,fresco,elettrodomestici,benessere,oneconcept,de-longhi&amp;d=2|AZ_41yIWsbEJTL",
"Condizionatori: De'Longhi PAC AN112 Silent VS oneConcept CarribeanBlue|De'Longhi PAC AN112 Silent, Climatizzatore Portatile Pinguino VS oneConcept CarribeanBlue Condizionatore ventilatore depuratore aria|2016/06/condizionatori-de-longhi-pac-an112-silent-vs-oneconcept-carribeanblue.html?t=condizionatori,climatizzatori,ventilatori,casa,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettrodomestici,fresco,benessere,aria,deumidificatori,de-longhi,oneconcept&amp;d=27|AZ_31p-7Yh3SQL",
"I 10 condizionatori più venduti: giugno 2016|Condizionatori: i 10 migliori in commercio a giugno 2016|2016/06/i-10-condizionatori-piu-venduti-giugno-2016.html?t=casa,condizionatori,aria-condizionata,climatizzatori,climatizzazione,deumidificatori,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,benessere,argoclima,oneconcept,de-longhi&amp;d=11|AZ_41o0sWy6GyL",
"Condizionatore portatile Klarstein Pure Blizzard 3 2G 3-in-1|Un potente e silenzioso climatizzatore e condizionatore portatile da 7000 BTU in Classe A|2016/06/condizionatore-portatile-klarstein-pure-blizzard-3-2g-3-in-1.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,aria,deumidificatori,klarstein&amp;d=7|AZ_61ubezZEbAL",
"Climatizzatore Portatile Pinguino De' Longhi PAC AN97 Real Feel|Tra i migliori condizionatori portatili oggi sul mercato!|2016/06/climatizzatore-portatile-pinguino-de-longhi-pac-an97-real-feel.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,aria,deumidificatori,de-longhi&amp;d=6|AZ_71XTcQKZG3L",
"Condizionatore portatile Argoclima Relax: silenzioso e potente|Alta qualità di climatizzazione e utilizzo super-facile!|2016/05/condizionatore-portatile-argoclima-relax-silenzioso-e-potente.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,ventilatori,aria,vento,deumidificatori,argoclima&amp;d=26|AZ_816XVPYtl2L",
"Condizionatore d'aria TROTEC PAC 2000: spedizione gratis!|Il TROTEC PAC 2000 è uno dei condizionatori d'aria più apprezzati!|2016/05/condizionatore-d-aria-trotec-pac-2000-spedizione-gratis.html?t=condizionatori,casa,climatizzatori,aria-condizionata,climatizzazione,ufficio,bagno,cucina,elettronica,elettrodomestici,fresco,ventilatori,aria,vento,deumidificatori&amp;d=25|AZ_61TSLz5mIxL",
"La classifica dei 16 deumidificatori migliori di maggio 2016|I 16 deumidificatori migliori sul mercato|2016/05/la-classifica-dei-16-deumidificatori-migliori-di-maggio-2016.html?t=casa,letto,ufficio,climatizzazione,umidificatori,deumidificatori,aerosol,benessere,aria,respirazione,naso,gola,bronchi,polmoni,purificatori-d-aria,de-longhi,probreeze,olimpia,argoclima,duronic&amp;d=13|AZ_315fziMiu3L",
"18 marzo: i 15 deumidificatori migliori|Ecco i deumidificatori migliori, valutati al 18 marzo|2016/03/18-marzo-i-15-deumidificatori-migliori.html?t=casa,cucina,ufficio,climatizzazione,umidificatori,deumidificatori,de-longhi,probreeze,duronic,argoclima&amp;d=18|AZ_315fziMiu3L",
];
