Gr = [
"TV 4K Ultra HD: le 10 migliori a ottobre 2016|Le 10 TV 4K Ultra HD al top, in commercio ora: ottobre 2016|2016/10/tv-4k-ultra-hd-le-10-migliori-a-ottobre-2016|AZ_5156yd609-L",
"I 10 proiettori consigliati: ottobre 2016|I 10 proiettori più apprezzati del mercato: ottobre 2016|2016/10/i-10-proiettori-consigliati-ottobre-2016|AZ_41wwTNF7eAL",
"Mountain Bike, Telecomandi TV: i 5 migliori di settembre 2016|I 5 migliori prodotti in Mountain Bike, Telecomandi TV|2016/09/mountain-bike-telecomandi-tv-i-5-migliori-di-settembre-2016|AZ_51WJ+Qm4YPL",
"I 10 lettori DVD portatili che piacciono di più: settembre 2016|I 10 lettori DVD portatili che incontrano il maggiore gradimento|2016/09/i-10-lettori-dvd-portatili-che-piacciono-di-piu-settembre-2016|AZ_51goQGh83lL",
"I 10 lettori Blu-Ray migliori: settembre 2016|I 10 lettori Blu-Ray più quotati sul mercato a settembre 2016|2016/09/i-10-lettori-blu-ray-migliori-settembre-2016|AZ_31OnTBo9diL",
"Scarpe Da Corsa Per Donna, Pannelli Fonoassorbenti: i 5 migliori di agosto 2016|I 5 migliori in Scarpe Da Corsa Per Donna, Pannelli Fonoassorbenti|2016/08/scarpe-da-corsa-per-donna-pannelli-fonoassorbenti-i-5-migliori-di-agosto-2016|AZ_51fbL-BjbuL",
"I 10 migliori telecomandi TV: agosto 2016|I 10 telecomandi TV universali più quotati: la classifica di agosto 2016|2016/08/i-10-migliori-telecomandi-tv-agosto-2016|AZ_41awpK4PnrL",
"I 14 pannelli fonoassorbenti più comprati: luglio 2016|I 14 pannelli fonoassorbenti che piacciono di più: guida all'acquisto|2016/07/i-14-pannelli-fonoassorbenti-piu-comprati-luglio-2016|AZ_51TWy+HZf8L",
"Le 10 Smart TV migliori e i 5 migliori Smart TV Box Android: giugno 2016|Le 10 Smart TV più consigliate e i 5 migliori Smart TV Box Android: la classifica di giugno 2016|2016/06/le-10-smart-tv-migliori-e-i-5-migliori-smart-tv-box-android-giugno-2016.html?t=elettronica,smart-tv,smart-tv-box,televisori,tv,video,tempo-libero,full-hd,film,home-cinema,home-video,dvd,blu-ray,telecomandi-tv,android,samsung,toshiba,telefunken,lg&amp;d=23|AZ_51A6wEwU5aL",
"I proiettori più quotati: la guida all'acquisto di aprile 2016|Il meglio dei proiettori disponibili per l'acquisto|2016/04/i-proiettori-piu-quotati-la-guida-all-acquisto-di-aprile-2016.html?t=proiettori,elettronica,video,tempo-libero,full-hd,televisori,tv,film,home-cinema,home-video,dvd,blu-ray,videogiochi,console-videogiochi,dbpower,tronfy,excelvan,benq,epson,acer&amp;d=25|AZ_31soCGu+0EL",
"Lettori DVD: la guida all'acquisto di aprile 2016|La classifica aggiornata a aprile 2016 dei lettori DVD più venduti|2016/04/lettori-dvd-la-guida-all-acquisto-di-aprile-2016.html?t=televisori,lettori-dvd,elettronica,tv,home-cinema,home-video,video,tempo-libero,full-hd,3d,dvd,samsung,lg,sony,philips&amp;d=20|AZ_31OnTBo9diL",
"Aprile 2016: i 14 migliori lettori blu-ray|Ecco i 14 lettori blu-ray più venduti|2016/04/aprile-2016-i-14-migliori-lettori-blu-ray.html?t=elettronica,lettori-blu-ray,blu-ray,televisori,tv,home-cinema,home-video,video,tempo-libero,full-hd,3d,sony,samsung,philips,lg&amp;d=9|AZ_214kB3JJ-zL",
];
