Gr = [
"Stivaletti Boxe|Scarpa da boxe polivalente adatta per l'allenamento e per il tempo|2017/12/stivaletti-boxe|data.oliviero.it/imgprodotto/stivaletti-boxe_171393",
"Borsone Sportivo a Zaino|Borsa a zaino in materiale antistrappo, con spalline a scomparsa|2017/12/borsone-sportivo-a-zaino|data.oliviero.it/imgprodotto/borsone-sportivo-a-zaino-ac908_154992",
"Guantoni Boxe 14oz. GN083|Guantoni 14oz. Chiusura: Velcro Disciplina: Boxe, kick boxing, muay|2017/12/guantoni-boxe-14oz-gn083|data.oliviero.it/imgprodotto/guantoni-boxe-14oz-gn083_155001",
"Guanti Xpad GM249|Guanti protezione maestro con nuova imbottitura 'no shock advanced'|2017/12/guanti-xpad-gm249|data.oliviero.it/imgprodotto/guanti-xpad-gm249_169630",
"Guanti Fit Boxe|I Guanti da fit boxe Leone Power Fit GK099 sono stati creati dai|2017/12/guanti-fit-boxe|data.oliviero.it/imgprodotto/guanti-fit-boxe_169635",
"Guanto da Boxe GN038|Guantoni interamente in pelle; la scelta dei materiali più validi|2017/12/guanto-da-boxe-gn038|data.oliviero.it/imgprodotto/guanto-da-boxe-gn038_51787",
"Guanto Karate Fit Boxe Gk095 Rosso|Guanti pro da karate ideali anche per la fit-boxe, indispensabili per|2017/12/guanto-karate-fit-boxe-gk095-rosso|data.oliviero.it/imgprodotto/guanto-karate-fit-boxe-gk095-rosso_19305_big",
"Guanti Sacco Italy|Guanto in pelle particolarmente resistente ed anatomico, ideale per|2017/12/guanti-sacco-italy|data.oliviero.it/imgprodotto/guanti-sacco-italy_171395",
"Paradenti Safe Guard|Paradenti professionale in GEL modellabile. È composto da un corpo|2017/12/paradenti-safe-guard|data.oliviero.it/imgprodotto/paradenti-safe-guard_171419",
"Stivaletti da Boxe|Stivaletto da boxe da combattimento leggero e traspirante, rivestito|2017/12/stivaletti-da-boxe|data.oliviero.it/imgprodotto/stivaletti-da-boxe_171392",
"Borsone Sportivo|La borsa è interamente prodotta in CORDURA®, uno speciale Nylon66|2017/12/borsone-sportivo|data.oliviero.it/imgprodotto/borsone-sportivo-ac909_154994",
"Cavigliere Imbottite|Questa nuovissima cavigliera è dotata di una tripla imbottitura in|2017/12/cavigliere-imbottite|data.oliviero.it/imgprodotto/cavigliere-imbottite-ab720_154535",
"Cavigliere Thai|Logo a contrasto e nuovissimi e sfiziosi colori moda ridisegnano la|2017/12/cavigliere-thai|data.oliviero.it/imgprodotto/cavigliere-thai_171402",
"Guantoni da Allenamento Boxe 10 oz|I Guantoni Leone Fight GN052 uniscono qualità, un look moderno e un|2017/12/guantoni-da-allenamento-boxe-10-oz|data.oliviero.it/imgprodotto/guantoni-da-allenamento-boxe-10-oz_169631",
"Guanti Boxe Ska 10oz|Ad arricchire la limited edition 'Art and Gloves' arriva il GN099|2017/12/guanti-boxe-ska-10oz|data.oliviero.it/imgprodotto/guanti-boxe-ska-10oz_171406",
"Guantoni Boxe 140z|'Black' come l'oscurità delle tenebre, 'Whitè come la luce che|2017/12/guantoni-boxe-140z|data.oliviero.it/imgprodotto/guantoni-boxe-140z_169638",
"Guanti Fit Karate|Questi guanti sono ideali per la fitness boxe e il karate|2017/12/guanti-fit-karate|data.oliviero.it/imgprodotto/guanti-fit-karate_169632",
"Shorts Tech Nero e Giallo|Pantaloncino in poliestere INTERLOCK. Confortevole e leggero, grazie|2017/12/shorts-tech-nero-e-giallo|data.oliviero.it/imgprodotto/shorts-tech-nero-e-giallo_171408",
"Guanto Muay Thai 10oz|Costituiscono la scelta ideale per tutti coloro che praticano la muay|2017/12/guanto-muay-thai-10oz|data.oliviero.it/imgprodotto/guanto-muay-thai-10oz_171399",
"Short MMA Legionarivs|Dalla collaborazione tra la prestigiosa Facoltà del Design del|2017/12/short-mma-legionarivs|data.oliviero.it/imgprodotto/short-mma-legionarivs_171409",
"Guantoni Boxe 10oz. GN073|Il modernissimo look 'total black', il nuovo logo ufficiale con il|2017/12/guantoni-boxe-10oz-gn073|data.oliviero.it/imgprodotto/guantoni-boxe-10oz-gn073_154997",
"Pantaloncino da Boxe Italy Ab736|Pantaloncini da pugilato, boxe. Leone Sport modello Italy|2017/12/pantaloncino-da-boxe-italy-ab736|data.oliviero.it/imgprodotto/pantaloncino-da-boxe-italy-ab736_19353_big",
"Guantoni Boxe 10oz|Rappresentano il giusto compromesso per chi cerca un prodotto alla|2017/12/guantoni-boxe-10oz|data.oliviero.it/imgprodotto/guantoni-boxe-10oz_169639",
"Pantaloncini Thai|Eleganti ed al tempo stesso inconfondibili nella loro linea moderna|2017/12/pantaloncini-thai|data.oliviero.it/imgprodotto/pantaloncini-thai_169618",
"Pantaloncino Boxe Contender|Pantaloncino da boxe da combattimento 'Lega pro Boxe Official' in|2017/12/pantaloncino-boxe-contender|data.oliviero.it/imgprodotto/pantaloncino-boxe-contender_169617",
"Paratibia PT111|Paratibia con parapiede professionale Rivestimento in materiale|2017/12/paratibia-pt111|data.oliviero.it/imgprodotto/paratibia-pt111_163630",
"Guantoni Boxe Record 10 Oz|Quando la cura dei dettagli si fonde con lo studio e la ricerca dei|2017/12/guantoni-boxe-record-10-oz|data.oliviero.it/imgprodotto/guantoni-boxe-record-10-oz-gn056_154532",
"Corda Salto Basic|Leggera e pratica la corda da salto 'Basic ' è adatta ad ogni genere|2017/12/corda-salto-basic|data.oliviero.it/imgprodotto/corda-salto-basic_169636",
"Guanto da Boxe 6 oz|Quando la cura dei dettagli si fonde con lo studio e la ricerca dei|2017/12/guanto-da-boxe-6-oz|data.oliviero.it/imgprodotto/guanto-da-boxe-6-oz-gn056-record_154071",
"Guanto da Boxe Active GN061 14 Oz|Guantoni in materiale anti-strappo, garantiscono la resistenza tipica|2017/12/guanto-da-boxe-active-gn061-14-oz|data.oliviero.it/imgprodotto/guanto-da-boxe-active-gn061-14-oz_93126",
"Guanti Boxe Explosion|Incredibile design per il guanto Explosion consigliato per tutte le|2017/12/guanti-boxe-explosion|data.oliviero.it/imgprodotto/guanti-boxe-explosion_171403",
"T-Shirt Basic X|T- shirt da allenamento a manica corta e girocollo classico. La sua|2017/12/t-shirt-basic-x|data.oliviero.it/imgprodotto/t-shirt-basic-x_171413",
"Paratibia Defender PT120|Innovativi paratibia a calza con parapiede. L'accrata sagomatura|2017/12/paratibia-defender-pt120|data.oliviero.it/imgprodotto/paratibia-defender-pt120_169614",
"T-Shirt Leone Extrema Nero|La T-shirt Leone Extrema ABX20 è realizzata in poliestere, è leggera|2017/12/t-shirt-leone-extrema-nero|data.oliviero.it/imgprodotto/t-shirt-leone-extrema-nero-abx20_161021",
"Guantoni Boxe 10oz. GN083|Guantoni 10oz. Chiusura: Velcro Disciplina: Boxe, kick boxing, muay|2017/12/guantoni-boxe-10oz-gn083|data.oliviero.it/imgprodotto/guantoni-boxe-10oz-gn083_154999",
"Stivaletti Boxe CL186|Interamente in pelle e lavorazione artigianale per il classico|2017/12/stivaletti-boxe-cl186|data.oliviero.it/imgprodotto/stivaletti-boxe-cl186_65719",
"Bendaggio Semi-elastico 3,5m|Bendaggio semi-elastico in diverse colorazioni per il comfort e la|2017/12/bendaggio-semi-elastico-3-5m|data.oliviero.it/imgprodotto/bendaggio-semi-elastico-3-5m-ab705_169622",
"Casco da Boxe CS410|Casco best-seller con protezione anti-shock sulla nuca, orecchie|2017/12/casco-da-boxe-cs410|data.oliviero.it/imgprodotto/casco-da-boxe-cs410_93262",
"Guantoni Boxe Doctor 10 Oz|Dalla collaborazione tra il campione mondiale di K1 Giorgio Petrosyan|2017/12/guantoni-boxe-doctor-10-oz|data.oliviero.it/imgprodotto/guantoni-boxe-doctor-10-oz-gn050_154531",
"Guantoni Boxe Black and White 10 oz|I Guantoni Leone Black&White GN059 sono realizzati in poliuretano di|2017/12/guantoni-boxe-black-and-white-10-oz|data.oliviero.it/imgprodotto/guantoni-boxe-black-and-white-10-oz-gn059_161019",
"Corda Salto AT829|Corda da salto professionale in nylon con treccia in acciaio. Il|2017/12/corda-salto-at829|data.oliviero.it/imgprodotto/corda-salto-at829_169637",
"Short Thai Basic|Shorts da kick/thai boxing in satin lucido con logo ricamato, bordi|2017/12/short-thai-basic|data.oliviero.it/imgprodotto/short-thai-basic_171400",
"Boxe e Arti Marziali: Pera Veloce|Pera veloce in pelle, interamente cucita a mano|2017/06/boxe-e-arti-marziali-pera-veloce|data.oliviero.it/imgprodotto/pera-veloce-at805_155002",
"Guantoni Boxe Revenge 8 Oz - GN069|Guantoni Boxe per chi desidera distinguersi con una grafica d'impatto|2017/04/guantoni-boxe-revenge-8-oz-gn069|data.oliviero.it/imgprodotto/guantoni-boxe-revenge-8-oz-gn069_154530",
"Pantaloncino da Boxe AB772|Pantaloncino da MMA in microfibra top quality e poliestere...|2017/04/pantaloncino-da-boxe-ab772|data.oliviero.it/imgprodotto/pantaloncino-da-boxe-ab772_93249",
];
