Gr = [
"I 10 Tablet migliori: la guida di novembre 2016|La top 10 dei migliori Tablet, disponibili ora per l'acquisto|2016/11/i-10-tablet-migliori-la-guida-di-novembre-2016|AZ_51Bu4+euSyL",
"I 10 ebook-reader al top: settembre 2016|I 10 ebook-reader che incontrano il maggiore gradimento|2016/09/i-10-ebook-reader-al-top-settembre-2016|AZ_51T8lGbMT+L",
"I 16 migliori tablet in commercio a giugno 2016|I 16 tablet che piacciono di più: giugno 2016|2016/06/i-16-migliori-tablet-in-commercio-a-giugno-2016.html?t=hardware,tablet,tablet-computer,computer-portatili,ultrabook,notebook,laptop,elettronica,informatica,wi-fi,gps,smartphone,ebook,lettori-ebook,ebook-reader,libri,leggere,samsung,excelvan,asus,fire,dragon&amp;d=25|AZ_41eCLEQdOxL",
"Maggio 2016: i 10 lettori ebook più interessanti per l'acquisto|Tutti i migliori lettori ebook in commercio|2016/05/maggio-2016-i-10-lettori-ebook-piu-interessanti-per-l-acquisto.html?t=ebook,lettori-ebook,ebook-reader,libri,leggere,tablet,tablet-computer,hardware,elettronica,informatica,wi-fi,kobo,kindle,icarus&amp;d=6|AZ_51z1BrQOoIL",
"Ecco il migliore ebook reader!|E fino al 14 febbraio ci sono 20 euro di sconto su Kindle Paperwhite!|2016/02/ecco-il-migliore-ebook-reader.html?t=ebook,ebook-reader,kindle,libri,buono-sconto,codice-sconto,coupon,offerte,promozioni&amp;d=12|AZ_71AA3-dlDbL",
"Ma come può finire l'Eternità?|Per tutti gli amanti della fantascienza, e non solo|2015/11/ma-come-puo-finire-l-eternita.html?t=fantascienza,libri,isaac-asimov,scrittori,viaggio-nel-tempo,fringe,geek&amp;d=18|isaac-asimov",
"Scegli il tuo eBook gratis e scaricalo ora!|L'offerta speciale è ancora valida, ma solo fino al 27 settembre!|2015/09/scegli-il-tuo-ebook-gratis-e-scaricalo-ora.html?t=ebook,libri,buono-sconto,codice-sconto,coupon,offerte,promozioni&amp;d=22|read-kindle",
"Video - Come diventare uno scrittore di successo sfruttando le reti sociali|E magari vivere felici? Non lo sappiamo, e non è neanche facile, però nel frattempo vedere questo interessante panel male non fa|2015/03/video-come-diventare-uno-scrittore-di-successo-sfruttando-le-reti-sociali.html?t=libri,social-network,facebook,twitter,social-media-week,milano,blog,scrivere,foto-divertenti&amp;d=8|writers-block",
];
