Gr = [
"I 10 fornetti per pizza più comprati: settembre 2016|La top 10 dei migliori fornetti per pizza in commercio a settembre 2016|2016/09/i-10-fornetti-per-pizza-piu-comprati-settembre-2016|AZ_51KsTCM4dEL",
"I fornetti per pizza migliori: maggio 2016|Gli 11+1 fornetti per pizza che vanno per la maggiore!|2016/05/i-fornetti-per-pizza-migliori-maggio-2016.html?t=cucina,fornetti-pizza,pizza,casa,bar,elettrodomestici,forni,cibo,alimentazione,napoli,princess,melchioni,whirlpool,kemper,klarstein&amp;d=17|AZ_51J5MOcmr-L",
"Video - Se hai perso il transito di Mercurio e ora vuoi ammazzarti|ASPETTA, non tutto è perduto!|2016/05/video-se-hai-perso-il-transito-di-mercurio-e-ora-vuoi-ammazzarti.html?t=scienza,astronomia,astrofisica,spazio,inaf,pianeta,mercurio,sole,napoli,pink-floyd,queen,canzoni&amp;d=11|YT__uuVDA0FLlU",
"Video - Va bene lo Slow Food, ma qui si esagera!|Non irritiamoci, manteniamo una composta calma, lentamente|2016/04/video-va-bene-lo-slow-food-ma-qui-si-esagera.html?t=video-divertenti,umorismo,the-jackal,napoli,youtube,societa,candid-camera,lentezza,fretta,stress,scherzi&amp;d=3|YT_Wj7XgOxG2fM",
"Video - Non facciamoci fregare la ragazza da Rocco Siffredi!|In fondo cos'ha Rocco che noi non abbiamo?|2016/04/video-non-facciamoci-fregare-la-ragazza-da-rocco-siffredi.html?t=video-divertenti,umorismo,the-jackal,napoli,youtube,amore,donna,infedelta,tradimento,dating,incontri,rocco-siffredi&amp;d=1|YT_Pu5K2g8E1YE",
"Video - La faccia che faccia-mo è sempre quella vera?|A volte si è apprezzati anche maggiormente se ci si contiene un attimino|2016/03/video-la-faccia-che-faccia-mo-e-sempre-quella-vera.html?t=video-divertenti,umorismo,the-jackal,societa,youtube,napoli&amp;d=26|YT_gyMDi-Kjvk0",
"Video - Se lei ti chiede Rocco Siffredi|Se la tua ragazza ti chiede di vedere un film con Rocco Siffredi, ti devi preoccupare?|2015/12/video-se-lei-ti-chiede-rocco-siffredi.html?t=video-divertenti,umorismo,youtube,video,napoli,the-jackal,rocco-siffredi,amore&amp;d=13|YT_N8pBCp2OILE",
"Video - Il mondo visto dalla Mamma|Come vede il mondo la mia, la tua, la nostra Mamma. Cioè non nostra-nostra, intendevo... ok|2015/11/video-il-mondo-visto-dalla-mamma.html?t=video-divertenti,umorismo,youtube,video,napoli,the-jackal,mamma&amp;d=17|YT_9jMhgKYoq0A",
"Video - Passami l'insalatiera|Tutte le volte che mia nonna sbaglia il mio nome|2015/10/video-passami-l-insalatiera.html?t=video-divertenti,umorismo,youtube,video,napoli,nonno,nipote,tavola,the-jackal,cibo&amp;d=9|YT_FVslaLpSNRg",
"Viaggiare low cost in autobus con 1 euro?|Sì, grazie! Megabus.com arriva anche in Italia da mercoledì prossimo|2015/06/viaggiare-low-cost-in-autobus-con-1-euro.html?t=viaggi,vacanze,low-cost,autobus,roma,milano,firenze,venezia,napoli,torino,bologna,verona,padova,siena,genova,sarzana,pisa&amp;d=19|traffic-night_1",
];
