Gr = [
"La top 10 dei migliori Telescopi: gennaio 2017|I 10 Telescopi più venduti: la guida all'acquisto di gennaio 2017|2017/01/la-top-10-dei-migliori-telescopi-gennaio-2017|AZ_41qtiPiLgNL",
"Video - Cosa si nasconde dietro Sagittarius A?|Un'immagine che toglie il fiato|2016/04/video-cosa-si-nasconde-dietro-sagittarius-a.html?t=scienza,astronomia,astrofisica,spazio,inaf,nasa,infrarossi,hubble,telescopio,esa,via-lattea,galassia&amp;d=14|YT_p19fsfSfzRA",
"Video - Il mistero del pianeta nano Plutone|Plutone è stato un mistero per anni, anzi per decenni|2016/04/video-il-mistero-del-pianeta-nano-plutone.html?t=astronomia,astrofisica,spazio,scienza,inaf,nasa,pianeta,plutone,caronte,new-horizons,sonda-spaziale&amp;d=1|YT_AUjhYS9Zym0",
"Video - Scoperta acqua in un cratere di Cerere, e forse ai poli|Importante in questa scoperta il ruolo dello spettrometro italiano VIR|2016/03/video-scoperta-acqua-in-un-cratere-di-cerere-e-forse-ai-poli.html?t=astronomia,astrofisica,spazio,scienza,cerere,inaf,acqua,nasa,fascia-degli-asteroidi&amp;d=30|YT__4A3UBr6YKI",
"Video - Un robot umanoide per le missioni spaziali|R5 Valkyrie è pensato come un robot umanoide da inviare nello spazio, forse su Marte|2015/12/video-un-robot-umanoide-per-le-missioni-spaziali.html?t=nasa,spazio,robot,marte,massachusetts-institute-of-technology,northeastern-university,universita-del-texas,boston,darpa&amp;d=25|YT_jtnu9cmJKQM",
"Video - Il primo personal computer della storia fu italiano|La bellissima - o forse bruttissima - storia della Olivetti Programma 101|2015/11/video-il-primo-personal-computer-della-storia-fu-italiano.html?t=olivetti,olivetti-programma-101,personal-computer,informatica,programma-apollo,nasa,hewlett-packard,ivrea&amp;d=24|olivetti-programma-101",
"Video - Acqua su Marte: cosa c'è di diverso questa volta?|Scopriamolo insieme guardando questo video dell'Istituto Nazionale di AstroFisica|2015/10/video-acqua-su-marte-cosa-c-e-di-diverso-questa-volta.html?t=scienza,astronomia,astrofisica,spazio,marte,nasa,acqua,fantascienza,ray-bradbury&amp;d=2|ray-bradbury",
"Video - Abiogenesis: il corto di fantascienza che ha vinto tutto|Un corto fantascientifico del talentuoso Richard Mans ci fa vedere come potrebbe essere andata|2015/07/video-abiogenesis-il-corto-di-fantascienza-che-ha-vinto-tutto.html?t=fantascienza,spazio,nasa,vita,robot,sonda,video&amp;d=23|asteroid",
"Neil Armstrong e i souvenir della missione Apollo 11|Un valore storico inestimabile per un'inaspettata scoperta fatta dalla vedova di Neil Armstrong, Carol|2015/02/neil-armstrong-e-i-souvenir-della-missione-apollo-11.html?t=spazio,luna,neil-armstrong,nasa,programma-apollo&amp;d=10|moon-apollo-lem",
"Video - Lanciamoci tutti (nello Spazio)|Un divertente video musicale creato dai giovani stagisti del Johnson Space Center della NASA per omaggiare il primo volo della Orion|2014/12/video-lanciamoci-tutti-nello-spazio.html?t=nasa,spazio,musica,video-divertenti&amp;d=13|nasa",
];
