Gr = [
"I 7 acquari consigliati: ottobre 2016|I 7 acquari che vanno per la maggiore: la classifica aggiornata|2016/10/i-7-acquari-consigliati-ottobre-2016|AZ_51abTE3b0BL",
"Le 10 giacche da escursionismo da donna più apprezzate: ottobre 2016|La top 10 delle migliori giacche da escursionismo da donna in commercio|2016/10/le-10-giacche-da-escursionismo-da-donna-piu-apprezzate-ottobre-2016|AZ_41IqC68TmgL",
"Binocoli, Bollitori Elettrici: i 5 migliori di settembre 2016|I 5 migliori prodotti in Binocoli, Bollitori Elettrici|2016/09/binocoli-bollitori-elettrici-i-5-migliori-di-settembre-2016|AZ_41gOxevrkiL",
"I 14 binocoli che vanno per la maggiore: luglio 2016|La top 14 dei migliori binocoli disponibili per l'acquisto: luglio 2016|2016/07/i-14-binocoli-che-vanno-per-la-maggiore-luglio-2016.html?t=binocoli,trekking,escursioni,natura,montagna,alpinismo,caccia,pesca,birdwatching,campeggio,camping,concerti,astronomia,golf,outdoor,aria-aperta,zaini,zaini-escursioni,olympus,ghb,bresser,polaris,bushnell,lixada&amp;d=21|AZ_41ZlFHfaB8L",
"Zaini da escursionismo: i 15 migliori a luglio 2016|I 15 zaini da escursionismo che piacciono di più: luglio 2016|2016/07/zaini-da-escursionismo-i-15-migliori-a-luglio-2016.html?t=trekking,zaini,zaini-escursioni,campeggio,caccia,escursioni,outdoor,aria-aperta,tempo-libero,vacanze,natura,camping,pesca,montagna,alpinismo&amp;d=18|AZ_51EmJvYe+RL",
"Le 15 tende da campeggio più comprate: luglio 2016|Le 15 tende da campeggio più quotate: la guida all'acquisto di luglio 2016|2016/07/le-15-tende-da-campeggio-piu-comprate-luglio-2016.html?t=tende-campeggio,campeggio,outdoor,aria-aperta,tempo-libero,vacanze,trekking,escursioni,sacchi-a-pelo,birdwatching,natura,camping,canadese,ultrasport&amp;d=13|AZ_416aqs-uFQL",
"Video - Giove domina il cielo di luglio 2016|Si può vedere a occhio nudo, scopriamo come con questo bel video!|2016/07/video-giove-domina-il-cielo-di-luglio-2016.html?t=astronomia,scienza,astrofisica,spazio,inaf,pianeta,giove,stella,costellazione,natura,cielo,notte&amp;d=2|YT_Y152OugSwpw",
"I migliori sacchi a pelo: la guida all'acquisto di aprile 2016|Tutti i sacchi a pelo più gettonati|2016/04/i-migliori-sacchi-a-pelo-la-guida-all-acquisto-di-aprile-2016.html?t=tempo-libero,sacchi-a-pelo,campeggio,binocoli,caccia,concerti,pesca,birdwatching,astronomia,trekking,escursioni,letto,materassi,sonno,dormire,riposo,sport,natura&amp;d=27|AZ_41xoqArQ++L",
"Video - Le balene danzano sotto l'aurora boreale|Immagini che levano il fiato di un mondo magico, quasi alieno|2015/10/video-le-balene-danzano-sotto-l-aurora-boreale.html?t=mare,oceano,ambiente,ecologia,animali,natura,balena,norvegia,aurora-boreale,cielo&amp;d=14|aurora-whale",
"Video - Due enormi balene nuotano con surfista|Al largo della costa di Esperance, in Australia. Un incredibile filmato ripreso da un drone|2015/10/video-due-enormi-balene-nuotano-con-surfista.html?t=mare,oceano,biologia-marina,ambiente,ecologia,animali,natura,balena,esperance,australia,drone&amp;d=10|YT_g6U3VCneKfs",
];
