Gr = [
"I 10 Spremiagrumi Elettrici top a novembre 2016|La top 10 dei migliori Spremiagrumi Elettrici in commercio|2016/11/i-10-spremiagrumi-elettrici-top-a-novembre-2016|AZ_414PGYb17eL",
"I 10 estrattori di succo migliori: ottobre 2016|I 10 estrattori di succo che incontrano il maggiore gradimento|2016/10/i-10-estrattori-di-succo-migliori-ottobre-2016|AZ_31C6dY5ej4L",
"Congelatori, Spremiagrumi: i 5 migliori di settembre 2016|I 5 migliori prodotti di settembre 2016 in Congelatori, Spremiagrumi|2016/09/congelatori-spremiagrumi-i-5-migliori-di-settembre-2016|AZ_31QbYwzzoSL",
"Le 15 centrifughe più apprezzate: luglio 2016|Le 15 centrifughe più gettonate: la classifica aggiornata a luglio 2016|2016/07/le-15-centrifughe-piu-apprezzate-luglio-2016.html?t=cucina,centrifughe,elettrodomestici,frutta,verdura,estrattori-di-succo,dieta,vitamine,salute,alimentazione,alimenti,casa,cibo,risparmio,succo,agrume,spremiagrumi,spremiagrumi-elettrici,moulinex,severin,princess,tristar,philips,russell-hobbs,bosch,rgv,clatronic,duronic&amp;d=1|AZ_41iY4xdDcnL",
"I 14 spremiagrumi migliori: maggio 2016|Il top degli spremiagrumi disponibili per l'acquisto: maggio 2016|2016/05/i-14-spremiagrumi-migliori-maggio-2016.html?t=dieta,spremiagrumi,salute,alimentazione,agrume,benessere,vitamine,casa,cibo,cucina,elettrodomestici,risparmio,frutta,succo,braun,russell-hobbs,bosch,tristar,rgv,black-and-decker,philips,kenwood,macom,imetec&amp;d=30|AZ_41bD89c0mqL",
"Aprile 2016: la classifica dei migliori estrattori di succo|Tutti gli estrattori di succo più venduti!|2016/04/aprile-2016-la-classifica-dei-migliori-estrattori-di-succo.html?t=elettrodomestici,estrattori-di-succo,dieta,salute,alimentazione,benessere,vitamine,casa,cibo,cucina,risparmio,frutta,succo,panasonic,rgv,bosch,koenig,severin,philips,ariete&amp;d=6|AZ_41iY4xdDcnL",
"I 14 migliori spremiagrumi elettrici, valutati al marzo 2016|Ecco la classifica degli spremiagrumi elettrici migliori aggiornata al marzo 2016|2016/03/i-14-migliori-spremiagrumi-elettrici-valutati-al-marzo-2016.html?t=dieta,spremiagrumi-elettrici,spremiagrumi,salute,alimentazione,agrume,benessere,vitamine,casa,cibo,cucina,elettrodomestici,risparmio,frutta,succo,moulinex,black-and-decker,kenwood,philips&amp;d=30|AZ_41bD89c0mqL",
"Estrattore di Succo RGV 110600 Juice Art: il migliore|Per spremere qualsiasi tipo di frutta e verdura e rimanere in salute|2016/03/estrattore-di-succo-rgv-110600-juice-art-il-migliore.html?t=alimentazione,vitamine,casa,cibo,cucina,elettrodomestici,gastronomia,offerte,risparmio,salute,frutta,verdura,succo&amp;d=6|AZ_814VuOcn0sL",
];
