Gr = [
"Macchine per Waffle: le 10 migliori in commercio a gennaio 2017|Le 10 Macchine per Waffle più apprezzate oggi sul mercato: gennaio 2017|2017/01/macchine-per-waffle-le-10-migliori-in-commercio-a-gennaio-2017|AZ_51wpxM5nAKL",
"Le 10 migliori Crepiere Elettriche: gennaio 2017|Le 10 Crepiere Elettriche che i cuochi amano: la classifica aggiornata|2017/01/le-10-migliori-crepiere-elettriche-gennaio-2017|AZ_41C7ddyQwYL",
"I 10 pulitori a vapore migliori: ottobre 2016|Pulitori a vapore: i 10 migliori in commercio a ottobre 2016|2016/10/i-10-pulitori-a-vapore-migliori-ottobre-2016|AZ_41pLTthB5uL",
"I 9 multi-cooker migliori di ottobre 2016|La top 9 dei migliori multi-cooker disponibili ora per l'acquisto|2016/10/i-9-multi-cooker-migliori-di-ottobre-2016|AZ_41t3Y5IPXHL",
"I 10 macinacaffè elettrici migliori: settembre 2016|I 10 macinacaffè elettrici più acquistati: la classifica aggiornata|2016/09/i-10-macinacaffe-elettrici-migliori-settembre-2016|AZ_315VvbWZ3yL",
"Le 9 lavatrici da campeggio più gettonate: luglio 2016|La top 9 delle migliori lavatrici da campeggio disponibili per l'acquisto|2016/07/le-9-lavatrici-da-campeggio-piu-gettonate-luglio-2016|AZ_41dh+MXGF+L",
"Vaporetto: i 15 migliori in commercio a luglio 2016|La top 15 dei migliori vaporetto sul mercato a luglio 2016|2016/07/vaporetto-i-15-migliori-in-commercio-a-luglio-2016.html?t=casa,vaporetto,pulitori-a-vapore,elettrodomestici,igiene,pulizia,vapore,pavimento,cucina,bagno,scope-elettriche,polti,clatronic,scopa,koenig,hoover&amp;d=8|AZ_41pLTthB5uL",
"Le 15 centrifughe più apprezzate: luglio 2016|Le 15 centrifughe più gettonate: la classifica aggiornata a luglio 2016|2016/07/le-15-centrifughe-piu-apprezzate-luglio-2016.html?t=cucina,centrifughe,elettrodomestici,frutta,verdura,estrattori-di-succo,dieta,vitamine,salute,alimentazione,alimenti,casa,cibo,risparmio,succo,agrume,spremiagrumi,spremiagrumi-elettrici,moulinex,severin,princess,tristar,philips,russell-hobbs,bosch,rgv,clatronic,duronic&amp;d=1|AZ_41iY4xdDcnL",
"I 15 migliori ventilatori a torre: giugno 2016|I 15 ventilatori a torre che ammazzano il caldo: giugno 2016|2016/06/i-15-migliori-ventilatori-a-torre-giugno-2016.html?t=casa,ventilatori-torre,ventilatori,cucina,letto,ufficio,climatizzazione,aria,vento,fresco,condizionatori,aria-condizionata,illuminazione,rowenta,oneconcept,clatronic,klarstein,honeywell,aeg,dyson&amp;d=29|AZ_31F1CMYTu-L",
"Il meglio delle scope a vapore di maggio 2016|Le 13 scope a vapore più apprezzate subito disponibili per l'acquisto: maggio 2016|2016/05/il-meglio-delle-scope-a-vapore-di-maggio-2016.html?t=elettrodomestici,scope-vapore,casa,lavapavimenti,aspirapolvere,scope-elettriche,pulizia,igiene,pavimento,cucina,bagno,robot-aspirapolvere,black-and-decker,vileda,imetec,clatronic,polti,ariete&amp;d=29|AZ_21lLe5YhnVL",
"I 10 migliori essiccatori disponibili all'aprile 2016|Tutto il meglio degli essiccatori|2016/04/i-10-migliori-essiccatori-disponibili-all-aprile-2016.html?t=cucina,essiccatori,cibo,casa,alimentazione,gastronomia,cottura,dieta,elettrodomestici,grassi,benessere,vitamine,calorie,frutta,verdura,spezie,carne,pesce,melchioni,severin,beper,clatronic,princess,klarstein&amp;d=19|AZ_415chNCq9ZL",
"Le friggitrici più interessanti per l'acquisto disponibili ad aprile 2016|Il meglio delle friggitrici in commercio proprio ora|2016/04/le-friggitrici-piu-interessanti-per-l-acquisto-disponibili-ad-aprile-2016.html?t=cibo,friggitrici,cucina,alimentazione,gastronomia,elettrodomestici,patate-fritte,patata,tristar,moulinex,de-longhi,clatronic,tefal,rgv&amp;d=7|AZ_51pMIfYySIL",
];
