Gr = [
"I 10 Tablet migliori: la guida di novembre 2016|La top 10 dei migliori Tablet, disponibili ora per l'acquisto|2016/11/i-10-tablet-migliori-la-guida-di-novembre-2016|AZ_51Bu4+euSyL",
"I 10 ebook-reader al top: settembre 2016|I 10 ebook-reader che incontrano il maggiore gradimento|2016/09/i-10-ebook-reader-al-top-settembre-2016|AZ_51T8lGbMT+L",
"Borse per PC portatili: le 16 migliori a luglio 2016|Le 16 borse per PC portatili migliori subito disponibili: luglio 2016|2016/07/borse-per-pc-portatili-le-16-migliori-a-luglio-2016.html?t=borse-pc-portatili,pc,zaini,pc-portatili,computer,computer-portatili,ultrabook,notebook,laptop,informatica,personal-computer,tablet,tablet-computer,moda,borse,borse-tracolla,stile,accessori,abbigliamento,viaggi,lavoro,ufficio,bagagli,belkin,hp,hewlett-packard,amazonbasics,trust&amp;d=21|AZ_41+KmR+iX7L",
"Le 14 tastiere migliori: luglio 2016|Le 14 tastiere che piacciono di più: la classifica di luglio 2016|2016/07/le-14-tastiere-migliori-luglio-2016.html?t=computer,tastiere,informatica,computer-desktop,desktop,hardware,personal-computer,gaming,videogiochi,ufficio,studio,geek,media-center,tablet,tablet-computer,usb,wireless,trust,logitech,itek&amp;d=19|AZ_4123N4ZCc3L",
"I 16 migliori tablet in commercio a giugno 2016|I 16 tablet che piacciono di più: giugno 2016|2016/06/i-16-migliori-tablet-in-commercio-a-giugno-2016.html?t=hardware,tablet,tablet-computer,computer-portatili,ultrabook,notebook,laptop,elettronica,informatica,wi-fi,gps,smartphone,ebook,lettori-ebook,ebook-reader,libri,leggere,samsung,excelvan,asus,fire,dragon&amp;d=25|AZ_41eCLEQdOxL",
"Maggio 2016: i 10 lettori ebook più interessanti per l'acquisto|Tutti i migliori lettori ebook in commercio|2016/05/maggio-2016-i-10-lettori-ebook-piu-interessanti-per-l-acquisto.html?t=ebook,lettori-ebook,ebook-reader,libri,leggere,tablet,tablet-computer,hardware,elettronica,informatica,wi-fi,kobo,kindle,icarus&amp;d=6|AZ_51z1BrQOoIL",
"Gli 11 tablet più venduti aggiornati all'aprile 2016|Aprile 2016: il meglio dei tablet oggi disponibili negli 11 modelli top|2016/04/gli-11-tablet-piu-venduti-aggiornati-all-aprile-2016.html?t=hardware,tablet,tablet-computer,informatica,elettronica,gps,smartphone,telefono-cellulare,telefonia,fire,asus,samsung&amp;d=10|AZ_51+GBwz4LGL",
"Il caricabatterie che semplifica la vita|Non è un caso se questo è tra i prodotti più venduti su Amazon|2016/02/il-caricabatterie-che-semplifica-la-vita.html?t=smartphone,tablet-computer,tablet,shopping,usb,batteria,caricabatterie,caricatore,adattatore&amp;d=29|AZ_41duCPl36GL",
"Dimenticarsi della batteria con il PC convertibile HP Pavilion x2|Questo PC convertibile è molto più di un semplice notebook o tablet|2016/02/dimenticarsi-della-batteria-con-il-pc-convertibile-hp-pavilion-x2.html?t=notebook,laptop,personal-computer,computer-portatili,hardware,informatica,hp,tablet,windows&amp;d=5|AZ_81VFs8L5eGL",
"Uno splendido auricolare Bluetooth 4.1|Per ascoltare musica di qualità perfetta o fare chiamate a mani libere senza ingombranti cavetti|2016/01/uno-splendido-auricolare-bluetooth-4-1.html?t=elettronica,offerte,shopping,aukey,tablet,tablet-computer,smartphone,telefono-cellulare,telefonia,bluetooth,cuffie,auricolari&amp;d=31|AZ_41AsXMUosxL",
"Un tablet che è anche un telefono Dual Sim!|Un prezzo incredibile per un device di qualità che ci semplifica la vita|2016/01/un-tablet-che-e-anche-un-telefono-dual-sim.html?t=elettronica,offerte,hardware,shopping,asus,tablet,tablet-computer,smartphone,telefono-cellulare,telefonia,gps&amp;d=28|AZ_81XYFRJkbzL",
"Video - Dal CES il Lenovo Yoga 900S: un ultrabook meraviglioso|La casa cinese si è superata con un ultrabook Windows tra i più leggeri in commercio|2016/01/video-dal-ces-il-lenovo-yoga-900s-un-ultrabook-meraviglioso.html?t=notebook,laptop,ultrabook,personal-computer,computer-portatili,hardware,informatica,lenovo,tablet,windows,las-vegas,ces&amp;d=8|YT_iycxnjKWUFA",
];
