Gr = [
"I 10 migliori Rasoi Elettrici: ottobre 2016|I 10 Rasoi Elettrici più premiati dal mercato: ottobre 2016|2016/10/i-10-migliori-rasoi-elettrici-ottobre-2016|AZ_31edT76Bx7L",
"I 10 regolarbarba migliori: ottobre 2016|La top 10 dei migliori regolarbarba sul mercato a ottobre 2016|2016/10/i-10-regolarbarba-migliori-ottobre-2016|AZ_41cC27E1XqL",
"Spazzolini Elettrici, Regolacapelli: i 5 migliori di ottobre 2016|I 5 migliori prodotti in Spazzolini Elettrici, Regolacapelli|2016/10/spazzolini-elettrici-regolacapelli-i-5-migliori-di-ottobre-2016|AZ_31niyEj06TL",
"Regolacapelli, Barbecue a Gas: i 5 migliori di settembre 2016|I 5 migliori prodotti in Regolacapelli, Barbecue a Gas|2016/09/regolacapelli-barbecue-a-gas-i-5-migliori-di-settembre-2016|AZ_31aIbn0FthL",
"Tapis Roulant, Regolarbarba: i 5 migliori di settembre 2016|I 5 migliori prodotti di settembre 2016 in Tapis Roulant, Regolarbarba|2016/09/tapis-roulant-regolarbarba-i-5-migliori-di-settembre-2016|AZ_410Wr8uVIzL",
"I 10 regolarbarba migliori: agosto 2016|La top 10 dei migliori regolarbarba sul mercato a agosto 2016|2016/08/i-10-regolarbarba-migliori-agosto-2016|AZ_51BZOaAc2iL",
"I 14 regolacapelli migliori: luglio 2016|I 14 regolacapelli più interessanti per l'acquisto disponibili da subito|2016/07/i-14-regolacapelli-migliori-luglio-2016.html?t=uomo,regolacapelli,tagliacapelli,capelli,barba,peli,baffi,basette,cura-della-persona,regolabarba,igiene,moda,acconciatura,benessere,philips,ghb,panasonic&amp;d=22|AZ_31BWsDktHyL",
"Maggio 2016: il top dei rasoi elettrici|I più apprezzati rasoi elettrici: guida all'acquisto|2016/05/maggio-2016-il-top-dei-rasoi-elettrici.html?t=cura-della-persona,rasoi-elettrici,rasoio,rasatura,regolabarba,tagliacapelli,capelli,barba,peli,baffi,basette,igiene,uomo,moda,acconciatura,benessere,philips,braun,remington&amp;d=9|AZ_31DOxTWfj1L",
"I regolabarba più venduti: aprile 2016|Tutto il meglio dei regolabarba sul mercato|2016/04/i-regolabarba-piu-venduti-aprile-2016.html?t=cura-della-persona,regolabarba,tagliacapelli,capelli,moda,acconciatura,igiene,rasoio,rasatura,barba,uomo,salute,benessere,peli,baffi,basette,philips,panasonic,remington,rowenta,braun&amp;d=26|AZ_31DOxTWfj1L",
"I tagliacapelli più venduti: guida all'acquisto di aprile 2016|Il meglio dei tagliacapelli sul mercato|2016/04/i-tagliacapelli-piu-venduti-guida-all-acquisto-di-aprile-2016.html?t=cura-della-persona,tagliacapelli,capelli,moda,acconciatura,igiene,rasoio,rasatura,barba,uomo,philips,remington,panasonic,braun,ghb&amp;d=11|AZ_31-+OO54w5L",
];
