Gr = [
"Sedia Pieghevole York|Caratteristiche Telaio in alluminio diam. 25 mm Tessuto poliestere|2017/12/sedia-pieghevole-york|data.oliviero.it/imgprodotto/sedia-pieghevole-york_150024",
"Brandina Pieghevole Morfeo|Brandina pieghevole dalle dimensioni compatte, dotata di una|2017/12/brandina-pieghevole-morfeo|data.oliviero.it/imgprodotto/brandina-pieghevole-morfeo_150062",
"Sgabello Pratik 350|Caratteristiche tecniche: Materiale: polyestere Struttura: alluminio|2017/12/sgabello-pratik-350|data.oliviero.it/imgprodotto/sgabello-pratik-350_85530",
"Panca Catering 183x30|Materiale: HD Polietilene alta densità lavabile Struttura: Ferro Ø 25|2017/12/panca-catering-183x30|data.oliviero.it/imgprodotto/panca-catering-183x30_147530",
"Sedia Reclinabile Style|Sedia reclinabile in 8 posizioni con cuscino integrato e bracciolo|2017/12/sedia-reclinabile-style|data.oliviero.it/imgprodotto/sedia-reclinabile-style_150020",
"Zen Poggiapiedi Regolabile per sedia Style|Poggiapiedi regolabile in 2 posizioni per sedia Style Struttura:|2017/12/zen-poggiapiedi-regolabile-per-sedia-style|data.oliviero.it/imgprodotto/zen-poggiapiedi-regolabile-per-sedia-style_150022",
"Sedia Pieghevole Storm|Sedia pieghevole in ferro con sacca a tracolla Tessuto: poliestere|2017/12/sedia-pieghevole-storm|data.oliviero.it/imgprodotto/sedia-pieghevole-storm_149997",
"Set Birreria 220x67|Struttura: metallica con portanti in angolare elettrosaldato 30x30x3|2017/12/set-birreria-220x67|data.oliviero.it/imgprodotto/set-birreria-220x67_147531",
"Sedia Sdraio Cordobaby|Sedia sdraio Cordobaby Caratteristiche tecniche: Telaio: acciaio 20|2017/12/sedia-sdraio-cordobaby|data.oliviero.it/imgprodotto/sedia-sdraio-cordobaby_86987",
"Coppia di sedie pieghevoli Heidi Grigia|Sedia Pieghevole Struttura in ferro verniciata a polvere epossidica|2017/12/coppia-di-sedie-pieghevoli-heidi-grigia|data.oliviero.it/imgprodotto/coppia-di-sedie-pieghevoli-heidi-grigia_164394",
"Tavolo Catering 183x76|Materiale: HD Polietilene alta densità lavabile Struttura: Ferro Ø 25|2017/12/tavolo-catering-183x76|data.oliviero.it/imgprodotto/tavolo-catering-183x76_169141",
"Set Birreria 220x80|Materiale: Abete scelto ( certificato PEFC ), essiccato ad umidità|2017/12/set-birreria-220x80|data.oliviero.it/imgprodotto/set-birreria-220x80_147534",
"Sedia Regista Seven|Sedia regista con chiusura salva spazio. Seduta imbottita e schienale|2017/12/sedia-regista-seven|data.oliviero.it/imgprodotto/sedia-regista-seven_150031",
"Sedia Meeting Regista|Sedia in poliestere RICHIUDIBILE Caratteristiche tecniche: Materiale:|2017/12/sedia-meeting-regista|data.oliviero.it/imgprodotto/sedia-meeting-regista_146237",
"Tavolo Campus 4 c panche|Tavolo in mdf Caratteristiche tecniche: Materiale: MDF Struttura:|2017/12/tavolo-campus-4-c-panche|data.oliviero.it/imgprodotto/tavolo-campus-4-c-panche_87126",
];
