Gr = [
"La top 10 dei migliori apparecchi per aerosol: settembre 2016|I 10 apparecchi per aerosol più consigliati: la guida all'acquisto|2016/09/la-top-10-dei-migliori-apparecchi-per-aerosol-settembre-2016|AZ_41qa3XjtvnL",
"Umidificatori, Cappe Aspiranti: i 5 migliori di settembre 2016|I 5 migliori prodotti in Umidificatori, Cappe Aspiranti|2016/09/umidificatori-cappe-aspiranti-i-5-migliori-di-settembre-2016|AZ_41GR3CJQY-L",
"La top 10 dei migliori umidificatori: agosto 2016|I 10 umidificatori che incontrano il maggiore gradimento all'agosto 2016|2016/08/la-top-10-dei-migliori-umidificatori-agosto-2016|AZ_41jFktazBAL",
"La classifica dei 16 deumidificatori migliori di maggio 2016|I 16 deumidificatori migliori sul mercato|2016/05/la-classifica-dei-16-deumidificatori-migliori-di-maggio-2016.html?t=casa,letto,ufficio,climatizzazione,umidificatori,deumidificatori,aerosol,benessere,aria,respirazione,naso,gola,bronchi,polmoni,purificatori-d-aria,de-longhi,probreeze,olimpia,argoclima,duronic&amp;d=13|AZ_315fziMiu3L",
"I 14 migliori apparecchi per aerosol: aprile 2016|Tutti gli apparecchi per aerosol migliori|2016/04/i-14-migliori-apparecchi-per-aerosol-aprile-2016.html?t=salute,aerosol,benessere,farmacia,medicina,commercio-elettronico,aria,umidificatori,respirazione,apnea-notturna,inalatori,naso,gola,bronchi,polmoni,igiene,cura-della-persona,laica,nebula,chicco&amp;d=25|AZ_41rLbACqz+L",
"Il meglio degli umidificatori: la guida all'acquisto di aprile 2016|Tutti i più interessanti umidificatori disponibili per l'acquisto|2016/04/il-meglio-degli-umidificatori-la-guida-all-acquisto-di-aprile-2016.html?t=casa,umidificatori,cucina,ufficio,climatizzazione,elettronica,profumazione,olio-essenziale,ultrasuoni,aria,purificatori-d-aria,diffusori-di-aromi,rixow,chicco,aukey,taotronics,de-longhi,olimpia&amp;d=21|AZ_41jFktazBAL",
"18 marzo: i 15 deumidificatori migliori|Ecco i deumidificatori migliori, valutati al 18 marzo|2016/03/18-marzo-i-15-deumidificatori-migliori.html?t=casa,cucina,ufficio,climatizzazione,umidificatori,deumidificatori,de-longhi,probreeze,duronic,argoclima&amp;d=18|AZ_315fziMiu3L",
"Il migliore diffusore di aromi e umidificatore|Questo è il diffusore di aromi/umidificatore che si è imposto come il migliore!|2016/02/il-migliore-diffusore-di-aromi-e-umidificatore.html?t=offerte,shopping,casa,cucina,ufficio,climatizzazione,umidificatori,elettronica,profumazione,olio-essenziale,ultrasuoni&amp;d=1|AZ_41GR3CJQY-L",
];
