Gr = [
"I 10 forni da incasso top: agosto 2016|La top 10 dei migliori forni da incasso disponibili da subito: agosto 2016|2016/08/i-10-forni-da-incasso-top-agosto-2016|AZ_31UdW8LJhwL",
"Asciugatrici: le 10 migliori a agosto 2016|La top 10 delle migliori asciugatrici subito disponibili: agosto 2016|2016/08/asciugatrici-le-10-migliori-a-agosto-2016|AZ_51nTuJEk8+L",
"Le 10 cucine a gas al top: agosto 2016|La top 10 delle migliori cucine a gas sul mercato a agosto 2016|2016/08/le-10-cucine-a-gas-al-top-agosto-2016|AZ_21Y6jvrW2mL",
"I 14 frigoriferi doppia porta più venduti: agosto 2016|La top 14 dei migliori frigoriferi doppia porta subito disponibili|2016/08/i-14-frigoriferi-doppia-porta-piu-venduti-agosto-2016|AZ_41EhilJrcFL",
"I 14 piani cottura più acquistati: luglio 2016|La top 14 dei migliori piani cottura disponibili per l'acquisto: luglio 2016|2016/07/i-14-piani-cottura-piu-acquistati-luglio-2016.html?t=cucina,piani-cottura,casa,piastre-elettriche,griglie-elettriche,elettrodomestici,forni-elettrici,fornetti-elettrici,alimentazione,cibo,cottura,pentole,padelle,casseruole,tegami,candy,ariston,electrolux,bosch,smeg,whirlpool&amp;d=20|AZ_315rWK2ZXeL",
"Le 10 lavastoviglie più comprate: giugno 2016|La top 10 delle migliori lavastoviglie sul mercato a giugno 2016|2016/06/le-10-lavastoviglie-piu-comprate-giugno-2016.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,pulizia,igiene,stoviglie,piatti,pentole,beko,electrolux,klarstein,bosch,ariston,indesit,smeg&amp;d=2|AZ_41tdMsxE9QL",
"Le 9 lavatrici TOP di maggio 2016|La classifica aggiornata a maggio 2016 delle 9 lavatrici più acquistate|2016/05/le-9-lavatrici-top-di-maggio-2016.html?t=elettrodomestici,lavatrici,casa,igiene,abbigliamento,pulizia,ferro-a-vapore,ferro-da-stiro,sangiorgio,bosch,beko,smeg,ariston&amp;d=18|AZ_413rI5dYhML",
"Al marzo 2016, ecco le 9 lavastoviglie migliori|La nostra classifica delle 9 migliori lavastoviglie|2016/03/al-marzo-2016-ecco-le-9-lavastoviglie-migliori.html?t=elettrodomestici,lavastoviglie,cucina,casa,bar,igiene,stoviglie,klarstein,beko,indesit,bosch,smeg,electrolux&amp;d=31|AZ_51zRVIL8yqL",
];
