Gr = [
"Affettatrici: le 10 migliori in commercio a dicembre 2016|Le 10 Affettatrici che vanno per la maggiore, disponibili da subito|2016/12/affettatrici-le-10-migliori-in-commercio-a-dicembre-2016|AZ_41Hbw5-ZNlL",
"I 10 Spremiagrumi Elettrici top a novembre 2016|La top 10 dei migliori Spremiagrumi Elettrici in commercio|2016/11/i-10-spremiagrumi-elettrici-top-a-novembre-2016|AZ_414PGYb17eL",
"I 10 estrattori di succo migliori: ottobre 2016|I 10 estrattori di succo che incontrano il maggiore gradimento|2016/10/i-10-estrattori-di-succo-migliori-ottobre-2016|AZ_31C6dY5ej4L",
"Le 10 grattugie elettriche più quotate: settembre 2016|Le 10 grattugie elettriche top che puoi trovare oggi: settembre 2016|2016/09/le-10-grattugie-elettriche-piu-quotate-settembre-2016|AZ_41u8P1oRluL",
"Le 15 centrifughe più apprezzate: luglio 2016|Le 15 centrifughe più gettonate: la classifica aggiornata a luglio 2016|2016/07/le-15-centrifughe-piu-apprezzate-luglio-2016.html?t=cucina,centrifughe,elettrodomestici,frutta,verdura,estrattori-di-succo,dieta,vitamine,salute,alimentazione,alimenti,casa,cibo,risparmio,succo,agrume,spremiagrumi,spremiagrumi-elettrici,moulinex,severin,princess,tristar,philips,russell-hobbs,bosch,rgv,clatronic,duronic&amp;d=1|AZ_41iY4xdDcnL",
"Friggitrici elettriche: le 15 migliori a giugno 2016|La top 15 delle migliori friggitrici elettriche in commercio a giugno 2016|2016/06/friggitrici-elettriche-le-15-migliori-a-giugno-2016.html?t=cibo,friggitrici-elettriche,friggitrici,cucina,casa,alimentazione,gastronomia,elettrodomestici,patate-fritte,patata,tristar,de-longhi,princess,rgv&amp;d=15|AZ_31PgteVTx4L",
"I 14 spremiagrumi migliori: maggio 2016|Il top degli spremiagrumi disponibili per l'acquisto: maggio 2016|2016/05/i-14-spremiagrumi-migliori-maggio-2016.html?t=dieta,spremiagrumi,salute,alimentazione,agrume,benessere,vitamine,casa,cibo,cucina,elettrodomestici,risparmio,frutta,succo,braun,russell-hobbs,bosch,tristar,rgv,black-and-decker,philips,kenwood,macom,imetec&amp;d=30|AZ_41bD89c0mqL",
"Il top delle affettatrici: la guida all'acquisto di maggio 2016|Le 15 affettatrici più interessanti per l'acquisto|2016/05/il-top-delle-affettatrici-la-guida-all-acquisto-di-maggio-2016.html?t=cucina,affettatrici,casa,bar,elettrodomestici,cibo,alimentazione,macelleria,gastronomia,rgv,bosch,ritter,domoclip,dpe&amp;d=17|AZ_51urpkH0E3L",
"Le friggitrici più interessanti per l'acquisto disponibili ad aprile 2016|Il meglio delle friggitrici in commercio proprio ora|2016/04/le-friggitrici-piu-interessanti-per-l-acquisto-disponibili-ad-aprile-2016.html?t=cibo,friggitrici,cucina,alimentazione,gastronomia,elettrodomestici,patate-fritte,patata,tristar,moulinex,de-longhi,clatronic,tefal,rgv&amp;d=7|AZ_51pMIfYySIL",
"Aprile 2016: la classifica dei migliori estrattori di succo|Tutti gli estrattori di succo più venduti!|2016/04/aprile-2016-la-classifica-dei-migliori-estrattori-di-succo.html?t=elettrodomestici,estrattori-di-succo,dieta,salute,alimentazione,benessere,vitamine,casa,cibo,cucina,risparmio,frutta,succo,panasonic,rgv,bosch,koenig,severin,philips,ariete&amp;d=6|AZ_41iY4xdDcnL",
"La classifica delle affettatrici migliori al 20 marzo|Aggiornata alla data del 20 marzo, ecco la classifica delle affettatrici migliori|2016/03/la-classifica-delle-affettatrici-migliori-al-20-marzo.html?t=cucina,affettatrici,casa,elettrodomestici,cibo,alimentazione,macelleria,gastronomia,rgv,bosch,dpe,siemens,olimpic,domoclip&amp;d=20|AZ_51urpkH0E3L",
];
